### ISSUE TITLE
Service CMD+num shortcut not working

### ISSUE THREAD

**Issue by ClaireBookworm** [getferdi/ferdi#212] opened 2019-11-17 09:20 UTC
The `cmd+num` command doesn't work--can't switch services. When mouse hovers over service names, there is a `cmd+3` (or whatever number) prompt but it never works. This might be a just be a problem with my computer, but if it's not, this feels like quite a core feature...

**Specs**
- OS: macOS Catalina
- Version 5.3.3

**Comment by vantezzen** [comment] 2019-11-18 09:52
Is this a duplicate of #204?

**Comment by ClaireBookworm** [comment] 2019-11-19 04:17
No, this persists even after immediately adding a service...

**Comment by kytwb** [comment] 2019-11-28 04:54
I haven't been able to reproduce.  
@ClaireBookworm do you still experience the issue with the latest update?

**Comment by kytwb** [comment] 2019-12-19 13:05
Closing for now, please let us know if that is still an issue.

**Closed by kytwb** 2019-12-19 13:05 UTC
Labels: bug, feedback wanted
