### ISSUE TITLE
Little things that don't work

### ISSUE THREAD

**Issue by Nickyg001** [getferdi/ferdi#1508] opened 2021-06-08 07:47 UTC
Currently I have found three things that don't work perfectly well.

1. If there are external links in the email by clicking (double clicking) on ​​the link, nothing opens in the browser.
The present function works in these two ways:
to. ctrl + click
b. right click + open link

2. If I have a service set up: eg gmail, if in an e-mail I opened link within Ferdi, the link opens, but the preset GMAIL service changes to the link just clicked and it is not possible to go back to the 'preset setting.
I believe that a set Active service must always remain so by clicking on the icon on the left and that it is not so easy to change the link, even if we open a link within a ferdi service, the set service must remain so and not change.

3. Activating a GMAIL mail service, minimizing the Ferdi icon, the red dot appears on the icon if there are messages, but no notification from Windows 10 appears, instead with Whatsapp active the notifications arrive on windows.

4. Is it possible to ensure that Whatsapp does not lose the connection with the phone, so that it is always active?**

**Comment by vraravam** [comment] 2021-06-18 01:27
@Nickyg001 - it would be good to know which version of Ferdi you are using. The only relevant info that I could get from the above description is that you are on Windows. But, the Ferdi version number and other pertinent info would be really appreciated before we can try to solve the root cause.

If, by any chance you are on Ferdi 5.5, I would request you to please try with the nightly builds from [here](http://github.com/vraravam/nightlies/releases) - this exposes the ability to the user to control the user-agent via the UI as opposed to editing files in the Ferdi profile. Please do be aware of the **unsigned nature** of the builds in this repo - while we work on fixing the issue with signing of our build artifacts.

If you do not want to try the unsigned releases, a slightly older version (without the above functionality) would be available [here](https://github.com/getferdi/nightlies/releases) - please try this one and report back as to what's working and what's not.

**Comment by cereum** [comment] 2021-06-24 00:03
I am on Windows using Ferdi 5.6.0-nightly.57. I have noticed that spell check defaults to German and is kinda slow on right click in both my slack and telegram-react recipes.

**Comment by vraravam** [comment] 2021-06-24 01:37
Thanks for confirming @cereum . So, based on the above, points # 1 and # 2 appear to be fixed.
Regarding # 4, this is not something that we can control. (Please do ensure that you haven't setup WhatsApp as a custom service - due to the existence of this bug/enhancement: #872 
Windows-specific issues will not be addressable by me since I am on a mac. I will let one of the other contributors take a stab at it.

**Comment by xannasavin** [comment] 2021-06-25 11:32
I want to add in on the link issue: this occurs for me in Slack. If I click on a link it does nothing which is super annyoing since my work brings the need for a lot of links today that I need to open.
If I right click and chose "open link" it works, but on single left click it does nothing.
Same software as OT, Win10 and latest beta.

**Comment by vraravam** [comment] 2021-06-25 11:47
@xannasavin - please try the latest nightly and then report back whether the issue is fixed or not.

**Comment by xannasavin** [comment] 2021-06-28 13:27
@vraravam the latest release I can see is 
> 5.6.0-beta.6 @FerdiBot FerdiBot released this 29 days ago

Appearently I can't find the nightly releases

**Comment by vraravam** [comment] 2021-06-28 17:13
@xannasavin - the code signing process is currently broken, and the unsigned nightlies are present [here](http://github.com/vraravam/nightlies/releases)

**Comment by vraravam** [comment] 2021-07-07 03:47
@xannasavin - the new location of the nightlies is here: http://github.com/getferdi/nightlies/releases.

**Comment by vraravam** [comment] 2021-08-24 11:37
@xannasavin - I'm closing this ticket. If you face any more issues, please feel free to raise 1 ticket per issue/incorrect behavior - so that we can independently work and close them out.

**Closed by vraravam** 2021-08-24 11:37 UTC
Labels: outstanding question
