### ISSUE TITLE
"Restart and install updates" only closes app, no update is installed

### ISSUE THREAD

**Issue by iamsisar** [getferdi/ferdi#2231] opened 2021-11-15 08:24 UTC
**Bug description:**
Available updates are correctly notified but clicking on "restart & install update" button does nothing but closing the app. When manually reopened, no update seems to be installed and the notification banner is still visible.

**Steps to reproduce:**

NOTE: software update must be available

1. Go to 'Settings'
2. Click on 'Updates', 'Restart & install update'
3. Wait for the app to restart, it won't.
4. Manually reopen app

**Expected behavior**

App should be updated to the last version but it doesn't. 

**Environment:**

- Operating System: MacOS Big Sur - MacBook Pro M1
- Ferdi Version: 5.6.3-beta.2
- Server: Using without an account

**Comment by vraravam** [comment] 2021-11-15 08:26
Duplicate of #329

**Closed by vraravam** 2021-11-15 08:26 UTC
