### ISSUE TITLE
Debian/Ubuntu repository

### ISSUE THREAD

**Issue by janniknils** [getferdi/ferdi#1060] opened 2020-11-05 11:10 UTC
Updating Ferdi on a debain-based Linux distribution is a manual process of reinstalling a updated .deb-file.
It would be nice to create a repository, which could be added to the apt-sources.list to be able to update the application via apt.

**Comment by LongJohn-Silver** [comment] 2020-11-08 19:59
This is a duplicate of #895, where I see that you also comment. I understand that you would like this to happen, but the team behind Ferdi isn't that big and they have quite a few problems as it is, maybe it is too time consuming to distribute via apt, but anyway, creating duplicate issues is not going to help with that, but on the contrary. Please close this issue and keep the discussion on the other thread.

**Closed** 2020-11-09 09:13 UTC
Labels: enhancement
