### ISSUE TITLE
Double sys tray icon

### ISSUE THREAD

**Issue by x-tk** [getferdi/ferdi#2100] opened 2021-10-19 17:05 UTC
Hey there, having issues with two systray icons for ferdi.  Originally I had it installed as a package but moved over to a snap recently.  I checked to ensure that the previous package has been removed and only the running processes are active.  Anyone else having this issue or anything I can look into to resolve?

**Comment by vraravam** [comment] 2021-10-19 23:42
Duplicate of #1980

**Closed by vraravam** 2021-10-19 23:42 UTC
