### ISSUE TITLE
Windows 10 - Ferdi won't open

### ISSUE THREAD

**Issue by qdqm** [getferdi/ferdi#2001] opened 2021-09-30 08:02 UTC
I've had this problem recently where Ferdi just won't open. I've uninstalled and reinstalled many times (with 5.6.2, 5.6.1, 5.6.0 and the nightly versions). I've tried deleting the settings.json and proxy.json files too.

It shows up in the Background Processes on Task Manager, but no actual program opens. I'm at a loss here, any help would be greatly appreciated.

**Comment by qdqm** [comment] 2021-10-02 08:00
**Describe the bug**
After installing Ferdi, the program itself doesn't open. It does show up on Background Processes on Task Manager

**To Reproduce**
Steps to reproduce the behavior:

Installing the .exe onto Windows
Getting to past the Ferdi set up install window

**Expected behavior**
The program to open

Screenshots
![Screenshot 2021-10-02 085703](https://user-images.githubusercontent.com/74113660/135708503-3afa7754-5163-4185-a222-4e425696aade.png)
![Screenshot 2021-10-02 090006](https://user-images.githubusercontent.com/74113660/135708574-d0c8c4ee-c38e-4b2b-b146-fcef8c4d7562.png)


**Desktop (please complete the following information):**
    OS: Windows 10 Pro OS Build:19043.1266 Version: 21H1
    Browser: Firefox 92.0.1 (64-bit)
    Version: Ferdi version 5.6.2 / 5.6.1 / 5.6.0 & nightly

**Additional context**
As mentioned above, Ferdi won't open but does open on background processes after install. 
I've tried
- reinstalling different versions
- rebooting system
- running as administrator
- running troubleshooting compatibility 
- added all the troubleshooting recipes from here: https://www.electronjs.org/apps/ferdi

I'm not super savvy, but I can follow instructions if needs be. I miss Ferdi!

**Comment by qdqm** [comment] 2021-10-03 21:54
Update: Tried installing via Chocolatey and that didn't work either. :(

**Comment by indeed-a-genius** [comment] 2021-11-10 15:22
The issue is still present after all, in 5.6.3 stable. Testing on Windows 10.
It's related to starting/closing/minimizing to the system tray.
For the window to be restored properly from the minimized state, Ferdi needs to be visible in the taskbar when minimized.
So a workaround is setting `minimizeToSystemTray `and `closeToSystemTray` to `false `in settings.json.

**Comment by TheRittler** [comment] 2021-11-12 10:16
Workaround from @indeed-a-genius worked for me! My problem was, the `startMinimized` option which was `true`. Minimizing to system tray works now, only the `startMinimized` seems to be broken here. So the error seems to be a part of the `startMinimized` option. Can someone check this?

**Comment by Techsigns** [comment] 2021-11-16 20:10
Same here, minimize to tray doesn't work anymore after upgrading from 5.6.2 to 5.6.3. Downgrading to 5.6.2 brings back the working behaviour. Seems to be a bug with 5.6.3 somehow

**Comment by vraravam** [comment] 2021-11-16 23:29
Please try the latest nightly 5.6.4-nightly.7 - this issue has been fixed in the past couple of days

**Comment by Techsigns** [comment] 2021-11-17 11:56
@vraravam thanks! works for me now with 5.6.4-nightly.7

**Comment by vraravam** [comment] 2021-11-17 12:00
Thanks @Techsigns - closing the ticket now.

**Closed by vraravam** 2021-11-17 12:00 UTC
Labels: outstanding question
