### ISSUE TITLE
Duplicated paste non-formated

### ISSUE THREAD

**Issue by MauricioAedo** [getferdi/ferdi#792] opened 2020-06-02 18:43 UTC
**Bug description:**
Any paste non-formated (Ctrl+shift+c) will be duplicated

**Steps to reproduce:**

1. Copy any text (Ctrl+c)
2. Go to any service like Gmail, WhatsApp and paste non-formated (Ctrl+shift+v)
3. See error, for explample if you copy "‭5.107‬" it will be pasted "‭5.107‭5.107"

**Expected behavior**

**Screenshots**

**Environment:**

- Operating System: Windows 10
- Ferdi Version: 5.5.0
- Server: Ferdi

- Debug information:

**Comment by darhe** [comment] 2021-07-01 18:41
This issue is still relevant (and very frustrating). Can I provide any additional details to help support development around it?

**Comment by vraravam** [comment] 2021-07-02 02:22
I don't see this behavior. I'm on macos, running the latest nightly (v71) from [here](http://github.com/getferdi/nightlies/releases)

**Comment by darhe** [comment] 2021-07-02 23:50
Just went to v72 on Windows 10 Enterprise and still get the duplicate paste when I use ctrl+shift+v. It's identical to what MauricioAedo originally reported. Just tested the behavior in Discord and Microsoft Teams recipes and had the same doubling issue.

I just used ctrl+shift+v to paste "MauricioAedo" here in my browser (Chrome) without an issue.

**Comment by mhatvan** [comment] 2021-08-19 06:33
Hey @darhe, can you try it with the latest nightly release: https://github.com/getferdi/nightlies/releases/tag/v5.6.1-nightly.33

I cannot reproduce this behavior, it seems it was fixed in this PR: https://github.com/getferdi/ferdi/pull/1723

**Comment by darhe** [comment] 2021-08-19 16:25
Hi @mhatvan,

Downloaded the nightly and tried it out and do not get the double paste. Looks like it has been fixed. Thank you to @stnkl @vraravam, and all the contributors!

**Comment by vraravam** [comment] 2021-08-19 16:45
thanks for confirming @darhe . Closing this ticket!

**Closed by vraravam** 2021-08-19 16:45 UTC
Labels: bug, outstanding question, platform-specific
