### ISSUE TITLE
Discord not staying logged in with Linux client

### ISSUE THREAD

**Issue by MisterShifty** [getferdi/ferdi#1769] opened 2021-08-11 13:45 UTC
I use Ferdi on both Linux (Pop!_OS) and on Windows 10. Both are version 5.6.0.  On Windows 10 I have no problems with Discord, but on my Linux machines I have to log in to Discord every time.

1. Add Discord as a service
2. Log in with username and password + MFA or QR code scan from Discord mobile app
3. Close Ferdi 
4. Relaunch Ferdi 
5. Discord is logged out

I have not encountered this issue on the Windows version or with any other service I use in Ferdi (Gmail, Slack, Google Messaging, etc.). Only Discord, and only with Ferdi on Linux.  It is very consistent.

I have found a few other reports of this behavior here, but there doesn't seem to be any action on them and it's definitely still an issue with the current version.

**Comment by vraravam** [comment] 2021-08-11 13:49
Duplicate of #1198  - please add more info there to continue this conversation.

**Closed by vraravam** 2021-08-11 13:49 UTC
