### ISSUE TITLE
Spellcheck not functioning in 5.4.0 Windows 

### ISSUE THREAD

**Issue by Vinminto** [getferdi/ferdi#246] opened 2019-12-02 17:16 UTC
### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Ferdi Version used:
* Operating System and version:

**Comment by vantezzen** [comment] 2019-12-02 18:34
Duplicate of already resolved #220

**Closed by vantezzen** 2019-12-02 18:34 UTC
