### ISSUE TITLE
Ferdi no longer working with Slack as it was  

### ISSUE THREAD

**Issue by AndySymons** [getferdi/ferdi#1956] opened 2021-09-16 19:39 UTC
Not exactly a bug but ... today, suddenly, Slack does not open in the Ferdi window any more. You get a message saying you can open the app or open it in your browser. Is this due to a change of policy at Slack??   

Can anything be done?

**Comment by vraravam** [comment] 2021-09-16 23:41
Duplicate of #1951

**Comment by vraravam** [comment] 2021-09-16 23:42
Please see the suggested workaround in this comment: https://github.com/getferdi/ferdi/issues/1951#issuecomment-920878302

**Closed by vraravam** 2021-09-16 23:42 UTC
