### ISSUE TITLE
No notifications for telegram

### ISSUE THREAD

**Issue by theniwo** [getferdi/ferdi#1900] opened 2021-09-10 06:19 UTC
I get neither a badge counter in the systray icon, nor on the service icon in the ferdi app. 

![image](https://user-images.githubusercontent.com/58772363/132808903-c0fc71e9-06ef-4ff1-89e9-ed035ac86ff6.png)

Occors on 5.6.0 installed as .deb as well as flatpak and 5.6.1-beta.1 as snap

All other services are working properly so far.

**Comment by vraravam** [comment] 2021-09-10 08:29
Please use the `telegram-react` service recipe. The `telegram` one seems to have too many bugs - we will converse amongst the contributors and possibly remove this one soon.

**Comment by theniwo** [comment] 2021-09-10 14:23
Still no notifications on `telegram-react`

**Comment by vraravam** [comment] 2021-09-10 23:30
<img width="44" alt="Screenshot 2021-09-11 at 4 58 44 AM" src="https://user-images.githubusercontent.com/69629/132927540-59b24d5f-fc88-40f7-8fbf-b6eb6291ae63.png">

I'm on v1.2.1 of the `telegram-react` recipe. As you can see, I get notification badges. I'm on the latest nightly 5.6.1-nightly.55

**Comment by mhatvan** [comment] 2021-09-19 06:17
Cannot reproduce this on either .deb or snap, closing,

**Closed** 2021-09-19 06:17 UTC
Labels: outstanding question
