### ISSUE TITLE
Teams Ran Into an Issue After Closing Ferdi

### ISSUE THREAD

**Issue by itsARIANbtw** [getferdi/ferdi#1243] opened 2021-03-15 02:39 UTC
Everytime I close my Ferdi, my Teams would always show up "We're sorry—we've run into an issue.". I've tried reloading and disable service, the only way to get it back is to delete the service and add it back again. Currently running Win 10 19043.867 and Ferdi 5.5.0

![image](https://user-images.githubusercontent.com/12449293/111096458-26e15680-8572-11eb-80d7-ecd697f10699.png)

**Comment by NicolaNauwynck** [comment] 2021-03-16 16:16
Experiencing the same issue, it worked stable for me the past 6 months and in the past 2 weeks the Microsoft Teams clients show this message after the laptop went in a sleep mode.

The only solution is to use developer tools and clear the application data but next time the laptop goes to sleep the issue is back...

**Comment by 1azyman** [comment] 2021-03-17 10:03
same here. teams doesn't work. I've tried to change user agent, clear application cache, nothing helped.

**Comment by nathancheung22** [comment] 2021-03-20 23:22
A temporary solution I've found is to delete the service from the "your services" tab in settings. Then re-add teams and log back in.

Not the best solution because it has to be done every time you power on your PC.

**Comment by NicolaNauwynck** [comment] 2021-03-21 12:22
> A temporary solution I've found is to delete the service from the "your services" tab in settings. Then re-add teams and log back in.
> 
> Not the best solution because it has to be done every time you power on your PC.

Yeah this is just not doable as you have to it everytime....
Any good alternatives, seems like it has been a while that an update was released.

**Comment by deanbruhn** [comment] 2021-04-02 21:41
I am having the same issue. Any of the developers need anything to help troubleshoot the issue?

**Comment by nathancheung22** [comment] 2021-04-14 03:14
I found that updating to `5.6.0-beta.5` fixed the Microsoft Teams issue

**Comment by Chris2011** [comment] 2021-04-15 07:34
Same here, and when I inspect the page with the button and I click on try again, the console shows me this:

```
ErrorTemplatePage-556e761.js:1941 Uncaught TypeError: Cannot read property 'logEvent' of undefined
    at Object.exports.sendTelemetry (ErrorTemplatePage-556e761.js:1941)
    at HTMLAnchorElement.<anonymous> (ErrorTemplatePage-556e761.js:2846)
```

same for logout.

**Comment by vraravam** [comment] 2021-08-29 13:30
@Chris2011 - what is the behavior once you moved to Ferdi 5.6.0? Is this still an issue? If not, can we close this ticket please?

**Comment by Chris2011** [comment] 2021-08-29 18:00
I think after 5.6.0 beta it worked, but I can't remember it well. I removed all electron apps from my laptop due to performance issues.

**Comment by vraravam** [comment] 2021-08-29 23:50
Thanks @Chris2011 - we hope you try Ferdi once again in the future. We have upgraded to the latest electron 13 btw

**Closed by vraravam** 2021-08-29 23:50 UTC
Labels: outstanding question

**Comment by Chris2011** [comment] 2021-08-30 08:52
Thx for the info.
