### ISSUE TITLE
Ferdi tries to connect to 127.0.0.1 but local server listens on 127.0.0.2

### ISSUE THREAD

**Issue by unode** [getferdi/ferdi#1253] opened 2021-03-22 18:35 UTC
**Bug description:**

Launching Ferdi and clicking **Use Ferdi without an account** shows no change.
Using the Developer Tools I see an error `POST http://127.0.0.1/v1/auth/login net::ERR_CONNECTION_REFUSED`.

When Ferdi starts I also see in the console:
```
info: serving app on http://pluto:45569
```

but `pluto` is actually `127.0.0.2`.

**Steps to reproduce:**

1. Add the following to `/etc/hosts`:
```
127.0.0.1 localhost
::1 localhost
127.0.0.2 pluto
::1 pluto
```

2. Open "Developer Tools" and select "Console"
3. Launch Ferdi and click **Use Ferdi without an account**
4. The connection error will be displayed

**Expected behavior**

Ferdi frontend and internal server should listen/connect to the same address.

**Environment:**

- Operating System: NixOS 20.09
- Ferdi Version: 5.5.0 and 5.6.0-beta.5
- Server: Using without an account
- Debug information:
<details>
{"host":{"platform":"linux","release":"5.9.16","screens":[{"id":1881264395124802,"bounds":{"x":0,"y":1080,"width":1920,"height":1080},"workArea":{"x":0,"y":1080,"width":1920,"height":1080},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1920,"height":1080},"workAreaSize":{"width":1920,"height":1080},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"},{"id":24967369140606020,"bounds":{"x":859,"y":0,"width":1920,"height":1080},"workArea":{"x":859,"y":0,"width":1920,"height":1080},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1920,"height":1080},"workAreaSize":{"width":1920,"height":1080},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.6.0-beta.5","electron":"9.3.2","installedRecipes":[{}],"devRecipes":[],"services":[],"messages":[{"type":"error","info":["error","[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[bound ]'",{}]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"default"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"health"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"You are using Ferdi without a server"}],"workspaces":[],"windowSettings":{"width":956,"height":1036,"x":962,"y":1122,"isMaximized":false,"isFullScreen":false,"displayBounds":{"x":0,"y":1080,"width":1920,"height":1080}},"settings":{"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":false,"minimizeToSystemTray":false,"privateNotifications":false,"notifyTaskBarOnMessage":false,"showDisabledServices":true,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"[\"en-US\"]","darkMode":false,"locale":"","fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":true,"serviceLimit":5,"server":"You are using Ferdi without a server","predefinedTodoServer":"https://app.franztodos.com","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernate":false,"hibernateOnStartup":true,"hibernationStrategy":300,"inactivityLock":0,"automaticUpdates":true,"showServiceNavigationBar":false,"universalDarkMode":true,"adaptableDarkMode":true,"accentColor":"#7266F0","serviceRibbonWidth":68,"iconSize":20,"sentry":false,"nightly":false,"navigationBarBehaviour":"never","useVerticalStyle":false,"alwaysShowWorkspaces":false,"todoServer":"isUsingCustomTodoService"},"features":{"isSpellcheckerIncludedInCurrentPlan":true,"needToWaitToProceed":false,"needToWaitToProceedConfig":{"delayOffset":3600000,"wait":10000},"isServiceProxyEnabled":false,"isServiceProxyIncludedInCurrentPlan":true,"isAnnouncementsEnabled":true,"isWorkspaceIncludedInCurrentPlan":true,"isWorkspaceEnabled":false,"isCommunityRecipesIncludedInCurrentPlan":true}}}
<details>

**Comment by unode** [comment] 2021-07-18 11:26
I believe the issue lies in either:

https://github.com/getferdi/ferdi/blob/4fc60686403d380c8f3d93a9dd98b9f7d6b9d6de/src/electron/ipc-api/localServer.js#L39

resulting is using the hostname or

https://github.com/getferdi/ferdi/blob/4fc60686403d380c8f3d93a9dd98b9f7d6b9d6de/src/electron/ipc-api/localServer.js#L14

where `127.0.0.1` is hardcoded instead of using the actual listen address.

But can one of the devs confirm?

**Comment by unode** [comment] 2021-07-22 00:14
The issue is still present as of 5.6.0-nightly.88

**Comment by mhatvan** [comment] 2021-08-04 16:07
Hey @unode, I updated my `/etc/hosts` file but was unable to reproduce this with `ferdi@5.6.1-nightly.13`, but probably I did something wrong.

What is pluto? How can I set it up?

I also don't receive `info: serving app on` in the output when starting ferdi.

With some further help from you I can provide a fix for this ;)

**Comment by unode** [comment] 2021-08-04 16:46
Hi @mhatvan .

`pluto` is the `hostname` of my system.

I believe the problem is that in most configurations the `/etc/hosts` file looks like:
```
127.0.0.1 localhost pluto
::1 localhost pluto
```
which means both the hostname `pluto`, `localhost` and `127.0.0.1` all resolve to the same IP address.
However this isn't always true for all Linux flavors.

The above plus a combination of what I understand as:
- ferdi/electron using a hostname based approach to start the internal server - resulting in listening on `127.0.0.2`
- ferdi connecting to the internal server assuming (i.e. hardcoding) that it is listening on `127.0.0.1`.

results in the bug described.

**Comment by vraravam** [comment] 2021-08-04 23:37
I see at least a couple of locations where `127.0.0.1` is hardcoded in the codebase. Maybe this should be pulled into a single user-configurable value (defaulting to `127.0.0.1`). If so, then folks like @unode can override it with their hostname values. @mhatvan - do you want to take a crack at it?

**Comment by unode** [comment] 2021-08-05 08:16
@vraravam I think the configuration option would be avoidable if `localhost` is used in both cases (internal server and ferdi's connection to it). `localhost` is safer for assumptions than the machine hostname. It doesn't guarantee that the IP will always be `127.0.0.1` or `::1` but is more predictable than the hostname.

There's also a small security aspect tied to this. The internal server should probably only bind/listen on local addresses and not accept connections from other hosts. This will likely always be true for `localhost` but may not be for `hostname`.

**Comment by vraravam** [comment] 2021-08-05 09:19
@unode - Yes, I am making a first change to align all of them to `localhost`. I was thinking (long term) that if this was exposed for the user, then they could change it as per their wishes. As a first step, let me commit the `localhost` instead of `127.0.0.1`

**Closed** 2021-08-05 12:56 UTC

**Comment by unode** [comment] 2021-08-05 14:15
Is this really closed by c1aa23a? Before this commit the internal server was starting on the `hostname` and that doesn't seem to have been changed in #1744.
If I understand it correctly, ferdi will now connect to `localhost` which will resolve to `127.0.0.1` but the internal server will still launch in the wrong address.

If the following line is where the server gets launched, shouldn't it read `localhost` as well?

https://github.com/getferdi/ferdi/blob/8fa129cd5a93b7033ec72b207c95895496107cae/src/electron/ipc-api/localServer.js#L39

**Comment by vraravam** [comment] 2021-08-05 15:31
@unode - thanks for bringing this to my attention. Based on further drilldown, adonis is expecting to start a server based on another env var `HOST` - which I have now explicitly set with my latest commit.

**Comment by unode** [comment] 2021-08-05 16:06
Awesome. I'll wait for the next nightly and see how that goes.

**Comment by vraravam** [comment] 2021-08-06 03:31
Will be released in another 20 mins or so. Please confirm if this is fixed or not.

**Comment by unode** [comment] 2021-08-06 11:11
Confirmed. It now works as expected. Thanks for the fix!

**Comment by mhatvan** [comment] 2021-08-06 11:41
Awesome, great work Vijay ;)
