### ISSUE TITLE
Ferdi 5.5 does not support Google Chat anymore

### ISSUE THREAD

**Issue by squalou** [getferdi/ferdi#1273] opened 2021-04-09 13:42 UTC
Since  this morning, Google Chat inside Ferdi does not work properly anymore.

Windows users get this message :

![image](https://user-images.githubusercontent.com/4623644/114188836-d202e700-9949-11eb-8be0-aa87ff13d2e3.png)

Mac and Linux users cannot display embedded images anymore.

It could be related to a too old version of electron used by Ferdi.

**Steps to reproduce:**

1. Open service "Google Chat"  (used to be 'google hangouts chat', not to be confused with Hangouts. 
2. See error

**Environment:**

![image](https://user-images.githubusercontent.com/4623644/114189087-17271900-994a-11eb-8e3f-3ff62bb7a05c.png)

- Operating System: Windows 10, MacOS Big Sur
- Ferdi Version: 5.5.0
- Server: Using without an account

**Comment by ao-jhelmich** [comment] 2021-04-12 12:04
Can confirm this happens

**Comment by squalou** [comment] 2021-04-12 12:18
Additional info : also fails with 5.6 beta using electron 9

I have another electron app doing the job fine with electron 11 and 12.

**Comment by vraravam** [comment] 2021-04-13 02:25
Not sure if this is ok with you, but I use the nightly version of Ferdi - and I am using gChat, gDrive, gCalendar, gMail, WhatsApp, Github, Gitlab, Telegram (as a custom service), yahooMail and android Messages. The only change that I needed to do was for a personal gMail service, I needed to comment out the code in the `recipes/gmail/index.js` (the whole function `modifyRequestHeaders`). Please try that and report back if this helps.

**Comment by squalou** [comment] 2021-04-13 06:40
Thank you @vraravam , don't you have issues with images display in gChat ?

**Comment by vraravam** [comment] 2021-04-13 07:08
Yes - I noticed some images not working in the past 24 hours. Earlier this
was working.

**Comment by squalou** [comment] 2021-04-13 08:54
Damn, that's what is happening among my teammates too. Not the same day for everyone, must be a new version deployed progressively by google that limits a minimum chrome version.

**Comment by michaeldrouin** [comment] 2021-04-13 23:48
i don't think any google messaging service is working anymore. google hangouts and android messages no longer work either.

**Comment by squalou** [comment] 2021-04-14 07:46
We're taking about Google Chat, which once was named "Google Hangouts Chat", and has nothing to do with Hangouts .... blame Google on their naming scheme :-)

I assure you the service works(using it exactly right now) , it's probably only available to google-suite paid users.

**Comment by wiggisser** [comment] 2021-04-14 11:03
So I currently see the following: I have Hangouts and Google Chat app installed on my phone and Hangouts and Hangouts Chat recipies in Ferdi. Hangouts recipie stopped working in the last view days (it still worked on friday, didn't work on monday, see #1276) 

- When I send an image from my Google Chat app on my device I can see it in the Chat App on my phone and on the Chat web site (mail.google.com/chat) but not in the "Hangouts Chat" recipie in ferdi. Hangouts app and Hangouts website display "I shared IMAGE in the new Google Chat app. Click here to view"

- When I send an image fom my Hangouts app I can see it everywhere (ie both apps on my phone, both webapps in browser, and also hangouts chat recipie in ferdi. Can't tell about old hangouts recipie, because it's not loading)

I'm on 

![image](https://user-images.githubusercontent.com/3647678/114700365-bb7dd680-9d21-11eb-938e-c9cf8fd3d024.png)

**Comment by 8restcoop8** [comment] 2021-04-14 12:57
@wiggisser that is a separate issue with images being sent from Google Chat; it has nothing to do with Ferdi.  That happens if you send an image from Google Chat by any means (e.g. phone app) as well.

**Comment by wiggisser** [comment] 2021-04-14 13:18
@8restcoop8 Yes, images sent from Google Chat not displayed in (old) Hangouts mobile app and WebApp may have to do with different protocols. But the images should be at least visible in the Hangouts Chat (ie new Google chat) recipie. But they are not. There is just the placeholder 

![image](https://user-images.githubusercontent.com/3647678/114715794-bd509580-9d33-11eb-9c49-5d3e6ae0da04.png)

whereas the same picture can be seen perfectly fine in the Google Chat webapp and mobile app

And when I click on it, I get an messagebox "there was a problem displaying this image. Download"

![image](https://user-images.githubusercontent.com/3647678/114716015-ef61f780-9d33-11eb-8998-4622dbf3348c.png)

On the other hand, the Google Chat recipie in Ferdi is also perfectly fine of displaying images sent by (old) Hangouts. So only images from specific sources (ironically from the same protocol) stopped to work, not all of them ... I don't know whether that is intended or just accidental ...

**Comment by 8restcoop8** [comment] 2021-04-14 14:24
@wiggisser OK, that doesn't happen to me.  Google Chat is still working fine in Ferdi (beta and nightly) for me although Android Messages won't load since the last couple of days.  Clearly Google is making some changes that have impacted Ferdi/Electron.

**Comment by michaeldrouin** [comment] 2021-04-14 15:23
> 
> 
> Clearly Google is making some changes that have impacted Ferdi/Electron.

this is what i thought as well since Hamsket no longer loads Android Messages either. but the 2 widely used unofficial Android Messages Desktop clients both use Electron and don't seem to have problems. so i'm wondering if it's something to do with the way Ferdi and others render the content that might be different than the standalone desktop clients.

**Comment by timwsuqld** [comment] 2021-04-19 04:37
I also have the images issue in Google Chat, Ferdi 5.6.0-nightly.15, Electron 10.2.0, running on Linux

**Comment by squalou** [comment] 2021-04-19 06:05
note : for linux and windows users interested in a dedicated client, this one works.

https://github.com/squalou/google-chat-linux

**Comment by antonc42** [comment] 2021-04-21 12:52
Also having this issue. Ferdi 5.5.0 Electron 8.2.3 Nodejs 12.13.0 Linux Flatpak

**Comment by CarlinhaCamargo** [comment] 2021-04-27 12:29
I'm also having this issue. 
On Mac OS Catalina, the problem was just the missing images like people already talked about.
I just upgraded to Mac OS Big Sur (11.3) and the gChat is unavailable now, with the following message:  
![image](https://user-images.githubusercontent.com/4423019/116241193-02fd5d00-a73b-11eb-8934-f1bc0914e130.png)

**Comment by vraravam** [comment] 2021-04-27 12:42
Can you please try the steps that I have outlined [here](https://github.com/getferdi/ferdi/issues/1299#issuecomment-826485949) please? and report back whether replacing the recipe files did the trick?

**Comment by antonc42** [comment] 2021-04-27 13:08
This solution (https://github.com/getferdi/ferdi/issues/1283#issuecomment-826310980) from issue #1283 worked to fix the images not displaying. I don't use macOS, so I can't confirm that it will fix the Big Sur issue.

**Comment by vraravam** [comment] 2021-04-27 13:14
thanks for referencing that issue @antonc42 - I had put a lot of the similar comments in a lot of similar issues - but forgot where I had responded with this specific working soln.

**Comment by vraravam** [comment] 2021-05-11 07:53
The issue will be fixed when [this PR](https://github.com/getferdi/recipes/pull/477) is merged - please upvote and close this issue.

**Comment by vraravam** [comment] 2021-05-14 09:48
@squalou : The above referenced PR has been merged. I would suggest that you follow the instructions [here](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help) and report back if the issue is fixed.

**Comment by vraravam** [comment] 2021-05-27 15:52
This is working in the latest nightlies with the upgraded recipes. Closing the issue.

**Closed by vraravam** 2021-05-27 15:52 UTC
Labels: question, service-specific
