### ISSUE TITLE
Paste prepends to current message rather than inserts in place

### ISSUE THREAD

**Issue by steve-manes** [getferdi/ferdi#1199] opened 2021-02-13 10:25 UTC
**Bug description:**

When pasting content from the clipboard to an in-progress Hangouts message, the content is prepended to the message rather than inserted at the cursor location.

**Steps to reproduce:**

1. Start a Hangouts message to a recipient.
2. Type something like "Check out this amazing link: "
3. Copy a URL from the browser and paste it into your message.
4. The link is inserted at the beginning of the message, not at the cursor location.

**Expected behavior**

Pasted content should be inserted in context with the message at the current cursor location.
![Screen Shot 2021-02-13 at 5 23 02 AM](https://user-images.githubusercontent.com/60283625/107847695-a5a07380-6dbb-11eb-9a96-01c5a95d7d96.png)

**Screenshots**

**Environment:**

- Operating System: 
- MacOS 11.2 (Big Sur)
- 
-
- Ferdi Version: 
- Server: 
- Ferdi 5.5.0.2116

- Debug information:

**Comment by mastercko** [comment] 2021-03-01 19:21
Yeah, I'm glad that someone else found this. It is pretty annoying. I also verified that copy-pasting works fine on the website https://hangouts.google.com/ via Chrome.

**Comment by steve-manes** [comment] 2021-03-31 00:42
I've been sending pastes as a separate post. Wish I didn't have to but 
it works.

**Comment by mastercko** [comment] 2021-03-31 00:44
Yeah, I guess have to unlearn my usual keystroke of "type type type ctrl-v enter" (urggh)

**Comment by mhatvan** [comment] 2021-08-19 06:39
Hey guys, I was unable to reproduce this in Google Hangouts with the latest nightly: https://github.com/getferdi/nightlies/releases/tag/v5.6.1-nightly.33

There were some copy and paste related code changes recently, please let me know if it works for you too.

**Comment by mastercko** [comment] 2021-08-19 08:29
I switched over to using the Google Hangouts Chat service instead of classic Hangouts, so I can't quickly test this anymore.

**Comment by vraravam** [comment] 2021-08-19 08:53
@steve-manes - are you able to revert back on whether you are still seeing this as an issue?

**Comment by steve-manes** [comment] 2021-08-19 09:07
I've been using nightly builds and haven't seen the problem in them.

**Comment by vraravam** [comment] 2021-08-19 09:26
Thanks @steve-manes , @mastercko - closing this ticket based on your confirmations.

**Closed by vraravam** 2021-08-19 09:26 UTC
