### ISSUE TITLE
Icon of self hosted Rocket.Chat not visible in sidebar

### ISSUE THREAD

**Issue by Firnor** [getferdi/ferdi#940] opened 2020-09-01 09:52 UTC
**Bug description:**

When adding a new Rocket.Chat service, the icon in the sidebar disappears shortly after. The same happens after a restart of Ferdi.
Setting a custom icon also doesn't work, instead the preview in the setting shows a white image (tested with multiple images and formats).

**Steps to reproduce:**

1. Go to 'Add new service'
2. Select 'Rocket.Chat'
3. Switch to 'Self hosted'
4. Enter address of self-hosted Rocket.Chat
5. (Optional: add custom icon)
6. Click on 'Save service'
7. The Rocket.Chat icon in the sidebar disappears (after a few seconds)
8. (Optional: if custom icon was set -> icon shows up as completely white in the preview)

**Expected behavior**

Rocket.Chat icon should not disappear. Custom icon should preview the actual icon.

**Screenshots**

**Environment:**
- Operating System: Windows 10 2004
- Ferdi Version: 5.5.0
- Server: Without account

- Debug information:

[debug.json.txt](https://github.com/getferdi/ferdi/files/5155406/debug.json.txt)

**Comment by cgaspard** [comment] 2020-09-21 15:47
This issue is happening because the favorite icon is getting setup with double slashes in the favorite icon path.

Debugging Ferdi with dev tools I see the path to the favorite icon is marked as:   https://chat.server.name//assets/favicon_192.png

Notice the // in the path.    Removing that in the DOM fixes it.

**Comment by bfbones** [comment] 2020-10-27 10:06
Fixed that by changing line 29 of rocket.chats recipe `webview.js` from
`ipcRenderer.sendToHost('avatar', `${window.location.protocol}//${window.location.host}/${response.icons[0].src}`);`
to
`ipcRenderer.sendToHost('avatar', `${window.location.protocol}//${window.location.host}${response.icons[0].src}`);`

Got that idea from: https://github.com/meetfranz/recipe-rocketchat/blob/master/webview.js

**Comment by Firnor** [comment] 2020-10-27 10:13
Thank you very much, that fixed it!

**Comment by bfbones** [comment] 2020-10-27 10:15
@Firnor Sure closing that issue? - I don't know if it will be fixed then..

**Comment by Firnor** [comment] 2020-10-27 10:17
Sorry, yeah, you are totally right.
Reopening this to let the devs fix it for a future release.

**Comment by LongJohn-Silver** [comment] 2020-11-08 20:03
I think this is a duplicate of #780.

**Comment by vantezzen** [comment] 2020-11-09 15:21
Thank you for reporting duplicated @LongJohn-Silver, it really helps keeping our issues clean!

**Closed by vantezzen** 2020-11-09 15:21 UTC
Labels: bug

**Comment by LongJohn-Silver** [comment] 2020-11-09 15:59
@vantezzen It's nothing!
