### ISSUE TITLE
Gmail: Quit allowing standard view due to old browser

### ISSUE THREAD

**Issue by raguay** [getferdi/ferdi#1779] opened 2021-08-13 02:59 UTC
**Bug description:**

I'm running the latest nightly version of Ferdi on a MacBook Pro M1 computer. Today, 08/13/2021, I go to check my email accounts and they all say that I have to use gmail in basic HTML mode due to incompatible browser.
**Steps to reproduce:**

1. Go to 'gmail.com'
2. Login to your account
3. See the error screen for incompatible browser

**Expected behavior**

I would expect to open my gmail account as normal.
**Screenshots**

![F22C7B0C-7880-4CF2-BDD8-A2C708C258FF](https://user-images.githubusercontent.com/2487495/129298627-e0d556a2-3985-45aa-bdbf-6e150653bd2a.png)

**Environment:**

- Operating System: macOS Big Sur, MacBook Pro M1
- Ferdi Version: Version: 5.6.0-nightly.70
- Server: Without an account

- Debug information:

This doesn't seem to be working either.

**Comment by vraravam** [comment] 2021-08-13 03:13
@raguay : Thanks for trying out Ferdi.

At the outset, let me tell you that you are on an **old version** of Ferdi. We have released `v5.6.0` almost a month ago, and as of a few hours ago, we have also released a new beta of the next upcoming version - which itself has huge number of changes. Please see the website's [download](http://getferdi.com/download) for the links and changelogs. For future reference, the same page also has a link to the nightlies that will come after the beta.

Secondly, the `user-agent` has been a property that we have exposed both in the main/global Ferdi preferences as well as for each service. Please try to check if you have any custom values here.

Finally, I am also on macos BigSur on an intel MBP (and also occassionally use an ARM M1 MBP) - but, I have never seen these issues in the recent builds.

Please do try it out and report back as to the latest status. And thanks once again for trying out Ferdi and logging bugs.

**Comment by raguay** [comment] 2021-08-13 03:23
Hi,

I just downloaded the latest nightly:  Version: 5.6.1-nightly.24

It still is showing gmail in the basic HTML version. When I click on to use
standard, it briefly shows the standard and then switches back to the basic
saying `You have been redirected to the basic HTML version because this
browser is not supported. To use standard view please upgrade to a supported
browser
<https://support.google.com/mail/bin/answer.py?ctx=%67mail&answer=6557>.`.

I haven't touched or changed the user agent or anything like that.

**Comment by raguay** [comment] 2021-08-13 04:25
BTW: the latest version does copy the debug information okay. Here it is:
```json
{"host":{"platform":"darwin","release":"20.6.0","screens":[{"id":1,"bounds":{"x":0,"y":0,"width":1680,"height":1050},"workArea":{"x":0,"y":25,"width":1680,"height":1025},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":30,"colorSpace":"{primaries:BT709,
transfer:IEC61966_2_1_HDR, matrix:RGB,
range:FULL}","depthPerComponent":10,"size":{"width":1680,"height":1050},"displayFrequency":59,"workAreaSize":{"width":1680,"height":1025},"scaleFactor":2,"rotation":0,"internal":true,"touchSupport":"unknown"}]},"ferdi":{"version":"5.6.1-nightly.24","electron":"13.1.9","installedRecipes":[{"id":"discord","version":"1.1.5"},{"id":"franz-custom-website","version":"1.0.5"},{"id":"github","version":"2.0.2"},{"id":"gitter","version":"1.0.4"},{"id":"gmail","version":"1.3.10"},{"id":"googlecalendar","version":"2.1.1"},{"id":"googledrive","version":"1.0.3"},{"id":"googlekeep","version":"1.0.6"},{"id":"messenger","version":"1.2.0"},{"id":"slack","version":"1.1.0"},{"id":"trello","version":"1.0.4"},{}],"devRecipes":[],"services":[{"id":"533f1376-9e6b-495f-b6b7-0e0aea05312c","recipe":"slack","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"82edf88f-e1e1-4f2e-981e-94f692541353","recipe":"slack","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"68ee9cf8-44c9-4512-b3c3-50ced1b93814","recipe":"gitter","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"27949859-af65-4c62-a209-a9697e0b8702","recipe":"messenger","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"c290f7c5-d7f5-4310-b1b8-7086ac25c337","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"b3c61167-6131-405f-85bc-d9313d26ebed","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"4efa06b1-36d7-4711-a64f-a8049e1d477a","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"14e20def-455e-4a37-8c08-bf1bcd3008b1","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"d2c5db4b-9f15-4a55-ab85-44c2eef7cd8e","recipe":"gmail","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"7d1136d5-9277-45ce-ac3d-f2be06ef167f","recipe":"gmail","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"2917bfe5-3bf1-4e01-86c5-d32ca312a6dd","recipe":"gmail","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"6abbca89-9075-4763-b6c9-ce99af2f402a","recipe":"slack","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"83f023c2-0230-4c35-aa4a-25618d34a6cf","recipe":"slack","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"b7e2a61a-dbf4-423c-8e73-1e4a6b449329","recipe":"googlecalendar","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"4b75a97d-70f9-433f-bb13-c1dfcb71e295","recipe":"googlekeep","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"b12ac327-d63d-4975-b733-fe00af885a12","recipe":"github","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"0e6e8f4e-62e5-4ee2-8269-233764aa21ce","recipe":"trello","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"19f2b7d2-7c30-4f16-ae4b-d1515efd67b7","recipe":"discord","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true}],"messages":[{"type":"error","info":["error","Warning:
Failed prop type: Invalid prop `actions.service` of type `Object` supplied
to `_class2`, expected instance of `_class`.\n    in _class2 (created by
inject-_class2-with-stores-actions)\n    in
inject-_class2-with-stores-actions (created by RouterContext)\n    in
RouterContext (created by Router)\n    in Router (created by _class)\n
 in _class (created by inject-_class-with-stores-actions)\n    in
inject-_class-with-stores-actions\n    in IntlProvider (created by
_class)\n    in _class (created by inject-_class-with-stores)\n    in
inject-_class-with-stores\n    in
Provider"]},{"type":"error","info":["error","Warning: Failed prop type:
Invalid prop `actions.settings` of type `Object` supplied to `_class2`,
expected instance of `_class`.\n    in _class2 (created by
inject-_class2-with-stores-actions)\n    in
inject-_class2-with-stores-actions (created by _class2)\n    in div
(created by _class2)\n    in div (created by _class2)\n    in _class2
(created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in
_class2 (created by Jss(_class2))\n    in Jss(_class2) (created by
_class2)\n    in ThemeProvider (created by _class2)\n    in _class2
(created by inject-_class2-with-stores-actions)\n    in
inject-_class2-with-stores-actions (created by RouterContext)\n    in
RouterContext (created by Router)\n    in Router (created by _class)\n
 in _class (created by inject-_class-with-stores-actions)\n    in
inject-_class-with-stores-actions\n    in IntlProvider (created by
_class)\n    in _class (created by inject-_class-with-stores)\n    in
inject-_class-with-stores\n    in
Provider"]},{"type":"error","info":["error","Warning: Failed prop type: The
prop `stores.app.accentColor` is marked as required in `_class2`, but its
value is `undefined`.\n    in _class2 (created by Jss(_class2))\n    in
Jss(_class2) (created by WithTheme(Jss(_class2)))\n    in
WithTheme(Jss(_class2)) (created by
inject-WithTheme(Jss(_class2))-with-stores)\n    in
inject-WithTheme(Jss(_class2))-with-stores (created by _class2)\n    in
_class2 (created by WithTheme(_class2))\n    in WithTheme(_class2) (created
by Jss(WithTheme(_class2)))\n    in Jss(WithTheme(_class2)) (created by
_class2)\n    in ThemeProvider (created by _class2)\n    in _class2
(created by inject-_class2-with-stores-actions)\n    in
inject-_class2-with-stores-actions (created by RouterContext)\n    in
RouterContext (created by Router)\n    in Router (created by _class)\n
 in _class (created by inject-_class-with-stores-actions)\n    in
inject-_class-with-stores-actions\n    in IntlProvider (created by
_class)\n    in _class (created by inject-_class-with-stores)\n    in
inject-_class-with-stores\n    in
Provider"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"You
are using Ferdi without a
server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"You
are using Ferdi without a
server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"You
are using Ferdi without a
server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You
are using Ferdi without a
server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You
are using Ferdi without a
server"},{"type":"error","info":["error","Warning: You cannot PUSH the same
path using hash
history"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You
are using Ferdi without a
server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You
are using Ferdi without a
server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You
are using Ferdi without a
server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You
are using Ferdi without a
server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You
are using Ferdi without a
server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You
are using Ferdi without a
server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You
are using Ferdi without a
server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You
are using Ferdi without a
server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You
are using Ferdi without a
server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You
are using Ferdi without a
server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You
are using Ferdi without a
server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You
are using Ferdi without a
server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You
are using Ferdi without a
server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You
are using Ferdi without a
server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You
are using Ferdi without a
server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You
are using Ferdi without a
server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You
are using Ferdi without a
server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You
are using Ferdi without a
server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You
are using Ferdi without a
server"},{"type":"error","info":["error","Warning: Failed prop type:
Invalid prop `actions.ui` of type `Object` supplied to `_class`, expected
instance of `_class`.\n    in _class (created by
inject-_class-with-stores-actions)\n    in
inject-_class-with-stores-actions (created by RouterContext)\n    in div
(created by _class2)\n    in div (created by _class2)\n    in div (created
by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2)
(created by _class2)\n    in _class2 (created by Jss(_class2))\n    in
Jss(_class2) (created by _class2)\n    in ThemeProvider (created by
_class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n
   in inject-_class2-with-stores-actions (created by RouterContext)\n    in
RouterContext (created by Router)\n    in Router (created by _class)\n
 in _class (created by inject-_class-with-stores-actions)\n    in
inject-_class-with-stores-actions\n    in IntlProvider (created by
_class)\n    in _class (created by inject-_class-with-stores)\n    in
inject-_class-with-stores\n    in
Provider"]},{"type":"error","info":["error","Warning: Failed prop type:
Invalid prop `actions.app` of type `Object` supplied to `_class2`, expected
instance of `_class`.\n    in _class2 (created by
inject-_class2-with-stores-actions)\n    in
inject-_class2-with-stores-actions (created by RouterContext)\n    in div
(created by _class2)\n    in _class2 (created by Jss(_class2))\n    in
Jss(_class2) (created by _class2)\n    in div (created by _class2)\n    in
CSSTransitionGroupChild (created by TransitionGroup)\n    in span (created
by TransitionGroup)\n    in TransitionGroup (created by
CSSTransitionGroup)\n    in CSSTransitionGroup (created by Appear)\n    in
Appear (created by _class2)\n    in _class2 (created by _class)\n    in
_class2 (created by Jss(_class2))\n    in Jss(_class2) (created by
_class)\n    in _class (created by inject-_class-with-stores-actions)\n
 in inject-_class-with-stores-actions (created by RouterContext)\n    in
div (created by _class2)\n    in div (created by _class2)\n    in div
(created by _class2)\n    in _class2 (created by Jss(_class2))\n    in
Jss(_class2) (created by _class2)\n    in _class2 (created by
Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in
ThemeProvider (created by _class2)\n    in _class2 (created by
inject-_class2-with-stores-actions)\n    in
inject-_class2-with-stores-actions (created by RouterContext)\n    in
RouterContext (created by Router)\n    in Router (created by _class)\n
 in _class (created by inject-_class-with-stores-actions)\n    in
inject-_class-with-stores-actions\n    in IntlProvider (created by
_class)\n    in _class (created by inject-_class-with-stores)\n    in
inject-_class-with-stores\n    in
Provider"]},{"type":"error","request":{"result":8506526946,"wasExecuted":true,"method":"getAppCacheSize"},"error":{"errno":-2,"code":"ENOENT","syscall":"lstat","path":"/Users/raguay/Library/Application
Support/Ferdi/Partitions/service-68ee9cf8-44c9-4512-b3c3-50ced1b93814/Cache/0020599cf9046326_0"},"response":{},"server":"You
are using Ferdi without a
server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You
are using Ferdi without a
server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You
are using Ferdi without a
server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You
are using Ferdi without a
server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You
are using Ferdi without a
server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You
are using Ferdi without a
server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You
are using Ferdi without a
server"}],"workspaces":[{"id":"da3c61ad-9195-460a-9011-2ad267547d69","services":["0a0aa000-0a0a-49a0-a000-a0a0a0a0a0a0","0a0aa000-0a0a-49a0-a000-a0a0a0a0a0a0","533f1376-9e6b-495f-b6b7-0e0aea05312c","82edf88f-e1e1-4f2e-981e-94f692541353","0a0aa000-0a0a-49a0-a000-a0a0a0a0a0a0","0e6e8f4e-62e5-4ee2-8269-233764aa21ce","0a0aa000-0a0a-49a0-a000-a0a0a0a0a0a0","7d1136d5-9277-45ce-ac3d-f2be06ef167f","0a0aa000-0a0a-49a0-a000-a0a0a0a0a0a0","4b75a97d-70f9-433f-bb13-c1dfcb71e295","0a0aa000-0a0a-49a0-a000-a0a0a0a0a0a0","b7e2a61a-dbf4-423c-8e73-1e4a6b449329","0a0aa000-0a0a-49a0-a000-a0a0a0a0a0a0","d2c5db4b-9f15-4a55-ab85-44c2eef7cd8e","0a0aa000-0a0a-49a0-a000-a0a0a0a0a0a0"]},{"id":"1349fe71-6fe4-4f04-aef5-b5c22af75fdb","services":["4b75a97d-70f9-433f-bb13-c1dfcb71e295","b12ac327-d63d-4975-b733-fe00af885a12","19f2b7d2-7c30-4f16-ae4b-d1515efd67b7","b3c61167-6131-405f-85bc-d9313d26ebed","14e20def-455e-4a37-8c08-bf1bcd3008b1","4efa06b1-36d7-4711-a64f-a8049e1d477a","6abbca89-9075-4763-b6c9-ce99af2f402a","83f023c2-0230-4c35-aa4a-25618d34a6cf","2917bfe5-3bf1-4e01-86c5-d32ca312a6dd","d2c5db4b-9f15-4a55-ab85-44c2eef7cd8e"]}],"windowSettings":{"width":1440,"height":942,"x":203,"y":25,"isMaximized":false,"isFullScreen":false,"displayBounds":{"x":0,"y":0,"width":1680,"height":1050}},"settings":{"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":false,"minimizeToSystemTray":"","closeToSystemTray":false,"privateNotifications":false,"clipboardNotifications":true,"notifyTaskBarOnMessage":false,"showDisabledServices":true,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"en-us","darkMode":true,"locale":"en-US","fallbackLocale":"en-US","beta":true,"isAppMuted":false,"enableGPUAcceleration":true,"server":"You
are using Ferdi without a server","predefinedTodoServer":"
https://tasks.google.com/embed/?origin=https%3A%2F%2Fcalendar.google.com&fullWidth=1
","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernateOnStartup":true,"hibernationStrategy":"600","wakeUpStrategy":"300","inactivityLock":0,"automaticUpdates":true,"showServiceNavigationBar":false,"universalDarkMode":true,"userAgentPref":"","adaptableDarkMode":true,"accentColor":"#7367f0","serviceRibbonWidth":68,"iconSize":"20","sentry":true,"nightly":true,"navigationBarBehaviour":"never","searchEngine":"duckDuckGo","useVerticalStyle":false,"alwaysShowWorkspaces":false,"serviceLimit":5,"hibernate":false,"todoServer":"isUsingCustomTodoService","customTodoServer":""},"features":{"isServiceProxyEnabled":true,"isAnnouncementsEnabled":true,"isWorkspaceEnabled":true,"isTodosEnabled":true,"isSettingsWSEnabled":false,"isMagicBarEnabled":true,"subscribeURL":"
https://getferdi.com
","hasInlineCheckout":true},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}
```

**Comment by vraravam** [comment] 2021-08-13 04:48
This seems to be a setting on Google's side. I was using Ferdi (same beta) - and when I restarted my machine for some reason, I am now unable to use Gmail in the "standard" view. It keeps pushing me into the "basic html" view. At the same time, I am also using Gmail in another instance of the same service for my work email - which works fine without any issues **simultaneously**!!!

**Comment by raguay** [comment] 2021-08-13 05:39
Actually, that is true for me also. I have three gmail services: one for
work, one for my freelance work, and a family email. The work and family
gmails will only show in basic HTML, while my freelance account is still in
the standard. Very weird.

**Comment by vraravam** [comment] 2021-08-13 05:50
Thanks for confirming @raguay. Can we close this - because it looks like this is not controllable/fixable on our side?

**Comment by raguay** [comment] 2021-08-13 06:29
So, we can't reliably use Ferdi for gmail? That's not good.

**Comment by Taapo** [comment] 2021-08-13 07:56
Same problem here. If it works in all browsers, it should work in Ferdi. Back to a browser then. Too bad, I liked Ferdi though ...

**Comment by raguay** [comment] 2021-08-13 07:59
I've got it working now by changing my user agent id to:  Mozilla/5.0
(Macintosh; Intel Mac OS X 10.15; rv:93.0) Gecko/20100101 Firefox/93.0

Back to using Ferdi fine.

**Comment by vraravam** [comment] 2021-08-13 07:59
Not necessarily - imo, the same "broken" behavior would be there in any electron-based apps. Google is notorious for this specific reason.
Reason is simple: electron is built on top of the chromium engine - which is not a first-class citizen listed in [this page](https://support.google.com/mail/answer/6557?hl=en&co=GENIE.Platform%3DDesktop)

**Comment by vraravam** [comment] 2021-08-13 08:01
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:93.0) Gecko/20100101 Firefox/93.0

Thanks for this @raguay - this is a huge help for me (as a user of Ferdi as well)

**Comment by vraravam** [comment] 2021-08-13 08:02
@Taapo - can you also please confirm this workaround?

**Comment by Taapo** [comment] 2021-08-13 08:03
> @Taapo - can you also please confirm this workaround?

Yes, works perfectly for me as well now.

**Comment by vraravam** [comment] 2021-08-13 08:14
Closing the ticket then. Thanks all

**Comment by Taapo** [comment] 2021-08-13 08:15
> Closing the ticket then. Thanks all

You might need to set a new default user agent in the builds then, not?

**Comment by vraravam** [comment] 2021-08-13 08:16
I should call out that this has been an exemplary ticket - each of us coming together and helping to get back on track! Kudos!

**Comment by vraravam** [comment] 2021-08-13 08:17
> You might need to set a new default user agent in the builds then, not?

Yes - I have added it to my backlog to verify this new setting for different services and take it forward into the main codebase itself.

**Comment by raguay** [comment] 2021-08-13 08:35
Well, for me. After a reboot it quit working again. I've tried the
user agent for FireFox, Chrome, and now Safari. None are working now.

**Comment by Taapo** [comment] 2021-08-13 08:39
> Well, for me. After a reboot it quit working again. I've tried the user agent for FireFox, Chrome, and now Safari. None are working now.

Did a test here, rebooted, still working for me. Win10 though ...

**Comment by priyeshsharma** [comment] 2021-08-13 10:00
Tried with different user agents (Chrome, Safari, Firefox) - none worked for me. Switched from latest nightly to latest beta, issue persists.

Also tried the user agent mentioned above - `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:93.0) Gecko/20100101 Firefox/93.0` - didn't work for me despite Ferdi restart and Mac reboots too.

**Comment by vraravam** [comment] 2021-08-13 10:12
<img width="1792" alt="Screenshot 2021-08-13 at 3 38 05 PM" src="https://user-images.githubusercontent.com/69629/129341859-633e8904-bbcc-4294-9fcc-1f0cbdfc1246.png">

I'm unable to reproduce the issue. I have set the `user-agent` as described up above, and gmail is now working for me. Will try rebooting my mac after posting this comment.

**Comment by 0x5c4r3** [comment] 2021-08-13 10:22
Here's my situation.

GOOGLE CHAT
![image](https://user-images.githubusercontent.com/16732213/129343125-2123f5d1-a98c-47dc-b032-7393606fb210.png)
GOOGLE CALENDAR
![image](https://user-images.githubusercontent.com/16732213/129343156-e08d6c09-7ae1-47c5-8a2b-ffd52433bd52.png)

Environment:
- Operating System: arch 5.13.7
- Ferdi Version: 5.6.1-nightly.0 (installed as ferdi from AUR using yay)
- Server: Ferdi

All was good in version 5.6.0.

**Comment by psyonara** [comment] 2021-08-13 10:42
Mine works with the custom user agent given my @raguay. But I also think the default user agent should then be fixed in Ferdi, since that seems to be the root cause.

**Comment by digas** [comment] 2021-08-13 11:00
Same here . Can any of you point me on how i change the user-agent temporally ? 
Is it on the devtools ?  
Thank you

**Comment by vraravam** [comment] 2021-08-13 11:12
@digas, You can set the `user-agent` in 2 different mechanisms:
1) "Global" : This applies to ALL the services. Go to the Ferdi Preferences, click on `Advanced`. Paste the `user-agent` value from above into the text box.
2) "Service-specific": If you want this setting/override to only be for specific service(s), you can go into the same preferences screen, click on "Your Services" on the top left, select the targeted service, scroll down and enter the value for `user-agent`.

Please do remember that these changes will require you to restart Ferdi since they are loaded up when the application starts. HTH.

**Comment by digas** [comment] 2021-08-13 11:16
> @digas, You can set the `user-agent` in 2 different mechanisms:
> 
> 1. "Global" : This applies to ALL the services. Go to the Ferdi Preferences, click on `Advanced`. Paste the `user-agent` value from above into the text box.
> 2. "Service-specific": If you want this setting/override to only be for specific service(s), you can go into the same preferences screen, click on "Your Services" on the top left, select the targeted service, scroll down and enter the value for `user-agent`.
> 
> Please do remember that these changes will require you to restart Ferdi since they are loaded up when the application starts. HTH.

Thanks didn't notice until now that was there :D eheheh , my hacking spirit just took me on the wrong path eheheh

**Comment by Redirts** [comment] 2021-08-13 11:19
This ticket should not have been closed. If the permanent solution is to change the user agent then this should be commited to the recipes, IMO

**Comment by vraravam** [comment] 2021-08-13 11:30
@Redirts - we can always reopen. That being said, there are intermittent reports that this was in fact working. In fact, at the time I first responded to the ticket, I had my gmail working. After a couple of hours, it stopped. And, as I also explained, we will need to test whether this is something that needs to be applicable to all the services or not. If this is specific to gmail/google services, we will not be able to "hard code" this in the code. Since the solution is generic and the users have been given the ability to manage the user-agent string through the UI.

**Comment by g4z** [comment] 2021-08-13 14:25
i have the same problem since today.

Using Ferdi: `5.6.1-nightly.14` (Chromium 91.0.4472.164)

Gmail will only load in HTML/slow mode with the message:

```
You have been redirected to the basic HTML version because this browser is not supported.
To use standard view, please upgrade to a supported browser.
```

Meanwhile, my desktop Chromium (91.0.4472.101) will load normal/full-feature Gmail

**Comment by dafeder** [comment] 2021-08-13 15:07
User agent `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:93.0) Gecko/20100101 Firefox/93.0` fixed the same issue for me, running the ferdi manjaro package at 5.6.0.beta.5.r394.gf4243601-1

**Comment by huang-jy** [comment] 2021-08-13 15:53
Running Windows 10 here on 5.6.0, can confirm setting the Mac user agent works. Weird considering I'm using a different agent in Chrome to  access gmail, but using that same user agent in Ferdi for the gmail recipe doesn't work 🤷‍♂️

**Comment by martemorfosis** [comment] 2021-08-13 16:21
The aforementioned User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:93.0) Gecko/20100101 Firefox/93.0`  solved the issue for me on 5.6.0 running on Ubuntu 20.04

**Comment by onimaca** [comment] 2021-08-14 06:44
The work around isn't working for me on Mac OS

**Comment by stnkl** [comment] 2021-08-14 13:01
The service specific user agent doesn't appear to be saved after restarting Ferdi on Windows 20H2. It stays after reloading the service but gets reset when reloading Ferdi or restarting it. The global user agent works as expected and stays after a restart.

**Comment by zkhcohen** [comment] 2021-08-14 15:52
+1 for the user agent fix running W10 21H1

**Comment by RomLecat** [comment] 2021-08-14 18:26
The user agent fix works (I use the Firefox one, Chrome seems to still trigger the error), however it breaks left-click on links. Does anyone have a user agent working with left-click links ?

**Comment by vraravam** [comment] 2021-08-15 02:18
@RomLecat -
1) It would be good if you can post the actual string of the `user-agent` that works for you. It might be helpful for others
2) The opening of browsers via a left-click vs context-menu is not related to the `user-agent`.

**Comment by RomLecat** [comment] 2021-08-15 02:22
1. My user agent is: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0
2. It's the same issue as #321, which got fixed by a user agent change. Left click links used to work until the need to change the user agent from default.

**Comment by vraravam** [comment] 2021-08-15 02:27
1. Please also edit your response to include your OS and version (not within the `user-agent`)
2. #321 was fixed by https://github.com/getferdi/ferdi/issues/321#issuecomment-851938069

**Comment by RomLecat** [comment] 2021-08-15 02:39
#321 had a workaround that worked here: https://github.com/getferdi/ferdi/issues/321#issuecomment-581141362.
And since the popup issue came back since the user agent change, so I'd say there's definitively a correlation between the link clicking issue and the user agent.

**Comment by wenkunst** [comment] 2021-08-16 07:43
Gmail works for me after changing to this user agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:93.0) Gecko/20100101 Firefox/93.0` (MacOS 10.14.6, Ferdi Version: 5.6.0)

Same problem with links, I get the popupblocker.

**Comment by Tsakatac** [comment] 2021-08-16 16:25
Hello everyone,

I can confirm that I'm also facing this issue now and changing the user agent to `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:93.0) Gecko/20100101 Firefox/93.0` is working for me but I'm now unable to open links as some other users here (I get the popupblocker).
Here is my info:
![129590685-68cfd038-2eb1-402b-a70e-ae60fb5f4d77](https://user-images.githubusercontent.com/89021195/129596905-75f64472-b0b9-48ac-9758-74ab4b9c3df6.png)

Thanks.

**Comment by huang-jy** [comment] 2021-08-16 16:28
If you're having problems with the popup blocker (i.e get the "Grrr" message):

![image](https://user-images.githubusercontent.com/2756283/129597254-ea5da489-afa3-4a49-9ee2-94974b2f94ec.png)

Try using CTRL + Click or MMB on the link. Mac users, use CMD + Click.

**Comment by kishaningithub** [comment] 2021-08-25 09:17
Seems the issue got fixed by google. I am able to see gmail again in full color.

Note i am using 5.6.0 version of ferdi with absolutely no customizations



<img width="1400" alt="Screenshot 2021-08-25 at 2 46 06 PM" src="https://user-images.githubusercontent.com/763760/130763820-12c43513-fa4d-4dab-b86f-9bcc9b5372fc.png">

**Comment by vraravam** [comment] 2021-08-25 09:29
Thanks for the confirmation @kishaningithub ! This is a vindication that the variable being controlled is not from code changes that we have done. woot!!!!

**Comment by vraravam** [comment] 2021-08-29 12:57
Closing this issue - since its confirmed that we are not able to control this within Ferdi.

**Closed by vraravam** 2021-08-29 12:57 UTC
Labels: bug
