### ISSUE TITLE
Workspace's auto-lock

### ISSUE THREAD

**Issue by MichaelBui** [getferdi/ferdi#395] opened 2020-02-22 10:21 UTC
**Is your feature request related to a problem? Please describe.**
No, I'm currently so happy with Ferdi

**Describe the solution you'd like**
There should be a configuration per workspace to set a password for the workspace (possible with an auto-lock timing setting?) so when you open the app or switch from another workspace, users need to key in a valid password in order to continue.
If auto-lock timing is set, after that amount of time of inactivity, the workspace will be auto-locked. Users need to key in the password again to continue. This feature is similar to the app password but applied to each workspace.
This workspace password can be set as the 2nd layer of security after the app password.

**Describe alternatives you've considered**
We can implement the auto-locking feature for services

**Additional context**
None

**Comment by xerus2000** [comment] 2020-05-19 18:04
Not stale :)

**Comment by kytwb** [comment] 2022-01-09 21:06
Duplicate of https://github.com/getferdi/ferdi/issues/141.

**Closed by kytwb** 2022-01-09 21:06 UTC
Labels: enhancement :sparkles:, wontfix but contributions are welcome
