### ISSUE TITLE
Disable hibernation for specific apps doesn't work

### ISSUE THREAD

**Issue by piyushasawni55** [getferdi/ferdi#826] opened 2020-06-17 07:29 UTC
Hi 
First of all, really good work. Kudos 👏 
Just a few issues I'm facing with Lock and Hibernate features, well mainly with Hibernate feature.
The option to disable hibernation for specific service is not working for me once I quit and restart the app.
I see that my setting for specific disable hibernation is not there anymore and I have to again do that setting for all the apps I don't want to hibernate.
Would be really thankful if this thing works fine for me otherwise it takes a lot of system resources and even heats up the machine.
Please help.
Thank You. 😄

**Comment by ayakaruu** [comment] 2020-06-17 08:33
Hello! Same issue here. Hibernate does not work for specific apps. Either I turn it on for all apps or I have to turn it off.

**Comment by vantezzen** [comment] 2020-06-17 11:18
This is a duplicate of #715. The bug has already been fixed - this fix will be released with the next version of Ferdi.

**Closed by vantezzen** 2020-06-17 11:18 UTC

**Comment by piyushasawni55** [comment] 2020-06-17 11:31
@vantezzen any update on when is the next version coming out.
I am on v5.5.0.2116, also I am facing issues with lock functionality. No notifications if locked and once locked most of the options from top are disabled.
Also, quick switch focus is not working fine for me.

Actually i'm kinda confused between Station & Ferdi now, Station is very smooth but it lacks some functionality Ferdi has. But again the functionality in Ferdi is a little buggy.

**Comment by vantezzen** [comment] 2020-06-17 12:05
> any update on when is the next version coming out

No ETA yet, we are working on releasing a first beta build of 5.6.0 in a few days though.

> No notifications if locked and once locked most of the options from top are disabled

This is intentional as to protect your notifications and messages.

**Comment by piyushasawni55** [comment] 2020-06-17 12:09
@vantezzen sure, I guess I'll just have to wait then. Already enrolled beta.
Also, there is an option in setting to hide the message content. With locked option enabled that can be enabled so that privacy is there as well as the notification comes.
Another problem with lock feature is that even though I have disabled the lock, still option on top bar are missing.
