### ISSUE TITLE
[Bug]: No notification badge for ProtonMail

### ISSUE THREAD

**Issue by mizzunet** [getferdi/ferdi#2277] opened 2021-11-24 12:50 UTC
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

### Ferdi Version

5.6.3

### What operating system are you using?

Other Linux

### Server

Using without an account

### Operating System Version

Arch

### What arch are you using?

x64

### Steps to reproduce

1. Create ProtonMail service
2. Log in to ProtonMail

### Expected Behavior

 No notification badge on service icon as having unread emails

### Actual Behavior

Display badge with number 

### Screenshots

![image](https://user-images.githubusercontent.com/10193999/143241608-0ad1cc13-4e48-4c19-bff1-c9f0dd29415a.png)

### Debug information

{"host":{"platform":"linux","release":"5.15.4-zen1-1-zen","screens":[{"id":33,"bounds":{"x":0,"y":0,"width":1366,"height":768},"workArea":{"x":0,"y":0,"width":1366,"height":768},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1366,"height":768},"displayFrequency":59,"workAreaSize":{"width":1366,"height":768},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.6.4-nightly.15","electron":"15.3.2","installedRecipes":[{"id":"proton-mail","version":"1.3.1"},{"id":"proton-mail","version":"1.0.0"}],"devRecipes":[{"id":"proton-mail","version":"1.0.0"}],"services":[{"id":"379e647b-ff0b-47c9-9ed5-efa6921c48a5","recipe":"proton-mail","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false}],"messages":[{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.service` of type `Object` supplied to `_class2`, expected instance of `_class`.","\n    at _class2 (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/containers/layout/AppLayoutContainer.js:1:1960)\n    at Injector (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at <anonymous> (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at <anonymous> (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at Routes (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/routes.js:1:2629)\n    at Injector (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at IntlProvider (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/node_modules/react-intl/src/components/provider.js:81:47)\n    at I18N (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/I18n.js:1:504)\n    at Injector (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at Provider (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/node_modules/mobx-react/index.js:1328:7)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.settings` of type `Object` supplied to `_class2`, expected instance of `_class`.","\n    at _class2 (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/components/layout/Sidebar.js:1:2094)\n    at Injector (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at injectIntl(inject-_class2-with-stores-actions)\n    at div\n    at div\n    at _class2 (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/components/util/ErrorBoundary/index.js:1:1023)\n    at Jss (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/node_modules/react-jss/lib/createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at _class2 (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/components/layout/AppLayout.js:1:2715)\n    at Jss (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/node_modules/react-jss/lib/createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at ThemeProvider (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/node_modules/theming/dist/cjs/create-theme-provider.js:66:7)\n    at _class2 (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/containers/layout/AppLayoutContainer.js:1:1960)\n    at Injector (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at <anonymous> (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at <anonymous> (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at Routes (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/routes.js:1:2629)\n    at Injector (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at IntlProvider (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/node_modules/react-intl/src/components/provider.js:81:47)\n    at I18N (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/I18n.js:1:504)\n    at Injector (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at Provider (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/node_modules/mobx-react/index.js:1328:7)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.settings` of type `Object` supplied to `_class`, expected instance of `_class`.","\n    at _class (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/features/nightlyBuilds/Component.js:1:2135)\n    at Injector (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at Jss (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/node_modules/react-jss/lib/createHoc.js:138:7)\n    at injectIntl(Jss(inject-_class-with-stores-actions))\n    at div\n    at div\n    at div\n    at _class2 (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/components/util/ErrorBoundary/index.js:1:1023)\n    at Jss (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/node_modules/react-jss/lib/createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at _class2 (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/components/layout/AppLayout.js:1:2715)\n    at Jss (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/node_modules/react-jss/lib/createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at ThemeProvider (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/node_modules/theming/dist/cjs/create-theme-provider.js:66:7)\n    at _class2 (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/containers/layout/AppLayoutContainer.js:1:1960)\n    at Injector (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at <anonymous> (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at <anonymous> (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at Routes (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/routes.js:1:2629)\n    at Injector (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at IntlProvider (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/node_modules/react-intl/src/components/provider.js:81:47)\n    at I18N (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/I18n.js:1:504)\n    at Injector (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/node_modules/mobx-react/index.js:616:9)\n    at Provider (/tmp/.mount_Ferdi-cuseWH/resources/app.asar/node_modules/mobx-react/index.js:1328:7)"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"You are using Ferdi without a server"}],"workspaces":[],"windowSettings":{"width":800,"height":600,"isMaximized":true,"isFullScreen":false,"displayBounds":{"x":0,"y":0,"width":1366,"height":768}},"settings":{"autoLaunchOnStart":false,"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":true,"confirmOnQuit":false,"minimizeToSystemTray":false,"closeToSystemTray":false,"privateNotifications":false,"clipboardNotifications":true,"notifyTaskBarOnMessage":false,"showDisabledServices":true,"showServiceName":false,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"en-us","darkMode":false,"splitMode":false,"splitColumns":3,"fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":true,"enableGlobalHideShortcut":false,"server":"You are using Ferdi without a server","predefinedTodoServer":"https://app.franztodos.com","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernateOnStartup":true,"hibernationStrategy":300,"wakeUpStrategy":300,"inactivityLock":0,"automaticUpdates":false,"universalDarkMode":true,"userAgentPref":"","adaptableDarkMode":true,"accentColor":"#7266F0","serviceRibbonWidth":55,"iconSize":20,"sentry":false,"nightly":false,"navigationBarBehaviour":"custom","searchEngine":"duckDuckGo","useVerticalStyle":false,"alwaysShowWorkspaces":false,"liftSingleInstanceLock":false,"enableLongPressServiceHint":false,"proxyFeatureEnabled":false,"onlyShowFavoritesInUnreadCount":false,"locale":"en-US","customTodoServer":""},"features":{},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}

### Additional Information

I tried 5.6.4-nightly, the issue is on this version as well. 
I have used Rambox before, it did show the badge

**Comment by vraravam** [comment] 2021-11-25 13:29
This was just merged. Please see https://github.com/getferdi/recipes/pull/773

**Closed by vraravam** 2021-11-25 13:29 UTC
Labels: bug :beetle:

**Comment by mizzunet** [comment] 2021-11-25 13:30
Thank you very much!

**Comment by mizzunet** [comment] 2021-11-26 13:05
>  it should appear in the next nightly 

I tried `nightly-17`. Where the issue still exists. 

I guess the commit hasn't been included for the version https://github.com/getferdi/ferdi/compare/v5.6.4-nightly.16...v5.6.4-nightly.17

**Comment by DominusExult** [comment] 2021-11-26 15:57
I'm also on .17 and still don't see notifications for Proton

**Comment by vraravam** [comment] 2021-11-27 00:54
Please wait for the next nightly - the code might not have merged in time.

**Comment by mizzunet** [comment] 2021-11-27 00:57
Sure :+1: 

Well, I also had tried applying its [commits](https://github.com/getferdi/recipes/pull/773/commits) manually for nightly 16, but it didn't work either.

**Comment by vraravam** [comment] 2021-11-27 01:00
I just built locally - and am able to see the "Services have been updated - Reload" blue bar on the bottom. After this, my Protonmail recipe shows version `1.3.2`

**Comment by mizzunet** [comment] 2021-11-27 01:09
Do you use ProtonMail? Can you confirm badge if appears?

**Comment by DominusExult** [comment] 2021-12-04 10:00
I've updated to all nightlies that were released since then and couldn't get the notification to show. Even tried to delete all recipes in ~/Library/Application Support/Ferdi/recipes but after starting Ferdi it fetched the old recipes again.
Only by manually updating the proton-mail recipe in that folder did the notifications begin to work.

So the question is how do I get the nightlies to fetch the current recipe and why is it not doing that automatically?

**Comment by vraravam** [comment] 2021-12-04 10:09
The only reason that that would happen, @DominusExult , would be if the versions of the recipe were not older based on semantic versioning. As part of the our review process, we have automated checks for this in place.

If you have the older recipe backed up, could you please verify the `version` of the old one vs the one that you manually put in?

**Comment by vraravam** [comment] 2021-12-04 10:13
I just logged into my protonmail via Ferdi, and I am able to see the badges:
<img width="42" alt="Screenshot 2021-12-04 at 3 42 03 PM" src="https://user-images.githubusercontent.com/69629/144705719-9e6cf8e5-4b8a-4966-bc5a-f38f4e4ff7f2.png">

I'm using version `1.3.2` of the `proton-mail` recipe

**Comment by DominusExult** [comment] 2021-12-04 10:13
the old one was version 1.3.1 as per package.json

**Comment by vraravam** [comment] 2021-12-04 10:17
ok - if you are running the latest nightly (any version beyond when this was merged), the installer package should contain the new version of the recipe, and should prompt you with a ribbon on the lower edge of Ferdi. When that happens, please restart Ferdi.

**Comment by DominusExult** [comment] 2021-12-04 10:24
Hmm, there might be the problem:
I'm downloading the dmg for macOS. In the contained app bundle I can find the recipes in contents/resources/app.asar.unpacked and all are Gzipped.
*BUT* the proton-mail.gz contains version 1.3.1 not the newest one.
Same for Skype, btw. (version 3.2.2 *NOT* 3.2.3)

So the release script is messing this up for some reason

**Comment by vraravam** [comment] 2021-12-04 10:34
which version have you downloaded?

**Comment by DominusExult** [comment] 2021-12-04 10:42
5.6.4-nightly.23 and of that I downloaded Ferdi-5.6.4-nightly.23.dmg and Ferdi-5.6.4-nightly.23-arm64.dmg (even though I don't have an Arm64 mac - just to verify it has the same problem, which it has)

**Comment by DominusExult** [comment] 2021-12-04 10:45
And just for checking there, the ferdi-5.6.4-nightly.23.x86_64.rpm also has the old version. Which all seems to me is pointing at a problem with the nightly script, not getting the nightly recipes but a release tag or so.

**Comment by vraravam** [comment] 2021-12-04 11:59
Yes - I have just confirmed that this is the behavior. I have also downloaded v24 of the nightly which hasn't been released yet, and this has the same issue. I will have to investigate what's happening. For now, I have manually merged the submodule, and this should show up in the next nightly correctly.

**Comment by vraravam** [comment] 2021-12-04 12:02
Let me trigger an off-band nightly release now - will be available after 30 mins

**Comment by DominusExult** [comment] 2021-12-04 12:07
Thanks, I'll revert my manual upgrade and will then report back whether it updates (which I'm sure it will).

**Comment by vraravam** [comment] 2021-12-04 12:37
@DominusExult - thanks - just released nightly-25 and i confirmed that the recipes have been upgraded.

**Comment by mizzunet** [comment] 2021-12-04 15:19
Working perfectly on `25`. Thank you very much :+1:

**Comment by DominusExult** [comment] 2021-12-04 15:40
yes, 25 is working for me as well now. Services asked to be reloaded and then it worked.

BUT, sorry, could it be made that the badge only refers to the inbox instead of "All Mail"? "all Mail" includes Spam messages as well which is fairly annoying to have notifications for IMO.

@vraravam do you need a proper issue for the nightlies not including nightly recipes?

**Comment by mizzunet** [comment] 2021-12-04 15:45
I actually prefer `All Mail` count.
The way get notification count is defined at `webview.js`

**Comment by vraravam** [comment] 2021-12-04 15:47
@DominusExult - no, afaik, the commit that I have done based on your earlier comment should fix the build not picking up the latest recipes.

and as @mizzunet said above, this is the default (to include `all mail`)

**Comment by DominusExult** [comment] 2021-12-04 15:48
yeah, I figured this is a touchy subject. I'll try and find out which is the correct change for only showing the inbox count.

**Comment by DominusExult** [comment] 2021-12-04 16:16
Hmm, this exceeds my abilities. Tried comparing to Gmail but again, I don't understand most of what it does.
Btw. for Gmail it shows only the Inbox counter not the All Mail counter.
