### ISSUE TITLE
purple screen of death

### ISSUE THREAD

**Issue by schapira** [getferdi/ferdi#1294] opened 2021-04-25 06:21 UTC
A few minutes after long loading ferdi became purple screen and stay like that even hours. 
using on win 10, cant check ferdi version but I keep it update.
version might be last beta, last actions was to try the nextcloud recipes

**Comment by schapira** [comment] 2021-04-25 06:23
version might be last beta, last actions was to try the nextcloud recipes

**Comment by vraravam** [comment] 2021-05-01 05:47
@schapira - did you use Ferdi with a login - if so, was it franz server or ferdi server?

1) Delete your ferdi profile on your local machine - if you were using Ferdi with a server, then all your profile data will get resurrected.
2) If it is with a server, I would suggest that you try to [login](https://meetfranz.com/login) and edit your profile/saved services - to remove the ones that you think might be the cause of the issue.

Please report back as to which step worked - and after that, we can try to check if there's any other debugging / help that is needed.

**Comment by atin** [comment] 2021-05-01 08:34
possible duplicate of #873 ?

**Comment by MosheGross** [comment] 2021-05-04 01:03
For me this worked.

Move the entire Ferdi folder in appdata to a different location.
Relaunch Ferdi.
Replace the new Ferdi folder with the old one.

**Comment by vraravam** [comment] 2021-05-22 09:52
@schapira - do you have any updates on the workarounds suggested above?

**Comment by mhatvan** [comment] 2021-09-19 06:54
Closing due to inactivity.

**Closed by mhatvan** 2021-09-19 06:54 UTC
Labels: feedback wanted
