### ISSUE TITLE
Only HTML version available for Gmail

### ISSUE THREAD

**Issue by mathiasmayrhofer** [getferdi/ferdi#1803] opened 2021-08-16 12:37 UTC
Hi,
since today I am only able to access the HTML version of all my Gmail accounts.
This is the message: "You’re about to use a version of Gmail designed for slower connections and legacy browsers. To get all of Gmail’s features, including inbox categories, images, and quick actions, please use the latest version of Gmail (recommended)."

My connection has not changed and I reconnected service/reinstalled Ferdi. How can I fix this issue?
I'm on the latest version of Windows 10.

**Comment by vraravam** [comment] 2021-08-16 12:40
Duplicate of #1779 - Please see over there for a workaround.

**Closed by vraravam** 2021-08-16 12:40 UTC
