### ISSUE TITLE
Reddit notification links open outside of Ferdi

### ISSUE THREAD

**Issue by CaptainFrosty** [getferdi/ferdi#1994] opened 2021-09-26 20:50 UTC
**Bug description:**
Clicking on any links from Reddit notifications opens them in the default browser instead of Fervi

**Steps to reproduce:**

1. Go to Reddit service
2. Click on notification bell icon at top of page
3. Click a link to a post
4. Opens outside of application

**Expected behavior**

Post opens as others do when clicking on them

**Screenshots**

**Environment:**

- Operating System:  Windows 10 Home
- Ferdi Version:  5.6.2
- Server:  Ferdi

- Debug information:

**Comment by vraravam** [comment] 2021-11-16 11:57
Duplicate of #1501

**Closed by vraravam** 2021-11-16 11:57 UTC
