### ISSUE TITLE
Won't upgrade on ubuntu 21.10 (deb package)

### ISSUE THREAD

**Issue by jasmines** [getferdi/ferdi#2241] opened 2021-11-16 09:41 UTC
I was running 5.6.2, went to settings/upgrade but no upgrades were available nor searched.
I had to download and upgrade manually.
Please solve.

**Comment by vraravam** [comment] 2021-11-16 10:10
@jasmines - please search for other tickets that have the same issue.

Closing as a duplicate of #329

**Closed by vraravam** 2021-11-16 10:10 UTC
