### ISSUE TITLE
Enable Password Lock - crash Ferdi

### ISSUE THREAD

**Issue by aurelien-castel** [getferdi/ferdi#873] opened 2020-07-09 15:27 UTC
**Bug description:**
Enabling Password Lock make the app unusable

**Steps to reproduce:**
1. Go to Settings
2. Click on Enable Password Lock
3. Click on Reload
4. The app is unusable stucked on a purple screen (even after reloading)

**Expected behavior**
The app should not be stucked

**Screenshots**
After clicking on Enable Password Lock:
![Capture d’écran du 2020-07-09 17-16-20](https://user-images.githubusercontent.com/45433718/87058423-5af8c080-c208-11ea-935b-71b3fc8403dd.png)
After clicking on Reload:
![Capture d’écran du 2020-07-09 17-16-42](https://user-images.githubusercontent.com/45433718/87058600-8e3b4f80-c208-11ea-9852-8236836896ba.png)

**Environment:**
- Operating System: Linux (Pop OS 20.04)
- Ferdi Version: 5.5.0
- Server: Using without an account

- Debug information:
Sorry can't get it (clicking on ?>Copy Debug Information doesn't paste any information). 
If anyone has this problem I solved it by deleting the .var/app/com.getferdi.Ferdi file

**Comment by xardinero** [comment] 2020-07-10 01:33
> **Bug description:**
> Enabling Password Lock make the app unusable
> 
> **Steps to reproduce:**
> 
>     1. Go to Settings
> 
>     2. Click on Enable Password Lock
> 
>     3. Click on Reload
> 
>     4. The app is unusable stucked on a purple screen (even after reloading)
> 
> 
> **Expected behavior**
> The app should not be stucked
> 
> **Screenshots**
> After clicking on Enable Password Lock:
> ![Capture d’écran du 2020-07-09 17-16-20](https://user-images.githubusercontent.com/45433718/87058423-5af8c080-c208-11ea-935b-71b3fc8403dd.png)
> After clicking on Reload:
> ![Capture d’écran du 2020-07-09 17-16-42](https://user-images.githubusercontent.com/45433718/87058600-8e3b4f80-c208-11ea-9852-8236836896ba.png)
> 
> **Environment:**
> 
>     * Operating System: Linux (Pop OS 20.04)
> 
>     * Ferdi Version: 5.5.0
> 
>     * Server: Using without an account
> 
>     * Debug information:
>       Sorry can't get it (clicking on ?>Copy Debug Information doesn't paste any information).
>       If anyone has this problem I solved it by deleting the .var/app/com.getferdi.Ferdi file

Hi. Where can I find this file? I have arch but don't see a .var folder or that com.getferdi.Ferdi file.

Thank you!

**Comment by ogarsan** [comment] 2020-07-15 13:07
Im having the same issue but my screen is black, i guess it's because i had the black mode activated.
Did you manage a way to get it working back again?
Even if it's without the locking feature.
TY

**Comment by aurelien-castel** [comment] 2020-07-15 13:48
Hi, try to delete your Ferdi user data folder and relaunch Ferdi. On Windows, maybe in AppData doing Win+R and entering %appdata%. I don't know on Mac.

**Comment by ogarsan** [comment] 2020-07-15 15:12
Hi thank you, i managed to fix it. For reference I'm using Fedora, i went to /home/USER/.config/Ferdi/config/ and opened the settings.json file, then i changed the "lockingFeatureEnabled": option back to false, that fixed it without having to set my whole profile again.

**Comment by kelmee** [comment] 2020-08-14 13:46
> 
> 
> Hi, try to delete your Ferdi user data folder and relaunch Ferdi. On Windows, maybe in AppData doing Win+R and entering %appdata%. I don't know on Mac.

This fixed my issue (**Permanently blacked out after selecing the lock feature #917**)[Idk how to link to my post on git sorry].
I went to appdata and just deleted the whole folder, on reopening I got a fresh login screen. 
I wonder if this happen only when you are in no-account mode?

**Comment by kelmee** [comment] 2020-08-14 13:59
Any word on whether this might be fixable? 
The locking feature was a primary decision factor for me trying Ferdi

**Comment by sam1am** [comment] 2020-08-17 17:25
You don't need to delete your entire ferdi folder in appdata. Go to AppData\Roaming\Ferdi\config and edit the settings.json file. 

Make sure the lockingFeatureEnabled line says "false" 

`  "lockingFeatureEnabled": false,` 

Also looking forward to a fix for this!

**Comment by Sanjay-marwal** [comment] 2020-08-17 23:16
The same issue, I found but I got my profile back after using the aforementioned methods. Regards

**Comment by kris7t** [comment] 2020-12-04 23:06
Not stale.

**Comment by iamsababa** [comment] 2021-01-19 16:39
Bug still exists.

**Comment by PabloSzx** [comment] 2021-03-22 00:01
Not stale

**Comment by muratbulat** [comment] 2021-04-13 13:28
Bug still exists, Windown 10 20H2

**Comment by domi810** [comment] 2021-05-31 08:31
Bug still exists, Windows 10 Pro  21H1

**Comment by vraravam** [comment] 2021-07-20 10:18
I am using Ferdi without a server, and with password locking enabled. I use Ferdi on macos Mojave - and no issue with the latest 5.6.0 that was released a few days ago.

**Comment by mhatvan** [comment] 2021-09-04 17:02
Cannot reproduce this with 5.6.1-nightly.47 on Ubuntu.

Anyone still experiencing this?

**Comment by mhatvan** [comment] 2021-09-10 07:13
Closing due to inactivity.

Please report back in case this still happens with the latest nightly.

**Closed by mhatvan** 2021-09-10 07:13 UTC
Labels: bug, outstanding question
