### ISSUE TITLE
UI glitches make Ferdi unusable for me

### ISSUE THREAD

**Issue by beppe9000** [getferdi/ferdi#299] opened 2020-01-14 17:19 UTC
**Describe the bug**

Service button not working. Probably the integrated server issues.
![button not working](https://i.imgur.com/igACUrV.gif)

Severe update check trolling while I tried to update in order to fix above issue.
![update trolling](https://i.imgur.com/6VUmMGz.gif)

**To Reproduce**
see the gifs

**Expected behavior**
Both buttons doing things

**Screenshots**
See bug description

**Desktop (please complete the following information):**

- OS: Windows Server 2016 14393

**Comment by vantezzen** [comment] 2020-01-14 17:34
The first issue looks to be related to the internal server bug I mentioned and should be fixed in beta 5.
The second issue is probably an issue with how Ferdi communicates with the Electron updater. Can you try activating the option, restarting Ferdi (using File > Quit Ferdi instead of just closing the window) and trying to update?

**Comment by beppe9000** [comment] 2020-01-14 18:46
I tried that before reporting. The setting is off after the restart. :\

**Comment by beppe9000** [comment] 2020-01-14 18:49
Is there setup for the beta ?

**Comment by vantezzen** [comment] 2020-01-15 12:52
The newest beta downloads are available at https://github.com/getferdi/ferdi/releases/tag/v5.4.1-beta.5. Download "Ferdi-Setup-5.4.1-beta.5.exe" to install it on Windows

**Comment by beppe9000** [comment] 2020-01-15 18:18
both problems persist

**Comment by beppe9000** [comment] 2020-01-15 18:55
Also it seem this is related to #253

**Comment by beppe9000** [comment] 2020-03-16 15:25
This command fixed everything for me: `attrib -r "%APPDATA%\Ferdi\server.sqlite"`.
Please consider adding equivalent functionality to the setup and an explicit check during app startup.

**Comment by vantezzen** [comment] 2020-03-18 10:26
Thank you for the report. We are already discussing this issue and are trying all kinds of fixes over at https://github.com/getferdi/internal-server/issues/2 so this isn't anything new. The problem is that Ferdi doesn't seem to be able to remove the write protection - at least with the techniques we tried.

**Closed by vantezzen** 2020-03-18 10:26 UTC
Labels: question

**Comment by beppe9000** [comment] 2020-03-18 13:46
I did some experimenting with the nodejs repl and `fs.chmodSync(dbPath, fs.statSync(dbPath).mode | 146);` worked for me after re-adding the read-only attribute with `attrib +r "%APPDATA%\Ferdi\server.sqlite"`.

**Comment by vantezzen** [comment] 2020-03-19 08:18
Thank you for the suggestion, we'll try if that works.

What is the `| 146` for?

**Comment by beppe9000** [comment] 2020-03-19 12:34
It is supposed to just remove the 'read-only' attribute without affecting anything else.

```
C:\Users\Administrator>node --version
v10.13.0

C:\Users\Administrator>attrib +r %dbPath% & attrib %dbPath%
A    R  I    C:\Users\Administrator\AppData\Roaming\Ferdi\server.sqlite

C:\Users\Administrator>node
> let dbPath = 'C:\\Users\\Administrator\\AppData\\Roaming\\Ferdi\\server.sqlite';
undefined
> fs.chmodSync(dbPath, fs.statSync(dbPath).mode | 146);
undefined
> .exit

C:\Users\Administrator>attrib %dbPath%
A       I    C:\Users\Administrator\AppData\Roaming\Ferdi\server.sqlite
```

See also : https://github.com/gulpjs/gulp/issues/1057#issuecomment-99211021
