### ISSUE TITLE
No icon is visible on Mac version

### ISSUE THREAD

**Issue by Bit2Rich** [getferdi/ferdi#1152] opened 2021-01-12 02:24 UTC
I am using the Mac version with the latest update. When I set a custom icon, I am not able to view any icon that I have a custom set. If it's the default icon, the icon shows up with no problem.

**Comment by n00bundercover** [comment] 2021-03-25 00:12
Same on Linux, SolusOS. Both: Icon not changing to custom icon, instead showing no icon at all. When resetting, it will show the default icon for this session, but as soon as you restart Ferdi it's back to no icon at all.

**Comment by c4tb3rt** [comment] 2021-04-15 11:36
I have the same problem on MacOS 11.2.3 and ond Windows 10.

**Comment by matheusfillipe** [comment] 2021-04-25 04:38
Same problem on arch linux.

OS: Arch Linux x86_64, DE: KDE Plasma 5.20.2, CPU: Intel i7-7700HQ (8) @ 3.800GHz, GPU: NVIDIA GeForce GTX 1050 Ti Mobile, GPU: Intel HD Graphics 630, Memory: 15.5 GiB

**Comment by mhatvan** [comment] 2021-09-04 16:12
Cannot reproduce this, seems it was fixed by the PR linked above.

Custom icon shows correctly on both macOS and Ubuntu, also after restarting Ferdi.

**Closed by mhatvan** 2021-09-04 16:12 UTC
