### ISSUE TITLE
Since 5.6.3.beta2 cannot be shown from system tray icon

### ISSUE THREAD

**Issue by norbusan** [getferdi/ferdi#2147] opened 2021-10-27 04:38 UTC
Till 5.6.3.beta1 I could left/right click on the icon in the system tray and click on "Show Ferdi" to make it appear.

Since 5.6.3.beta2 this functionality is gone and the main window doesn't reappear.

**Steps to reproduce:**

1. Activate "Keep Ferdi in background when closing the window" in the settings
2. Close the Window, the icon remains in the system tray
3. Click on the system tray icon, a menu is shown with "Show Ferdi" "Disable Notification & Audio" "Quit Ferdi"
4. Select "Show Ferdi"

**Expected behavior**

The main window reappears

**Environment:**

- Operating System: Linux (Debian/unstable)
- Ferdi Version: 5.6.3.beta2 and 5.6.3.beta3
- Server: Ferdi

**Comment by norbusan** [comment] 2021-11-07 23:56
Still presetn in release 5.6.3, Linux, Plasma desktop

**Comment by lysutchi** [comment] 2021-11-08 00:17
The issue is also present in release 5.6.3 in Windows 11 version 21H2.

**Comment by droideparanoico** [comment] 2021-11-08 07:22
Present in 5.6.3 with Ubuntu linux 21.10

**Comment by Mowto** [comment] 2021-11-08 08:13
Launching Ferdi from a terminal i get this error when i push "Show Ferdi" from the systray icon menu:

TypeError: Cannot read properties of undefined (reading 'isMinimized')
    at click (/tmp/.mount_FerdiDJb5fn/resources/app.asar/lib/Tray.js:1:692)

**Comment by vraravam** [comment] 2021-11-08 09:56
I have just merged a fix based on https://github.com/getferdi/ferdi/issues/2147#issuecomment-962907993 - but, please try out the next nightly (in another 16+ hours I would think)

**Comment by norbusan** [comment] 2021-11-08 10:16
Hmm, from quick reading of the code (but without any knowledge of the code base), that would just return and not restore the image, since the code flow will never reach the restore line?!

**Comment by Shrekmachine** [comment] 2021-11-08 13:46
How would I be able to apply fix? I made mistake to start Ferdi minimized so I'm no longer able to reach settings

**Comment by FeikoJoosten** [comment] 2021-11-08 13:51
This bug is even better if you've set Ferdi to launch minimized. As I'm now unable to open Ferdi at all. I had to rollback to 5.6.2 until a proper fix is available.

**Comment by Shrekmachine** [comment] 2021-11-08 14:09
I found a workaround. Starting the ferdi.exe brings the window up. by this settings can be changed

**Comment by sgautrin** [comment] 2021-11-08 15:23
> This bug is even better if you've set Ferdi to launch minimized. As I'm now unable to open Ferdi at all. I had to rollback to 5.6.2 until a proper fix is available.

I got the exact same issue. Just got prompted with the new 5.6.3 version, updated, and then Ferdi just sits there in the task bar and impossible to open it. I do have the “Show Ferdi” option when I righ click the icon in the task bar, it just does nothing at all.

Starting it from command line I indeed also get the same error when trying to open it from tray
```
TypeError: Cannot read properties of undefined (reading 'isMinimized')
```

**Comment by Shrekmachine** [comment] 2021-11-08 16:46
The workaround should enable you to change the setting. I hope it helps

**Comment by sgautrin** [comment] 2021-11-08 17:37
I just rolled back to the previous version and will wait until a new version fixes that. That lets me keep current behaviour, which is much more preferable to changing the settings.
Though I think I had tried to execute Ferdi.exe again without success, but I'm not sure now (possibly I had closed Ferdi between each tries to execute it)

**Comment by norbusan** [comment] 2021-11-09 03:50
Hi @vraravam 
as I suspected, the code change you made does not fix the bug. The only thing it does is hiding the error message
```
TypeError: Cannot read properties of undefined (reading 'isMinimized')
```

To quote the current code from `Tray.js`:
```
      label: 'Show Ferdi',
      click() {
        if (!app.mainWindow) {
          return;
        }
        if (app.mainWindow.isMinimized()) {
          app.mainWindow.restore();
        } else if (app.mainWindow.isVisible()) {
          app.mainWindow.hide();
        } else {
          app.mainWindow.show();
          app.mainWindow.focus();    
        }
      },
```
The introduced code change returns when `app.mainWindow` is not defined, but comparing it with the previous code it should be. I don't see why the app.mainWindow got destroyed when closing it to the Notification area, though.

**Comment by vraravam** [comment] 2021-11-09 08:38
I suspect the code sequence where the `mainWindow` is defined (not in `Tray.js`) to be the culprit. Unfortunately, I have to step back into work (and am travelling for the rest of this week) to be able to debug this further. Will have to request the other contributors to take this up.

cc @sad270 @mhatvan - do you have bandwidth for this?

**Comment by CiteopehtEripmav** [comment] 2021-11-09 14:24
I ask for forgiveness if I manage to stick my foot in my mouth with this, but this block of code inside Tray.js doesn't make sense to me

        if (app.mainWindow.isMinimized()) {
          app.mainWindow.restore();
        } else if (app.mainWindow.isVisible()) {
          app.mainWindow.hide();
        } else {
          app.mainWindow.show();
          app.mainWindow.focus();    
        }

Isn't the whole idea of clicking the Ferdi icon, or Show Ferdi menu item, to show the application or make it pop into visibility? If so, why hide it? Shouldn't the code be something like the following?

        if (app.mainWindow.isMinimized()) {
          app.mainWindow.restore();
        } else if (app.mainWindow.isVisible()) {
          app.mainWindow.show();
        } else {
          app.mainWindow.focus();    
        }

I searched for all instances of mainWindow inside all of the JS files from the source code and found that Tray.js was the only one that had that block written with hide, instead of show. Not sure if this will help, but there's no worst attempt than one that's never made. I really hope it helps. May you all have a great day.

**Comment by norbusan** [comment] 2021-11-09 14:42
Hi

> ```
>     if (app.mainWindow.isMinimized()) {
>       app.mainWindow.restore();
>     } else if (app.mainWindow.isVisible()) {
>       app.mainWindow.show();
>     } else {
>       app.mainWindow.focus();    
>     }
> ```

Why would you want to `show` the main window when it is already visibile?

The point is to show it when it is hidden.

**Comment by FeikoJoosten** [comment] 2021-11-09 14:42
>    if (app.mainWindow.isMinimized()) {
      app.mainWindow.restore();
    } else if (app.mainWindow.isVisible()) {
      app.mainWindow.hide();
    } else {
      app.mainWindow.show();
      app.mainWindow.focus();    
    }

This code hides the window if clicked when visible, and shows + focusses the window if clicked when hidden.

**Comment by vraravam** [comment] 2021-11-09 16:14
Sorry - I dont use the tray icon at all, and so cannot comment on whether the fix works. The logic is as per what @FeikoJoosten had stated in the above comment.

**Comment by CiteopehtEripmav** [comment] 2021-11-09 16:32
I was thinking it more as a way to force the window to the front, but I do understand all of the points expressed. Thank you all for the feedback.

**Comment by arturh85** [comment] 2021-11-09 19:23
If you are stuck because of startMinimized: true you can revert his in ~\AppData\Roaming\Ferdi\config\settings.json

**Comment by martinbernat** [comment] 2021-11-13 18:09
@mhatvan, looks like this was caused by your https://github.com/getferdi/ferdi/pull/2049 - you've removed the `app.mainWindow = mainWindow;` assignment, therefore `app.mainWindow` is not defined in `Tray.js`

I've a fix for this, getting the mainWindow from `BrowserWindows` like this:
`let mainWindow = BrowserWindow.getAllWindows()[0];`

Assuming we always have only one window. Not completely sure about this, but works. I'll test that a bit more, and I can prepare a PR then.
Feel free to correct me if I'm going in the wrong direction.

**Comment by mhatvan** [comment] 2021-11-15 20:47
Hey all, sorry for causing this regression. The codebase is pretty outdated and legacy, so even small cleanups can cause big problems. 

@martinbernat thank you for taking the initiative on this and figuring out a great solution. Everything sounds better than just randomly assigning non-existent values onto variable like `app.mainWindow` how it was the case before.

**Closed** 2021-11-15 23:38 UTC
Labels: bug
