### ISSUE TITLE
Service Developer Tools not available

### ISSUE THREAD

**Issue by copitz** [getferdi/ferdi#147] opened 2019-10-21 14:48 UTC
**Describe the bug**
The service developer tools are disabled in the view menu and also the keyboard shortcut doesn't do anything. What's possible is to open the developer tools of Ferdi and run `ferdi.actions.service.openDevToolsForActiveService()` in its console.

**To Reproduce**
1. Select any service
2. Click on View -> "Toggle Service Developer Tools" will be disabled
3. Press Ctrl/Cmd+Shift+Alt+i -> Nothing will happen

**Expected behavior**
- The menu item "View -> Toggle Service Developer Tools" shouldn't be disabled
- The shortcut "Ctrl/Cmd+Shift+Alt+i should bring up the service developer tools

**Screenshots**

**Desktop (please complete the following information):**

- OS: Linux Mint 18
- Version 5.3.3
- Using Franz API server - tasks disabled

**Comment by vantezzen** [comment] 2019-10-21 15:53
Can't reproduce on Mac, can anyone on Windows and Linux confirm this?

@copitz Can you please execute this code in the developer tools and share the output here:
```js
console.log(
 'isLoggedIn',
 window.ferdi.stores.user.isLoggedIn ? 'y' : 'n',
 'enabledServices',
 window.ferdi.stores.services.enabled.length ? 'y' : 'n'
);
```
These are the two checks [required to enable the menu option](https://github.com/getferdi/ferdi/blob/develop/src/lib/Menu.js#L755). I suspect this bug could be due to the [Menu constructor](https://github.com/getferdi/ferdi/blob/develop/src/lib/Menu.js#L709) not using `@observer`.

**Comment by Makazzz** [comment] 2019-10-22 00:16
@vantezzen Everything is working on windows with this build commit 07a52285111f6f5d1fbf15f0e9055187ef67d612

**Comment by vantezzen** [comment] 2019-10-24 13:41
The menu should normally dynamically change as soon a value changes - but in this case it doesn't. At least we now know that the problem is in the Menu constructor and not in the stores.

**Comment by arioki1** [comment] 2021-02-19 10:35
i still find this problem in version 5.6.0-nightly.15 @vantezzen 
I use linux and run this command in togle developers tools
```
console.log(
 'isLoggedIn',
 window.ferdi.stores.user.isLoggedIn ? 'y' : 'n',
 'enabledServices',
 window.ferdi.stores.services.enabled.length
);
```
Result
`isLoggedIn y enabledServices 14`

what should I do to fix this issue @vantezzen

**Comment by mhatvan** [comment] 2021-08-08 10:25
@arioki1 can you take another look with the latest nightly? I use Ubuntu and can toggle all dev tools just fine.

**Comment by mhatvan** [comment] 2021-09-04 16:42
Seems it was fixed with the PR linked above.

**Closed by mhatvan** 2021-09-04 16:42 UTC
Labels: bug
