### ISSUE TITLE
No system tray icon in elementaryOS 5.1.7

### ISSUE THREAD

**Issue by WebShapedBiz** [getferdi/ferdi#1154] opened 2021-01-14 07:27 UTC
There is no system tray icon in elementaryOS 5.1.7

- Operating System: elementaryOS 5.1.7 (Ubuntu 18.04.4 LTS based)
- Ferdi Version: 5.5.0
- Server: Ferdi

Cheers.

**Comment by alexthamm** [comment] 2021-02-12 11:39
Same here on Ubuntu with AwesomeWM:
```
$ awesome --version
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

I couldn't find a "dubugging" guide. Please let me know if (and how) I can provide you with relevant information to get this fixed.

**Comment by kris7t** [comment] 2021-02-12 16:01
Duplicate of #437 

Unfortunately, this is not that simple to debug, because the problem is in Chromiums DBusNotifier implementation that Electron uses to show tray icons. The DBusNotifier support in various desktop environments is highly irregular, so it's no surprise Chromium (which has to support a bunch of other APIs for tray icons on various other platforms) doesn't support it fully properly.

As a way forward, we should skip on Chromium's tray icon support (at least on Linux) and roll our own DBusNotifier implementation in Javascript. But this is far from trivial (pull requests are of course welcome, though).

**Closed by kris7t** 2021-02-12 16:01 UTC
Labels: bug, duplicate
