### ISSUE TITLE
System tray icon doesn't open ferdi

### ISSUE THREAD

**Issue by Dedi-Data** [getferdi/ferdi#2262] opened 2021-11-21 08:18 UTC
Hi,
Thank you for this great open source application
in new version, when I click on the system tray icon, it doesn't open the Ferdi window when I minimize it

Thank you

**Comment by vraravam** [comment] 2021-11-21 08:23
Duplicate of #2234 

(Please do search more thoroughly for tickets around the same issue - including closed ones).

**Closed by vraravam** 2021-11-21 08:23 UTC
