### ISSUE TITLE
Per-service "Disable hibernation" option not always saved

### ISSUE THREAD

**Issue by MurzNN** [getferdi/ferdi#763] opened 2020-05-22 06:39 UTC
I enable global hibernation feature, and try to disable it for most part of my services. On first (Gmail) and second (Riot) service "Disable hibernation" option is enabled and saved successfully. But for other services (Skype, VK, custom webpage, etc) - it enables in interface well, but resets to "off" when app is restarted.

Can you describe where can be the problem? In which file this option is stored?

**Comment by vantezzen** [comment] 2020-05-22 11:53
Duplicate of #715. The bug has now been fixed - this fix will be released with the next version of Ferdi.

**Closed by vantezzen** 2020-05-22 11:53 UTC
