### ISSUE TITLE
Add Signal messenger to Ferdi

### ISSUE THREAD

**Issue by Myalternativea** [getferdi/ferdi#1177] opened 2021-01-31 13:01 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Myalternativea** [comment] 2021-01-31 13:04
Hello Ferdi Team,
Could you add Signal Messenger to Ferdi?
As you know, Signal messenger could be installed on Windows PC§
Thank you

**Comment by lecoredump** [comment] 2021-02-01 12:57
Although not on the support / development team, from what I know, all clients currently supported by `Ferdi` are the web versions "packaged" in some way. Contrary to other applications, Signal doesn't come with an existing web application that can be simply accessed through a URL. 

The Signal Desktop client, even though it also runs on `electron`, would require being distributed directly within the Ferdi client, which doesn't seem to be its purpose. I'm not sure this would allow its integration moving forward.

**Comment by kris7t** [comment] 2021-02-01 13:12
Duplicate of #1155.

Please see https://github.com/getferdi/ferdi/issues/1155#issuecomment-766143811 on why Signal is unlikely to be added.

**Closed by kris7t** 2021-02-01 13:12 UTC

**Comment by Myalternativea** [comment] 2021-02-01 15:26
Hello,
Thank you for your quick reply.
But, I advice you that, Signal has a web application ( windows, Mac and
Linux). This is the URL:
https://signal.org/fr/download/windows/
Please check and I hope that it can be integrated to Ferdi.

Best regards

----
Bouazza EL KHALFI

**Comment by kris7t** [comment] 2021-02-01 15:53
@Myalternativea This is not a web application, but an Electron application that needs download.

We can't distribute Signal's downloads (either in part or in full) without violating their trademarks. While Signal is open source, only the Signal Foundation is allowed distribute clients with the Signal branding that can communicate with the official Signal servers. Thus, the ecosystem is not open at all.

Either the Signal Foundation would need to relax their trademark policy (which is unlikely, as their position regard the need for a centrally controlled ecosystem to ensure optimal user experience is both explicit and deliberate), or they'd need to release a client that runs in a web browser (as opposed to an Elector download), which would be extremely technically challenging due to the way they manage encryption keys).

**Comment by Myalternativea** [comment] 2021-02-01 16:03
Hello,

I understand now,

Hope that Signal Foundation will do the necessary in the next future.

Thank you

----
Bouazza EL KHALFI

Le lun. 1 févr. 2021 à 16:53, Kristóf Marussy <notifications@github.com> a
écrit :
