### ISSUE TITLE
Invalid password after upgrade to 5.6.0-beta.2

### ISSUE THREAD

**Issue by sad270** [getferdi/ferdi#845] opened 2020-06-24 16:37 UTC
**Bug description:**
I upgrade Ferdi to 5.6.0-beta.2 and when i try to unlock ferdi with my pasword (set on previous version of Ferdi) he say it is invalid.
I think it's related with #694 

To fix it i rollback to Ferdi 5.5.0 clear my password and disable the pasword, reinstall Ferdi 5.6.0-beta.2 and go to config to enable password protection and set my password

And to upgrade to Ferdi 5.6.0-beta.2, I don't update from the Ferdi settings because he doesn't find the beta and i can't wait :) so I download the .dmg from github release page and install it

**Steps to reproduce:**

1. Enable password protection on Ferdi 5.5.0
2. Set password on Ferdi 5.5.0
3. Download and install Ferdi 5.6.0-beta.2
4. Try to unlock Ferdi

**Expected behavior**
Unlock Ferdi with the same password of my old version of Ferdi

**Screenshots**

**Environment:**

- Operating System: macOS Catalina
- Ferdi Version: 5.6.0-beta.2
- Server: Ferdi

**Comment by sad270** [comment] 2020-06-26 09:13
I don't know how Ferdi settings work. But I think we should use a hidden configuration 'password_hash_type' to store the hash algorithm used
If no 'password_hash_type' set that's means it's plain password

And on the unlock we check if password is good, with the hashtype, if it's good, and the hash_type is not set, we update the stored password.

This can be isefull if we decide to change the hash for using a strongest hash. We juste change the hash_type and when we will upgrade from old hash to new strongest hash we don't have this issue again ?

What do you think ?

**Comment by vraravam** [comment] 2021-07-20 10:19
Possible duplicate of #1672 ?

**Comment by sad270** [comment] 2021-07-20 10:35
Yes it's seems to be the same.
In Ferdi 5.5 the password wasn't hashed, and in 5.6 we hash the password, there is no backward compatibility when we update 5.5 to 5.6
I fully uninstall Ferdi, remove all local files, and reinstall 5.6, sync with my Ferdi server account. The password is stored locally not on the Ferdi Server. And I reconfigure the password and everythings back.
A little bit long, but it works for me :)

I'm not going to follow this issue. We can close this one and continue in the duplicate if you want ?

**Comment by vraravam** [comment] 2021-07-20 11:03
Yes - thanks for the details @sad270 . Closing this one now in favor of the linked ticket.

**Closed by vraravam** 2021-07-20 11:03 UTC
Labels: bug, high priority
