### ISSUE TITLE
Latest version shows banner for update

### ISSUE THREAD

**Issue by pookdeveloper** [getferdi/ferdi#2178] opened 2021-11-02 17:47 UTC
Always It show this message, I have the latest version:
![image](https://user-images.githubusercontent.com/3384734/139918284-cc5faad4-c1e6-4d98-8656-5682ec0e43ec.png)

![image](https://user-images.githubusercontent.com/3384734/139918357-c6aea269-77ef-43a5-9844-89a0f71c530c.png)

I use mac with version:
![image](https://user-images.githubusercontent.com/3384734/139918540-e56fd700-338a-4887-9955-9000c194185d.png)

**Comment by vraravam** [comment] 2021-11-02 23:55
Duplicate of #329

**Closed by vraravam** 2021-11-02 23:55 UTC
