### ISSUE TITLE
No tray menu on Linux

### ISSUE THREAD

**Issue by xerus2000** [getferdi/ferdi#484] opened 2020-03-20 15:19 UTC
**Describe the bug**

When right-clicking on the Tray icon, nothing happens.

**Expected behavior**

A menu with the options to Quit or Open Ferdi, just as Franz has it.

**Desktop:**

- OS: KDE Neon (based on Ubuntu)
- Ferdi Version: 5.4.4-beta.3
- Server Used: https://api.getferdi.com

Debug information: https://debug.getferdi.com/fb1e0982-7f91-4e7b-bb55-76bc3ff0b9dd

**Comment by vantezzen** [comment] 2020-03-20 15:30
Probably caused by the changes in #390

**Comment by kytwb** [comment] 2020-05-13 10:49
This has been potentially fixed via https://github.com/getferdi/ferdi/pull/741 and is available for user testing via [5.5.1-nightly.14](https://github.com/getferdi/nightlies/releases/tag/v5.5.1-nightly.14).

**Comment by janhohner** [comment] 2020-05-13 10:53
Context menu is back for me, but the icon disappears after I lock the OS and log back in. I'm using Pop!OS 20.04 (based on Ubuntu 20.04).

**Comment by kytwb** [comment] 2020-05-13 10:56
@janhohner Thank you for the quick feedback! 🙏 I will wait for some more confirmations to see if this also fixes the missing tray icon for some Linux users.

**Comment by kytwb** [comment] 2020-05-13 11:05
@all-contributors please add janhohnr for userTesting

**Comment by kytwb** [comment] 2020-05-13 11:06
@all-contributors please add janhohner for userTesting

**Comment by kytwb** [comment] 2020-05-13 11:30
@janhohner I think the disappearing icon can be discussed following https://github.com/getferdi/ferdi/issues/437#issuecomment-624517015.

**Closed** 2020-05-13 11:35 UTC
Labels: bug
