### ISSUE TITLE
Can't update from 5.6.2 to 5.6.3

### ISSUE THREAD

**Issue by chipse** [getferdi/ferdi#2192] opened 2021-11-08 19:10 UTC
I get a notification that an update is available but when I click the link Ferdi closes down and never opens up again. When I manually restart Ferdi it's still 5.6.2 and the notification appears again.

I'm on a Macbook Pro mid 2015 with a 2,5 GHz Quad-Core Intel Core i7, 6 GB 1600 MHz DDR3 and Intel Iris Pro 1536 MB. Also I'm on Big Sur 11.6.

**Comment by Mark-Turner0** [comment] 2021-11-08 22:26
Having the exact same issue here!

Similar specs to you, but running macOS Monterey 12.0.1. Perhaps a macOS issue?

**Comment by tarikd** [comment] 2021-11-08 22:44
👍

**Comment by haykh** [comment] 2021-11-08 22:55
Same here (macOS 12.0.1). When I click restart & install the app just closes and never opens.

![image](https://user-images.githubusercontent.com/7251306/140831175-83ee01f8-4528-485b-868b-36e6808fc871.png)

**Comment by vraravam** [comment] 2021-11-09 00:48
Duplicate of #329 - please update manually.

**Closed by vraravam** 2021-11-09 00:48 UTC
