### ISSUE TITLE
No system tray menu on right-click

### ISSUE THREAD

**Issue by Govi59** [getferdi/ferdi#1156] opened 2021-01-14 10:51 UTC
**Bug description:**
When right-clicking on the Ferdi system tray icon, an empty and unclickable menu appears.

**Steps to reproduce:**
1. Log in your linux session
2. Ferdi auto-launch, tray icon appears
3. Right-click on the Ferdi tray icon
4. Empty menu appears

**Expected behavior**
Access the system tray menu, be able to click on options such as "quit".

**Screenshots**
![image](https://user-images.githubusercontent.com/22171202/104581481-eee79100-565e-11eb-9bef-d29cc8760f03.png)

**Environment:**
- Operating System: Linux Mint 20 Cinnamon
- Cinnamon Version: 4.6.7
- Ferdi Version: 5.5.0 (x64)
- Server: Using without an account

**Comment by mauro-miatello** [comment] 2021-01-18 11:09
same here, Mint Cinnamon 20.1

**Comment by mauro-miatello** [comment] 2021-03-20 06:39
the issue is still relevant

**Comment by atin** [comment] 2021-05-04 02:45
Same issue. LM 20.1 Cinnamon without account. Any workaround to close it?

**Comment by ajboni** [comment] 2021-06-10 01:41
Seems to be fixed for in 5.6 nightly. LM20.1 Cinnamon

**Comment by BenjaminJacober** [comment] 2021-06-16 06:51
No system tray at all on Gnome 3.38

**Comment by mhatvan** [comment] 2021-07-04 07:48
@BenjaminJacober which Linux OS do you use?
I use Ubuntu 21.04 with GNOME 3.38.5 and it works as expected with 5.6.0-nightly.73

**Comment by mhatvan** [comment] 2021-09-02 20:24
Closing due to inactivity.

**Closed by mhatvan** 2021-09-02 20:24 UTC

**Comment by BenjaminJacober** [comment] 2021-09-02 20:39
Had a similar problem on gnome, problem was resolved wheb updating gammy.
