### ISSUE TITLE
On Windows 11, update to Ferdi.5.6.3, if minimize Ferdi it never show again

### ISSUE THREAD

**Issue by damced** [getferdi/ferdi#2222] opened 2021-11-13 03:41 UTC
On Windows 11, this morning  I updated to Ferdi.5.6.3, all work fine but when minimize Ferdi it never show again, I have to close from Tray Icon and start Ferdi again, and all repeat again it works until minimize, then never will show Ferdi again.

**Comment by vraravam** [comment] 2021-11-13 03:50
Duplicate of #2147

**Closed by vraravam** 2021-11-13 03:50 UTC
