### ISSUE TITLE
Spammed by "Your services have been updated. Reload services"

### ISSUE THREAD

**Issue by slimshizn** [getferdi/ferdi#662] opened 2020-04-27 14:12 UTC
**Describe the bug**
Spammed with "Your services have been updated. Reload services"

**To Reproduce**
Went from 5.3.3 to 5.5.0

Spamming happens on the bottom of the screen constantly.

**Expected behavior**
After one reload should stop getting spammed.

**Screenshots**

**Desktop:**

- OS: [e.g. macOS, Windows 10 etc.]
- Ferdi Version [e.g. 5.4.3]
Windows 10 V 5.5.0

Debug information: https://debug.getferdi.com/...

**Additional context**

**Comment by vantezzen** [comment] 2020-04-27 15:20
Thank you for reporting this. What server are you using?

**Comment by slimshizn** [comment] 2020-04-27 16:02
https://hub.docker.com/r/getferdi/ferdi-server From: BennettSent: Monday, April 27, 2020 11:21 AMTo: getferdi/ferdiCc: slimshizn; AuthorSubject: Re: [getferdi/ferdi] Spammed by "Your services have been updated. Reload services" (#662) Thank you for reporting this. What server are you using?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by slimshizn** [comment] 2020-04-27 17:00
https://hub.docker.com/r/getferdi/ferdi-server

**Comment by bittner** [comment] 2020-04-28 08:17
As a side question, is it possible to download the Ferdi account setup and use that for an offline setup?

- I'd like to use Ferdi without a server to get rid of the mentioned notifications, but I'm afraid to lose the account settings (I have _a lot_ of services and workspaces configured!).
- In the long run, I'd like to go back and forth with "online" and "offline", taking advantage of both worlds.

**Comment by vantezzen** [comment] 2020-04-28 08:26
@bittner Ferdi servers support importing and exporting your data from and to any other Ferdi server. e.g. You can export your data from the Ferdi API from the account dashboard at https://api.getferdi.com/user/login
To import data into the local server (i.e. "Using Ferdi without an account"), you'll have to first choose to use Ferdi without an account - this will start the internal server. You can then visit `http://127.0.0.1:45569` in your browser and follow the instructions there.

**Comment by catarino** [comment] 2020-04-29 16:16
Happening the same. Using or not using an account. 

Unfortunately, following last @vantezzen advice resulted only in duplicating the services. :S

**Comment by vantezzen** [comment] 2020-04-29 17:12
Sorry, looks like I caused a misunderstanding there: My comment was only meant as a reply to @bittner's question and was in no way intended as a fix to your described problem.

**Comment by catarino** [comment] 2020-04-30 11:04
> Sorry, looks like I caused a misunderstanding there: My comment was only meant as a reply to @bittner's question and was in no way intended as a fix to your described problem.

Hi @vantezzen no worries, thanks.

**Comment by slimshizn** [comment] 2020-05-10 17:42
Any info on this? @vantezzen Thanks for your time.

**Comment by zeeh1975** [comment] 2020-05-22 20:34
Still happenning, windows client
Server: https://api.franzinfra.com

![Ferdi_xe1P5SJD8U](https://user-images.githubusercontent.com/1238547/82707442-70169180-9c52-11ea-93db-234ae48f7959.png)

**Comment by vantezzen** [comment] 2020-05-23 16:34
@zeeh1975 Your problem is due to a different reason, please look at #98 for more information about that - this issue is only about this error occurring with Ferdi servers, not Franz's server.

**Comment by zeeh1975** [comment] 2020-05-23 18:41
> @zeeh1975 Your problem is due to a different reason, please look at #98 for more information about that - this issue is only about this error occurring with Ferdi servers, not Franz's server.

Sorry my bad.

**Comment by xapienz** [comment] 2021-02-14 05:28
Same problem happening since yesterday in Ferdi 5.5.0

**Comment by xapienz** [comment] 2021-02-15 01:18
I checked the problem a little bit and found some issues.
First of all, I tried to debug in developer console and found that `remoteUpdates` is empty, but `localUpdates` is not empty here:
https://github.com/getferdi/ferdi/blob/84f28d670a4586d63958438cfd9ca387dcf03ac3/src/stores/RecipesStore.js#L110

I compared `/usr/lib/ferdi/app.asar.unpacked/recipes/all.json` with contents inside `~/.config/Ferdi/recipes/` and see that version number is indeed different, so there is local update pending.

Then I see in the code that it should install local updates, and I see the log in developer console:
```
/usr/lib/ferdi/app.asar/node_modules/@sentry/utils/dist/instrument.js:104 Error: /home/xapienz/.config/Ferdi/recipes/temp/telegram-react/package.json: ENOENT: no such file or directory, open '/home/xapienz/.config/Ferdi/recipes/temp/telegram-react/package.json'
    at Object.openSync (fs.js:440)
    at Object.func [as openSync] (electron/js2c/asar.js:140)
    at Object.readFileSync (fs.js:342)
    at Object.fs.readFileSync (electron/js2c/asar.js:542)
    at Object.readFileSync (/usr/lib/ferdi/app.asar/node_modules/jsonfile/index.js:61)
    at ServerApi.getRecipePackage (/usr/lib/ferdi/app.asar/api/server/ServerApi.js:formatted:279)
```

So looks like `/home/xapienz/.config/Ferdi/recipes/temp/telegram-react/package.json` is missing.
Then I checked contents of `/home/xapienz/.config/Ferdi/recipes/temp/telegram-react`, and I see that `package.json` is missing, but `recipe.tar.gz` exists. So I think that `package.json` should be inside the archive.

However, `recipe.tar.gz` is not a valid archive file, instead it is just a html:
https://gist.github.com/xapienz/3d1f58c3dfc0d44fef8454c8d55acc14

So I think that retrieval of local updates is broken, and I see two issues:
* local updates should not download from the server, so they should not get the html;
* update server seems to return html, but it should return .tar.gz archive.

**Comment by nullredvector** [comment] 2021-05-05 01:35
any fix for this?

**Comment by vraravam** [comment] 2021-07-07 04:42
The tried and tested fix for this "spamming" is to delete the `<ferdiProfile>/recipes` folder and restart Ferdi. Please be sure to use one of the latest Ferdi *nightly builds* from http://github.com/getferdi/nightlies/releases.

The reason for the issue is that when Ferdi starts up, it tries to ensure that the installed recipes (for the services that have been signed-up) are in sync with the pre-packaged recipes that are in the installation package. Any outdated recipes will trigger this blue ribbon - asking the user to reload/restart Ferdi. For some rare cases, this in-place update seems to silently error out. Deleting the `recipes` folder will force this overwrite. HTH.

**Comment by vraravam** [comment] 2021-09-06 23:54
Closing this since this seems like an issue at the installation folder. Feel free to reopen if the above workaround doesn't fix it.

**Closed by vraravam** 2021-09-06 23:54 UTC
Labels: outstanding question
