### ISSUE TITLE
Importing doesn't work, also can't add any services

### ISSUE THREAD

**Issue by ZweiEuro** [getferdi/ferdi#1382] opened 2021-05-10 07:37 UTC
**Bug description:**
Trying to import my franz account gives me this error:
Could not login into Franz with your supplied credentials. Please check and try again.
I double checked the credentials and they work fine for franz.

Trying to create a new account does log me in, but I still can't add any services (described below).

**Steps to reproduce:**

1. Go to 'Add new services'
2. Click on ''All Services"
3. Click on "(e.g) Airtable"
4. Loading symbol briefly appears, then throws me into 'Most popular' with "Sorry, but no service matched your search terms."

This happens with any service I try to add, this also happens when 'not using an account'

**Expected behavior**
Add the service

**Environment:**

- Operating System: Manjaro Linux
- Ferdi Version: 
Name            : ferdi
Version         : 5.5.0-10
according to pacman -Q --info ferdi

**Comment by ZweiEuro** [comment] 2021-05-11 13:54
Where can i find the nightly version?

**Comment by kris7t** [comment] 2021-05-12 00:25
@ZweiEuro I think I figured out what causes the bad button color. I'll need a bit more time to properly create a fix, but will try to push one tomorrow.

**Comment by kris7t** [comment] 2021-05-12 16:50
The visibility issue was fixed in #1398. Do you have other remaining problems?

**Comment by leoheck** [comment] 2021-05-13 23:18
The same is happening for me. Started to happen today after updating my services. https://github.com/getferdi/ferdi/issues/1390
I cannot use or add any service. =/

**Comment by ajboni** [comment] 2021-06-10 01:10
Same here on linux mint on latest beta. It seems that I can only add telegram, whatsapp an hangouts.
Will try stable...

**Comment by edtbl76** [comment] 2021-08-11 03:34
I have the same issue. I shut off my Mac last night, and restarted it this AM. All of my services were gone from Ferdi, and I can no longer add services. Big Sur 10.5. 

Nothing in App Support folder was readonly. *saw this in another thread*

It goes away after a reinstall, but it certainly doesn't instill confidence :(

**Comment by vraravam** [comment] 2021-08-12 15:00
Which version of Ferdi are you using @ajboni @edtbl76 @leoheck ? Please specify that information before we can try to debug the issue.

**Comment by edtbl76** [comment] 2021-08-12 16:45
I’m using 5.6.0. 

(The main download). Reinstalling seems to have fixed the issue. (I had to wipe all of the app data and start from scratch). I was using it w/o a login. I’m hoping that using it w/ a login helps fix the experience. (I notice that you retain my services/workspaces in my account metadata).


Ed Mangini
***@***.***


On August 12, 2021 at 12:43:41 PM, Leandro Heck ***@***.***) wrote:

Hi @vraravam , this was 3 month ago. I don't have this issue anymore. I saw this after replacing all the recipes - I believe.
I think I have fixed it by completely removing Ferdi and its config files and starting all over again. I am not sure it its version.

This is the version I am currently using.
I can't copy and paste info from this screen (this is so bad, why disable the cursor there?)


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by vraravam** [comment] 2021-08-12 17:03
@leoheck - please update to at least the latest public (non-beta version) - 5.6.0

Thanks for responding on the version.

On the topic of the about dialog - that is unfortunately the native dialog that electron delegates to and we can't do anything about it - other than revamp that code to use the equivalent one from the `electron-utils` package. #1420 is the one where we are tracking that work.

**Comment by vraravam** [comment] 2021-08-12 17:05
Closing the issue with the latest fix that I just committed. Unable to reproduce the original comment since that is logged against v5.5 which we no longer support.

**Closed by vraravam** 2021-08-12 17:05 UTC
Labels: question
