### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mycanaletto** [getferdi/ferdi#2364] opened 2021-12-27 18:05 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

### Ferdi Version

5.6.5

### What operating system are you using?

Windows

### Server

Ferdi

### Operating System Version

Windows 10, Windows 11

### What arch are you using?

x64

### Steps to reproduce

Change language

### Expected Behavior

Hello,

Spell check does not work for French.

I tried it in Italian or Spanish, it's perfect. But for French the dictionary is not downloaded and if I add it by hand (Franz's dictionary for example (fr-FR-3-0.bdic or fr-FR.bdic) it doesn't work any better and the proposed translation is always into English.

### Actual Behavior

In all other languages the dictionaries are automatically downloaded.

**Comment by kytwb** [comment] 2021-12-27 18:12
Duplicate of https://github.com/getferdi/ferdi/issues/2364.

**Closed by kytwb** 2021-12-27 18:12 UTC
Labels: bug :beetle:
