### ISSUE TITLE
Images hiding in Telegram

### ISSUE THREAD

**Issue by rctneil** [getferdi/ferdi#349] opened 2020-02-04 11:41 UTC
**Describe the bug**
Sometimes in Telegram, images in a conversation suddenly disappear.  The space for them shows up but the images don't. Reloading the service fixes it but after another unknown amount of time they disappear again

**To Reproduce**
Use Telegram until images disappear

**Expected behavior**
Images in conversations stay visible.

**Desktop (please complete the following information):**

- OS: MacOS 10.14.6 - Happens on 10.15 too
- Browser Chrome 79

Also happened when I was using Franz

**Comment by vantezzen** [comment] 2020-02-23 11:31
I can't reproduce this bug locally so I can't investigate for myself.
Can you please try ans see if Telegram's `service.css` may be at fault? Open the file at `~/Library/Application Support/Ferdi/recipes/telegram/service.css` and remove its contents (do not delete the file, only its contents as deleting the file can cause issues).

**Comment by sebastien1234** [comment] 2020-03-03 19:41
I reproduced the bug as well, although refreshing does not always work and it happens with images/videos/stickers, I believe it's just that the images/videos take a long time to download. I use a VPN.

**Comment by PashaKagan** [comment] 2020-05-27 06:28
This happens to me as well - and yesterday I confirmed it happens to another friend of mine who uses Ferdi as per my recommendation.

Images in Telegram do not show. For us, at least, no images whatsoever.

I found this bug and decided to comment on it instead of opening up a new bug, but I can confirm that 3 separate installations act the same.

**Comment by rafaelmaeuer** [comment] 2020-06-03 10:29
having the same issue, restarting ferdi is a temporary fix until it happens again...

**Comment by shukon** [comment] 2020-06-21 18:34
Same, no images show up, but space is occupied and empty (white). Reloading the service Telegram by rightklick on symbol -> Reload fixes this. Running:
Ubuntu 20.04
Ferdi 5.5.0 (64x)
Electron 8.2.3
Node.js v12.13.0

**Comment by PashaKagan** [comment] 2020-08-27 07:30
> This issue has been automatically marked as stale because it has not had recent activity. Please check if this issue is still relevant and please close it if it's not. This will make sure that our open issues are actually of use and reduce the list of obsolete issues. Thank you for your contributions.

Still relevant I afraid

**Comment by vraravam** [comment] 2021-07-07 05:02
@rctneil @sebastien1234 @PashaKagan @rafaelmaeuer @shukon - could you please try with the latest nightlies? http://github.com/getferdi/nightlies/releases - I think this issue is fixed.

**Comment by mhatvan** [comment] 2021-07-08 07:42
I had this happening to me too with the `telegram` recipe, but never with the `telegram-react` recipe, so in case the latest nightly doesnt fix it, switchign

**Comment by vraravam** [comment] 2021-07-08 07:55
Yes - I have also moved from the `telegram` recipe to the `telegram-react` recipe.

Also - fyi, we released a new beta yesterday.

Closing since there's no confirmation.

**Closed by vraravam** 2021-07-08 07:55 UTC
Labels: bug, question, service-specific
