### ISSUE TITLE
Make update banner dismissible

### ISSUE THREAD

**Issue by antonisv** [getferdi/ferdi#561] opened 2020-04-11 12:21 UTC
**Is your feature request related to a problem? Please describe.**
Well calls and video calls from facebook messenger don't work after version 5.3.3 (ferdi & franz). 
So as i am using ferdi most about FB Messenger, I am stuck with version 5.3.3 . 
I am frustrated with the update notification. 

**Describe the solution you'd like**
Is there a way to hide the update notification, as it's clear the the bug causing messenger not to work correctly, is not going to be fixed anytime soon. ( I saw the bug report and it is categorized as low-priority). A small "x" somewhere that closes that notification would be much appreciated.

**Describe alternatives you've considered**
Only alternative is to switch application (for the bug)

**Additional context**
![Screenshot_7](https://user-images.githubusercontent.com/11294927/79043457-f5486880-7c07-11ea-9b65-3afd2de59933.png).

**Comment by kytwb** [comment] 2020-04-11 20:00
@antonisv we will address this via https://github.com/getferdi/ferdi/issues/373 directly as we can't push you updates without you updating Ferdi. Thank you for your patience 🙏 I double checked and the issue is not marked as low priority. I can see how this is inconvenient, we will see to address after the current priorities at hand (release of the next stable release, that requires some bug fixes and in depth review). Closing for now 🙏

**Comment by vantezzen** [comment] 2020-04-12 09:22
I still think that we should add a button for users to hide the update notification - at least for the current session. Some users may not want to update (yet) and having this permanent notification can be annoying.

**Comment by kytwb** [comment] 2020-04-12 15:29
Thanks to @vantezzen for catching this one and to @sampathBlam <> @mahadevans87 for collaborating on a fix! 💪🙏

**Comment by kytwb** [comment] 2020-04-12 15:33
@all-contributors please add sampathBlam for code

**Closed** 2020-04-12 15:34 UTC
Labels: enhancement, good first issue
