### ISSUE TITLE
SVG icon blank image

### ISSUE THREAD

**Issue by greghab** [getferdi/ferdi#1475] opened 2021-06-01 08:14 UTC
**Bug description:**

Uploaded SVG appears in "Custom Icon" edit pane, but when clicking save, it doesn't show (is blank) on the left hand panel. PNGs work fine.

Related somewhat to #271 where SVG support was added.

**Steps to reproduce:**

1. edit a service
2. upload a svg
3. wait till it shows in "Custom Icon" pane
4. click "Save service"
5. Notice that it's blank on left panel

**Expected behavior**
- Should show image for that service

**Screenshots**

Edit Pane (uploaded SVG):
![image](https://user-images.githubusercontent.com/7407672/120289210-e7273280-c275-11eb-82ef-db3d63bed534.png)
Sidebar after save (blank):
![image](https://user-images.githubusercontent.com/7407672/120289267-f6a67b80-c275-11eb-8b0e-27d0da5d568d.png)

**Environment:*
- Operating System: NixOS
- Ferdi Version: 5.6.0-beta.5
- Server: Without an account

- Debug information:
https://pastebin.com/534a7rZc

**Comment by vraravam** [comment] 2021-07-01 09:48
Nightlies are now available at https://github.com/getferdi/nightlies/releases - please try with these.xx

**Comment by mhatvan** [comment] 2021-09-04 16:16
Cannot reproduce this, seems it was fixed by the PR linked above.

Custom .svg icon shows correctly on both macOS and Ubuntu, also after restarting Ferdi.

**Comment by keunes** [comment] 2021-12-19 14:17
@mhatvan @vraravam Sorry to bother you, but this still seems the case with the [Google Play Console SVG icon](https://github.com/getferdi/ferdi/files/7740927/Google.Play.Console.zip). I'm on Ferdi 5.6.4 on Ubuntu 18.04.6 LTS. It happens in the Custom Website recipe (v 1.1.0), but also in other recipes it seems.

Could this issue be reopened, so we can investigate?

**Closed** 2021-12-19 15:21 UTC

**Comment by kytwb** [comment] 2021-12-19 15:23
Reproduced when using Ferdi without an Account.  

Ported https://github.com/getferdi/server/pull/61 to the internal server.

![Screen Shot 2021-12-19 at 4 22 49 PM](https://user-images.githubusercontent.com/412895/146680539-3b89cc48-84f6-4823-a7d9-8679b43dea27.png)
