### ISSUE TITLE
Can't import Franz account

### ISSUE THREAD

**Issue by armanatz** [getferdi/ferdi#1036] opened 2020-10-19 06:21 UTC
**Bug description:**

When trying to import my Franz account using `https://api.getferdi.com/import` I receive the following error:

```
Could not login into Franz with your supplied credentials. Please check and try again.
```

I have checked my credentials and they are indeed valid.

**Steps to reproduce:**

1. Go to `https://api.getferdi.com/import`
2. Try to login using Franz credentials

**Expected behavior**

Able to import account using the above link

**Screenshots**

![image](https://user-images.githubusercontent.com/3622268/96408491-343e2300-1216-11eb-9d6c-539d3e3d05e7.png)
![image](https://user-images.githubusercontent.com/3622268/96408509-3dc78b00-1216-11eb-8e19-8581817f3288.png)

**Environment:**

- Operating System:  Windows 10
- Ferdi Version:  5.5.0
- Server:  N/A

**Comment by bittner** [comment] 2020-10-21 09:32
Ferdi also now seems unable to authenticate against the Franz server. I can log in into [my Franz account](https://meetfranz.com/user/dashboard) on the Franz website with the same credentials that fail to authenticate Ferdi. Is it possible that Ferdi is being locked out purposely?

**Comment by bittner** [comment] 2020-10-21 09:58
I verified the following:

1. I can successfully log in with my Franz credentials into my [Franz account](https://meetfranz.com/user/dashboard) on the Franz website :heavy_check_mark: 
1. I can successfully log in with my Franz credentials with the [Franz app](https://meetfranz.com/#download) (AppImage on Ubuntu 18.04) :heavy_check_mark: 
1. The very same credentials fail to authenticate with the current stable Ferdi app (v5.5.0-2116 Debian package) :x: 
1. The very same credentials fail to import data from the Franz server via https://api.getferdi.com/import (as originally reported) :x:

**Comment by bittner** [comment] 2020-10-21 18:47
Franz allows to export its data from your Franz account, I figured. Hence, I tried the following:

1. Log in to my **Franz** account (https://meetfranz.com/login)
1. Go to "Privacy" (https://meetfranz.com/user/privacy) and click on <kbd>Request Data Export</kbd> to download all your data
1. Extract the downloaded pseudo-ZIP archive using the `tar` command, e.g.
   ```
   tar xvfz data-export-2020-10-21T00-00-00.zip
   ```

The extracted file `data/data.json` will contain your account data.

Unfortunately, this data can't be imported into a Ferdi account (anymore?), e.g.

1. Log in to my **Ferdi** account (https://api.getferdi.com/user/login)
1. Click on "Import/Export account data" (https://api.getferdi.com/user/transfer)
1. Import the exported Franz data (`data/data.json`) via <kbd>Browse...</kbd> and <kbd>Import Data</kbd>

The following error message shows:

> Invalid Ferdi account file (2)

![franz-export-is-invalid-for-ferdi-import](https://user-images.githubusercontent.com/665072/96768643-55517000-13de-11eb-8714-0331fa9a38c5.png)

**Comment by bittner** [comment] 2020-10-21 20:50
Duplicate of #927.

**Closed** 2020-10-22 07:48 UTC
Labels: bug, duplicate

**Comment by RavHilton** [comment] 2020-12-11 02:36
Same here.  My Franz account creds are correct, but Ferdi claims they are not.  :(

**Comment by RavHilton** [comment] 2020-12-11 02:46
Also exact same issue with the failure of Ferdi to import the Franz exported accounts in .json format.

**Comment by SHU-red** [comment] 2021-03-12 17:26
Same here

**Comment by mcrwanek** [comment] 2021-03-25 08:23
why is it closed? it's still not fixed
