### ISSUE TITLE
No badge notification for Messenger

### ISSUE THREAD

**Issue by xpliz** [getferdi/ferdi#1113] opened 2020-12-13 21:59 UTC
**Bug description:**
No notification badge appears on new messages from Messenger. I've tried 5.5.0 and 5.6.0-beta. 

**Steps to reproduce:**
Add Messenger service get a new message?

**Expected behavior**
Notification badge should appear

**Screenshots**

**Environment:**

- Operating System: Windows 10 H2 & MacOS Big Sur 11.0.1
- Ferdi Version: 5.5.0 & 5.6.0-beta2
- Server: Using without an account

**Comment by abmantis** [comment] 2020-12-16 14:36
This is probably related to the new Messenger web version.

**Comment by username02** [comment] 2020-12-17 05:07
This Franz's edit [https://github.com/meetfranz/recipe-messenger/commit/7c1c1f86897ccf1dc807aecb0b9cd1381294fa6c](url) works on Ferdi as well.

**Comment by davisgarcesn** [comment] 2020-12-20 20:16
> There is a Franz's edit that works on Ferdi as well
> here [meetfranz/recipe-messenger@7c1c1f8](https://github.com/meetfranz/recipe-messenger/commit/7c1c1f86897ccf1dc807aecb0b9cd1381294fa6c), line 10.

Tried this fix and it didn't work

**Comment by xpliz** [comment] 2020-12-21 18:07
It somewhat worked for me but not interly. It always shoved +1 message for me but no unreads on FB itself. Also I changed recipe somewhat:
`let count = document.querySelectorAll('._5fx8:not(._569x),._1ht3:not(._569x),.is6700om.not(._569x)').length;`

**Comment by davisgarcesn** [comment] 2020-12-22 17:42
> It somewhat worked for me but not entirely. It always shoved +1 message for me but no unreads on FB itself. Also I changed recipe somewhat:
> `let count = document.querySelectorAll('._5fx8:not(._569x),._1ht3:not(._569x),.is6700om.not(._569x)').length;`

Tried this and still not luck. I am using 5.6.0.beta2 on Windows

**Comment by manavortex** [comment] 2020-12-25 16:41
It's not working for me either - macOS Mojave. 

Also, there's a typo in your fix - the last `.not` needs to be `:not`
`let count = document.querySelectorAll('._5fx8:not(._569x),._1ht3:not(._569x),.is6700om:not(._569x)').length;`

**Comment by HugLifeTiZ** [comment] 2020-12-25 18:48
This most recent correction does work. However, it also creates unread badges for muted conversations, which is not ideal and something the previous version didn't do.

**Comment by ccioanca** [comment] 2020-12-25 19:23
I've just made this correction myself:
`let count = document.querySelectorAll('.bp9cbjyn.j83agx80.btwxx1t3 > div > div[aria-label="Mark as Read"]').length;`
It just uses the aria label to read in the badges and doesn't bother with the obfuscated facebook classes. You could probably delete everything before the aria label selector and just use that, but I haven't tested that at all.

**Comment by HugLifeTiZ** [comment] 2020-12-26 04:31
That version still counts muted conversations for the unread badge.

It's probably also worth noting that notifications are also currently broken.

**Comment by username02** [comment] 2020-12-30 11:11
> > It somewhat worked for me but not entirely. It always shoved +1 message for me but no unreads on FB itself. Also I changed recipe somewhat:
> > `let count = document.querySelectorAll('._5fx8:not(._569x),._1ht3:not(._569x),.is6700om.not(._569x)').length;`
> 
> Tried this and still not luck. I am using 5.6.0.beta2 on Windows

It is working for me; this is what's in my webview.js
`"use strict";

module.exports = Franz => {
  const getMessages = function getMessages() {
    let count = document.querySelectorAll('._5fx8:not(._569x),._1ht3:not(._569x),.is6700om').length;
    const messageRequestsElement = document.querySelector('._5nxf');

    if (messageRequestsElement) {
      count += parseInt(messageRequestsElement.innerHTML, 10);
    }

    Franz.setBadge(count);
  };

  Franz.loop(getMessages);
  localStorage.setItem('_cs_desktopNotifsEnabled', JSON.stringify({
    __t: new Date().getTime(),
    __v: true
  }));

  if (typeof Franz.onNotify === 'function') {
    Franz.onNotify(notification => {
      if (typeof notification.title !== 'string') {
        notification.title = ((notification.title.props || {}).content || [])[0] || 'Messenger';
      }

      if (typeof notification.options.body !== 'string') {
        notification.options.body = (((notification.options.body || {}).props || {}).content || [])[0] || '';
      }

      return notification;
    });
  }
};`

**Comment by tamas646** [comment] 2021-01-06 15:07
> That version still counts muted conversations for the unread badge.
> 
> It's probably also worth noting that notifications are also currently broken.

I spent nearly 2 hours trying to resolve this problem, but i found nothing at all in messenger's html code that we could use to determine whether the channel is muted or not. :cry:

**Comment by JCKodel** [comment] 2021-01-20 22:34
Had this today in 5.5.0.2116.

Had to change the
```js
const elements = document.querySelectorAll("[class=OUeyt]");
```

to 

```js
const elements = document.querySelectorAll("[class=VOr2j]");
```

(apparently, the new class name is `VOr2j`)

**Comment by HugLifeTiZ** [comment] 2021-01-27 17:49
@JCKodel which file are you referring to? None of the webview.js implementations in this thread or in any of the recipe repos have anything like that.

It feels like we have a whole lot of wildly different webview.js files flying around in this thread trying to fix the same issue and each one gets different results for each person. Is it possible that differences between different Ferdi versions are making this confusion worse?

**Comment by tamas646** [comment] 2021-01-27 18:34
@HugLifeTiZ I think the part of the code responsible for counting the unread messages is the one begins with `let count = ...`.
If this variable gets 0 than there won't be any notification badge.

The problem is that Messenger upgraded it's web interface, and because of this the previous counting function does not work properly and always returns 0. I think we all need to find a solution for this to fix the badge notification issue.

There is a semi-functional fix for this function mentioned above by @xpliz and @manavortex, but it still counts muted channels:
```js
let count = document.querySelectorAll('._5fx8:not(._569x),._1ht3:not(._569x),.is6700om:not(._569x)').length;
```

I have spent a lot of time finding out how could we write a function that counts only non-muted channels, but I didn't find anyhing useful in the new HTML code. It seems like the HTML code of a muted channel is exactly the same as the non-muted one.

Any ideas?

**Comment by austkel** [comment] 2021-02-09 19:33
Just here to say I'm experiencing this too

**Comment by DmitriyVdE** [comment] 2021-02-19 14:15
This is happening for me as well. Besides this I also don't get notification sounds from messenger, even after enabling them in the messenger settings. Other extensions do work and have notification sound. Audio from video's works as normal.

**Comment by HugLifeTiZ** [comment] 2021-02-20 17:22
Okay so I think we have a breakthrough. I've switched to using Caprine because I need the desktop features of most of the webapps I had integrated in Ferdi, but I still care about making Ferdi the best it can be! I noticed something in Caprine: its window title is just the page title, which is usually just "Messenger". But if you get a message, it changes to "(1) Messenger". I think that number might be the number of unread, unmuted conversations. So our next step is probably just to watch for changes to the page title and parse the parenthesized number for our unread count. :)

This doesn't help us with notifications unless we're willing to just throw out a notification whenever the page title changes until they have real desktop notification support back.

**Comment by tamas646** [comment] 2021-02-20 18:25
It could be a good start, but we have to get through some difficulties first, such as the frequently changing title after getting new message, and the bug I noticed just now:
For me sometimes the title is `Messenger` when there is **either zero or one** unread message and `(n - 1) Messenger - Facebook` when there are more messages (where *n* is the number of unread messages), but hopefully it's a rare anomaly.

**Comment by tamas646** [comment] 2021-02-20 19:06
I managed to rewrite the counter function based on @HugLifeTiZ's idea. This is how it looks:
```js
let count = /^\((\d+)\)/.test(document.title) ? parseInt(/^\((\d+)\)/.exec(document.title)[1]) : 0;
```
And this is my webview.js:
```js
"use strict";

module.exports = Franz => {
  const getMessages = function getMessages() {
    let count = /^\((\d+)\)/.test(document.title) ? parseInt(/^\((\d+)\)/.exec(document.title)[1]) : 0;
    const messageRequestsElement = document.querySelector('._5nxf');

    if (messageRequestsElement) {
      count += parseInt(messageRequestsElement.innerHTML, 10);
    }

    Franz.setBadge(count);
  };

  Franz.loop(getMessages);
  localStorage.setItem('_cs_desktopNotifsEnabled', JSON.stringify({
    __t: new Date().getTime(),
    __v: true
  }));

  if (typeof Franz.onNotify === 'function') {
    Franz.onNotify(notification => {
      if (typeof notification.title !== 'string') {
        notification.title = ((notification.title.props || {}).content || [])[0] || 'Messenger';
      }

      if (typeof notification.options.body !== 'string') {
        notification.options.body = (((notification.options.body || {}).props || {}).content || [])[0] || '';
      }

      return notification;
    });
  }
};
```

Unfortunately it doesn't work properly for me due to the issue I described above. :(
But I hope you will be luckier.

**Comment by tamas646** [comment] 2021-02-20 19:32
I made a correction to avoid flashing badge icon:
```js
"use strict";

module.exports = Franz => {
  const getMessages = function getMessages() {
    // let count = document.querySelectorAll('._5fx8:not(._569x),._1ht3:not(._569x),.is6700om').length;
    let count = /^\((\d+)\)/.test(document.title) ? parseInt(/^\((\d+)\)/.exec(document.title)[1]) : 0;
    const messageRequestsElement = document.querySelector('._5nxf');

    if (messageRequestsElement) {
      count += parseInt(messageRequestsElement.innerHTML, 10);
    }
    if (!/ - Facebook$/.test(document.title)) {
      Franz.setBadge(count);
    }
  };

  Franz.loop(getMessages);
  localStorage.setItem('_cs_desktopNotifsEnabled', JSON.stringify({
    __t: new Date().getTime(),
    __v: true
  }));

  if (typeof Franz.onNotify === 'function') {
    Franz.onNotify(notification => {
      if (typeof notification.title !== 'string') {
        notification.title = ((notification.title.props || {}).content || [])[0] || 'Messenger';
      }

      if (typeof notification.options.body !== 'string') {
        notification.options.body = (((notification.options.body || {}).props || {}).content || [])[0] || '';
      }

      return notification;
    });
  }
};
```
I think it will solve the problem. (it solved for me)

**Comment by tamas646** [comment] 2021-02-22 14:21
Another correction for group channels. :D
```js
"use strict";

module.exports = Franz => {
  const getMessages = function getMessages() {
    // let count = document.querySelectorAll('._5fx8:not(._569x),._1ht3:not(._569x),.is6700om').length;
    let isNotification = /^\((\d+)\)/.test(document.title);
    let count = isNotification ? parseInt(/^\((\d+)\)/.exec(document.title)[1]) : 0;
    const messageRequestsElement = document.querySelector('._5nxf');

    if (messageRequestsElement) {
      count += parseInt(messageRequestsElement.innerHTML, 10);
    }
    if (isNotification || document.title == 'Messenger') {
      Franz.setBadge(count);
    }
  };

  Franz.loop(getMessages);
  localStorage.setItem('_cs_desktopNotifsEnabled', JSON.stringify({
    __t: new Date().getTime(),
    __v: true
  }));

  if (typeof Franz.onNotify === 'function') {
    Franz.onNotify(notification => {
      if (typeof notification.title !== 'string') {
        notification.title = ((notification.title.props || {}).content || [])[0] || 'Messenger';
      }

      if (typeof notification.options.body !== 'string') {
        notification.options.body = (((notification.options.body || {}).props || {}).content || [])[0] || '';
      }

      return notification;
    });
  }
};
```

**Comment by SkepticSpoon** [comment] 2021-05-23 19:18
The unread badge for Messenger is not working for me. I tried the above mod by @tamas646 and it's still not fixed

**Comment by manavortex** [comment] 2021-05-23 19:21
Following fix worked for me: 

```
    let count = document.querySelectorAll('._5fx8:not(._569x),._1ht3:not(._569x)').length;
    if (0 === count) {
      count = document.querySelectorAll('.pq6dq46d.is6700om.qu0x051f.esr5mh6w.e9989ue4.r7d6kgcz.s45kfl79.emlxlaya.bkmhp75w.spb7xbtv.cyypbtt7.fwizqjfa').length;
    } 
    if (0 === count) {
      count = document.querySelectorAll('[aria-label="Mark as read"]').length;
    }
```

**Comment by SkepticSpoon** [comment] 2021-05-23 19:31
The fix by @manavortex worked for me as well for 1:1 conversations!

**Comment by vraravam** [comment] 2021-05-24 01:40
@manavortex - could I please request you to raise a PR with the complete working solution [here](https://github.com/getferdi/recipes/pulls). Unfortunately, since I don't use Messenger, I cannot test the solution myself. But, if you raise the PR, I will definitely approve it. Please be sure to run the `npm run package` invocation - since it verifies some hygiene stuff and auto-generates entries in another file based on your changes.

**Comment by manavortex** [comment] 2021-05-24 04:31
@vraravam Hey - I'm running into issues with npm install on my mac, and

```
> node-mac-permissions@2.2.0 install /Users/manavortex/Documents/11_coding/ferdi/node_modules/node-mac-permissions
> node-gyp rebuild

  CC(target) Release/obj.target/nothing/node_modules/node-addon-api/src/nothing.o
  LIBTOOL-STATIC Release/nothing.a
  CXX(target) Release/obj.target/permissions/permissions.o
../permissions.mm:11:9: fatal error: 'Speech/Speech.h' file not found
```

... given that I'm on vacation, I'm little-motivated to tinker around with that right now :D 

here's the full webview.js: 

```
"use strict";

module.exports = Franz => {
  const getMessages = function getMessages() {
    let count = document.querySelectorAll('._5fx8:not(._569x),._1ht3:not(._569x)').length;
    if (0 === count) {
      count = document.querySelectorAll('.pq6dq46d.is6700om.qu0x051f.esr5mh6w.e9989ue4.r7d6kgcz.s45kfl79.emlxlaya.bkmhp75w.spb7xbtv.cyypbtt7.fwizqjfa').length;
    } 
    if (0 === count) {
      count = document.querySelectorAll('[aria-label="Mark as read"]').length;
    }
    const messageRequestsElement = document.querySelector('._5nxf');

    if (messageRequestsElement) {
      count += parseInt(messageRequestsElement.innerHTML, 10);
    }

    Franz.setBadge(count);
  };

  Franz.loop(getMessages);
  localStorage.setItem('_cs_desktopNotifsEnabled', JSON.stringify({
    __t: new Date().getTime(),
    __v: true
  }));

  if (typeof Franz.onNotify === 'function') {
    Franz.onNotify(notification => {
      if (typeof notification.title !== 'string') {
        notification.title = ((notification.title.props || {}).content || [])[0] || 'Messenger';
      }

      if (typeof notification.options.body !== 'string') {
        notification.options.body = (((notification.options.body || {}).props || {}).content || [])[0] || '';
      }

      return notification;
    });
  }
};
```

I don't assume you could do the necessary building etc.?

**Comment by vraravam** [comment] 2021-05-24 04:48
@manavortex - does the full webview that you copied above - work as-is? If so, I can create a PR and merge it in. But, as I said before, I dont use Messenger, and would not be able to test the changes.

**Comment by manavortex** [comment] 2021-05-24 04:53
@vraravam: Yes, but only for 1:1 conversations. 
Should I try to hack in tamas's fix for the group convos first?

**Comment by vraravam** [comment] 2021-05-24 04:54
Yes pls - if you don't mind. We can iterate with the recipe changes if its still broken

**Comment by manavortex** [comment] 2021-05-24 04:56
It will probably not work for too long, since facebook are changing their web API around for no reason (or probably out of spite. I think it's spite.) 
Maybe it would be worth thinking about a way to have the webview.js files for the individual services update from a central repository with lower-level pull requests or something.

**Comment by manavortex** [comment] 2021-05-24 05:07
Hey, 

confirmed working with help of husband:
![image](https://user-images.githubusercontent.com/965785/119299161-b4ba7b80-bc5e-11eb-8f6c-7943e887c90b.png)

```
"use strict";

module.exports = Franz => {
  const getMessages = function getMessages() {

    let count = 0

    let isNotification = /^\((\d+)\)/.test(document.title);
    
    /* 
     * Notification case for group chats, workaround by tamas646 
     * see https://github.com/getferdi/ferdi/issues/1113#issuecomment-783409154
     */
     if (isNotification) {
      count = parseInt(/^\((\d+)\)/.exec(document.title)[1]);      
    } else {
     /* 
      * Notification case for direct messages, workaround by manavortex
      * see https://github.com/getferdi/ferdi/issues/1113#issuecomment-846611765
      */
      count = document.querySelectorAll('._5fx8:not(._569x),._1ht3:not(._569x)').length;
      if (0 === count) {
        count = document.querySelectorAll('.pq6dq46d.is6700om.qu0x051f.esr5mh6w.e9989ue4.r7d6kgcz.s45kfl79.emlxlaya.bkmhp75w.spb7xbtv.cyypbtt7.fwizqjfa').length;
      } 
      if (0 === count) {
        count = document.querySelectorAll('[aria-label="Mark as read"]').length;
      }
    }
    /* 
     * add count of message requests on top of notification counter
     */
    const messageRequestsElement = document.querySelector('._5nxf');
    if (messageRequestsElement) {
      count += parseInt(messageRequestsElement.innerHTML, 10);
    }

    Franz.setBadge(count);
  };

  Franz.loop(getMessages);
  localStorage.setItem('_cs_desktopNotifsEnabled', JSON.stringify({
    __t: new Date().getTime(),
    __v: true
  }));

  if (typeof Franz.onNotify === 'function') {
    Franz.onNotify(notification => {
      if (typeof notification.title !== 'string') {
        notification.title = ((notification.title.props || {}).content || [])[0] || 'Messenger';
      }

      if (typeof notification.options.body !== 'string') {
        notification.options.body = (((notification.options.body || {}).props || {}).content || [])[0] || '';
      }

      return notification;
    });
  }
};
```

**Comment by vraravam** [comment] 2021-05-24 05:32
Thanks for the code - I have raised the PR and also merged it in.

> Maybe it would be worth thinking about a way to have the webview.js files for the individual services update from a central repository with lower-level pull requests or something.

Actually, I have already logged a feature request for the same :  #1302 - please upvote or give any other suggestions in that ticket.

**Comment by vraravam** [comment] 2021-05-24 09:00
If anyone is interested in new functionality that we haven't yet released, (along with many bug fixes), please find the macos builds [here](https://drive.google.com/drive/folders/1mJmKbhpVHdb066IHlrdYiD8TG9wlmuBv).

**Comment by tamas646** [comment] 2021-05-26 14:06
@manavortex  It's still not perfect with muted conversations.
I currently have 2 of them, and the badge shows 2 notifications. (however it should not show any)
But I think it's almost impossible to detect any differences between a normal and a muted chat's HTML code. This is why I tried to extract the number of notifications from the title as @HugLifeTiZ suggested.

Also I don't really understand why we want to separate group chats from direct chats. The HTML code is nearly the same.

As I see, there are two different solutions for the problem:

1. Count a specific element or class in the HTML code. (@manavortex 's solution)
    **Disadvantages:** It also counts muted conversations.

2. Extract the current number of notification from the title. (this is what I tried)
    **Disadvantages:** Sometimes the title doesn't contain information about the notifications, and sometimes the number is less than the real one.

I think we should not combine these two solutions because non of them is perfect and the result will be chaos.
A semi-working solution is still better because it works logically, but these two different solutions only cause randomness in result.

**Comment by vraravam** [comment] 2021-05-26 15:52
> If anyone is interested in new functionality that we haven't yet released, (along with many bug fixes), please find the macos builds [here](https://drive.google.com/drive/folders/1mJmKbhpVHdb066IHlrdYiD8TG9wlmuBv).

The latest [nightlies are out now](https://github.com/getferdi/nightlies/releases). Please try with the latest builds and continue the conversation.

**Comment by tamas646** [comment] 2021-06-08 17:02
I tried with the latest nightly (5.6.0-nightly.57).
The problem is the same as I described above.

**Comment by vraravam** [comment] 2021-07-01 09:17
can you please try with the latest nightlies? http://github.com/getferdi/nightlies/releases

**Comment by cris2d2** [comment] 2021-07-08 07:02
Just tried latest Ferdi nightly (5.6.0-nightly.78) for Windows 10 but Facebook Messenger service (or just Messenger) shows no notifications in Action Center, no desktop badges and no sounds for new messages. Only unread count is working for new notifications. In fact, Ferdi is missing from "Get notifications from these senders" list in Windows "Notifications & Action settings".

**Comment by fuzzy76** [comment] 2021-07-08 07:57
@cris2d2 that sounds like a problem with Ferdi notifications in general, not the Messenger service in particular. You can try with any other service to see if this is correct. Which makes it a totally different issue, and not related to this.

**Comment by vraravam** [comment] 2021-07-08 08:01
Unfortunately, I am strictly off of FB (Messenger, Insta, etc) - and can't help with the issue.

Please confirm whether the notifications and badges appear for other services. IF so, then its a problem only in the specific service (I suspect this to be the case)

**Comment by manavortex** [comment] 2021-07-08 08:06
5.6.0-nightly.76 on osX 10.14.6 shows notifications on FB messenger - at least for DMs.

**Comment by vraravam** [comment] 2021-07-08 08:08
tx for the confirmation @manavortex - btw, a new beta was released yesterday (you might want to upgrade)

**Closed by vraravam** 2021-07-08 08:08 UTC
Labels: bug, service-specific

**Comment by cris2d2** [comment] 2021-07-08 08:18
> @cris2d2 that sounds like a problem with Ferdi notifications in general, not the Messenger service in particular. You can try with any other service to see if this is correct. Which makes it a totally different issue, and not related to this.

I added GMail, sent me an email and Ferdi showed Windows badge, Windows notification in action center and played a sound. Also, Ferdi icon badge was showing also. But for Messenger there is only icon badge showing, no other notifications.

**Comment by fuzzy76** [comment] 2021-07-08 09:02
Sorry if this is obvious, but have you edited the service and verified that the settings for notifications and sound is set to on? They should be by default, but you never know.

**Comment by cris2d2** [comment] 2021-07-08 09:06
> Sorry if this is obvious, but have you edited the service and verified that the settings for notifications and sound is set to on? They should be by default, but you never know.

Yes, all notifications are on. I disabled and re-enabled them just to be sure.

**Comment by vraravam** [comment] 2021-07-08 15:10
Did you try deleting the caches? I had to help a colleague earlier today where they had upgraded to beta-7, but somehow their local cache folders were not cleaning up. Thus, they were seeing older behavior of the recipe code.

**Comment by cris2d2** [comment] 2021-07-08 17:51
> Did you try deleting the caches? I had to help a colleague earlier today where they had upgraded to beta-7, but somehow their local cache folders were not cleaning up. Thus, they were seeing older behavior of the recipe code.

I didn't try to delete the caches but it's the same behavior on freshly installed Ferdi or Franz: Facebook Messenger has no Windows notifications, like other services/apps. Maybe there's something wrong on Facebook side that Ferdi devs are not aware, regarding notifications.
