### ISSUE TITLE
Missing unread message badges for Outlook 365

### ISSUE THREAD

**Issue by fkn-iteratec** [getferdi/ferdi#1217] opened 2021-02-22 09:53 UTC
**Bug description:**
I miss the unread messages badges for the service Outlook 365. If there are already unread messages or I receive a new message, Ferdi do not display that in the left column on the icon of the service.  

**Screenshots**
![missing_unread_messages](https://user-images.githubusercontent.com/79155082/108691382-bbb8dd00-74fb-11eb-941b-6dd3a664f04c.png)
**Environment:**

- Operating System: Ubuntu 20.04.2 LTS
- Ferdi Version: 5.5.0
- Server: Using without an account

**Comment by matthijsvp** [comment] 2021-03-12 04:45
Experiencing the same on MacOS 11.2.1.

**Comment by vraravam** [comment] 2021-05-22 10:05
There seem to be 3 different recipes for the same: `outlook`, `office 365` and `enterprise office 365`.
Could you please try with all 3 of them, and tell us which one works?

**Comment by fkn-iteratec** [comment] 2021-05-25 09:51
I tried it: 

- `outlook` -> works
- `outlook 365` -> doesn't work
- `enterprise office 365` -> I can see the service on the web page but not selectable within Ferdi. Don't now why.

**Comment by matthijsvp** [comment] 2021-05-25 10:25
I've just tried `outlook` and that does not work for me.

> I tried it:
> 
>     * `outlook` -> works
> 
>     * `outlook 365` -> doesn't work
> 
>     * `enterprise office 365` -> I can see the service on the web page but not selectable within Ferdi. Don't now why.

**Comment by darhe** [comment] 2021-06-30 23:27
As an addendum, I'm using the Office 365 Outlook Web App recipe and it shows the unread total including the Deleted Items folder. I recommend we exclude that folder, if possible.[
![2021-06-30 16_22_02-Ferdi](https://user-images.githubusercontent.com/85759231/124043496-f954d780-d9bf-11eb-884d-f43ed3fbb812.png)
](url)

If this should be a new bug report, just let me know and I'll resubmit.

**Comment by oizik** [comment] 2021-07-10 08:39
Running into the same problem, 
Ferdi: 5.5.0
Electron: 8.2.3
Note.js: V12.13.0
Platform Linux

`outlook` -> works
`office365` -> does not work 

![2021-07-10_18-35](https://user-images.githubusercontent.com/23091923/125157387-0b97f800-e1ae-11eb-9d7a-750fed93810b.png)

**Comment by vraravam** [comment] 2021-07-10 09:32
Sorry @oizik - we are not in a position to support Ferdi v5.5 any more. Please try out the latest beta (quite stable in fact) over [here](http://github.com/getferdi/ferdi/releases). Please get back whether this new version (with updated service configuration capabilities) works for your usecase.

**Comment by oizik** [comment] 2021-07-10 09:49
@vraravam apology, I didn't even bother to check GitHub released, just downloaded from https://getferdi.com/download this morning. Thank you.

**Comment by michaeldrouin** [comment] 2021-07-22 19:12
i have had this same issue for a while (since one of the nightlies in 60's or 70's range). none of the 3 outlook recipes work for me, either. account is a azure office 365 subscription if that changes anything.

**Comment by michaeldrouin** [comment] 2021-07-22 19:32
it seems the issue may be `const folders = Array.from(favorites.nextSibling.childNodes);` it's saying `.nextSibling` is `null`.

**Comment by mhatvan** [comment] 2021-08-04 16:24
I am using the one called `Office 365 - Outlook` with Self hosted setup and it works great.

**Comment by michaeldrouin** [comment] 2021-08-04 20:53
i seem to have figured out the issue and workaround. the recipe is only pulling unread counts from folders in your "Favorites". not sure if this should be that way. but workaround for other people having the issue is add whatever folders you want unread counts for to your favorites.

**Comment by mhatvan** [comment] 2021-08-05 08:13
Ohhh, you are right about that haha, interesting!

Never noticed this, because Outlook had folders like Inbox favorited out of the box for me.

So you would like to have every folder be relevant for unread count? I can make that change.

**Comment by michaeldrouin** [comment] 2021-08-05 16:09
yeah, i'm kinda wondering which option is better. i remember for a long time (pretty much until commit [822c568](https://github.com/getferdi/recipes/commit/822c5680c0461c90468cd8a69a37e3354376c73c) on the recipes repo, which is where the code changes), junk mail and deleted items would show up on my unread counter, and it was a bit annoying. however, if someone has email rules in place that automatically organize their emails into subfolders, but all those subfolders aren't favorited, then they won't be counted either. there's always the option of parsing all folders, but ignoring the counts on junk and deleted items, but not sure if that's really a practical solution either.

**Comment by vraravam** [comment] 2021-08-29 10:50
Sorry it took so long - till date, I did not use outlook. Starting last week, I went into a new client where they use Outlook, and I spent some time fixing the duplications in the recipes (there were 3!), and also figuring out the css selectors for the `folders` and `groups` in outlook. As of the latest commit 2 mins ago - this should be fixed. Closing this bug ticket.

**Closed by vraravam** 2021-08-29 10:50 UTC
Labels: feedback wanted

**Comment by LordBoos** [comment] 2021-09-08 08:44
Hello, I see that you made a fix for this issue, but it does not work for me and it only introduced new issue for my custom script.
Before this change my custom user script correctly set the unread badge, but now it sets the unread badge and after a second or less, badge disappears again presumably because the native script overwrites it with 0.
I also tried to remove the `if (recent == last) {` condition, but then the badge just constantly changes (blinks) between 0 and 1 unread.

My custom user script follows (with debug console log messages):
```
module.exports = (config, Ferdi) => {
	var last = 0;
	setInterval(() => {
		try {
			var ac = 0;
			var bc = 0;
			var cc = 0;
			var dc = 0;
			var ec = 0;
			var fc = 0;
			var gc = 0;
			var recent = 0;
			var a = document.querySelector("#app > div > div.zZJcFiYp1GsQ-Zkcz02eC > div.mXEfuMleN9V2Rx6d6qvsu > div > div > div > div.tQjtZGBXoedSUDzkcRzw5.css-45 > div._1mmhFz6xbEHFv6FfTUKPW2 > div > div > div > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div > span._3rASdLVQxHgpaejCMPDNFO > span > span.PUV1mki0rYSBZsGVrzV9q")
			if (a != null) {
			  ac = parseInt(a.innerText)
			}
			var b = document.querySelector("#app > div > div.zZJcFiYp1GsQ-Zkcz02eC > div.mXEfuMleN9V2Rx6d6qvsu > div > div > div > div.tQjtZGBXoedSUDzkcRzw5.css-45 > div._1mmhFz6xbEHFv6FfTUKPW2 > div > div > div > div:nth-child(2) > div:nth-child(2) > div:nth-child(2) > div > span._3rASdLVQxHgpaejCMPDNFO > span > span.PUV1mki0rYSBZsGVrzV9q")
			if (b != null) {
			  bc = parseInt(b.innerText)
			}
			var c = document.querySelector("#app > div > div.zZJcFiYp1GsQ-Zkcz02eC > div.mXEfuMleN9V2Rx6d6qvsu > div > div > div > div.tQjtZGBXoedSUDzkcRzw5.css-45 > div._1mmhFz6xbEHFv6FfTUKPW2 > div > div > div > div:nth-child(2) > div:nth-child(2) > div:nth-child(3) > div > span._3rASdLVQxHgpaejCMPDNFO > span > span.PUV1mki0rYSBZsGVrzV9q")
			if (c != null) {
			  cc = parseInt(c.innerText)
			}
			var d = document.querySelector("#app > div > div.zZJcFiYp1GsQ-Zkcz02eC > div.mXEfuMleN9V2Rx6d6qvsu > div > div > div > div.tQjtZGBXoedSUDzkcRzw5.css-45 > div._1mmhFz6xbEHFv6FfTUKPW2 > div > div > div > div:nth-child(2) > div:nth-child(2) > div:nth-child(4) > div > span._3rASdLVQxHgpaejCMPDNFO > span > span.PUV1mki0rYSBZsGVrzV9q")
			if (d != null) {
			  dc = parseInt(d.innerText)
			}
			var e = document.querySelector("#app > div > div.zZJcFiYp1GsQ-Zkcz02eC > div.mXEfuMleN9V2Rx6d6qvsu > div > div > div > div.tQjtZGBXoedSUDzkcRzw5.css-45 > div._1mmhFz6xbEHFv6FfTUKPW2 > div > div > div > div:nth-child(2) > div:nth-child(2) > div:nth-child(5) > div > span._3rASdLVQxHgpaejCMPDNFO > span > span.PUV1mki0rYSBZsGVrzV9q")
			if (e != null) {
			  ec = parseInt(e.innerText)
			}
			var f = document.querySelector("#app > div > div.zZJcFiYp1GsQ-Zkcz02eC > div.mXEfuMleN9V2Rx6d6qvsu > div > div > div > div.tQjtZGBXoedSUDzkcRzw5.css-45 > div._1mmhFz6xbEHFv6FfTUKPW2 > div > div > div > div:nth-child(2) > div:nth-child(2) > div:nth-child(6) > div > span._3rASdLVQxHgpaejCMPDNFO > span > span.PUV1mki0rYSBZsGVrzV9q")
			if (f != null) {
			  fc = parseInt(f.innerText)
			}
			var g = document.querySelector("#app > div > div.zZJcFiYp1GsQ-Zkcz02eC > div.mXEfuMleN9V2Rx6d6qvsu > div > div > div > div.tQjtZGBXoedSUDzkcRzw5.css-45 > div._1mmhFz6xbEHFv6FfTUKPW2 > div > div > div > div:nth-child(2) > div:nth-child(2) > div:nth-child(7) > div > span._3rASdLVQxHgpaejCMPDNFO > span > span.PUV1mki0rYSBZsGVrzV9q")
			if (g != null) {
			  gc = parseInt(g.innerText)
			}
			recent = parseInt(ac+bc+cc+dc+ec+fc+gc);
			if (recent == last) {
				console.info("Outlook custom script: recent==last, not setting the badge, but value would be " + recent);
			} else {
				console.info("Outlook custom script: setting unread badge to " + recent);
				Ferdi.setBadge(recent);
				last = recent;
			}
		} catch (error) {
			console.error("Outlook custom script: error");
			console.error(error);
		}
	}, 1000);
}
```

**Comment by matthijsvp** [comment] 2021-09-16 10:43
For me after updating the fix seems to work. however, it also takes into account Draft messages, which is less than helpful :-)
