### ISSUE TITLE
Instagram recipe opens instagram.com, instead of messages inbox [Bug]: 

### ISSUE THREAD

**Issue by CiteopehtEripmav** [getferdi/ferdi#2291] opened 2021-12-01 22:03 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

### Ferdi Version

5.6.4 nightly 20

### What operating system are you using?

Windows

### Server

Ferdi

### Operating System Version

Windows 10 Pro 21H2 build 19044.1387

### What arch are you using?

x64

### Steps to reproduce

Open Instagram service and wait for the page to load

### Expected Behavior

Open Instagram service and load straight to Instagram's messages inbox, instead of Instagram's home page

### Actual Behavior

Service opens to Instagram's home page instead of Instagram messages inbox

### Additional Information

Have tried deleting all files regarding the Instagram recipe and redownloading it, with no change in behavior. Only manually editing the package.json file and changing the line "serviceURL": "https://instagram.com" to "serviceURL": "https://instagram.com/direct/inbox" has given me the desired effect and forced the Instagram messages inbox to be the initial page when opening the Instagram service.

**Comment by vraravam** [comment] 2021-12-02 05:24
@CiteopehtEripmav - if this is common expected behavior (I dont use instagram), and since you have found the place where the changes need to be made, please raise a PR. Till we get more votes on which `serviceURL` to use, imo, its not fair to the other users to change the url.

**Comment by michaeldrouin** [comment] 2021-12-02 22:34
@vraravam technically, it was recently changed to `https://instagram.com`. it had been the inbox (`https://instagram.com/direct/inbox`) until recently (about a month ago) when the `direct/inbox` link broke and the recipe had to be updated (see commit [e835913](https://github.com/getferdi/recipes/commit/e835913081994e5441a1cd603715a18966340cd7#diff-6a8e00ff7f1106b8c08544fa34c5403f3946a9d0dfd175ce4c3d8a28f38171a2). however, instagram reverted their inbox link back to `/direct/inbox` and it is working again. i modified the recipe and tested it and it works fine. rolling back this commit should be all that is needed to have the recipe functioning as it always had before.

**Comment by vraravam** [comment] 2021-12-02 23:09
thanks for that link @michaeldrouin - I have committed the revert. It should appear in the next nightly.

**Closed** 2021-12-02 23:09 UTC
Labels: bug :beetle:

**Comment by michaeldrouin** [comment] 2021-12-10 00:32
actually, it looks like it's broken again. it seems to be an issue with an expired cookie (see #2185). the url for the inbox will work for a day or two and then start producing the "An error has occured" message again

**Comment by harryfear** [comment] 2021-12-29 13:57
Same here
