### ISSUE TITLE
"Grrr! A popup blocker..." when clicking print or new window icon in Gmail

### ISSUE THREAD

**Issue by stevengliebe** [getferdi/ferdi#942] opened 2020-09-02 15:54 UTC
Hello,

**Bug description:**

When viewing an email in Gmail and clicking on the print icon or the new window icon next to it, Ferdi shows an error about a popup blocker.

_Grrr! A popup blocker may be preventing the application from opening the page. If you have a popup blocker, try disabling it to open the window._

**Steps to reproduce:**

1. View an email in Gmail
2. Click the print or new window icon at the top-right
3. See the error message

**Expected behavior**

The print dialog should appear or the email should be opened in a new window.

**Screenshots**

![ferdi-issue](https://user-images.githubusercontent.com/3372396/92005713-6ac4ea80-ed09-11ea-9508-9ded107f58cd.png)

**Environment:**

- Operating System: macOS Catalina 0.15.6 (19G2021)
- Ferdi Version: 5.6.0-beta.2 (5.6.0-beta.2.2329)
- Server: Using without an account

- Debug information:

[debug.txt](https://github.com/getferdi/ferdi/files/5163367/debug.txt)

Thank you.

**Comment by vantezzen** [comment] 2020-09-04 10:29
Duplicate of #321

**Closed by vantezzen** 2020-09-04 10:29 UTC
Labels: bug
