### ISSUE TITLE
Clearing the cache resets all settings

### ISSUE THREAD

**Issue by mitelg** [getferdi/ferdi#795] opened 2020-06-03 05:22 UTC
**Bug description:**
Yesterday I cleared the cache and all my settings are deleted, too.

**Steps to reproduce:**

1. Clear cache in the settings menu
2. Slack appearance design settings are reset
3. All Ferdi settings are reset to default, like "Launch Ferdi on start"

**Expected behavior**

I would expect that really the cache is cleared and not the whole application to be reset. It is quite inconvenience to set all settings again, after clearing the cache. I would like to do this once in a while, as it has grown up to 2GB in this case :blush: 

**Environment:**

- Operating System: Ubuntu 20.04
- Ferdi Version: 5.5.0 (x64)
- Server: Using without an account

- Debug information:
```
{
  "host": {
    "platform": "linux",
    "release": "5.4.0-33-generic",
    "screens": [
      {
        "id": 33,
        "bounds": {
          "x": 3840,
          "y": 0,
          "width": 1920,
          "height": 1080
        },
        "workArea": {
          "x": 3840,
          "y": 27,
          "width": 1920,
          "height": 1053
        },
        "accelerometerSupport": "unknown",
        "monochrome": false,
        "colorDepth": 24,
        "colorSpace": "{primaries:INVALID, transfer:INVALID, matrix:INVALID, range:INVALID}",
        "depthPerComponent": 8,
        "size": {
          "width": 1920,
          "height": 1080
        },
        "workAreaSize": {
          "width": 1920,
          "height": 1053
        },
        "scaleFactor": 1,
        "rotation": 0,
        "internal": false,
        "touchSupport": "unknown"
      },
      {
        "id": 35,
        "bounds": {
          "x": 1920,
          "y": 0,
          "width": 1920,
          "height": 1080
        },
        "workArea": {
          "x": 1920,
          "y": 0,
          "width": 1920,
          "height": 1080
        },
        "accelerometerSupport": "unknown",
        "monochrome": false,
        "colorDepth": 24,
        "colorSpace": "{primaries:INVALID, transfer:INVALID, matrix:INVALID, range:INVALID}",
        "depthPerComponent": 8,
        "size": {
          "width": 1920,
          "height": 1080
        },
        "workAreaSize": {
          "width": 1920,
          "height": 1080
        },
        "scaleFactor": 1,
        "rotation": 0,
        "internal": false,
        "touchSupport": "unknown"
      },
      {
        "id": 37,
        "bounds": {
          "x": 0,
          "y": 0,
          "width": 1920,
          "height": 1080
        },
        "workArea": {
          "x": 0,
          "y": 0,
          "width": 1920,
          "height": 1080
        },
        "accelerometerSupport": "unknown",
        "monochrome": false,
        "colorDepth": 24,
        "colorSpace": "{primaries:INVALID, transfer:INVALID, matrix:INVALID, range:INVALID}",
        "depthPerComponent": 8,
        "size": {
          "width": 1920,
          "height": 1080
        },
        "workAreaSize": {
          "width": 1920,
          "height": 1080
        },
        "scaleFactor": 1,
        "rotation": 0,
        "internal": false,
        "touchSupport": "unknown"
      }
    ]
  },
  "ferdi": {
    "version": "5.5.0",
    "electron": "8.2.3",
    "installedRecipes": [
      {
        "id": "discord",
        "version": "1.0.3"
      },
      {
        "id": "gitter",
        "version": "1.0.2"
      },
      {
        "id": "slack",
        "version": "1.0.15"
      },
      {
        "id": "whatsapp",
        "version": "2.0.3"
      },
      {}
    ],
    "devRecipes": [],
    "services": [
      {
        "id": "0ba05054-87b8-416b-b1cd-cb8be1fd95f7",
        "recipe": "slack",
        "isAttached": true,
        "isActive": true,
        "isEnabled": true,
        "isHibernating": false,
        "hasCrashed": false,
        "isDarkModeEnabled": false
      },
      {
        "id": "f504598c-f49a-4740-a121-a68c80652624",
        "recipe": "gitter",
        "isAttached": true,
        "isActive": false,
        "isEnabled": true,
        "isHibernating": false,
        "hasCrashed": false,
        "isDarkModeEnabled": false
      },
      {
        "id": "369fd4d2-35fa-420a-92c8-6a5fb56c6b9a",
        "recipe": "slack",
        "isAttached": true,
        "isActive": false,
        "isEnabled": true,
        "isHibernating": false,
        "hasCrashed": false,
        "isDarkModeEnabled": false
      },
      {
        "id": "d35f0429-83dc-4fa7-a832-e3c4b1c786a1",
        "recipe": "whatsapp",
        "isAttached": true,
        "isActive": false,
        "isEnabled": true,
        "isHibernating": false,
        "hasCrashed": false,
        "isDarkModeEnabled": true
      },
      {
        "id": "528fea44-7c33-4d84-86a3-4c8840b4d982",
        "recipe": "slack",
        "isAttached": true,
        "isActive": false,
        "isEnabled": true,
        "isHibernating": false,
        "hasCrashed": false,
        "isDarkModeEnabled": false
      }
    ],
    "messages": [
      {
        "type": "error",
        "info": [
          "error",
          "[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@160]'",
          {}
        ]
      },
      {
        "type": "error",
        "request": {
          "result": null,
          "wasExecuted": true,
          "method": "getInfo"
        },
        "error": {},
        "response": {},
        "server": "You are using Ferdi without a server"
      },
      {
        "type": "error",
        "request": {
          "result": null,
          "wasExecuted": true,
          "method": "features"
        },
        "error": {},
        "response": {},
        "server": "You are using Ferdi without a server"
      },
      {
        "type": "error",
        "request": {
          "result": null,
          "wasExecuted": true,
          "method": "all"
        },
        "error": {},
        "response": {},
        "server": "You are using Ferdi without a server"
      },
      {
        "type": "error",
        "info": [
          "error",
          "Warning: You cannot PUSH the same path using hash history"
        ]
      }
    ],
    "workspaces": [],
    "windowSettings": {
      "width": 800,
      "height": 600,
      "x": 536,
      "y": 480,
      "displayBounds": {
        "x": 0,
        "y": 0,
        "width": 1920,
        "height": 1080
      },
      "isMaximized": true,
      "isFullScreen": false
    },
    "settings": {
      "autoLaunchInBackground": false,
      "runInBackground": true,
      "reloadAfterResume": true,
      "enableSystemTray": false,
      "startMinimized": false,
      "minimizeToSystemTray": false,
      "privateNotifications": false,
      "showDisabledServices": true,
      "showMessageBadgeWhenMuted": true,
      "showDragArea": false,
      "enableSpellchecking": true,
      "spellcheckerLanguage": "en-us",
      "darkMode": true,
      "locale": "en-US",
      "fallbackLocale": "en-US",
      "beta": false,
      "isAppMuted": false,
      "enableGPUAcceleration": true,
      "serviceLimit": 5,
      "server": "You are using Ferdi without a server",
      "predefinedTodoServer": "https://app.franztodos.com",
      "autohideMenuBar": false,
      "lockingFeatureEnabled": false,
      "locked": false,
      "lockedPassword": "******",
      "useTouchIdToUnlock": true,
      "scheduledDNDEnabled": false,
      "scheduledDNDStart": "17:00",
      "scheduledDNDEnd": "09:00",
      "hibernate": false,
      "hibernateOnStartup": true,
      "hibernationStrategy": 300,
      "inactivityLock": 0,
      "automaticUpdates": false,
      "showServiceNavigationBar": false,
      "universalDarkMode": false,
      "adaptableDarkMode": true,
      "accentColor": "#189eff",
      "serviceRibbonWidth": "45",
      "iconSize": "30",
      "sentry": false,
      "navigationBarBehaviour": "never",
      "customTodoServer": "",
      "noUpdates": false,
      "todoServer": "isUsingCustomTodoService"
    },
    "features": {
      "isSpellcheckerIncludedInCurrentPlan": true,
      "needToWaitToProceed": false,
      "needToWaitToProceedConfig": {
        "delayOffset": 3600000,
        "wait": 10000
      },
      "isServiceProxyEnabled": true,
      "isServiceProxyIncludedInCurrentPlan": true,
      "isAnnouncementsEnabled": true,
      "isWorkspaceIncludedInCurrentPlan": true,
      "isWorkspaceEnabled": true,
      "isCommunityRecipesIncludedInCurrentPlan": true,
      "isSpellcheckerPremiumFeature": false,
      "isServiceProxyPremiumFeature": true,
      "isWorkspacePremiumFeature": false,
      "isSettingsWSEnabled": false,
      "isServiceLimitEnabled": false,
      "serviceLimitCount": 0,
      "isCommunityRecipesPremiumFeature": false,
      "isCustomUrlIncludedInCurrentPlan": true,
      "isMagicBarEnabled": true,
      "isTeamManagementIncludedInCurrentPlan": true,
      "isTodosEnabled": true,
      "isTodosIncludedInCurrentPlan": true,
      "defaultTrialPlan": "franz-pro-yearly",
      "subscribeURL": "https://getferdi.com",
      "planSelectionURL": "https://getferdi.com",
      "hasInlineCheckout": true,
      "isPlanSelectionEnabled": false,
      "isTrialStatusBarEnabled": false,
      "canSkipTrial": true,
      "pricingConfig": {
        "currency": "$",
        "currencyID": "USD",
        "plans": {
          "personal": {
            "monthly": {
              "id": "ferdi-free",
              "price": 0,
              "billed": 0
            },
            "yearly": {
              "id": "ferdi-completely-free",
              "price": 0,
              "billed": 0
            }
          },
          "pro": {
            "monthly": {
              "id": "ferdi-still-free",
              "price": 0,
              "billed": 0
            },
            "yearly": {
              "id": "ferdi-forever-free",
              "price": 0,
              "billed": 0
            }
          }
        }
      }
    },
    "user": "82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"
  }
}
```

**Comment by vantezzen** [comment] 2020-06-03 07:12
I suspect that this regression got introduced via our recent efforts to improving the cache clearing via #544

**Comment by mahadevans87** [comment] 2020-06-23 15:35
I can take this up. @vantezzen so shall we clear the cache of the individual service partitions and leave out the default partition?

**Comment by vantezzen** [comment] 2020-06-24 12:19
I'm not too familiar with all cache files Ferdi uses. Clearing the cache should also not delete any in-service data (Cookies, sessions etc.), so we need to test that, too.

**Comment by mitelg** [comment] 2020-08-24 06:46
the issue still exists!

**Comment by mitelg** [comment] 2020-10-23 08:05
the issue still exists :blush:

**Comment by BB8771** [comment] 2020-11-16 19:19
Still exists (16Nov2020) Win10 Ferdi 5.5.0

**Comment by alexdevero** [comment] 2021-01-16 10:39
The issue is still relevant.

**Comment by alexdevero** [comment] 2021-03-20 03:53
The issue is still relevant.

**Comment by mitelg** [comment] 2021-03-20 07:06
would be nice, if this could be fixed 🙈 I'm already thinking about switching back to Franz

**Comment by vraravam** [comment] 2021-08-04 07:18
@mitelg - sorry for the delay. This should now be fixed, and I will release it in the next nightly (in approx 20 hrs)

**Comment by mhatvan** [comment] 2021-08-07 06:20
@mitelg can you verify that this works for you?

**Comment by mitelg** [comment] 2021-08-07 14:34
is it fixed with the latest release (5.6.0)?
or do I need to build it manually, to test this

**Comment by vraravam** [comment] 2021-08-07 14:35
@mitelg - this is present in the latest nightlies from 3 days ago - any of the newer nightlies should be good to test it out.

**Comment by mhatvan** [comment] 2021-08-07 15:32
Here is the link, because they are not so easy to find: https://github.com/getferdi/nightlies/releases

**Comment by vraravam** [comment] 2021-08-07 16:22
Actually, the beta and nightly links are present in the main website: https://getferdi.com/download - at the bottom of this page

**Comment by mitelg** [comment] 2021-08-07 18:13
seems to be fixed :+1: 

thank you guys :blush:

**Comment by mhatvan** [comment] 2021-08-07 20:40
Great to hear, closing.

**Closed** 2021-08-07 23:34 UTC
Labels: bug, question, high priority
