### ISSUE TITLE
Slack custom icon no longer automatically set starting in v5.6

### ISSUE THREAD

**Issue by mjgardner** [getferdi/ferdi#1927] opened 2021-09-13 15:40 UTC
**Bug description:**

After upgrading to version 5.6 and up, my Slack service icons show the generic Slack logo instead of the custom icon per Slack instance.

**Steps to reproduce:**

1. Install Ferdi 5.6 or up.
2. Add Slack services (mine are houstonpm.slack.com, perlfoundation.slack.com, bbeditbeta.slack.com, slackbits.slack.com, and dzonecore.slack.com).
3. Note that on connecting to services the icon remains as the generic Slack icon.

**Expected behavior**

Slack service icon changes to the icon customized for each instance

**Screenshots**

<img width="1680" alt="Screen Shot 2021-09-13 at 10 37 33 AM" src="https://user-images.githubusercontent.com/133483/133113811-00286619-f69b-4fc8-bd5f-efaa1bef64fb.png">

**Environment:**

- Operating System: macOS Catalina 10.15.7 
- Ferdi Version: 5.6.2 
- Server: Ferdi 

- Debug information:

```
{"host":{"platform":"darwin","release":"19.6.0","screens":[{"id":458678941,"bounds":{"x":0,"y":0,"width":2560,"height":1440},"workArea":{"x":0,"y":0,"width":2560,"height":1440},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:SMPTEST432_1, transfer:0.0777*x + 0.0000 if x < 0.0450 else (0.9495*x + 0.0495)**2.3955 + 0.0003, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":2560,"height":1440},"displayFrequency":59,"workAreaSize":{"width":2560,"height":1440},"scaleFactor":2,"rotation":0,"internal":false,"touchSupport":"unknown"},{"id":69733382,"bounds":{"x":2560,"y":206,"width":1680,"height":1050},"workArea":{"x":2560,"y":206,"width":1680,"height":1050},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":30,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1_HDR, matrix:RGB, range:FULL}","depthPerComponent":10,"size":{"width":1680,"height":1050},"displayFrequency":60,"workAreaSize":{"width":1680,"height":1050},"scaleFactor":2,"rotation":0,"internal":true,"touchSupport":"unknown"}]},"ferdi":{"version":"5.6.2","electron":"13.3.0","installedRecipes":[{"id":"bitbucket","version":"1.0.1"},{"id":"discord","version":"1.4.0"},{"id":"enterprise-owa","version":"1.1.1"},{"id":"facebook","version":"1.0.2"},{"id":"github","version":"2.2.0"},{"id":"gmail","version":"1.3.9"},{"id":"googlecalendar","version":"1.0.7"},{"id":"googledrive","version":"1.0.7"},{"id":"googlemeet","version":"2.0.2"},{"id":"hangoutschat","version":"1.4.2"},{"id":"iCloud","version":"1.1.0"},{"id":"instagram","version":"2.0.1"},{"id":"irccloud","version":"1.1.0"},{"id":"jira","version":"1.3.1"},{"id":"linkedin","version":"1.2.1"},{"id":"messenger","version":"1.3.2"},{"id":"msteams","version":"3.1.4"},{"id":"mstodo","version":"1.1.0"},{"id":"office365-owa","version":"1.4.5"},{"id":"proton-mail","version":"1.3.0"},{"id":"reddit","version":"1.0.1"},{"id":"skype","version":"2.1.1"},{"id":"slack","version":"1.3.0"},{"id":"steamchat","version":"1.1.4"},{"id":"tweetdeck","version":"1.2.0"},{"id":"whatsapp","version":"3.3.2"},{}],"devRecipes":[],"services":[{"id":"97f43393-e3fd-4e48-aad7-76737fed23c5","recipe":"office365-owa","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"f0a9782d-31c9-448b-9579-482c10acee07","recipe":"mstodo","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"95337226-fa71-4931-a86a-d269866261c8","recipe":"msteams","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"cd70a79c-4c08-4bc6-a4dd-2ea8e56cb505","recipe":"jira","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":true,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"e62a16fa-78e4-4198-b502-0b9c9e07cda1","recipe":"iCloud","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":true,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"e96d25be-c64b-4b3f-97e5-67b5d0add0b9","recipe":"proton-mail","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"5e46edad-e39a-46db-8080-39817174e354","recipe":"messenger","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"84816beb-5768-4351-8bd0-bf767e191d26","recipe":"whatsapp","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"a0aaf78a-ed68-443b-aab4-3d0c90ca584e","recipe":"tweetdeck","isAttached":false,"isActive":false,"isEnabled":true,"isHibernating":true,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"4430fb7b-180c-4d44-be08-604f7c06d2cd","recipe":"irccloud","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"f98a7d29-121d-4bec-a4b8-c5f6ed2be799","recipe":"discord","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"585d3ccb-5c82-45ce-aa28-d615a4a97d59","recipe":"linkedin","isAttached":false,"isActive":false,"isEnabled":true,"isHibernating":true,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"159f6e07-9db6-403e-af63-bd25c381adca","recipe":"slack","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"f5fdf287-a4a5-48c5-a53f-ceee7539d1b8","recipe":"slack","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"6d2bb51f-5b12-4ba9-97cd-fa19a32bf005","recipe":"slack","isAttached":false,"isActive":false,"isEnabled":true,"isHibernating":true,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"781fa883-27d5-426c-bcd9-53a5cebe419b","recipe":"slack","isAttached":false,"isActive":false,"isEnabled":true,"isHibernating":true,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"e79a1cc5-216a-4d92-aaa6-d93b4518a22f","recipe":"slack","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"24bbf512-0ca2-461a-9523-4862cd2605d8","recipe":"github","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":true,"hasCrashed":false,"isDarkModeEnabled":false}],"messages":[{"type":"error","info":["error","Warning: Failed prop type: Invalid prop `actions.service` of type `Object` supplied to `_class2`, expected instance of `_class`.\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","info":["error","Warning: Failed prop type: Invalid prop `actions.settings` of type `Object` supplied to `_class2`, expected instance of `_class`.\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in ThemeProvider (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","info":["error","Warning: You cannot PUSH the same path using hash history"]},{"type":"log","info":["log","New email received",{"icon":"data:image/gif;base64,R0lGODlhyADIAMQAAOTl9K6y28nM5/n5/Jqf0qes1+vs9tfY7fLy+bW53tDS6t7f8aGl1by/4cLG5P///5OYzwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH/C1hNUCBEYXRhWE1QPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS4zLWMwMTEgNjYuMTQ1NjYxLCAyMDEyLzAyLzA2LTE0OjU2OjI3ICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOnhtcE1NPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvbW0vIiB4bWxuczpzdFJlZj0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL3NUeXBlL1Jlc291cmNlUmVmIyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ1M2IChNYWNpbnRvc2gpIiB4bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOjA2MzRCN0Y5MTYyODExRTY5OUMxRjBFRjQyNEUwMzAzIiB4bXBNTTpEb2N1bWVudElEPSJ4bXAuZGlkOjA2MzRCN0ZBMTYyODExRTY5OUMxRjBFRjQyNEUwMzAzIj4gPHhtcE1NOkRlcml2ZWRGcm9tIHN0UmVmOmluc3RhbmNlSUQ9InhtcC5paWQ6MDYzNEI3RjcxNjI4MTFFNjk5QzFGMEVGNDI0RTAzMDMiIHN0UmVmOmRvY3VtZW50SUQ9InhtcC5kaWQ6MDYzNEI3RjgxNjI4MTFFNjk5QzFGMEVGNDI0RTAzMDMiLz4gPC9yZGY6RGVzY3JpcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ9InIiPz4B//79/Pv6+fj39vX08/Lx8O/u7ezr6uno5+bl5OPi4eDf3t3c29rZ2NfW1dTT0tHQz87NzMvKycjHxsXEw8LBwL++vby7urm4t7a1tLOysbCvrq2sq6qpqKempaSjoqGgn56dnJuamZiXlpWUk5KRkI+OjYyLiomIh4aFhIOCgYB/fn18e3p5eHd2dXRzcnFwb25tbGtqaWhnZmVkY2JhYF9eXVxbWllYV1ZVVFNSUVBPTk1MS0pJSEdGRURDQkFAPz49PDs6OTg3NjU0MzIxMC8uLSwrKikoJyYlJCMiISAfHh0cGxoZGBcWFRQTEhEQDw4NDAsKCQgHBgUEAwIBAAAh+QQAAAAAACwAAAAAyADIAAAF/yAkjmRpnmiqrmzrvnAsz3Rt33iu73zv/8CgcEgsGo/IpHLJbDqf0Kh0Sq1ar9isdsvter/gsHhMLpvP6LR6zW673/C4fE6v2+/4vH7P7/v/gIGCg4SFhoeIiYqLjI2Oj5CRkpOUlZaXmJmam5ydnp+goaKjpKWmp6ipqqusra6vsLGys7S1tre4ubq7vL2+v8DBwsOjBQHHAQXEOgkKBg/Q0dAGCgnLMgEHA9Lc3AMHAdcsAQDd5uYA4eImBArn7+YKBOsjBQjw+NwIyusB2/kAoQ1QtyxBwIPRrBEr8A9hwAH8ghG45xDhgHnBFiA0AADAs4MLghkEeCABRhEEEv8cCKjQF0V4BxioYLASH4JfDfANdOEPXwNfH89BhMEQnoFeBeANjVH0XcRc7t61jDHynAJeL7sBsFHu3E1dSd8RnBEA3lNbDt4dvRG0mwNdNc29vZH23AFdXc2NpVH23NZcebvtJfvuL67A3AZjK4xXLI6+6BqfUxwDslbJeh8zBuz4hmVuhm8hlnZAgOnTqFOrPh33MueKsF0fjk07Wmhbo2sjvF0rt+6AvGn5/p0v+KzhxOEZl9U6ecC7uQg0dJ7v4q6m1JWexVWgbXZuBrZH1/id24KTugTIFNFgOvUBP0UwEIAXfj3vxMOPaL88VtfzKDWn2wEYEUBef7DkhQD/Qe39Zp8IAbyE4CuI0ScffhutB4EAoGEWjQEaRlXRVRfKJpo5D0LQ00E7seceNBO6MhyAEBgYEI02+uVhNwuOkMCL0gzQUoTK7WiOhTWKyI08I3CIT4ytIPdhRAUEBgCVGJqI20NziVCAaU85AGRkr92IHgk5AmekTuqRMN+Ym80GmwEHHJBlcWuWp2VveuJZZp86/gnonsINGueJhpIpZ6IdQsVoNyTiMtGj0SBwpi0EIKPpppx26umnl9Ij6qiklmrqqaimquqqrLbq6quwxirrrLTWauutuOaq66689urrr8AGK+ywxBZr7LHIJqvsssw26+yz0EYr7bTUVmvtE7XYZqvtttx26+234IYr7riqhAAAOw==","body":"From: Twitter - Reserve your spot for tomorrow's #TwitterAdTalk"}]},{"type":"error","info":["error","Warning: Failed prop type: Invalid prop `actions.ui` of type `Object` supplied to `_class`, expected instance of `_class`.\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions (created by RouterContext)\n    in div (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in ThemeProvider (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","info":["error","Warning: Failed prop type: Invalid prop `actions.app` of type `Object` supplied to `_class2`, expected instance of `_class`.\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in div (created by _class2)\n    in CSSTransitionGroupChild (created by TransitionGroup)\n    in span (created by TransitionGroup)\n    in TransitionGroup (created by CSSTransitionGroup)\n    in CSSTransitionGroup (created by Appear)\n    in Appear (created by _class2)\n    in _class2 (created by _class)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions (created by RouterContext)\n    in div (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in ThemeProvider (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","info":["error","Warning: Failed prop type: Invalid prop `actions.service` of type `Object` supplied to `_class`, expected instance of `_class`.\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions (created by RouterContext)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in div (created by _class2)\n    in CSSTransitionGroupChild (created by TransitionGroup)\n    in span (created by TransitionGroup)\n    in TransitionGroup (created by CSSTransitionGroup)\n    in CSSTransitionGroup (created by Appear)\n    in Appear (created by _class2)\n    in _class2 (created by _class)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions (created by RouterContext)\n    in div (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in ThemeProvider (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","info":["error","Warning: Failed prop type: Invalid prop `router` of type `Object` supplied to `_class2`, expected instance of `RouterStore`.\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in div (created by _class2)\n    in CSSTransitionGroupChild (created by TransitionGroup)\n    in span (created by TransitionGroup)\n    in TransitionGroup (created by CSSTransitionGroup)\n    in CSSTransitionGroup (created by Appear)\n    in Appear (created by _class2)\n    in _class2 (created by _class)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions (created by RouterContext)\n    in div (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in ThemeProvider (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]}],"workspaces":[{"id":"4a747c81-ab61-45b2-9fd4-5e8c7dc23b00","services":["585d3ccb-5c82-45ce-aa28-d615a4a97d59"]},{"id":"e7d6e404-d65c-4c5f-bcad-1b65808805c8","services":["e96d25be-c64b-4b3f-97e5-67b5d0add0b9","4430fb7b-180c-4d44-be08-604f7c06d2cd","a0aaf78a-ed68-443b-aab4-3d0c90ca584e","f98a7d29-121d-4bec-a4b8-c5f6ed2be799","84816beb-5768-4351-8bd0-bf767e191d26","24bbf512-0ca2-461a-9523-4862cd2605d8"]},{"id":"790e0596-8609-49d2-8881-5d44a8291798","services":["a0aaf78a-ed68-443b-aab4-3d0c90ca584e","585d3ccb-5c82-45ce-aa28-d615a4a97d59"]}],"windowSettings":{"width":1707,"height":1063,"x":185,"y":230,"isMaximized":true,"isFullScreen":true,"displayBounds":{"x":2560,"y":206,"width":1680,"height":1050}},"settings":{"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":true,"confirmOnQuit":true,"minimizeToSystemTray":false,"closeToSystemTray":false,"privateNotifications":false,"clipboardNotifications":true,"notifyTaskBarOnMessage":true,"showDisabledServices":false,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"en-us","darkMode":true,"locale":"en-US","fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":true,"server":"https://api.getferdi.com","predefinedTodoServer":"https://app.franztodos.com","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":true,"scheduledDNDStart":"23:00","scheduledDNDEnd":"08:00","hibernateOnStartup":true,"hibernationStrategy":300,"wakeUpStrategy":300,"inactivityLock":0,"automaticUpdates":true,"showServiceNavigationBar":false,"universalDarkMode":true,"userAgentPref":"","adaptableDarkMode":true,"accentColor":"#7266F0","serviceRibbonWidth":45,"iconSize":30,"sentry":true,"nightly":false,"navigationBarBehaviour":"never","searchEngine":"duckDuckGo","useVerticalStyle":false,"alwaysShowWorkspaces":false,"liftSingleInstanceLock":false,"serviceLimit":5,"hibernate":true,"todoServer":"isUsingCustomTodoService","customTodoServer":""},"features":{"isServiceProxyEnabled":true,"isWorkspaceEnabled":true,"isTodosEnabled":true,"isSettingsWSEnabled":false},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}
```

**Comment by mhatvan** [comment] 2021-09-13 16:08
Can confirm this on Ubuntu.

**Comment by cmoulliard** [comment] 2021-09-16 20:21
Me too on macos

**Comment by mhatvan** [comment] 2021-09-17 06:55
Hmm strange, when I try to debug this locally in dev, the custom icons load fine.
@vraravam any idea what could have broken this?

**Comment by vraravam** [comment] 2021-09-17 07:12
no idea. I tried to switch back to the older version of Ferdi (cleaning the slack recipe in the profile as well), but no luck in identifying the root cause.

**Comment by guyguy333** [comment] 2021-09-18 18:20
Similar issue on macOS

**Comment by kris7t** [comment] 2021-09-18 23:24
This should be fixed by https://github.com/getferdi/ferdi/pull/1964

**Closed by kris7t** 2021-09-18 23:24 UTC
Labels: bug

**Comment by cmoulliard** [comment] 2021-09-21 17:12
When this fix is planned to be released ? In version 5.6.2 ?

**Comment by kris7t** [comment] 2021-09-21 21:20
It should be in the latest nightly: https://github.com/getferdi/nightlies/releases

**Comment by guyguy333** [comment] 2021-09-23 06:45
@kris7t I confirm it works with nightly 5.6.3-nightly.10 You need to force reload to get icons. Thanks :)
