### ISSUE TITLE
got a problem on ferdi password lock!!

### ISSUE THREAD

**Issue by cbshourov** [getferdi/ferdi#1133] opened 2020-12-25 11:54 UTC
Hi, I got a major problem with ferdi. After I turned on ferdi's password lock, it crashed. Now I can not use ferdi at all. I can exit and lunch ferdi just fine, but it only shows a blue screen and top navigation bar. I have tried to uninstall and install it back, but no. 

I am using the latest version of linuxmint on intel based hp laptop. Is there a way to solve this problem?

Thanks in advance.

**Comment by Soliman2020** [comment] 2021-01-12 13:06
Same issue occurred while setting up password lock while using Windows 10 version 20H2 !!
I had to uninstall Ferdi files by IObit uninstaller then reinstall Ferdi again to able to reuse it without password lock this time.

**Comment by lecoredump** [comment] 2021-01-14 22:53
I just ran into the same issue as you both.

Quick trick on any GNU/Linux that should at least let you keep your stuff. Before any attempt at enabling it, run : 
```shell
user@host $ [ -f ferdi.tgz ] && rm -f ferdi.tgz; tar czf ferdi.tgz $HOME/.config/Ferdi
```
And when / if it crashes, simply shut it down (`killall` seems to work, at least on Archlinux) : 
```
user@host $ [ -f ferdi.tgz ] && tar xzf ferdi.tgz
```
You should be able to run Ferdi agin afterwards.
Regarding the issue itself, below is all I could collect so far

### Technical information
- Ferdi : [ferdi-bin](https://aur.archlinux.org/packages/ferdi-bin/) 5.5.0-1, installed from the AUR 
- OS: Arch Linux 
- Kernel: x86_64 Linux 5.10.7-arch1-1
- Shell: bash 5.1.4

### Logs and stuff
Running ferdi rfom the CLI gives out the following on start : 
```
ferdi 
Gtk-Message: 23:08:39.602: Failed to load module "colorreload-gtk-module"
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
(node:459457) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:459457) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:459457) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:459457) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
Starting local server on port 45569
info: serving app on http://127.0.0.1:45569
```
When the `Password lock` functionality is enabled, the following occurs in the application itself
![image](https://user-images.githubusercontent.com/30411803/104658078-626eba00-56c2-11eb-845a-b92bef48d48f.png)
And when you click on "Reload", this happens in the terminal :
```
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: SettingsStore.js:1:2731
Remote event names: blur
(node:459457) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:459457) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:459457) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:459457) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: SettingsStore.js:1:2934
Remote event names: focus
```

Any further attempt at doing anything that would result in an interaction stumps instead and results in more of the same (here, attempts to reload services, then Ferdi itself): 
```
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: Menu.js:1:20199
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: Menu.js:1:20199
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: Menu.js:1:20199
```

I haven't tried the other 2 version from the AUR, I'll do so and get back to you ASAP.

**Comment by lecoredump** [comment] 2021-01-14 23:47
By the time I was done commenting, the Git version was finally built (v. 5.6.0.beta.5.r6.g6aeae690-1), and the problem no longer occurs for this version at least.

I don't have time tonight to bisect when the fix occurred, but at least it seems fixed in current HEAD.

**Comment by gwlit** [comment] 2021-01-31 12:49
I got the same problem just as @cbshourov describes. I had this problem before when first setting up ferdi and enabling a ferdi account or trying to set a problem - would usually "solve" it by entirely wiping all ferdi files ans reinstalling. Now I got the problem again because I didn't think about it anymore.. Before I do the same all-new procedure again (would also appreciate explanations for alternative solution): Is there a way to save my settings, service profiles and so on? Which files could I copy back into it so I wont have to set it all up after reinstalling?

Unfortunately, I don't understand code (and thus major parts of your above comment, @lecoredump ), but I can follow simple command tasks and the like if explained in detail...

**Comment by gwlit** [comment] 2021-01-31 21:08
okay, so that might be obvious to people who know who this programs worked, but I found a fix that was rather a lucky hit for me:
Editet the "settings.json" file in %appdata%\Roaming\Ferdi\config with txt editor and set "lockingFeatureEnabled": to "false" instead of "true". Ferdi is loading as intended now.

**Comment by lecoredump** [comment] 2021-02-01 11:53
@gwlit, yep, my comment may be a little too technical, as I wanted to describe the issue with as much details as possible to find its source. Basically, the commands I provided before the "Technical information" title only backup and restore your whole `Ferdi` configuration and Cache files on a GNU/Linux machine (Ubuntu, Debian...)

Since I don't run any Windows machine, I won't be able to help regarding how to fix it, the only "issue" I could see with your proposed `fix` would be the potential impact on local cache and/or data already stored by `Ferdi`.
Anyway, you could run the following to back everything up before enabling `locking` from a Powershell Terminal, as such: 
```powershell 
# "Backup" command
PS C:\Users\someuser> Compress-Archive -LiteralPath $env:APPDATA\Roaming\Ferdi\ -DestinationPath where\you\wanna\backup.zip
# "Restore" command
PS C:\Users\someuser> Expand-Archive -LiteralPath where\you\wanna\backup.zip -DestinationPath $env:APPDATA\Roaming\Ferdi\
```

**Comment by jacquesndl** [comment] 2021-03-25 13:50
Hello everyone, any news on this ?

**Comment by ColtonBeery** [comment] 2021-04-08 00:23
Looks to me like a duplicate of #750

**Closed** 2021-06-05 19:36 UTC
Labels: duplicate
