### ISSUE TITLE
Add Signal messening to Ferdi. A Web application of Signal is already available.

### ISSUE THREAD

**Issue by Myalternativea** [getferdi/ferdi#1179] opened 2021-02-01 15:46 UTC
Hello, I submitted a request to ask you to add Signal messenging to Ferdi.
I got a reply, that Signal has no web application. So, the request is closed.
But, I'd like you to reconsider your position. Indeed, Signal messenging has already developped a web application which works perfectly, on Windows, Mac and Linux. I am using it currently on my PC.
You can check the following URL, wich give the possibility to download the corresponding web application regarding the OS used:
https://signal.org/fr/download/windows/

Hope that, your  sympathic team will add Signal to Ferdi.
Thank you

**Comment by kris7t** [comment] 2021-02-01 15:53
Duplicate of #1155.

Please don't open any more new issues on this. If you want to discuss further, do so under #1155, but keep in mind that the we won't be able to distribute any Signal client unless the Signal Foundation changes its policy on third-party clients.

**Closed by kris7t** 2021-02-01 15:53 UTC
