### ISSUE TITLE
Copy & Paste on Hangouts, doesn't behave the way it's supposed to

### ISSUE THREAD

**Issue by keplerk** [getferdi/ferdi#770] opened 2020-05-23 16:50 UTC
**Bug description:**
Pasting text in conversation insert it at the beginning of everything

**Steps to reproduce:**
Copy any text and paste in a conversation where you have already some text wrote, the paste text will be inserted at the beginning of everything

**Expected behavior**
The text should be inserted on the cursor position

**Environment:**

- Operating System: Windows 10
- Ferdi Version: 5.5.0 (x64)
- Server: Ferdi

**Comment by mahadevans87** [comment] 2020-05-23 17:01
This seems to be a duplicate of #643 . But this was fixed in recipes. @vantezzen How can we confirm if this fix was shipped with 5.5.0?

**Comment by keplerk** [comment] 2020-05-23 17:04
Hi @mahadevans87 i didn't knew it was already reported, well im using 5.5.0 maybe it was shipped but not deployed when compiled. Do we know which file must have changed to check if it was fixed ?

**Comment by mahadevans87** [comment] 2020-05-23 17:22
Looks like this was merged - https://github.com/getferdi/recipes/pull/142

**Comment by timwsuqld** [comment] 2020-06-22 06:53
I'm having this issue on 5.5.0 as well

**Comment by bpwned** [comment] 2020-06-23 18:44
Is this supposed to have been fixed with the merge? I ask because I also have this issue on 5.5.0.2116 on macOS.

**Comment by ganicotte** [comment] 2020-11-24 13:41
Still an issue for me (5.5.0 Windows 10)

**Comment by timwsuqld** [comment] 2021-01-27 02:32
It appears to be fixed in the 5.6.0 beta that I'm running, so maybe close once 5.6 is released?

**Comment by mhatvan** [comment] 2021-08-23 16:16
Closing as duplicate of https://github.com/getferdi/ferdi/issues/643 and https://github.com/getferdi/ferdi/issues/1199

Was fixed in the mean time.

**Closed by mhatvan** 2021-08-23 16:16 UTC
Labels: duplicate
