### ISSUE TITLE
WhatsApp multi-device beta keeps logging out

### ISSUE THREAD

**Issue by zemmyang** [getferdi/ferdi#2278] opened 2021-11-24 18:59 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

### Ferdi Version

5.6.3

### What operating system are you using?

Windows

### Server

Ferdi

### Operating System Version

Windows 10 21H1

### What arch are you using?

x64

### Steps to reproduce

I'm on the WhatsApp multi-device beta, and when I log in to WA using Ferdi, it's fine. But when the PC goes on hibernate or is shut down and then is turned back on, it get stuck on _connecting_... and I get the attached screenshot.

Reloading the service doesn't work, reloading Ferdi doesn't work, quitting and re-starting Ferdi does not work.

### Expected Behavior

It'll just get reconnected.

### Actual Behavior

See screenshot, it just says "connecting to whatsapp" even though my computer's internet works fine.

### Screenshots

![image](https://user-images.githubusercontent.com/1752285/143297961-cfc97494-a51d-4c76-9ae8-61ee19846141.png)

**Comment by jpennekamp** [comment] 2021-11-24 19:12
Duplicate of #1745

**Closed** 2021-11-24 23:17 UTC
Labels: bug :beetle:
