### ISSUE TITLE
Images/Videos on Google Chat are not being displayed anymore.

### ISSUE THREAD

**Issue by leoheck** [getferdi/ferdi#1283] opened 2021-04-19 15:11 UTC
It is like this since a week ago. 

This is all I can see, even if I am the one posting pictures
![image](https://user-images.githubusercontent.com/1277920/115259333-2bb49f80-a108-11eb-9517-4a4808db5867.png)

I am using this
![image](https://user-images.githubusercontent.com/1277920/115259531-5bfc3e00-a108-11eb-9401-242cd84faae6.png)

**Comment by jorisc90** [comment] 2021-04-20 09:45
+1 - just wanted to note that I see the same issue, running 5.5.0 on Mac.

<img width="588" alt="Screenshot 2021-04-20 at 11 44 55" src="https://user-images.githubusercontent.com/789370/115375195-d8a52000-a1cd-11eb-8108-da99121a776c.png">

**Comment by leoheck** [comment] 2021-04-20 14:08
Franz is working. Ferdi looks abandoned.

**Comment by pfeiffee** [comment] 2021-04-21 21:57
I am seeing the same issue. I also tried it in the latest 5.6.0 beta and it still happens.

**Comment by leoheck** [comment] 2021-04-22 14:43
For me, 5.6.0 beta is useless since it is not showing the input field. So it is not possible to write a message.

**Comment by stealthgyro** [comment] 2021-04-22 15:58
I don't know if this is relevant, I did notice old photos that do work come from the following type of domain.
https://lh3.googleusercontent.com/<someguidstring>/<anotherguid>/<anotherone>/s0/filename.png
https://chat.google.com/u/0/api/get_attachment_url?url_type=FIFE_URL&content_type=image%2Fjpeg&attachment_token=<stupid long string>

old content from hangouts in the chat does load, I have no idea if this is relevant, but thought I would call it out.

**Comment by MichaelBui** [comment] 2021-04-24 03:33
I have the same issue

**Comment by vraravam** [comment] 2021-04-25 11:49
Update: I am on the latest nightly, but maybe that is not too relevant.

First, please try this:
1) Close Ferdi.
2) Open the following location: `<FerdiProfileForYourOS>/recipes/hangoutschat/index.js` in your favorite editor
3) Comment out all the lines *within* the class definition ie make it an empty javascript class. For the version of the recipes that are in my installation, it looks like:
```javascript
    // // Method to add headers to requests from Hangouts Chat's webview
    // modifyRequestHeaders() {
    //   return [{
    //     headers: {
    //       'user-agent': window.navigator.userAgent.replace(/(Ferdi|Electron)\/\S+ \(?[^)]+\)?/g, '').trim(),
    //       'origin': 'https://chat.google.com'
    //     },
    //     requestFilters: {
    //       urls: ['*://*/*']
    //     }
    //   }]
    // }

    // overrideUserAgent() {
    //   return window.navigator.userAgent.replace(/(Ferdi|Electron)\/\S+ \(?[^)]+\)?/g, '').trim();
    // }
```

Please confirm if image previewss are now working. I can see the image previews that were previously broken.

**Comment by vraravam** [comment] 2021-04-25 12:05
I have raised a PR for this - if you confirm, please also upvote the referenced PR - so that it can be merged for the next release.

**Comment by leoheck** [comment] 2021-04-25 18:06
@vraravam thanks. this fixes the issue for me.

**Comment by antonc42** [comment] 2021-04-27 13:05
This also fixed my issue.

**Comment by MichaelBui** [comment] 2021-04-27 16:48
The root cause is the `Origin` header in the request. I used Postman to send requests (must include your cookie or you will see the login page), without the `Origin` header, it returns an image (after a 302 redirection).

As long as I include the `Origin` header (whatever values), the request always returns `204` with empty content which is why images are not displaying.

I'm not familiar with Franz/Ferdi but I hope someone can instruct me on how to remove the `Origin` header so I can try and confirm. At least we can fix it in the local `index.js` file.

**Comment by vraravam** [comment] 2021-04-28 07:04
@MichaelBui - if you want to be totally surgical, you can comment out line no 9 from the above screenshot - that should do the trick.

**Comment by themagpieswarble** [comment] 2021-04-30 17:51
> @MichaelBui - if you want to be totally surgical, you can comment out line no 9 from the above screenshot - that should do the trick.

This worked great for me. Thanks everyone for the solutions! By the way if anyone else needed the full explorer path to get to the 'index.js' file it's:

C:\Users\%username%\AppData\Roaming\Ferdi\recipes\hangoutschat

**Comment by neel1996** [comment] 2021-05-05 09:38
> Update: I am on the latest nightly, but maybe that is not too relevant.
> 
> First, please try this:
> 
> 1. Close Ferdi.
> 2. Open the following location: `<FerdiProfileForYourOS>/recipes/hangoutschat/index.js` in your favorite editor
> 3. Comment out all the lines _within_ the class definition ie make it an empty javascript class. For the version of the recipes that are in my installation, it looks like:
> 
> ```js
>     // // Method to add headers to requests from Hangouts Chat's webview
>     // modifyRequestHeaders() {
>     //   return [{
>     //     headers: {
>     //       'user-agent': window.navigator.userAgent.replace(/(Ferdi|Electron)\/\S+ \(?[^)]+\)?/g, '').trim(),
>     //       'origin': 'https://chat.google.com'
>     //     },
>     //     requestFilters: {
>     //       urls: ['*://*/*']
>     //     }
>     //   }]
>     // }
> 
>     // overrideUserAgent() {
>     //   return window.navigator.userAgent.replace(/(Ferdi|Electron)\/\S+ \(?[^)]+\)?/g, '').trim();
>     // }
> ```
> 
> Please confirm if image previewss are now working. I can see the image previews that were previously broken.

@vraravam Thanks. The work around fixed the issue. 

In case if anyone is trying to locate the `index.js` file on a Mac for hangoutschat, then it can be located under `/Users/<user_name>/Library/Application Support/Ferdi/recipes/hangoutschat`. 

If you try to add a custom service, then it will show the recipes path as well

**Comment by vraravam** [comment] 2021-05-05 09:49
thanks @neel1996 - another quick way to find out the location of the recipes folder is to open the Service in preferences and clicking on the "Open User.js" button.

**Comment by vraravam** [comment] 2021-05-11 07:46
This if fixed by the PR: https://github.com/getferdi/recipes/pull/477

**Comment by vraravam** [comment] 2021-05-11 12:45
Here's the correct one: https://github.com/getferdi/recipes/pull/476

**Comment by antonc42** [comment] 2021-05-11 13:00
Looks like it's been merged, so everything should be good. Thanks for the great work!

**Comment by vraravam** [comment] 2021-05-12 06:14
The latest code for the recipes are now all merged. Please refer to the brand new [self-help documentation](https://drive.google.com/drive/folders/1mJmKbhpVHdb066IHlrdYiD8TG9wlmuBv) - which might help to solve the issue.

**Comment by vraravam** [comment] 2021-05-13 17:20
Sorry - this PR has now been merged into the main Ferdi repo: https://github.com/getferdi/ferdi/#troubleshooting-recipes-self-help

**Comment by leoheck** [comment] 2021-05-14 03:21
I have replaced my recipes with the latest version of it some minutes ago, now I have the same problem. 
Are you sure this thing was fixed?

![image](https://user-images.githubusercontent.com/1277920/118216685-5b766f00-b44a-11eb-9f8a-b53806530264.png)

**Comment by leoheck** [comment] 2021-05-14 03:22
I still had to comment out the same block of lines.

**Comment by vraravam** [comment] 2021-05-14 03:40
If you had to comment out the same block of lines - then it means that you do not have the latest recipes from the repo. Please check once again.

**Comment by vraravam** [comment] 2021-05-14 03:41
I just verified: https://github.com/getferdi/recipes/blob/70b5c9920860e9bf2663b13a26e07177e0152524/recipes/hangoutschat/index.js - the file is only the shell - all the intermediate lines were removed.

**Comment by leoheck** [comment] 2021-05-14 12:34
You are right. I am checking this on my filesystem here too. Does Ferdi change these recipes automatically?

**Comment by vraravam** [comment] 2021-05-14 13:18
Yes - it will remove when a new version of Ferdi is installed AND when the `version` of the installed recipe is older than the one that comes packaged within Ferdi.

But, since the nightlies are broken, this process doesn't work - yet. Thus, the manual jugglery.

I have created a feature request for this #1302 - which then can be done irrespective of whether a new version of Ferdi is being installed or not. If you find that useful, please upvote and/or add comments in there. Tx.

**Comment by vraravam** [comment] 2021-05-15 23:47
@leoheck - can we close this issue if your problem is resolved with the latest recipes?

**Comment by leoheck** [comment] 2021-05-15 23:49
Sure thing

**Closed** 2021-05-15 23:49 UTC
Labels: question, service-specific
