### ISSUE TITLE
no badge notification counter

### ISSUE THREAD

**Issue by rnogueira-namoadigital** [getferdi/ferdi#1095] opened 2020-12-03 12:30 UTC
there is no badge notification counter in any service.
I am on macos,
Ferdi 5.5.0

**Comment by GhyslainBruno** [comment] 2020-12-08 14:15
Almost same for me. 
Some of my services are having counter notification, some don't (especially Whatsapp). 

**Environment**: 
macOS BigSur (11.0.1)
Ferdi (5.5.0)

**Comment by croulibri** [comment] 2020-12-08 15:10
Hello,  
None of my service have notification (Discord, Element, Nextcloud, Mastodon, Dispora, Discourse) :-(

**Environment:**
Windows 10
Ferdi portable (5.6.0-beta2)

**Comment by beckermr** [comment] 2020-12-10 18:01
Same for me! :(

**Comment by b4umchen** [comment] 2020-12-15 09:28
Same for me!

**Comment by croulibri** [comment] 2020-12-15 11:20
Just to be more precise :

- Discord have notification, but no counter
- Element installed with Riot app has no notification and no counter
- Nextcloud installed with Custom app has no notification and no counter
- Discourse installed with Custom app has no notification and no counter
- Mastodon and Diaspora has no notification and no counter

**Comment by b4umchen** [comment] 2020-12-15 15:14
Hi,

- Whats App has notification, but no counter.
- Asana has notification, but no counter.
- Slack has notification, but no counter.

All Services i use the same as this.
Best regards

**Comment by beckermr** [comment] 2021-02-13 20:44
not stale!

**Comment by rnogueira-namoadigital** [comment] 2021-02-16 12:44
still there is no badge notification in Mac OS. A lot of message that I was not able to see!

**Comment by vraravam** [comment] 2021-05-22 13:08
With the latest version of Ferdi and the latest recipes, this should no longer be the case. I have a bunch of services and most of them show the unread counter + notification.
<img width="66" alt="Screen Shot 2021-05-22 at 6 37 35 PM" src="https://user-images.githubusercontent.com/69629/119227688-cac81f00-bb2c-11eb-94cb-394a7b07fd35.png">

Can you please try to upgrade to the nightlies available [here](https://github.com/getferdi/nightlies/releases) AND then upgrading the recipes by following the steps outlined [here](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help)?

If you are on macos or linux, I have shared some newer builds of the latest source code [here](https://drive.google.com/drive/folders/1mJmKbhpVHdb066IHlrdYiD8TG9wlmuBv)

**Comment by mhatvan** [comment] 2021-09-02 17:41
If there is a service that doesn't show a badge notification counter with the latest nightly from: https://github.com/getferdi/nightlies/releases, please open a new, specific issue for it.

Closing since outdated and cannot reproduce.

**Closed by mhatvan** 2021-09-02 17:41 UTC
Labels: outstanding question, service-specific

**Comment by vraravam** [comment] 2021-09-02 22:45
Also - in such cases if they occur, the better place to open such a service-specific ticket would be: https://github.com/getferdi/recipes/issues
