### ISSUE TITLE
At launch always says new version is available...

### ISSUE THREAD

**Issue by mikeyj110** [getferdi/ferdi#2349] opened 2021-12-21 12:54 UTC
At launch Ferdi always says new version is available and restart even when confirmed to be on most current version (5.6.3).  Package was downloaded and installed in December 2021.

M1 MacBook Air
macOS Monterey 12.1
Ferdi 5.6.3

<img width="524" alt="Screen Shot 2021-12-21 at 7 53 07 AM" src="https://user-images.githubusercontent.com/20076808/146933223-e8c3855e-cb3b-4077-b2b1-9abc1ec00a56.png">
<img width="296" alt="Screen Shot 2021-12-21 at 7 53 48 AM" src="https://user-images.githubusercontent.com/20076808/146933391-84e2a350-24b1-48f4-8096-94679b746c79.png">

**Comment by mhatvan** [comment] 2021-12-21 13:43
Closing as duplicate of https://github.com/getferdi/ferdi/issues/329
Auto-updating doesn't work currently for macOS while it does for e.g. Linux AppImage, I can recommend disabling updates in Ferdi settings for now until it is fixed to avoid the annoying prompt.

5.6.3 is not the latest version, you can see the newest releases here: https://github.com/getferdi/ferdi/releases

**Closed by mhatvan** 2021-12-21 13:43 UTC
