### ISSUE TITLE
[Bug]: Whitespace between sidebar and content in horizontal style

### ISSUE THREAD

**Issue by schousda** [getferdi/ferdi#2399] opened 2022-01-09 11:24 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

### Ferdi Version

5.6.9

### What operating system are you using?

Windows

### Server

Ferdi

### Operating System Version

Windows 11

### What arch are you using?

x64

### Steps to reproduce

There is some whitespace between the sidebar and the content, when i use the horizontal style for the sidebar.

1. Enable sidebar

### Expected Behavior

There should be no whitespace between sidebar and content.

### Actual Behavior

There is some visible whitespace of about half of the height of the sidebar.

### Screenshots

![2022-01-09_12-23-45](https://user-images.githubusercontent.com/21222928/148680168-1e7b9cb1-fbd2-4eb2-9d15-35b9a574c747.png)

**Comment by kytwb** [comment] 2022-01-09 11:44
Duplicate of https://github.com/getferdi/ferdi/issues/2256.

**Closed by kytwb** 2022-01-09 11:44 UTC
Labels: bug :beetle:
