### ISSUE TITLE
Right click not working

### ISSUE THREAD

**Issue by halcyon101** [getferdi/ferdi#452] opened 2020-03-10 08:08 UTC
it opens the right-click menu then closes it immediately how to fix this issue?

**Comment by kytwb** [comment] 2020-03-10 08:34
Duplicate of https://github.com/getferdi/ferdi/issues/357; we will be publishing a new beta release with the fix (https://github.com/getferdi/ferdi/pull/419) today.

**Closed by kytwb** 2020-03-10 08:34 UTC
Labels: duplicate

**Comment by kytwb** [comment] 2020-03-12 08:06
Shipped in [v5.4.4-beta.3](https://github.com/getferdi/ferdi/releases/tag/v5.4.4-beta.3).
