### ISSUE TITLE
Linux Mint: On tray icon (both left-click and right-click) open the context menu

### ISSUE THREAD

**Issue by fermmm** [getferdi/ferdi#2237] opened 2021-11-16 02:30 UTC
At least in Linux Mint and Ubuntu when clicking on the tray icon with any mouse button a context menu appears. This is annoying because to open the Ferdi window you need: tray icon click > move the mouse to "Show Ferdi" > Click "Show Ferdi".
Instead the Ferdi window should appear just by clicking with the left mouse button on the tray icon without context menu. The context menu should be open with the right mouse button.
My version of Ferdi: 5.6.4 Nightly 7

**Comment by vraravam** [comment] 2021-11-16 03:17
This must be an issue specific to linux. I tested the PR just this morning on macos, and the left-click vs the right-click behave as expected. (Left only hides/shows Ferdi's main window, while the right-click opens the context menu)

**Comment by fermmm** [comment] 2021-11-16 03:45
> This must be an issue specific to linux. I tested the PR #2234 just this morning on macos, and the left-click vs the right-click behave as expected. (Left only hides/shows Ferdi's main window, while the right-click opens the context menu)
> 
> @martinbernat - could you please comment?

Yes I just got a windows machine to test and it works ok on Windows too. I'll change the title

**Comment by martinbernat** [comment] 2021-11-16 06:14
@fermmm @vraravam yes I'll look into the linux issue ASAP (today evening probably).

**Comment by martinbernat** [comment] 2021-11-16 18:13
@fermmm I'm afraid I would need a bit more information about the issue. 
Just tested on Ubuntu (Server 21.10, with Gnome 40.4.0) and works exacly as on macOS. 
I've tested on nightly.6 with the fix (PR #2234) and also the on latest commit (nightly.7 + 2).

Which Ubuntu version are you using?

**Comment by fermmm** [comment] 2021-11-16 19:15
> @fermmm I'm afraid I would need a bit more information about the issue. Just tested on Ubuntu (Server 21.10, with Gnome 40.4.0) and works exacly as on macOS. I've tested on nightly.6 with the fix (PR #2234) and also the on latest commit (nightly.7 + 2).
> 
> Which Ubuntu version are you using?

Sorry I only tested on Linux Mint, I mentioned Ubuntu because Linux Mint is based on Ubuntu and I thought they share the same issues in general. Linux Mint is the second most used Linux distro (on desktop) so I think fixing this is important. I can run a fresh install of Mint and try there.

**Comment by martinbernat** [comment] 2021-11-16 20:26
Ok thanks, I’ll try on Mint as well.

**Comment by fermmm** [comment] 2021-11-17 01:15
> Ok thanks, I’ll try on Mint as well.

Confirmed. A live CD boot of Mint has the issue. Is this related to Ferdi? or should I report this to the Linux Mint team?

**Comment by vraravam** [comment] 2021-11-17 01:46
> Is this related to Ferdi? or should I report this to the Linux Mint team?

If this is not reproducible across other linux distros (and since we only publish the `deb` and `AppImage` packages, I would assume that this needs to be logged against Mint. Ferdi will not be able to support such exceptions.

**Comment by pulver22** [comment] 2021-11-17 09:43
I have the same problem on Ubuntu 18.04 with Gnome 3.28.4 .

**Comment by martinbernat** [comment] 2021-11-18 11:53
@fermmm, I tried to debug this on Ubuntu 18.04 and the 'click' event (left click) seems to be not fired. Doing some google work showed that it is an very old Electron issue:
https://github.com/electron/electron/issues/14941
https://github.com/patrikx3/onenote/issues/38
https://github.com/electron/electron/issues/21576
...

There is a workaround mentioned in the discussion, but does not work for Ubuntu (only for Mint) and it is kind of hack.
Some people mentioned that opening tray context menu on both left and right click is desired behavior and they do not plan to fix Electron.
Not sure if we can do anything here. @vraravam what do you think, can we close this bug?

**Comment by vraravam** [comment] 2021-11-18 12:08
Yes - if that's an upstream behavior, I don't see what we can do to overcome it unfortunately.

@pulver22 @fermmm - are you ok closing this?

**Comment by pulver22** [comment] 2021-11-18 13:50
@vraravam it's fine for me. I'm not so bothered by this behaviour in the end :)

**Comment by vraravam** [comment] 2021-11-18 15:58
thanks @pulver22 - closing this ticket for now.

**Closed by vraravam** 2021-11-18 15:58 UTC
Labels: bug :beetle:, outstanding question, Implement upstream, platform-specific
