### ISSUE TITLE
[Bug]: Ferdi doesnt show after minimized to systray

### ISSUE THREAD

**Issue by Wlkus** [getferdi/ferdi#2255] opened 2021-11-18 18:55 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

### Ferdi Version

5.6.3

### What operating system are you using?

Windows

### Server

Ferdi

### Operating System Version

Windows 11 Pro Version	10.0.22000 Build 22000.318

### What arch are you using?

x64

### Git SHA and/or build date

7ab8abe / Sun Nov 07 2021

### Steps to reproduce

1. Minimize Ferdi to systray ie. hide from taskbar and show only in systray
2. Try to click/doubleclick/use Show Ferdi option from Ferdi systray icon
3. Nothing happens, Ferdi doesnt popup, if I have it setup to start minimized in settings, there is no way to pop it back. Had to manually edit config json.

### Expected Behavior

Show main window of Ferdi

### Actual Behavior

Nothing happens, main window doesnt show whatever I do.

### Debug information

{"host":{"platform":"win32","release":"10.0.22000","screens":[{"id":2528732444,"bounds":{"x":-2560,"y":56,"width":2560,"height":1440},"workArea":{"x":-2560,"y":56,"width":2560,"height":1392},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":2560,"height":1440},"displayFrequency":59,"workAreaSize":{"width":2560,"height":1392},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"},{"id":2779098405,"bounds":{"x":0,"y":0,"width":1200,"height":1600},"workArea":{"x":0,"y":0,"width":1200,"height":1552},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1200,"height":1600},"displayFrequency":60,"workAreaSize":{"width":1200,"height":1552},"scaleFactor":1,"rotation":90,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.6.3","electron":"15.3.0","installedRecipes":[{"id":"android-messages","version":"2.2.4"},{"id":"discord","version":"1.4.5"},{"id":"hangouts","version":"1.2.1"},{"id":"icq","version":"1.1.2"},{"id":"messenger","version":"1.3.3"},{"id":"skype","version":"3.2.2"},{"id":"slack","version":"1.3.3"},{"id":"telegram","version":"3.2.4"},{"id":"trello","version":"1.2.0"},{"id":"whatsapp","version":"3.3.6"},{}],"devRecipes":[],"services":[{"id":"690323bc-ee45-47eb-8501-85eefa332838","recipe":"whatsapp","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"612efb51-bbb1-4b95-a403-464b4a963714","recipe":"hangouts","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"8a4704f3-080f-401b-a33a-d75caaeb0800","recipe":"messenger","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"8eb84a80-f7fa-4f89-91f1-8f5f754a95dc","recipe":"android-messages","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"d98acb86-d411-4577-a325-68d1b2ac6351","recipe":"telegram","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"441340fc-da40-41e1-8c86-474a63fae38a","recipe":"slack","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"d35d70b6-c022-4a8a-9234-8be703fafed4","recipe":"discord","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"2d61354b-9797-42ed-8640-467ce405e4cd","recipe":"skype","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"4dc69a82-4c45-4d86-b337-d7c1e8e3179d","recipe":"icq","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true}],"messages":[{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.service` of type `Object` supplied to `_class2`, expected instance of `_class`.","\n    at _class2 (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\containers\\layout\\AppLayoutContainer.js:1:1960)\n    at Injector (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at <anonymous> (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at <anonymous> (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at _class (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\routes.js:1:2781)\n    at Injector (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at IntlProvider (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-intl\\src\\components\\provider.js:81:47)\n    at _class (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\I18n.js:1:842)\n    at Injector (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at Provider (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:1328:7)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.settings` of type `Object` supplied to `_class2`, expected instance of `_class`.","\n    at _class2 (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\layout\\Sidebar.js:1:2094)\n    at Injector (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at injectIntl(inject-_class2-with-stores-actions)\n    at div\n    at div\n    at _class2 (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\util\\ErrorBoundary\\index.js:1:1023)\n    at Jss (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at _class2 (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\layout\\AppLayout.js:1:2715)\n    at Jss (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at ThemeProvider (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\theming\\dist\\cjs\\create-theme-provider.js:66:7)\n    at _class2 (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\containers\\layout\\AppLayoutContainer.js:1:1960)\n    at Injector (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at <anonymous> (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at <anonymous> (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at _class (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\routes.js:1:2781)\n    at Injector (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at IntlProvider (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-intl\\src\\components\\provider.js:81:47)\n    at _class (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\I18n.js:1:842)\n    at Injector (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at Provider (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:1328:7)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.settings` of type `Object` supplied to `_class`, expected instance of `_class`.","\n    at _class (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\features\\nightlyBuilds\\Component.js:1:2135)\n    at Injector (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at Jss (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(inject-_class-with-stores-actions))\n    at div\n    at div\n    at div\n    at _class2 (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\util\\ErrorBoundary\\index.js:1:1023)\n    at Jss (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at _class2 (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\layout\\AppLayout.js:1:2715)\n    at Jss (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at ThemeProvider (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\theming\\dist\\cjs\\create-theme-provider.js:66:7)\n    at _class2 (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\containers\\layout\\AppLayoutContainer.js:1:1960)\n    at Injector (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at <anonymous> (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at <anonymous> (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at _class (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\routes.js:1:2781)\n    at Injector (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at IntlProvider (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-intl\\src\\components\\provider.js:81:47)\n    at _class (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\I18n.js:1:842)\n    at Injector (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at Provider (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:1328:7)"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.ui` of type `Object` supplied to `_class`, expected instance of `UIStore`.","\n    at _class (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\containers\\settings\\SettingsWindow.js:1:1183)\n    at Injector (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at div\n    at div\n    at div\n    at _class2 (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\util\\ErrorBoundary\\index.js:1:1023)\n    at Jss (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at _class2 (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\layout\\AppLayout.js:1:2715)\n    at Jss (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at ThemeProvider (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\theming\\dist\\cjs\\create-theme-provider.js:66:7)\n    at _class2 (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\containers\\layout\\AppLayoutContainer.js:1:1960)\n    at Injector (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at <anonymous> (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at <anonymous> (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at _class (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\routes.js:1:2781)\n    at Injector (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at IntlProvider (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-intl\\src\\components\\provider.js:81:47)\n    at _class (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\I18n.js:1:842)\n    at Injector (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at Provider (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:1328:7)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.app` of type `Object` supplied to `_class`, expected instance of `_class`.","\n    at _class (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\containers\\settings\\EditSettingsScreen.js:1:7812)\n    at Injector (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at injectIntl(inject-_class-with-stores-actions)\n    at div\n    at _class2 (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\util\\ErrorBoundary\\index.js:1:1023)\n    at Jss (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at div\n    at CSSTransitionGroupChild (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-transition-group\\CSSTransitionGroupChild.js:83:5)\n    at span\n    at TransitionGroup (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-transition-group\\TransitionGroup.js:50:5)\n    at CSSTransitionGroup (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-transition-group\\CSSTransitionGroup.js:56:5)\n    at Appear (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\ui\\effects\\Appear.js:1:447)\n    at _class2 (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\settings\\SettingsLayout.js:1:962)\n    at injectIntl(_class2)\n    at _class2 (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\util\\ErrorBoundary\\index.js:1:1023)\n    at Jss (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at _class (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\containers\\settings\\SettingsWindow.js:1:1183)\n    at Injector (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at div\n    at div\n    at div\n    at _class2 (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\util\\ErrorBoundary\\index.js:1:1023)\n    at Jss (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at _class2 (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\layout\\AppLayout.js:1:2715)\n    at Jss (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at ThemeProvider (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\theming\\dist\\cjs\\create-theme-provider.js:66:7)\n    at _class2 (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\containers\\layout\\AppLayoutContainer.js:1:1960)\n    at Injector (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at <anonymous> (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at <anonymous> (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at _class (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\routes.js:1:2781)\n    at Injector (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at IntlProvider (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-intl\\src\\components\\provider.js:81:47)\n    at _class (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\I18n.js:1:842)\n    at Injector (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at Provider (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:1328:7)"]},{"type":"error","info":["error","Warning: validateDOMNesting(...): %s cannot appear as a descendant of <%s>.%s","<div>","p","\n    at div\n    at p\n    at div\n    at div\n    at form\n    at div\n    at div\n    at _class2 (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\settings\\settings\\EditSettingsForm.js:1:6862)\n    at injectIntl(_class2)\n    at _class2 (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\util\\ErrorBoundary\\index.js:1:1023)\n    at Jss (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at _class (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\containers\\settings\\EditSettingsScreen.js:1:7812)\n    at Injector (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at injectIntl(inject-_class-with-stores-actions)\n    at div\n    at _class2 (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\util\\ErrorBoundary\\index.js:1:1023)\n    at Jss (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at div\n    at CSSTransitionGroupChild (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-transition-group\\CSSTransitionGroupChild.js:83:5)\n    at span\n    at TransitionGroup (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-transition-group\\TransitionGroup.js:50:5)\n    at CSSTransitionGroup (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-transition-group\\CSSTransitionGroup.js:56:5)\n    at Appear (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\ui\\effects\\Appear.js:1:447)\n    at _class2 (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\settings\\SettingsLayout.js:1:962)\n    at injectIntl(_class2)\n    at _class2 (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\util\\ErrorBoundary\\index.js:1:1023)\n    at Jss (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at _class (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\containers\\settings\\SettingsWindow.js:1:1183)\n    at Injector (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at div\n    at div\n    at div\n    at _class2 (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\util\\ErrorBoundary\\index.js:1:1023)\n    at Jss (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at _class2 (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\components\\layout\\AppLayout.js:1:2715)\n    at Jss (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-jss\\lib\\createHoc.js:138:7)\n    at injectIntl(Jss(_class2))\n    at ThemeProvider (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\theming\\dist\\cjs\\create-theme-provider.js:66:7)\n    at _class2 (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\containers\\layout\\AppLayoutContainer.js:1:1960)\n    at Injector (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at <anonymous> (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at <anonymous> (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\create-react-class\\factory.js:899:37)\n    at _class (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\routes.js:1:2781)\n    at Injector (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at IntlProvider (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\react-intl\\src\\components\\provider.js:81:47)\n    at _class (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\I18n.js:1:842)\n    at Injector (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:616:9)\n    at Provider (C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\mobx-react\\index.js:1328:7)"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAppCacheSize"},"error":{"killed":false,"code":1,"signal":null,"cmd":"\"C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\fast-folder-size\\bin\\du.exe\" -nobanner -accepteula -q -c ."},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAppCacheSize"},"error":{"killed":false,"code":1,"signal":null,"cmd":"\"C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\fast-folder-size\\bin\\du.exe\" -nobanner -accepteula -q -c ."},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAppCacheSize"},"error":{"killed":false,"code":1,"signal":null,"cmd":"\"C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\fast-folder-size\\bin\\du.exe\" -nobanner -accepteula -q -c ."},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAppCacheSize"},"error":{"killed":false,"code":1,"signal":null,"cmd":"\"C:\\Users\\Wlk\\AppData\\Local\\Programs\\ferdi\\resources\\app.asar\\node_modules\\fast-folder-size\\bin\\du.exe\" -nobanner -accepteula -q -c ."},"response":{},"server":"https://api.getferdi.com"}],"workspaces":[],"windowSettings":{"width":1168,"height":748,"x":11,"y":315,"isMaximized":false,"isFullScreen":false,"displayBounds":{"x":0,"y":0,"width":1200,"height":1600}},"settings":{"autoLaunchOnStart":false,"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":false,"confirmOnQuit":false,"minimizeToSystemTray":false,"closeToSystemTray":true,"privateNotifications":false,"clipboardNotifications":true,"notifyTaskBarOnMessage":false,"showDisabledServices":true,"showServiceName":false,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"en-us","darkMode":true,"splitMode":false,"fallbackLocale":"en-US","beta":true,"isAppMuted":false,"enableGPUAcceleration":true,"enableGlobalHideShortcut":true,"server":"https://api.getferdi.com","predefinedTodoServer":"https://app.franztodos.com","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernateOnStartup":true,"hibernationStrategy":300,"wakeUpStrategy":300,"inactivityLock":0,"automaticUpdates":true,"universalDarkMode":true,"userAgentPref":"","adaptableDarkMode":false,"accentColor":"#7266F0","serviceRibbonWidth":68,"iconSize":20,"sentry":false,"nightly":false,"navigationBarBehaviour":"custom","searchEngine":"duckDuckGo","useVerticalStyle":false,"alwaysShowWorkspaces":false,"liftSingleInstanceLock":false,"enableLongPressServiceHint":false,"proxyFeatureEnabled":false,"onlyShowFavoritesInUnreadCount":false,"locale":"en-US","customTodoServer":""},"features":{},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}

**Comment by Alt37** [comment] 2021-11-18 21:15
Duplicate of [#2551](https://github.com/getferdi/ferdi/issues/2251)

**Comment by Wlkus** [comment] 2021-11-18 21:24
Sorry for dupe, tried to search for minimized, but no results. Strange. Maybe misspell.

**Closed** 2021-11-19 01:43 UTC
Labels: bug :beetle:
