### ISSUE TITLE
QuickSwitch does not work (does not get focus)

### ISSUE THREAD

**Issue by dzg** [getferdi/ferdi#1073] opened 2020-11-17 19:16 UTC
**Bug description:**
QuickSwitch popup does not have focus. Only if I click with mouse **in** the popup can I type search string, etc.

**Steps to reproduce:**

1. Type Cmd-S
2. Type a letter (to search), or up or down arrows
3. The key event is sent to the background open service, NOT to the quickswitch panel

- Operating System: macOS Catalina
- Ferdi Version: 5.5.0
- Server: Ferdi

- Debug information:
`{"host":{"platform":"darwin","release":"19.6.0","screens":[{"id":69986212,"bounds":{"x":0,"y":0,"width":3200,"height":1800},"workArea":{"x":0,"y":23,"width":3200,"height":1777},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries_d50_referred: [[0.6818, 0.3196],  [0.2846, 0.6747],  [0.1562, 0.0554]], transfer:0.0777*x + 0.0000 if x < 0.0450 else (0.9495*x + 0.0495)**2.3955 + 0.0003, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":3200,"height":1800},"workAreaSize":{"width":3200,"height":1777},"scaleFactor":2,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.5.0","electron":"8.2.3","installedRecipes":[{"id":"android-messages","version":"1.3.0"},{"id":"ex-google-voice","version":"0.3.2"},{"id":"gmail","version":"1.3.1"},{"id":"googledrive","version":"1.0.3"},{"id":"googlekeep","version":"1.0.3"},{"id":"hangouts","version":"1.0.2"},{"id":"messenger","version":"1.1.0"},{"id":"whatsapp","version":"2.0.3"},{}],"devRecipes":[],"services":[{"id":"c12c815d-b351-4124-adda-014f4fd14fb7","recipe":"gmail","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"67d33f91-e938-4bef-9a87-3d60974bc96c","recipe":"whatsapp","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"a1856fd2-69d5-419c-92f1-09d22aa94ad5","recipe":"android-messages","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"8e9aed95-505b-49cb-a0c2-1690dc90f667","recipe":"ex-google-voice","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"dd2053b4-23f5-4040-b75b-5f3316e17bd9","recipe":"messenger","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"9f8fc38a-efe0-49ef-8ed6-9042968d7867","recipe":"googlekeep","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"caaa02fb-1955-4745-b30d-121953cf9df7","recipe":"googledrive","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"88c77c7d-c53e-4146-bc3b-fac72370bd24","recipe":"hangouts","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"3ed0d481-f2ec-4838-aafa-6f9a157e1814","recipe":"gmail","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false}],"messages":[{"type":"error","info":["error","[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@160]'",{}]},{"type":"error","info":["error","Warning: Failed prop type: Invalid prop `showMessageBadgeWhenMutedSetting` of type `string` supplied to `_class2`, expected `boolean`.\n    in _class2 (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in ThemeProvider (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","info":["error","Reaction doesn't converge to a stable state after 100 iterations. Probably there is a cycle in the reactive function: Reaction[bound _build]"]},{"type":"error","info":["error","Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s","the componentWillUnmount method","\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by Jss(inject-_class2-with-stores-actions))\n    in Jss(inject-_class2-with-stores-actions) (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)"]}],"workspaces":[{"id":"f867a05a-2ff5-498f-aa9f-3b420ad142af","services":["c12c815d-b351-4124-adda-014f4fd14fb7"]}],"windowSettings":{"width":2407,"height":1392,"x":337,"y":277,"isMaximized":false,"isFullScreen":false,"displayBounds":{"x":0,"y":0,"width":3200,"height":1800}},"settings":{"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":false,"minimizeToSystemTray":"","privateNotifications":false,"showDisabledServices":"","showMessageBadgeWhenMuted":"","showDragArea":false,"enableSpellchecking":"","spellcheckerLanguage":"en-us","darkMode":true,"locale":"en-US","fallbackLocale":"en-US","beta":true,"isAppMuted":false,"enableGPUAcceleration":"","serviceLimit":5,"server":"https://api.getferdi.com","predefinedTodoServer":"https://app.franztodos.com","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernate":false,"hibernateOnStartup":true,"hibernationStrategy":300,"inactivityLock":0,"automaticUpdates":true,"showServiceNavigationBar":false,"universalDarkMode":true,"adaptableDarkMode":true,"accentColor":"#7367f0","serviceRibbonWidth":68,"iconSize":20,"sentry":false,"navigationBarBehaviour":"never","customTodoServer":"","todoServer":"isUsingCustomTodoService"},"features":{"isSpellcheckerIncludedInCurrentPlan":true,"needToWaitToProceed":false,"needToWaitToProceedConfig":{"delayOffset":3600000,"wait":10000},"isServiceProxyEnabled":true,"isServiceProxyIncludedInCurrentPlan":true,"isAnnouncementsEnabled":true,"isWorkspaceIncludedInCurrentPlan":true,"isWorkspaceEnabled":true,"isCommunityRecipesIncludedInCurrentPlan":true,"isSpellcheckerPremiumFeature":false,"isServiceProxyPremiumFeature":true,"isWorkspacePremiumFeature":false,"isSettingsWSEnabled":false,"isServiceLimitEnabled":false,"serviceLimitCount":0,"isCommunityRecipesPremiumFeature":false,"isCustomUrlIncludedInCurrentPlan":true,"isMagicBarEnabled":true,"isTeamManagementIncludedInCurrentPlan":true,"isTodosEnabled":true,"isTodosIncludedInCurrentPlan":true,"defaultTrialPlan":"franz-pro-yearly","subscribeURL":"https://getferdi.com","planSelectionURL":"https://getferdi.com","hasInlineCheckout":true,"isPlanSelectionEnabled":false,"isTrialStatusBarEnabled":false,"canSkipTrial":true,"pricingConfig":{"currency":"$","currencyID":"USD","plans":{"personal":{"monthly":{"id":"ferdi-free","price":0,"billed":0},"yearly":{"id":"ferdi-completely-free","price":0,"billed":0}},"pro":{"monthly":{"id":"ferdi-still-free","price":0,"billed":0},"yearly":{"id":"ferdi-forever-free","price":0,"billed":0}}}}},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}`

**Comment by vantezzen** [comment] 2020-11-17 20:23
Duplicate of #322.

This is a known bug which we unfortunately cannot fix: Electron does not allow Ferdi to focus the box if the focus is currently inside a webview. If you find a way to do this, please let us know, but we already tried many suggestions in related electron issues.

Related:
https://github.com/electron/electron/issues/17882
https://github.com/getferdi/ferdi/issues/68#issuecomment-534146281
https://github.com/getferdi/ferdi/blob/1fea645b0b94e52a31158d47d0ad921110dfa95e/src/features/quickSwitch/Component.js#L232-L235

**Closed by vantezzen** 2020-11-17 20:23 UTC
