### ISSUE TITLE
Tiling

### ISSUE THREAD

**Issue by argosang** [getferdi/ferdi#1700] opened 2021-07-28 13:04 UTC
**Is your feature request related to a problem? Please describe.**

Like stack browser or vivaldi, I would like to be able to view multiple services in the same workspace at the same time, through a tiling manager.  

**Describe the solution you'd like**

Keyboard shortcut support and drag to resize/move tiles around, would want to be able to tile as many services within a single workspace as desired.  There is some desire for being able to tile multiple workspaces, such that you can view two workspaces at the same time as well, but that might be a secondary feature.  Again, this is simply to tile,  not nest workspaces or services; this would be  a visual feature.  

**Describe alternatives you've considered**

Have not tried, but opening a second Ferdi instance could be a temporary solution for me, but otherwise I will have to go back to using Stack or Vivaldi with saved sessions. 

**Additional context**

This is motivated by the fact that people are moving on from 1080p as the standard monitor resolution.  At 4k, it becomes much more viable to handle  multiple services on the same window; it almost becomes a  waste of space to only show a single service in a workspace at a time.

**Comment by Alt37** [comment] 2021-07-28 18:53
Duplicate of #1631 (though this one has a very nice description)

**Comment by EgoDogg** [comment] 2021-07-29 13:51
This suggestion I'm about to make might not be the best solution for everyone. I know it isn't for me since I need my ToDos. But if you don't utilize ToDo's, you can probably work around this by having a custom website / service as the ToDo and have that be a way to split into two.

**Comment by argosang** [comment] 2021-07-29 19:15
> This suggestion I'm about to make might not be the best solution for everyone. I know it isn't for me since I need my ToDos. But if you don't utilize ToDo's, you can probably work around this by having a custom website / service as the ToDo and have that be a way to split into two.

That's honestly not a bad suggestion, I am assuming this is a far less involved temporary solution; the ability to swap out the ToDos with any existing service that has been configured for use in a "sidebar" workspace.

**Comment by niutech** [comment] 2021-08-20 14:09
This is how it looks like in Rambox: https://github.com/getferdi/ferdi/issues/1631#issuecomment-902718682

**Comment by vraravam** [comment] 2021-08-20 14:36
Closing this one - please continue conversation in #1631

**Closed by vraravam** 2021-08-20 14:36 UTC
Labels: enhancement
