### ISSUE TITLE
Can you pls add Ctrl+Tab for service switching along with existing Ctrl+1,2,3,etc. ? It'll be helpful.

### ISSUE THREAD

**Issue by sujay1844** [getferdi/ferdi#998] opened 2020-10-05 03:47 UTC
Can you pls add Ctrl+Tab for service switching along with existing Ctrl+1,2,3,etc. ? It'll be helpful.

**Comment by vantezzen** [comment] 2020-10-05 19:41
Duplicate of #850

**Closed by vantezzen** 2020-10-05 19:41 UTC
Labels: enhancement
