### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by poisonborz** [getferdi/ferdi#1258] opened 2021-03-26 19:03 UTC
The fact that the team couldn't push out 5.6 even though apparently all that was left was the changelog and some docu update, is really not a good sign. Coupled with "search for help" sticky and 400+ unresolved issues... It would be good to clarify this on the readme. It's super sad really, although I can imagine it's an increasingly hard, uphill battle to support various rando web services that have daily changing frontend of how they display new messages. 

Although all similar projects are in a somewhat usable state, we had Rambox, Hamsket, Franz, and now Ferdi all biting the bullet one way or another...

**Comment by austkel** [comment] 2021-03-28 17:11
Life was simpler when all we had was pidgin and trillian

**Comment by ylluminarious** [comment] 2021-03-29 20:32
Wow, I sure hope this project isn't dead / dying. I use this as my daily driver for chatting with my team, friends, colleagues, family, etc. If this is the case, someone really should please take up the torch and help maintain this extremely useful application. I'd be at a loss for what to use instead, if this project went belly-up.

**Comment by kytwb** [comment] 2021-03-30 12:27
@poisonborz here's what's left before being able to release 5.6.0: https://github.com/getferdi/ferdi/issues/1017#issuecomment-775014033.

To answer your question: no, the project is not dead.

Duplicate of https://github.com/getferdi/ferdi/issues/1256.

**Closed by kytwb** 2021-03-30 12:27 UTC

**Comment by ylluminarious** [comment] 2021-03-30 16:27
@kytwb Thanks for the info and the reassurance.

**Comment by Zethson** [comment] 2021-04-05 10:05
@kytwb thank you very much for your efforts.
