### ISSUE TITLE
Can't login after successful Franz account import

### ISSUE THREAD

**Issue by haedor** [getferdi/ferdi#855] opened 2020-06-30 06:49 UTC
Hey!
 I have imported my Franz Account via [https://api.getferdi.com/import](url) successful. But when I try to login, I've get the error "Invalid mail  or password".  When I try to import the Account again, this error occurs: 
"_Could not create your user in our system.
Error: error: insert into "users" ("created_at", "email", "password", "updated_at", "username") values ($1, $2, $3, $4, $5) returning "id" - duplicate key value violates unique constraint "users_email_unique_". 

Thx and Greets
haedor

**Comment by vantezzen** [comment] 2020-07-05 07:13
Duplicate of https://github.com/getferdi/server/issues/19.

Unfortunately, sometimes the password won't get transferred correctly when importing a Franz account - we don't know why yet. You should hopefully be able to reset your password using the "Forgot password" function at https://api.getferdi.com/user/forgot

**Closed by vantezzen** 2020-07-05 07:13 UTC
Labels: bug
