### ISSUE TITLE
FB MESSENGER

### ISSUE THREAD

**Issue by nacho1978** [getferdi/ferdi#589] opened 2020-04-17 20:36 UTC
**no funciona las videos llamadas de facebook messenger en getferdi. tengo instalado ferdi en ubuntu 18lts. aguardo 

aguardo solucion**

**Comment by nacho1978** [comment] 2020-04-17 20:37
** facebook messenger video calls in getferdi does not work. I have ferdi installed on ubuntu 18lts. I await

I await solution **

**Comment by vantezzen** [comment] 2020-04-17 20:59
Duplicate of #373

**Closed by vantezzen** 2020-04-17 20:59 UTC
