### ISSUE TITLE
I can't open the new version of Ferdi

### ISSUE THREAD

**Issue by Tofax** [getferdi/ferdi#2059] opened 2021-10-13 06:58 UTC
I have upgraded to the latest version of Ferdi and now I can't display it on the screen. It initializes minimized, but I can't open it.
I am using Windows 10.

**Comment by Alt37** [comment] 2021-11-08 00:10
Possible duplicate of  #2147

**Comment by vraravam** [comment] 2021-11-09 23:31
Closing as a duplicate of #2147

**Closed by vraravam** 2021-11-09 23:31 UTC
Labels: bug, platform-specific
