### ISSUE TITLE
[Feature Request]: A list of icons to choose from

### ISSUE THREAD

**Issue by napter** [getferdi/ferdi#2259] opened 2021-11-19 17:24 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

When adding a custom service it just uses the default icon which makes differentiating between them impossible. It allows me to choose an icon but I, like most people, don't have a folder of icons ready to use. 

### Proposed Solution

When choosing an icon instead of just choosing a file use a list of existing icons, like material design icons or another list of open source free icons.

### Alternatives Considered

N/A

**Comment by vraravam** [comment] 2021-11-20 01:23
Duplicate of #2121 - please do not create duplicates. I see that you have commented on the other ticket as well - please confine to the same conversation. Fragmented conversations do not help anyone.

**Closed by vraravam** 2021-11-20 01:23 UTC
Labels: enhancement :sparkles:

**Comment by napter** [comment] 2021-11-20 04:06
2121 is a request to use the websites fav icon. This was a request to have a preset list if icons to choose from. They're not duplicates although that address the same issue.
