### ISSUE TITLE
Slack defaulting to German spell checking - v5.6.0

### ISSUE THREAD

**Issue by minisugar** [getferdi/ferdi#1763] opened 2021-08-09 17:52 UTC
Accidentally opened issue with my work account (#1762 - sorry about that, feel free to delete it). I originally wanted to put this under my personal account:

I'm currently running v5.6.0, also I'm not super GitHub literate - I switched to Ferdi from Franz due to performance issues and I'm loving Ferdi overall! However, spell checking in Slack is defaulting to German recently. I set spell checking in Ferdi to English and Slack still wants to use German (when I right-click on a misspelled word). I'm okay dealing with it till next big Release, but wanted to make others aware.

**Comment by vraravam** [comment] 2021-08-09 17:55
I have just committed a fix for a different bug related to spell-checking, and it should appear in the next nightly in approx 8 hours. If you can wait till then, I would request you to try out the nightly release and then update this ticket with the expected vs actual behavior.

**Comment by minisugar** [comment] 2021-08-09 18:02
Thank you for your quick response! How can I find details on switching to nightly builds?

**Comment by vraravam** [comment] 2021-08-09 18:04
Please see the `Downloads` page in the website - it has the links for the nightlies and betas towards the bottom.

**Comment by vraravam** [comment] 2021-08-10 04:52
@minisugar : Please check with the latest nightly that I have released just now. I would also request you to close this ticket if the issue is fixed.

**Closed** 2021-08-10 13:56 UTC
