### ISSUE TITLE
Google Calendar universal dark mode not working

### ISSUE THREAD

**Issue by fermmm** [getferdi/ferdi#211] opened 2019-11-15 21:52 UTC
I updated Ferdi from 5.3.3 to 5.4.0 beta 4 in order to have the universal dark mode. It's not working with google calendar.
In another computer I installed 5.4.0 beta 4 without any previous version installed and the universal dark mode worked fine with calendar, so it seems to be something caused by the previous version.
I tried reinstalling, removing the service and add it again, logout and login and nothing fixed it.

Maybe there is a way to remove all cache data so reinstalling Ferdi is like installing in a fresh computer.

**Comment by vantezzen** [comment] 2019-11-16 10:20
You could try deleting the `Ferdi`folder in `%appdata%` - this will delete all caches and other data. 
Could you please also check that dark mode is enabled both in Ferdi but also the the individual service?

**Comment by fermmm** [comment] 2019-11-16 20:33
That fixed the issue. This is what I did: 

1. Uninstalled Ferdi
2. I'm on Linux so instead of going to `%appdata%` I removed the folder `Ferdi` located at: `/home/[*user*]/.config/`.
3. Installed Ferdi again
4. Enabled dark mode
5. Closed Ferdi and opened again
6. Removed and added again the Google Calendar service and then it worked

**Comment by fermmm** [comment] 2019-11-17 03:43
**New issue with calendar and universal dark mode**: In the computer that always worked now suddenlty stopped working, I see white colors again, this computer never had an older version installed, I only had Franz intalled. The only thing that changed when stopped working was in a different place (it's my notebook)

**Comment by vantezzen** [comment] 2019-11-18 09:55
The "Fixing bugs" screen is only the normal loading screen Ferdi is using - the text displayed has nothing to do with what its actually doing.
I think this is a duplicate of #158 then: For some unknown reason the webview sometimes fails to load the recipe scripts and thus not enabling the darkmode feature.
If this error appears again, can you try just reloading Ferdi using `CTRL + SHIFT + R` to see if that fixes it? We have not yet found the root of this error so we can't fix it.

**Comment by fermmm** [comment] 2019-11-18 23:12
> The "Fixing bugs" screen is only the normal loading screen Ferdi is using - the text displayed has nothing to do with what its actually doing.
> I think this is a duplicate of #158 then: For some unknown reason the webview sometimes fails to load the recipe scripts and thus not enabling the darkmode feature.
> If this error appears again, can you try just reloading Ferdi using `CTRL + SHIFT + R` to see if that fixes it? We have not yet found the root of this error so we can't fix it.

Yes, CTRL + SHIFT + R fixes the issue, I'll follow #158 and test the fix when the beta 5 is released.

**Comment by kytwb** [comment] 2019-11-28 17:16
Closing in favour of https://github.com/getferdi/ferdi/issues/158.

**Closed by kytwb** 2019-11-28 17:16 UTC
