### ISSUE TITLE
"Syncronize dark mode with my OS's..." not working

### ISSUE THREAD

**Issue by sadanro100** [getferdi/ferdi#1675] opened 2021-07-21 19:14 UTC
Since the last update, OS dark mode syncronization is not working

<img width="463" alt="image" src="https://user-images.githubusercontent.com/14843839/126546413-91780399-302d-4b9a-9519-2d94995440df.png">
<img width="283" alt="image" src="https://user-images.githubusercontent.com/14843839/126546436-bb146858-0202-415d-a693-521452846889.png">

**Comment by Jendker** [comment] 2021-08-11 04:15
Maybe this issue is related? https://github.com/getferdi/ferdi/issues/1490

**Comment by vraravam** [comment] 2021-08-12 20:28
Please try with the latest beta that I have just released. There have been a lot of improvements and bug fixes - specifically for dark mode. https://github.com/getferdi/ferdi/releases/tag/v5.6.1-beta.1

Also, please close this ticket if your issue is resolved.

**Comment by Jendker** [comment] 2021-08-23 18:51
The "universal dark mode" does not seem to work at all now after updating to v5.6.1-beta.1. All the services are light and only the interface of Ferdi is in dark theme.

{"host":{"platform":"linux","release":"5.11.0-27-generic","screens":[{"id":2,"bounds":{"x":0,"y":0,"width":1920,"height":1080},"workArea":{"x":72,"y":27,"width":1848,"height":1053},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1920,"height":1080},"displayFrequency":60,"workAreaSize":{"width":1848,"height":1053},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.6.1-beta.1","electron":"13.1.9","installedRecipes":[{"id":"franz-custom-website","version":"1.0.5"},{"id":"googlecalendar","version":"2.1.1"},{"id":"messenger","version":"1.1.0"},{"id":"slack","version":"1.1.0"},{"id":"todoist","version":"1.2.2"},{"id":"wechat","version":"1.0.1"},{"id":"whatsapp","version":"3.1.0"},{}],"devRecipes":[],"services":[{"id":"bbca5135-1dec-42c3-bdcd-cf2250f60ad3","recipe":"slack","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"ab646a92-53c7-41d9-bc97-a270c18e7f07","recipe":"googlecalendar","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"72efb72c-06bd-4cdc-8dd5-5596e4379dc1","recipe":"todoist","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"ee2c5c11-aad3-41f0-a9b8-f260a31ecc01","recipe":"whatsapp","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"f11e23de-962a-464e-a265-59fc21cab80b","recipe":"franz-custom-website","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false}],"messages":[{"type":"error","info":["error","Warning: Failed prop type: Invalid prop `actions.service` of type `Object` supplied to `_class2`, expected instance of `_class`.\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","info":["error","Warning: Failed prop type: Invalid prop `actions.settings` of type `Object` supplied to `_class2`, expected instance of `_class`.\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in ThemeProvider (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","info":["error","Warning: Failed prop type: The prop `stores.app.accentColor` is marked as required in `_class2`, but its value is `undefined`.\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by WithTheme(Jss(_class2)))\n    in WithTheme(Jss(_class2)) (created by inject-WithTheme(Jss(_class2))-with-stores)\n    in inject-WithTheme(Jss(_class2))-with-stores (created by _class2)\n    in _class2 (created by WithTheme(_class2))\n    in WithTheme(_class2) (created by Jss(WithTheme(_class2)))\n    in Jss(WithTheme(_class2)) (created by _class2)\n    in ThemeProvider (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","info":["error","Warning: You cannot PUSH the same path using hash history"]},{"type":"error","info":["error","Warning: Failed prop type: Invalid prop `actions.ui` of type `Object` supplied to `_class`, expected instance of `_class`.\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions (created by RouterContext)\n    in div (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in ThemeProvider (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","info":["error","Warning: Failed prop type: Invalid prop `actions.app` of type `Object` supplied to `_class2`, expected instance of `_class`.\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in div (created by _class2)\n    in CSSTransitionGroupChild (created by TransitionGroup)\n    in span (created by TransitionGroup)\n    in TransitionGroup (created by CSSTransitionGroup)\n    in CSSTransitionGroup (created by Appear)\n    in Appear (created by _class2)\n    in _class2 (created by _class)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions (created by RouterContext)\n    in div (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in ThemeProvider (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","info":["error","Warning: Failed prop type: Invalid prop `actions.app` of type `Object` supplied to `_class`, expected instance of `_class`.\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions (created by RouterContext)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in div (created by _class2)\n    in CSSTransitionGroupChild (created by TransitionGroup)\n    in span (created by TransitionGroup)\n    in TransitionGroup (created by CSSTransitionGroup)\n    in CSSTransitionGroup (created by Appear)\n    in Appear (created by _class2)\n    in _class2 (created by _class)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions (created by RouterContext)\n    in div (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in ThemeProvider (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","info":["error","Warning: Failed prop type: Invalid prop `actions.service` of type `Object` supplied to `_class`, expected instance of `_class`.\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions (created by RouterContext)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in div (created by _class2)\n    in CSSTransitionGroupChild (created by TransitionGroup)\n    in span (created by TransitionGroup)\n    in TransitionGroup (created by CSSTransitionGroup)\n    in CSSTransitionGroup (created by Appear)\n    in Appear (created by _class2)\n    in _class2 (created by _class)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions (created by RouterContext)\n    in div (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in ThemeProvider (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","info":["error","Warning: Failed prop type: The prop `customWebsiteRecipe` is marked as required in `_class2`, but its value is `undefined`.\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in div (created by _class2)\n    in CSSTransitionGroupChild (created by TransitionGroup)\n    in span (created by TransitionGroup)\n    in TransitionGroup (created by CSSTransitionGroup)\n    in CSSTransitionGroup (created by Appear)\n    in Appear (created by _class2)\n    in _class2 (created by _class)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions (created by RouterContext)\n    in div (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in ThemeProvider (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]}],"workspaces":[],"windowSettings":{"width":1386,"height":752,"x":303,"y":188,"displayBounds":{"x":0,"y":0,"width":1920,"height":1080},"isMaximized":false,"isFullScreen":false},"settings":{"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":true,"minimizeToSystemTray":false,"closeToSystemTray":false,"privateNotifications":false,"clipboardNotifications":true,"notifyTaskBarOnMessage":false,"showDisabledServices":true,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"automatic","darkMode":true,"locale":"en-US","fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":true,"server":"https://api.getferdi.com","predefinedTodoServer":"https://app.franztodos.com","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernateOnStartup":true,"hibernationStrategy":300,"wakeUpStrategy":"300","inactivityLock":0,"automaticUpdates":true,"showServiceNavigationBar":false,"universalDarkMode":true,"userAgentPref":"","adaptableDarkMode":false,"accentColor":"#7367f0","serviceRibbonWidth":68,"iconSize":20,"sentry":false,"nightly":false,"navigationBarBehaviour":"never","searchEngine":"duckDuckGo","useVerticalStyle":false,"alwaysShowWorkspaces":false,"serviceLimit":5,"hibernate":false,"todoServer":"isUsingCustomTodoService","customTodoServer":""},"features":{"isServiceProxyEnabled":false,"isAnnouncementsEnabled":true,"isWorkspaceEnabled":false,"isTodosEnabled":true},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}

**Comment by mhatvan** [comment] 2021-08-24 08:01
Can confirm this doesn't work on Ubuntu.

**Comment by vraravam** [comment] 2021-08-24 09:21
Could this be related to a `darkreader` upgrade that happened a couple of weeks ago?

**Comment by emanuelst** [comment] 2021-08-24 09:33
With version: 5.6.1-beta.1 on macOS 11.5.2 (20G95) the UI is always in dark mode for me, regardless of what the OS is set to. The "Syncronize dark mode with my OS's dark mode setting" toggle is also inoperable for me, and always stays at "on".

**Comment by kytwb** [comment] 2022-01-09 14:51
Couldn't reproduce with 5.6.9 on macOS 12:

![Screen Shot 2022-01-09 at 3 49 07 PM](https://user-images.githubusercontent.com/412895/148687451-f798a104-0bc5-464c-8660-2a87f6f8c44e.png)

![Screen Shot 2022-01-09 at 3 48 53 PM](https://user-images.githubusercontent.com/412895/148687454-d946906c-d092-4012-b8c5-48f1aa1fbb09.png)

See https://github.com/getferdi/ferdi/issues/158 for Universal Dark Mode.

**Comment by Jendker** [comment] 2022-01-09 16:06
I would expect that many of MacOS users are using the "Auto" appearance mode and this one does not work properly. It does not respect the automatically changing light and dark system mode.

**Comment by kytwb** [comment] 2022-01-09 18:03
This should also work for Linux now.

**Closed by kytwb** 2022-01-09 18:03 UTC
Labels: bug :beetle:
