### ISSUE TITLE
Ferdi doesn't clean up /tmp after itself

### ISSUE THREAD

**Issue by sbienkow** [getferdi/ferdi#1010] opened 2020-10-09 07:20 UTC
**Bug description:**

Ferdi uses `/tmp` through electron to store quite a bit of data.
It looks like it doesn't delete the temporary files/folders after it no longer uses them.

Example contents of `/tmp` that use in total 6GB: https://gist.github.com/sbienkow/a2c34c969d91b7de5421dde85ea599d3#file-ferdi_tmp_usage
I only noticed it, because my `/tmp` is a tmpfs so it causes noticeable RAM usage.

It looks like I can remove these files while Ferdi is running and didn't notice any issues.
Ferdi doesn't delete those files even after being shut down.

**Steps to reproduce:**

1. Just run Ferdi for a few days

**Expected behavior**

Ferdi doesn't use a lot of `/tmp`, deleting its temporary files as they are no longer needed.
It also cleans up on shutdown.

**Environment:**

- Operating System: Manjaro Linux 20.1.1
- Ferdi Version: 5.5.0-8
- Server: No account
- Debug information: https://gist.github.com/sbienkow/a2c34c969d91b7de5421dde85ea599d3#file-ferdi-debug-json

I wish I could share any more information - unfortunately that's all I know so far.

It seems quite reproducible - especially after a few days there's plenty of the temporary files.

**Comment by kris7t** [comment] 2020-10-09 11:36
This is most likely a Chromium issue, seems like it creates temporary files, but does not clean them up.

The directory with the `SingletonCookie` and `SS` files is odd, though, because it seems like something that is caused by a non-persistent Chromium partition. As far as I know, Ferdi only creates persistent partitions (one for each service, stored in `~/.config/Ferdi/Partitions`). Are you sure these files are created by Ferdi, and not another Electron application?

The folders with `Ferdi1_329.png` are certainly created by Ferdi, though, and are related to the peculiar way Chromium handles tray icons on Linux. We should really write our own D-Bus `StatusNotifierItem` implementation with saner semantics (I'll try it this weekend if I have the time).

**Comment by sbienkow** [comment] 2020-10-09 11:52
Hey!

I'm sure this is caused by Ferdi (or electron instance used by Ferdi), because:

1. To my knowledge I have no other electron apps
2. When Ferdi is not running, `ps aux | grep electron` returns nothing
3. when Ferdi is not running and I clean up `/tmp`, no new files are created (monitored for a few minutes). As soon as I start Ferdi, those folders and files start to appear.

I'm also not using Chromium-based browser (using FF), so it's not it.

**Comment by sbienkow** [comment] 2020-12-09 23:20
Just commenting since this is still an issue. Though I have worked around that by setting cron to cleanup the files every few hours - didn't notice getting any abnormal behavior from doing so.

**Comment by sbienkow** [comment] 2021-02-08 09:47
Can confirm this is still an issue.
I've also noticed that similar files are created in Ferdi config directory `~/.config/Ferdi`, though it appears to create 1 every few months, so it's not a big issue.

**Comment by mhatvan** [comment] 2021-08-03 06:28
I was investigating a bit into this: couldn't find any Ferdi-related files in `/tmp` on Ubuntu 21.04.

On the other hand, `~/.config/Ferdi` is where I found the services and the cache location. 

**Before using "clear cache" button through Ferdi:** around 4GB in use, which Ferdi also says next to the clear cache button. This is how it looks with disk usage analyzer:
![Screenshot from 2021-08-03 08-10-44](https://user-images.githubusercontent.com/16797721/127966717-9a04c14d-4ac2-463c-a0c7-b501ecb70930.png)

**After using "clear cache" button through Ferdi with all services logged out:** only 350MB of data is left.
**After using "clear cache" button through Ferdi with all services logged in again:** back up to 1.2GB.

Seems all correct to me.

You are still running on Ferdi 5.5.0 which uses Electron 8, so I can really recommend upgrading to the latest nightly which uses Electron 13 and has plenty of improvements: https://github.com/getferdi/nightlies/releases/tag/v5.6.1-nightly.12

That alone might already solve this problem ;)

**Comment by mhatvan** [comment] 2021-08-15 18:55
Closing this, will reopen if the issue persists.

**Closed by mhatvan** 2021-08-15 18:55 UTC
Labels: bug
