### ISSUE TITLE
No system try icon !

### ISSUE THREAD

**Issue by Nokia808** [getferdi/ferdi#774] opened 2020-05-26 05:04 UTC
**Bug description:**

No system try icon
**Steps to reproduce:**

1) Launch Ferdi, 
2) then close it (without exit),
3) no system try icon

**Expected behavior**

It should be a system try icon that appear in system panel - as it was the case before - so that user can use this icon to bring Ferdi window again or use it to exit Ferdi.
Currently, I can not exit Ferdi after I launching it if I click "close" ! This is annoying !
**Screenshots**

**Environment:**

- Operating System: Fedora Linux 30 X64 Cinnamon edition
- Ferdi Version: 5.5.0
- Server: Using without an account

**Comment by ChTBoner** [comment] 2020-05-26 08:29
Same issue here with Gnome on Archlinux

**Comment by vantezzen** [comment] 2020-05-26 13:27
Duplicate of #437

**Closed by vantezzen** 2020-05-26 13:27 UTC
