### ISSUE TITLE
WhatsApp (multi-device) cannot connect after hibernation

### ISSUE THREAD

**Issue by SinTan1729** [getferdi/ferdi#1745] opened 2021-08-05 15:57 UTC
**Bug description:**

WhatsApp sometimes doesn't work after waking up from hibernation.
**Steps to reproduce:**

1. Add a WhatsApp account
2. Hibernate the machine
3. Try to use WhatsApp after wakeup
4. Error is thrown sometimes (not always)

**Expected behavior**

WhatsApp should work properly.
**Screenshots**

![image](https://user-images.githubusercontent.com/35728385/128525782-50f67bfa-89fb-49f1-8552-fb6f8afe99ca.png)

**Environment:**

- Operating System:  Manjaro Linux
- Ferdi Version: 5.6.1.nightly.2.r13.gbab27ed6-1
- Server:  Using without an account

- Debug information:

[Debug info](https://pastebin.com/Ziny8ZLd)

**Comment by Jendker** [comment] 2021-08-11 23:34
I have sometimes this issue on Ubuntu and what I do is I simply press right on the service and reload it.

**Comment by guilhem** [comment] 2021-08-12 15:51
> I have sometimes this issue on Ubuntu and what I do is I simply press right on the service and reload it.

It doesn't work for me. Have to disconnect and reconnect.

**Comment by guilhem** [comment] 2021-08-17 08:11
Error seen in console:
```
VM267 webview.js:34 Uncaught TypeError: Cannot read property 'children' of null
    at RecipeWebview.getMessages [as loopFunc] (VM267 webview.js:34)
    at EventEmitter.<anonymous> (VM136 RecipeWebview.js:1)
    at EventEmitter.emit (VM14 events.js:315)
    at Object.onMessage (VM75 renderer_init.js:93)
```

**Comment by vraravam** [comment] 2021-08-17 08:16
Thanks for the stacktrace @guilhem - I am pushing a fix now - it should come in the next nightly (v31)

**Comment by SinTan1729** [comment] 2021-08-19 13:06
It's not working for me.

**Comment by timwiel** [comment] 2021-08-22 23:55
This issue is also effecting me. Unfortunately adding the fix suggested by @vraravam did not solve the issue.

To clarify:
- closing Ferdi completely and restarting it also throws the error about logging in as shown in OP above
- reloading WhatsApp service also throws the error shown above
- reloading Ferdi alsos throw the error shown above 

So ...the only way to login to WhatsApp currently is to hit the logout button and run through linking accounts again on the device with QR code

**Comment by anned20** [comment] 2021-09-01 11:50
I'm experiencing the same as @timwiel.

I've tried and debug the cause and the only thing I could find is that the websocket communication times out. I'm not sure if it has anything to do with Ferdi or if it's a bug on WhatsApp's end.

**Comment by shvchk** [comment] 2021-09-18 15:07
Added `if (!parentChatElem) return;` at line 33 as @vraravam suggested. That didn't fix the issue. Getting this error in console:

```
Uncaught (in promise) TypeError: Failed to execute 'put' on 'Cache': Partial response (status code 206) is unsupported
    at serviceworker.js:1
    at Generator.next (<anonymous>)
    at c (serviceworker.js:1)
    at o (serviceworker.js:1)
```

Relevant code in `serviceworker.js` (pretty-printed), specifically line 5:
```js
put(e, t) {
    var a = this;
    return n((function*() {
        try {
            return (yield a.openCachePromise).put(e, t)
        } catch (s) {
            __LOG__(3)`Unable to put in cache: ${a.cacheName}, request: ${p(e)}, response status: ${t.status}, err: ${s}`
        }
    }
    ))()
}
```

**Comment by guilhem** [comment] 2021-09-18 15:12
This issue may be related to new multi clients in beta

**Comment by shvchk** [comment] 2021-09-18 15:26
Yeah, I'm using multi device.

**Comment by jpennekamp** [comment] 2021-11-05 09:40
I can confirm the issue as described by @timwiel with the latest nightly on both MacOS 12.0.1 and Windows 11.
Properly supporting the Multi Device version of WhatsApp Web would be highly appreciated.

Logging in and out is not a suitable workaround as it results in security notices for all contacts due to the updated key material.

**Comment by niebloomj** [comment] 2021-11-05 14:03
I have the same issue.

**Comment by jpennekamp** [comment] 2021-11-06 13:06
I had another computer on Windows 10 where the WhatsApp Web Beta was still working as intended in Ferdi. Unfortunately, after clearing the cache, the same error as on the other systems occurs.

**Comment by vraravam** [comment] 2021-11-06 16:07
My suspicion is that this is related to localStorage being somehow corrupted or being complex enough that Ferdi barfs.

**Comment by yann1cks** [comment] 2021-11-08 09:18
I think WhatsApp is rolling out this feature at the moment. This feature is enabled by default for me and I found this german news article confirming that Whatsapp is rolling out multi-device-support for all users. (https://www.chip.de/news/WhatsApp-auf-mehreren-Geraeten-nutzen-Neues-Feature-wird-fuer-Nutzer-ausgerollt_183927729.html).

**Comment by niebloomj** [comment] 2021-11-10 14:54
This feature is now out of beta and now in public release. I am now automatically logged out of whatsapp anytime the service goes to sleep or is restarted. Thanks!

**Comment by vraravam** [comment] 2021-11-10 15:58
@niebloomj - i am in India, and I have reverted back to the older non-multi-device settings. Unfortunately, I dont have the time/capacity to debug this issue. Any help from others is welcome

**Comment by niebloomj** [comment] 2021-11-11 14:59
In America it seems to be the new default, with no option to revert, so you'll soon have this bug also haha.

**Comment by niebloomj** [comment] 2021-11-11 15:00
Also, it is all the time, so I recommend removing the word sometimes from the title.

**Comment by lockieluke** [comment] 2021-11-11 15:52
+1 I am having this issue after joining the beta

**Comment by Nosudrum** [comment] 2021-11-13 10:02
Also having the same issue after enabling multi-device

**Comment by dominik-ba** [comment] 2021-11-16 13:27
> 
> 
> Also, it is all the time, so I recommend removing the word sometimes from the title.

also hibernation is a bit missleading since this happens after each refresh, restart, ... right?

**Comment by urielsalis** [comment] 2021-11-18 14:29
Having same issue

**Comment by taenzerme** [comment] 2021-11-18 15:21
Ferdi 5.6.3 on MacOS here. No problems here (no log out for days), WA Multiaccount enabled.

I'm not sure if all here are heaving the same issue...

**Comment by monossido** [comment] 2021-11-18 15:45
Some here with Ubuntu and Ferdi 5.6.3

**Comment by urielsalis** [comment] 2021-11-19 08:18
Contents of the console:

`VM2495 mobx.js:1835 [mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@1]' TypeError: Cannot read properties of null (reading 'removeAttribute')
    at removeDynamicTheme (VM2539 darkreader.js:5126)
    at disable (VM2539 darkreader.js:5253)
    at _class.update (VM2493 recipe.js:1)
    at VM2493 recipe.js:1
    at reactionRunner (VM2495 mobx.js:2106)
    at trackDerivedFunction (VM2495 mobx.js:776)
    at Reaction.track (VM2495 mobx.js:1806)
    at Reaction.onInvalidate (VM2495 mobx.js:2087)
    at Reaction.runReaction (VM2495 mobx.js:1772)
    at runReactionsHelper (VM2495 mobx.js:1909)
Reaction.reportExceptionInDerivation @ VM2495 mobx.js:1835
Reaction.track @ VM2495 mobx.js:1814
(anonymous) @ VM2495 mobx.js:2087
Reaction.runReaction @ VM2495 mobx.js:1772
runReactionsHelper @ VM2495 mobx.js:1909
reactionScheduler @ VM2495 mobx.js:1887
runReactions @ VM2495 mobx.js:1892
Reaction.schedule @ VM2495 mobx.js:1756
autorun @ VM2495 mobx.js:2108
initialize @ VM2493 recipe.js:1
_class @ VM2493 recipe.js:1
(anonymous) @ VM2493 recipe.js:1
(anonymous) @ VM2493 recipe.js:2
Module._compile @ VM2469 loader:1110
Module._extensions..js @ VM2469 loader:1140
Module.load @ VM2469 loader:982
Module._load @ VM2469 loader:823
c._load @ VM2488 asar_bundle:5
o._load @ VM2491 renderer_init:29
(anonymous) @ VM2491 renderer_init:81
./lib/renderer/init.ts @ VM2491 renderer_init:81
__webpack_require__ @ VM2491 renderer_init:1
(anonymous) @ VM2491 renderer_init:1
___electron_webpack_init__ @ VM2491 renderer_init:1
(anonymous) @ VM2491 renderer_init:149
compileForInternalLoader @ VM2390 loaders:312
compileForPublicLoader @ VM2390 loaders:252
loadNativeModule @ VM2472 helpers:40
Module._load @ VM2469 loader:805
c._load @ VM2488 asar_bundle:5
executeUserEntryPoint @ VM2487 run_main:79
(anonymous) @ VM2453 run_main_module:17

web.whatsapp.com/:1 The Content Security Policy directive 'upgrade-insecure-requests' is ignored when delivered in a report-only policy.
The Content Security Policy directive 'upgrade-insecure-requests' is ignored when delivered in a report-only policy.
web.whatsapp.com/:1 The Content Security Policy directive 'upgrade-insecure-requests' is ignored when delivered in a report-only policy.

The Content Security Policy directive 'upgrade-insecure-requests' is ignored when delivered in a report-only policy.

serviceworker.js:1 Uncaught (in promise) TypeError: Failed to execute 'put' on 'Cache': Partial response (status code 206) is unsupported
    at serviceworker.js:1
    at Generator.next (<anonymous>)
    at n (serviceworker.js:1)
    at o (serviceworker.js:1)
`

**Comment by alopix** [comment] 2021-11-19 10:37
Ferdi 5.6.3 on MacOS does not work for me. Have to login/logout once a day :(

**Comment by vraravam** [comment] 2021-11-19 11:46
I am using the latest nightly - and I don't see this behavior with the multi-device beta. Please try out the nightly and report back

**Comment by Wlkus** [comment] 2021-11-19 17:49
Same problem here on Windows 11 Pro and latest nightly 5.6.4-11

Fortunately I was able to leave multidevice beta...

**Comment by urielsalis** [comment] 2021-11-19 18:04
> I am using the latest nightly - and I don't see this behavior with the multi-device beta. Please try out the nightly and report back

Using Version: 5.6.4-nightly.11 in MacOS

As soon as I reload it stops working

**Comment by vraravam** [comment] 2021-11-20 01:25
I'm also on the latest nightly, on macos monterey. I don't see this issue.

**Comment by vraravam** [comment] 2021-11-20 03:18
Update: Now this has stopped working for me as well 😞

**Comment by flawnn** [comment] 2021-11-22 19:09
It stopped for a time, but now it's again there with the newest nightly 5.6.4-nightly11

**Comment by flawnn** [comment] 2021-11-29 16:53
https://stackoverflow.com/questions/66323598/service-worker-failed-to-execute-put-on-cache

This might help someone to fix this. I am sadly not proficient enough in PWAs to do this.

**Comment by vraravam** [comment] 2021-11-29 17:09
@flawnn : We are already releasing the service workers: https://github.com/vraravam/recipes/blob/master/recipes/whatsapp/webview.js#L60 - not sure what else we need to do on Ferdi's side

**Comment by flawnn** [comment] 2021-11-29 17:13
> @flawnn : We are already releasing the service workers: https://github.com/vraravam/recipes/blob/master/recipes/whatsapp/webview.js#L60 - not sure what else we need to do on Ferdi's side

Maybe we do need to delete WhatsApp as a whole in Ferdi and readd it to get this change?

**Comment by urielsalis** [comment] 2021-11-29 17:46
The same error is shown when you do the first login and it works, so I don't think it's related

**Comment by flawnn** [comment] 2021-11-29 17:47
> The same error is shown when you do the first login and it works, so I don't think it's related
I see. But what does it cause to break then?
There is not any other error afaik, I will check later.

**Comment by urielsalis** [comment] 2021-11-29 17:50
No. It shows the same error when working and not working

**Comment by flawnn** [comment] 2021-11-29 19:24
Might there be anything connected to [this](https://user-images.githubusercontent.com/19386703/143929652-16fa17f2-a011-4e77-8455-27fbc0e7335d.png)? 
The WebSockets aren't able to connect which makes sense as WhatsApp tells us the same but is this actually the issue or anything connected with this?

**Comment by themagpieswarble** [comment] 2021-12-05 19:28
Just adding my +1. Windows 10 and Version 5.6.0 of Ferdi. 

Anytime I restart Ferdi, Whatsapp is logged out.

**Comment by darksky82** [comment] 2021-12-06 03:05
Same here. Happens with windows 10. But not on 11.

**Comment by martinpaoloni** [comment] 2021-12-07 13:47
Ferdi 5.6.3 on macOS. Same issue. If there's anything I can contribute to get this fixed, please let me know. Thanks!

**Comment by flawnn** [comment] 2021-12-07 15:44
> Same here. Happens with windows 10. But not on 11. 

happens on 11 too

**Comment by Maikuh** [comment] 2021-12-09 12:59
This seems to happen to me specifically when I click on WhatsApp's update banner (see image below). After it finishes, the bug starts, regardless of whether I reload Ferdi or not.

Ferdi 5.6.3 on macOS Big Sur.

![image](https://user-images.githubusercontent.com/38594993/145400605-fadcd08c-feea-4791-a8fa-a2de5e1a49d0.png)

**Comment by themagpieswarble** [comment] 2021-12-09 15:53
Definitely related to that new update that allows linked devices to use your Whatsapp without your main device being online. When I deleted my WA service and added it back in, it rolled back to the old version of WA before this update and everything works great. If I close and re-load Ferdi, WA loads in and logs in no problem. 

So for now I'm just leaving this version installed until Ferdi updates to fix this issue. 

![image](https://user-images.githubusercontent.com/42039852/145429640-e576d791-386b-46b9-ac04-125c988297df.png)

**Comment by urielsalis** [comment] 2021-12-13 18:05
Fixed for me in the latest nightly (after https://github.com/getferdi/recipes/pull/778 was merged)

**Comment by vraravam** [comment] 2021-12-14 02:27
can we confirm on different OSes? If so, we can close this ticket.

I just downloaded the [latest nightly](https://github.com/getferdi/ferdi/releases/v5.6.4-nightly.33) and will report back for macos monterey (12.0.1) in a few hours.

**Comment by WladyX** [comment] 2021-12-14 05:35
I confirm on MacOS Big Sur M1 all good now.

**Comment by Zahrun** [comment] 2021-12-14 05:37
I confirm it works for me again on Kubuntu 21.10

**Comment by vraravam** [comment] 2021-12-14 10:28
I can also confirm this works for macos big sur. Closing the ticket.

**Closed by vraravam** 2021-12-14 10:28 UTC
Labels: outstanding question :question:

**Comment by flawnn** [comment] 2021-12-14 19:03
Yes, everything seems to work now.
