### ISSUE TITLE
Check for Updates Doesn't Do Anything

### ISSUE THREAD

**Issue by YisroelTech** [getferdi/ferdi#1832] opened 2021-08-24 13:55 UTC
**Bug description:**

I have **Enable updates** On, with **Include beta version**, but I do not seem to be getting the beta updates installed. And even when I manually press **Check for updates** it doesn't seem to be doing anything.

**Steps to reproduce:**

1. In Settings>Updates **Enable updates** with **Include beta version**
2. Click on **Check for update**

**Expected behavior**

It should've prompted me to update to the latest beta build (_5.6.1-beta.2_), but instead it doesn't do anything.

**Screenshots**

![x0vfZ6pLTI](https://user-images.githubusercontent.com/7387839/130628535-8c2191b2-71e0-40df-8a08-f6e1dfe453a5.gif)

**Environment:**

- Operating System: Windows 10
- Ferdi Version: 5.6.1-beta.1
- Server: Using without an account

- Debug information:

`{"host":{"platform":"win32","release":"10.0.19043","screens":[{"id":2528732444,"bounds":{"x":2560,"y":363,"width":1920,"height":1080},"workArea":{"x":2560,"y":363,"width":1920,"height":1040},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries_d50_referred: [[0.6370, 0.3300],  [0.3100, 0.6200],  [0.1530, 0.0670]], transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1920,"height":1080},"displayFrequency":60,"workAreaSize":{"width":1920,"height":1040},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"},{"id":2779098405,"bounds":{"x":0,"y":0,"width":2560,"height":1440},"workArea":{"x":0,"y":0,"width":2560,"height":1400},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":2560,"height":1440},"displayFrequency":60,"workAreaSize":{"width":2560,"height":1400},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.6.1-beta.1","electron":"13.1.9","installedRecipes":[{"id":"airtable","version":"1.0.1"},{"id":"gmail","version":"1.3.10"},{"id":"googledrive","version":"2.0.1"},{"id":"hangouts","version":"1.1.2"},{"id":"hangoutschat","version":"1.4.6"},{"id":"msteams","version":"3.0.2"},{"id":"telegram","version":"3.1.0"},{"id":"acd","version":"0.0.1"}],"devRecipes":[{"id":"acd","version":"0.0.1"}],"services":[{"id":"272bbfed-9927-45ae-924b-d729acc89a85","recipe":"gmail","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"cb585f73-3292-48e3-8b84-797ba4cceaff","recipe":"gmail","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"ed09650d-a932-43b0-b721-e47d2e35ca95","recipe":"gmail","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"c20cbc5c-90dc-4631-bb08-861ab5c9b091","recipe":"hangoutschat","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"c2c72db9-9c26-4c36-b0b9-4d42145761e1","recipe":"googledrive","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"554242e1-a552-4220-982b-ac2c7a89f8be","recipe":"acd","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"bb4c3d24-8557-4ffb-aab7-753ba7874ffd","recipe":"hangouts","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"40fbbe16-c473-4f8b-a081-f72e01ea0a2b","recipe":"hangoutschat","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"7eccfdeb-e0a1-449a-8492-b0c4c8b23456","recipe":"msteams","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"30040bd5-c62b-4d26-a6ed-b2fab9dcad06","recipe":"telegram","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false}],"messages":[{"type":"error","info":["error","Warning: Failed prop type: Invalid prop `actions.service` of type `Object` supplied to `_class2`, expected instance of `_class`.\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","info":["error","Warning: Failed prop type: Invalid prop `actions.settings` of type `Object` supplied to `_class2`, expected instance of `_class`.\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in ThemeProvider (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","info":["error","Warning: Failed prop type: The prop `stores.app.accentColor` is marked as required in `_class2`, but its value is `undefined`.\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by WithTheme(Jss(_class2)))\n    in WithTheme(Jss(_class2)) (created by inject-WithTheme(Jss(_class2))-with-stores)\n    in inject-WithTheme(Jss(_class2))-with-stores (created by _class2)\n    in _class2 (created by WithTheme(_class2))\n    in WithTheme(_class2) (created by Jss(WithTheme(_class2)))\n    in Jss(WithTheme(_class2)) (created by _class2)\n    in ThemeProvider (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","info":["error","Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s","the componentWillUnmount method","\n    in WithTheme(Jss(_class2)) (created by inject-WithTheme(Jss(_class2))-with-stores)\n    in inject-WithTheme(Jss(_class2))-with-stores (created by _class2)\n    in _class2 (created by WithTheme(_class2))\n    in WithTheme(_class2) (created by Jss(WithTheme(_class2)))\n    in Jss(WithTheme(_class2)) (created by _class2)"]},{"type":"error","info":["error","Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s","the componentWillUnmount method","\n    in WithTheme(_class2) (created by Jss(WithTheme(_class2)))\n    in Jss(WithTheme(_class2)) (created by _class2)"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getAnnouncement"},"error":{},"response":{},"server":"You are using Ferdi without a server"}],"workspaces":[],"windowSettings":{"width":1252,"height":539,"x":745,"y":404,"displayBounds":{"x":0,"y":0,"width":2560,"height":1440},"isMaximized":true,"isFullScreen":false},"settings":{"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":false,"minimizeToSystemTray":false,"closeToSystemTray":false,"privateNotifications":false,"clipboardNotifications":true,"notifyTaskBarOnMessage":false,"showDisabledServices":true,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"\"en-us\"","darkMode":false,"locale":"en-US","fallbackLocale":"en-US","beta":true,"isAppMuted":false,"enableGPUAcceleration":true,"server":"You are using Ferdi without a server","predefinedTodoServer":"isUsingCustomTodoService","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernateOnStartup":true,"hibernationStrategy":300,"wakeUpStrategy":"300","inactivityLock":0,"automaticUpdates":true,"showServiceNavigationBar":false,"universalDarkMode":true,"userAgentPref":"","adaptableDarkMode":true,"accentColor":"#28BCF1","serviceRibbonWidth":"68","iconSize":"20","sentry":false,"nightly":false,"navigationBarBehaviour":"custom","searchEngine":"google","useVerticalStyle":false,"alwaysShowWorkspaces":false,"serviceLimit":5,"hibernate":false,"todoServer":"isUsingCustomTodoService","customTodoServer":""},"features":{"isServiceProxyEnabled":false,"isAnnouncementsEnabled":true,"isWorkspaceEnabled":false,"isTodosEnabled":true},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}`

**Comment by vraravam** [comment] 2021-08-24 15:11
Duplicate of #1581

**Closed by vraravam** 2021-08-24 15:11 UTC

**Comment by YisroelTech** [comment] 2021-08-24 15:34
@vraravam is my issue also the same as that one?

For me, it doesn't even prompt with a **Restart & Install**, and even pressing _Check for Update_ doesn't bring that.

**Comment by vraravam** [comment] 2021-08-24 15:36
Yes - this is the same issue (same piece of code).
