### ISSUE TITLE
Downloaded Ferdi 5.4.3 for Windows and unable to add any service

### ISSUE THREAD

**Issue by mpatil19** [getferdi/ferdi#389] opened 2020-02-19 21:54 UTC
**Describe the bug: Services not getting added to Ferdi on clicking 'Save Service'**

**To Reproduce**

Ferdi account not created

1. Go to 'Get started' 
2. Click on 'Discover Services'
3. Scroll down to 'Whatsapp' or 'Hangouts' or any available services and click on 'Save Service'
4. No action is seen, no service is added, no error messages are seen

**Expected behavior**

**Screenshots**

**Desktop:**

- OS: Windows 10 pro
- Ferdi Version 5.4.3

- Server Used: [e.g. https://api.getferdi.com]

Debug information: https://debug.getferdi.com/...

**Additional context**

**Comment by vantezzen** [comment] 2020-02-20 08:33
Duplicate of #253. Please use Ferdi with an account while this error persists.

**Closed by vantezzen** 2020-02-20 08:33 UTC
