### ISSUE TITLE
Popup Blocker Supposedly Blocking URLs from GMAIL

### ISSUE THREAD

**Issue by zkhcohen** [getferdi/ferdi#640] opened 2020-04-24 16:58 UTC
**Describe the bug**

**To Reproduce**

1. Open Gmail
2. Click on any link embedded in an email.
3. The following pop-up appears:

![Ferdi_Gg30p1RwIS](https://user-images.githubusercontent.com/12313533/80236444-f0c07e80-860f-11ea-8c78-885d6cebfaec.png)

**Expected behavior**

Links should be able to be opened.

**Desktop:**

- OS: [e.g. macOS, Windows 10 etc.] Windows 10 Pro. 1903
- Ferdi Version [e.g. 5.4.3] 5.5.0-gm.2 (x64)

**Comment by kytwb** [comment] 2020-04-24 17:41
@zkhcohen Thank you for reporting! This is a duplicate of https://github.com/getferdi/ferdi/issues/321. Hopefully thanks to https://github.com/getferdi/ferdi/pull/639 we will be able to fix this long standing issue 🙏 Thanks for your patience!

**Comment by kytwb** [comment] 2020-04-24 17:41
In the meantime you should be able to right click and open the link from the context menu.

**Closed by kytwb** 2020-04-24 17:41 UTC
