### ISSUE TITLE
QuickSwitch is unusable without mouse (defeats the purpose of quick switching!)

### ISSUE THREAD

**Issue by vraravam** [getferdi/ferdi#1047] opened 2020-10-27 09:45 UTC
**Bug description:**
The QuickSwitch feature/modal/overlay is present for power users (in my understanding, those who like to use without mouse) to quickly navigate between different services. On my mac, when I open this with Cmd+S, the focus is not on the text box that is used to filter the services. As I type any characters, the list doesn't get filtered. I am forced to use the mouse to click into the text box, start typing, and once the shortlisted choices are present, I am forced to use the mouse again to click on a selection / service.

**Steps to reproduce:**

1. Setup a few services in Ferdi
2. Open the QuickSwitch overlay
3. Start typing

**Expected behavior**

Once the overlay pops up, any typing should filter the available services. The up/down arrow keys without modifiers should be used to traverse the shortlisted options, and enter press should go to that service.

**Screenshots**

**Environment:**

- Operating System: 
- Ferdi Version: 
- Server: 

- Debug information:

**Comment by vantezzen** [comment] 2020-10-27 17:18
Duplicate of #322.

This is a known bug which we unfortunately cannot fix: Electron does not allow Ferdi to focus the box if the focus is currently inside a webview. If you find a way to do this, please let us know, but we already tried many suggestions in related electron issues.

Related:
https://github.com/electron/electron/issues/17882
https://github.com/getferdi/ferdi/issues/68#issuecomment-534146281
https://github.com/getferdi/ferdi/blob/1fea645b0b94e52a31158d47d0ad921110dfa95e/src/features/quickSwitch/Component.js#L232-L235

**Closed by vantezzen** 2020-10-27 17:18 UTC
Labels: bug
