### ISSUE TITLE
External text links and external button links won't work

### ISSUE THREAD

**Issue by david-s-morris** [getferdi/ferdi#1465] opened 2021-05-29 23:13 UTC
**Bug description:**

In any application within Ferdi if you click on any text link that leads to an external page then nothing happens with the normal, left mouse click. This is the same for HTML button links that go external.

**Steps to reproduce:**

1. Go to Gmail
2. Click on a html email message
3. Left click on a link within the html email
4. See that no action takes place. Nothing happens at all

The only way to make the links work is to right-click and then click 'Open link' from the drop-down menu.

**Expected behavior**

The link should open a browser at the html locaiton.

**Screenshots**

**Environment:**

- Operating System: 
MacOS Big Sur 11.4 (20F71)

- Ferdi Version: 
Version 5.6.0-beta.5 (5.6.0-beta.5.2741)

- Server: 

- Debug information:

{"host":{"platform":"darwin","release":"20.5.0","screens":[{"id":2077750265,"bounds":{"x":0,"y":0,"width":1920,"height":1200},"workArea":{"x":0,"y":0,"width":1920,"height":1200},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":30,"colorSpace":"{primaries:SMPTEST432_1, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":10,"size":{"width":1920,"height":1200},"workAreaSize":{"width":1920,"height":1200},"scaleFactor":2,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.6.0-beta.5","electron":"9.3.2","installedRecipes":[{"id":"discord","version":"1.1.3"},{"id":"enterprise-owa","version":"1.1.0"},{"id":"franz-custom-website","version":"1.0.2"},{"id":"github","version":"2.0.0"},{"id":"gmail","version":"1.3.5"},{"id":"googlecalendar","version":"1.0.3"},{"id":"googledrive","version":"1.0.5"},{"id":"googlemeet","version":"1.0.4"},{"id":"jira","version":"1.2.0"},{"id":"linkedin","version":"1.0.0"},{"id":"messenger","version":"1.1.0"},{"id":"msteams","version":"2.0.0"},{"id":"office365-owa","version":"1.1.1"},{"id":"roundcube","version":"1.0.0"},{"id":"skype","version":"2.1.0"},{"id":"slack","version":"1.0.16"},{"id":"telegram","version":"3.0.0"},{"id":"whatsapp","version":"2.0.8"},{}],"devRecipes":[],"services":[{"id":"f744de91-e1e2-4ec3-9aff-1e6cc026a08a","recipe":"enterprise-owa","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"687c5466-9f8c-4d24-b4e2-38f8007d4931","recipe":"msteams","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"2354a1a3-b378-41fc-877f-f7eac7d4bdfd","recipe":"gmail","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"96b3a429-f28e-491e-8f8f-33e93596f828","recipe":"googlecalendar","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"8eb02bb0-b61e-4e77-9e2b-6bfbd15ff106","recipe":"slack","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"c7dc7698-653a-441c-9386-1e4dcc5c1cd5","recipe":"googledrive","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"3b84d691-faa7-4f5a-b589-90552bcdbaf5","recipe":"skype","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"6d2c0b3d-c6e6-40dc-944a-17d49a803771","recipe":"linkedin","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"37f39b66-22c6-407a-a7a3-75117dfb665b","recipe":"whatsapp","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"c29ec737-1735-4cb1-b862-490e9840e150","recipe":"messenger","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"d4b03279-cce9-4c91-90be-27d7942c9d11","recipe":"slack","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"01d70a54-4fdc-4a8d-bc38-882ffb412cc6","recipe":"discord","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"4bc451f3-05c0-4771-8ade-924317394334","recipe":"telegram","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"b44f467e-349e-4747-8e75-3458a07a8630","recipe":"googlemeet","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"b397b024-1461-4134-9e5d-1d43393ca14e","recipe":"gmail","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"ff14e53b-1d26-4232-975f-59a535c1d53e","recipe":"github","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"b7488edc-460d-4073-847e-3b95deb1a4ac","recipe":"jira","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false}],"messages":[{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"log","info":["log","Notification from Slack",{"body":"","icon":"/assets/img/notification-badge.gif","tag":"tag_1622206538.001600","silent":true}]},{"type":"log","info":["log","Notification from Slack",{"body":"","icon":"/assets/img/notification-badge.gif","tag":"tag_1622206549.002000","silent":true}]},{"type":"log","info":["log","Notification from Slack",{"body":"","icon":"/assets/img/notification-badge.gif","tag":"tag_1622206611.002900","silent":true}]},{"type":"log","info":["log","Notification from Slack",{"body":"","icon":"/assets/img/notification-badge.gif","tag":"tag_1622206823.157500","silent":true}]},{"type":"log","info":["log","Notification from Slack",{"body":"","icon":"/assets/img/notification-badge.gif","tag":"tag_1622207418.019900","silent":true}]},{"type":"log","info":["log","Notification from Slack",{"body":"","icon":"/assets/img/notification-badge.gif","tag":"tag_1622208420.034800","silent":true}]},{"type":"log","info":["log","Notification from Slack",{"body":"","icon":"/assets/img/notification-badge.gif","tag":"tag_1622209084.003100","silent":true}]},{"type":"log","info":["log","Notification from Slack",{"body":"","icon":"/assets/img/notification-badge.gif","tag":"tag_1622209113.004200","silent":true}]},{"type":"log","info":["log","Notification from Slack",{"body":"","icon":"/assets/img/notification-badge.gif","tag":"tag_1622209121.004500","silent":true}]},{"type":"log","info":["log","Notification from Slack",{"body":"","icon":"/assets/img/notification-badge.gif","tag":"tag_1622209180.005000","silent":true}]},{"type":"log","info":["log","Notification from Slack",{"body":"","icon":"/assets/img/notification-badge.gif","tag":"tag_1622210352.000300","silent":true}]},{"type":"log","info":["log","Notification from Slack",{"body":"","icon":"/assets/img/notification-badge.gif","tag":"tag_1622210747.006200","silent":true}]},{"type":"log","info":["log","Notification from Slack",{"body":"","icon":"/assets/img/notification-badge.gif","tag":"tag_1622210753.006400","silent":true}]},{"type":"log","info":["log","Notification from Slack",{"body":"","icon":"/assets/img/notification-badge.gif","tag":"tag_1622212140.000500","silent":true}]},{"type":"log","info":["log","Notification from Slack",{"body":"","icon":"/assets/img/notification-badge.gif","tag":"tag_1622216137.001100","silent":true}]},{"type":"log","info":["log","Notification from Slack",{"body":"","icon":"/assets/img/notification-badge.gif","tag":"tag_1622216149.001700","silent":true}]},{"type":"log","info":["log","Notification from Slack",{"body":"","icon":"/assets/img/notification-badge.gif","tag":"tag_1622216361.002300","silent":true}]},{"type":"log","info":["log","Notification from Slack",{"body":"","icon":"/assets/img/notification-badge.gif","tag":"tag_1622216700.153400","silent":true}]},{"type":"log","info":["log","Notification from Slack",{"body":"","icon":"/assets/img/notification-badge.gif","tag":"tag_1622216867.005000","silent":true}]},{"type":"log","info":["log","Notification from Slack",{"body":"","icon":"/assets/img/notification-badge.gif","tag":"tag_1622216944.006300","silent":true}]},{"type":"log","info":["log","Notification from Slack",{"body":"","icon":"/assets/img/notification-badge.gif","tag":"tag_1622216949.006600","silent":true}]},{"type":"log","info":["log","Notification from Slack",{"body":"","icon":"/assets/img/notification-badge.gif","tag":"tag_1622216977.007500","silent":true}]},{"type":"log","info":["log","Notification from Slack",{"body":"","icon":"/assets/img/notification-badge.gif","tag":"tag_1622217021.008300","silent":true}]},{"type":"log","info":["log","Notification from Slack",{"body":"","icon":"/assets/img/notification-badge.gif","tag":"tag_1622217036.008700","silent":true}]},{"type":"log","info":["log","Notification from Slack",{"body":"","icon":"/assets/img/notification-badge.gif","tag":"tag_1622217259.011300","silent":true}]},{"type":"log","info":["log","Notification from Slack",{"body":"","icon":"/assets/img/notification-badge.gif","tag":"tag_1622217294.012400","silent":true}]},{"type":"log","info":["log","Notification from Slack",{"body":"","icon":"/assets/img/notification-badge.gif","tag":"tag_1622217320.012900","silent":true}]},{"type":"log","info":["log","Notification from Slack",{"body":"","icon":"/assets/img/notification-badge.gif","tag":"tag_1622217700.013600","silent":true}]},{"type":"log","info":["log","Notification from Slack",{"body":"","icon":"/assets/img/notification-badge.gif","tag":"tag_1622217735.014300","silent":true}]},{"type":"error","info":["error","Uncaught TypeError: this.stores.settings.app.get is not a function","/Applications/Ferdi.app/Contents/Resources/app.asar/stores/AppStore.js",1,7269,{}]},{"type":"error","info":["error","Uncaught TypeError: this.stores.settings.app.get is not a function","/Applications/Ferdi.app/Contents/Resources/app.asar/stores/AppStore.js",1,7269,{}]},{"type":"error","info":["error","Uncaught TypeError: this.stores.settings.app.get is not a function","/Applications/Ferdi.app/Contents/Resources/app.asar/stores/AppStore.js",1,7269,{}]},{"type":"error","info":["error","Uncaught TypeError: this.stores.settings.app.get is not a function","/Applications/Ferdi.app/Contents/Resources/app.asar/stores/AppStore.js",1,7269,{}]},{"type":"error","info":["error","Uncaught TypeError: this.stores.settings.app.get is not a function","/Applications/Ferdi.app/Contents/Resources/app.asar/stores/AppStore.js",1,7269,{}]},{"type":"error","info":["error","Uncaught TypeError: this.stores.settings.app.get is not a function","/Applications/Ferdi.app/Contents/Resources/app.asar/stores/AppStore.js",1,7269,{}]},{"type":"error","info":["error","Uncaught TypeError: this.stores.settings.app.get is not a function","/Applications/Ferdi.app/Contents/Resources/app.asar/stores/AppStore.js",1,7269,{}]},{"type":"error","info":["error","Uncaught TypeError: this.stores.settings.app.get is not a function","/Applications/Ferdi.app/Contents/Resources/app.asar/stores/AppStore.js",1,7269,{}]},{"type":"error","info":["error","Uncaught TypeError: this.stores.settings.app.get is not a function","/Applications/Ferdi.app/Contents/Resources/app.asar/stores/AppStore.js",1,7269,{}]},{"type":"error","info":["error","Uncaught TypeError: this.stores.settings.app.get is not a function","/Applications/Ferdi.app/Contents/Resources/app.asar/stores/AppStore.js",1,7269,{}]},{"type":"error","info":["error","Uncaught TypeError: this.stores.settings.app.get is not a function","/Applications/Ferdi.app/Contents/Resources/app.asar/stores/AppStore.js",1,7269,{}]},{"type":"error","info":["error","Uncaught TypeError: this.stores.settings.app.get is not a function","/Applications/Ferdi.app/Contents/Resources/app.asar/stores/AppStore.js",1,7269,{}]},{"type":"error","info":["error","Uncaught TypeError: this.stores.settings.app.get is not a function","/Applications/Ferdi.app/Contents/Resources/app.asar/stores/AppStore.js",1,7269,{}]},{"type":"error","info":["error","Uncaught TypeError: this.stores.settings.app.get is not a function","/Applications/Ferdi.app/Contents/Resources/app.asar/stores/AppStore.js",1,7269,{}]},{"type":"error","info":["error","Uncaught TypeError: this.stores.settings.app.get is not a function","/Applications/Ferdi.app/Contents/Resources/app.asar/stores/AppStore.js",1,7269,{}]},{"type":"error","info":["error","Uncaught TypeError: this.stores.settings.app.get is not a function","/Applications/Ferdi.app/Contents/Resources/app.asar/stores/AppStore.js",1,7269,{}]},{"type":"error","info":["error","Uncaught TypeError: this.stores.settings.app.get is not a function","/Applications/Ferdi.app/Contents/Resources/app.asar/stores/AppStore.js",1,7269,{}]},{"type":"error","info":["error","Uncaught Error: An object could not be cloned.","/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/@sentry/browser/dist/helpers.js",91,13,{}]},{"type":"error","info":["error","Uncaught Error: An object could not be cloned.","/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/@sentry/browser/dist/helpers.js",91,13,{}]},{"type":"error","info":["error","Uncaught Error: An object could not be cloned.","/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/@sentry/browser/dist/helpers.js",91,13,{}]},{"type":"error","info":["error","Uncaught Error: An object could not be cloned.","/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/@sentry/browser/dist/helpers.js",91,13,{}]},{"type":"error","info":["error","Uncaught Error: An object could not be cloned.","/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/@sentry/browser/dist/helpers.js",91,13,{}]},{"type":"error","info":["error","Uncaught Error: An object could not be cloned.","/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/@sentry/browser/dist/helpers.js",91,13,{}]},{"type":"error","info":["error","Uncaught Error: An object could not be cloned.","/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/@sentry/browser/dist/helpers.js",91,13,{}]}],"workspaces":[],"windowSettings":{"width":800,"height":600,"x":-800,"y":170,"displayBounds":{"x":0,"y":0,"width":1920,"height":1200},"isMaximized":false,"isFullScreen":true},"settings":{"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":false,"minimizeToSystemTray":false,"privateNotifications":true,"notifyTaskBarOnMessage":true,"showDisabledServices":false,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"\"\\\"\\\\\\\"\\\\\\\\\\\\\\\"en-us\\\\\\\\\\\\\\\"\\\\\\\"\\\"\"","darkMode":false,"locale":"en-US","fallbackLocale":"en-US","beta":true,"isAppMuted":false,"enableGPUAcceleration":true,"serviceLimit":5,"server":"https://api.getferdi.com","predefinedTodoServer":"https://app.franztodos.com","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernate":false,"hibernateOnStartup":true,"hibernationStrategy":300,"inactivityLock":0,"automaticUpdates":true,"showServiceNavigationBar":false,"universalDarkMode":true,"adaptableDarkMode":true,"accentColor":"#7367f0","serviceRibbonWidth":68,"iconSize":20,"sentry":false,"nightly":false,"navigationBarBehaviour":"always","useVerticalStyle":false,"alwaysShowWorkspaces":false,"todoServer":"isUsingCustomTodoService","customTodoServer":""},"features":{"isSpellcheckerIncludedInCurrentPlan":true,"needToWaitToProceed":false,"needToWaitToProceedConfig":{"delayOffset":3600000,"wait":10000},"isServiceProxyEnabled":true,"isServiceProxyIncludedInCurrentPlan":true,"isAnnouncementsEnabled":true,"isWorkspaceIncludedInCurrentPlan":true,"isWorkspaceEnabled":true,"isCommunityRecipesIncludedInCurrentPlan":true,"isSpellcheckerPremiumFeature":false,"isServiceProxyPremiumFeature":true,"isWorkspacePremiumFeature":false,"isSettingsWSEnabled":false,"isServiceLimitEnabled":false,"serviceLimitCount":0,"isCommunityRecipesPremiumFeature":false,"isCustomUrlIncludedInCurrentPlan":true,"isMagicBarEnabled":true,"isTeamManagementIncludedInCurrentPlan":true,"isTodosEnabled":true,"isTodosIncludedInCurrentPlan":true,"defaultTrialPlan":"franz-pro-yearly","subscribeURL":"https://getferdi.com","planSelectionURL":"https://getferdi.com","hasInlineCheckout":true,"isPlanSelectionEnabled":false,"isTrialStatusBarEnabled":false,"canSkipTrial":true,"pricingConfig":{"currency":"$","currencyID":"USD","plans":{"personal":{"monthly":{"id":"ferdi-free","price":0,"billed":0},"yearly":{"id":"ferdi-completely-free","price":0,"billed":0}},"pro":{"monthly":{"id":"ferdi-still-free","price":0,"billed":0},"yearly":{"id":"ferdi-forever-free","price":0,"billed":0}}}}},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}

**Comment by vraravam** [comment] 2021-05-29 23:29
Thanks for repoting the bug @david-s-morris . This is a duplicate of #321 . Marking this as a duplicate and closing.

**Closed by vraravam** 2021-05-29 23:29 UTC
