### ISSUE TITLE
New issue on Google Chat

### ISSUE THREAD

**Issue by juliepellerin** [getferdi/ferdi#1345] opened 2021-05-04 06:38 UTC
Hi there, 

Since this morning I have an issue to connect to Google Chat, the message (in French) says : "Unfortunately, Google Chat is not compatible with your current browser" as you can see on the attached file. 
I tried to delete the Google Chat service and recreate it but it did not change anything. 

Do you have the same issue ? Do you know how to solve it ? 

Thanks !
![Capture d’écran 2021-05-04 à 08 35 03](https://user-images.githubusercontent.com/79444083/116968108-20d73e80-acb4-11eb-9ffa-d954cf9bf8ad.png)

**Comment by vraravam** [comment] 2021-05-04 06:45
Duplicate of #575 and #1273 - please see the workarounds over there.

**Comment by vraravam** [comment] 2021-05-05 01:38
@juliepellerin - if the workarounds in the linked issues work for you - I would request you to close this issue and follow one/both of those. Please report back so that we can fix anything else that we are not yet aware of.

**Comment by juliepellerin** [comment] 2021-05-05 06:57
Sorry but, as I am not familiar at all on coding, I did not succeed in doing the workarounds detailed in the linked issues...

**Comment by vraravam** [comment] 2021-05-05 07:34
@juliepellerin - let me try to help you. Could you please post the information about what Operating system? What version of Ferdi?
Inside of Ferdi preferences for your OS, can you please click on the "Services" on the left? Once it lists the services that you have signed-up for/configured, on the bottom of the right pane, it will show "Open User.js" - please click on this button, it should open the "Windows Explorer (for Windows) or Finder (for Mac). Copy this location and please send that across as well - so that I can type in exact steps to help.

**Comment by juliepellerin** [comment] 2021-05-05 07:42
Please find as attached documents the operating system and Ferdi Version. 
Regarding the "Services" it is only written "No adequate service" 
<img width="284" alt="Capture d’écran 2021-05-05 à 09 39 31" src="https://user-images.githubusercontent.com/79444083/117110329-3e74d880-ad86-11eb-8864-b5d7f94ae651.png">
<img width="277" alt="Capture d’écran 2021-05-05 à 09 39 50" src="https://user-images.githubusercontent.com/79444083/117110335-3fa60580-ad86-11eb-87de-4674c764d918.png">
<img width="406" alt="Capture d’écran 2021-05-05 à 09 42 27" src="https://user-images.githubusercontent.com/79444083/117110337-403e9c00-ad86-11eb-9f2a-212cce699e7e.png">

**Comment by juliepellerin** [comment] 2021-05-05 07:45
@vraravam  I just try again in Ferdi and Google Chat works ! I did not do any changes but for now it is working ! I am closing the ticket and will come back if the issue reappears. Thanks for your support

**Closed** 2021-05-05 07:49 UTC

**Comment by vraravam** [comment] 2021-05-05 07:51
@juliepellerin - if it happens again, then do the following:
1) Go to Ferdi > Preferences > Services
2) Click on the service (in this case, i would assume "hangouts chat")
3) On the right, pane, it will show "Open User.js" - click on this - it should open the "Finder" Application in macos.
4) Quit Ferdi
5) Go up 1 level to the "recipes folder" - and delete all the sub-folders there.
6) Start Ferdi

This should - in effect re-populate the recipes from what was bundled inside the application itself.

btw: I would strongly suggest that you get the version of Ferdi from [this folder](https://drive.google.com/drive/folders/1mJmKbhpVHdb066IHlrdYiD8TG9wlmuBv) - please use the latest file that is appropriate for your Mac hardware (either x86 or ARM)
