### ISSUE TITLE
No badges

### ISSUE THREAD

**Issue by larena1** [getferdi/ferdi#832] opened 2020-06-19 16:06 UTC
**Bug description:**
Started using Ferdi on version 5.5 but I don't see any badges in the app using WhatsApp Web. I've got badges turned on under service options and Ferdi is posting the notifications to the Win10 notification center.

**Steps to reproduce:**

**Expected behavior**

**Screenshots**

**Environment:**

- Operating System: 
- Ferdi Version: 
- Server: 

- Debug information:

**Comment by vantezzen** [comment] 2020-06-19 16:10
Duplicate of #818

**Closed by vantezzen** 2020-06-19 16:10 UTC

**Comment by larena1** [comment] 2020-06-19 16:12
Searched for badges but didn't find anything.

FWIW, I also don't have any badges for Roundcube. Is the recipe also broken?

**Comment by Potherca** [comment] 2020-11-27 11:30
@larena1 There issue with the Roundcube recipe that is fixed in https://github.com/getferdi/recipes/pull/359.

This change will be published with the next update of Ferdi, so keep an eye out for updates.
