### ISSUE TITLE
"Disable Hibernation" setting is not saved between restarts

### ISSUE THREAD

**Issue by CptDinosaur** [getferdi/ferdi#797] opened 2020-06-03 11:07 UTC
**Bug description:**
The "Disable Hibernation" setting for service is not saved between exiting and relaunching ferdi.
Others have reported this issue, see the last two posts on https://github.com/getferdi/ferdi/issues/280#issuecomment-625695236

This may also be an issue with "Keep services in hibernation on startup", conflicing with disabling hibernation for individual services.
End goal is to have some services (Like gmail) load normally and stay unhibernated, while others that I don't need notifications and stuff from (like ClickUp) to be hibernated at startup and remain so.

**Steps to reproduce:**

1. Enable hibernation in global settings
2. Turn on "Disable Hibernation" for a service
3. Restart ferdi
4. "Disable Hibernation" is now off again

**Expected behavior**
- Setting for "Disable Hibernation" is preserved
- Service with "Disable Hibernation" enabled does not go into hibernation when the software is started, while other services do.

**Environment:**

- Operating System: Win 10 x64 1909
- Ferdi Version: 5.5.0
- Server: Using without an account

- Debug information:
Pre-Restart https://debug.getferdi.com/238bd989-69ab-41b2-9abc-27b3ce6692fd
Post-Restart https://debug.getferdi.com/168903f4-ff4e-4cbb-b8bb-ee23d4620197
(Hope I got that right, it's not clear from link)

**Comment by vantezzen** [comment] 2020-06-03 12:16
Duplicate of #715. The bug has now been fixed - this fix will be released with the next version of Ferdi.

**Closed by vantezzen** 2020-06-03 12:16 UTC
Labels: bug
