### ISSUE TITLE
MS Teams left click on links not working

### ISSUE THREAD

**Issue by karolkpl** [getferdi/ferdi#2193] opened 2021-11-08 22:03 UTC
Left click on links posted in "Teams/Rooms" conversations is doing nothing (it should open the link in system browser). Right click + Open link works.
Left click is working in "Chat" conversations.

Tested on version 5.6.2 and 5.6.3 under linux.

**Comment by vraravam** [comment] 2021-11-09 01:03
As a workaround, please use the right-click to choose "open link in Ferdi" or "open link".

We have been contemplating revamping the link/url handler code to be more amenable to expose this behavior as preferences that the user can control - but, with other priorities, this hasn't made it into the list till date. We will be very glad to accept code contributions to help implement the same.

**Comment by vraravam** [comment] 2021-11-16 11:57
Duplicate of #1501

**Closed by vraravam** 2021-11-16 11:57 UTC
Labels: help wanted
