### ISSUE TITLE
infobar.servicesUpdated popup not disappearing

### ISSUE THREAD

**Issue by paperbenni** [getferdi/ferdi#282] opened 2019-12-23 23:12 UTC
**Describe the bug**
I get this popup about a minute after starting ferdi
![20191223234505](https://user-images.githubusercontent.com/15818888/71383797-45aaa480-25de-11ea-89f2-31adad26a28a.png)

This seems to be the german version of the infobar.servicesUpdated error/message
After  clicking the button, the entire window reloads and after a while the button appears again. 
The services I have "installed" are discord, trello, google messages and whatsapp. Deactivating some of them doesn't solve the problem. 

**To Reproduce**
1. Open ferdi
2. Wait a minute or so

**Expected behavior**
The popup should not appear. 

**Screenshots**
![20191223234505](https://user-images.githubusercontent.com/15818888/71383816-59eea180-25de-11ea-91c5-5a946b01507b.png)

**Desktop (please complete the following information):**

- OS: Arch Linux
- Browser: I thought ferdi was an electron app...
- Version 5.4.0

**Comment by vantezzen** [comment] 2019-12-24 08:16
Duplicate of #98

**Closed by vantezzen** 2019-12-24 08:16 UTC
