### ISSUE TITLE
Gmail problems on M1 with Ferdi 5.6.0 - switch to HTML version vs functional external links

### ISSUE THREAD

**Issue by davidsmehlik** [getferdi/ferdi#1799] opened 2021-08-15 20:04 UTC
Hi,

is there any WORKING user agent you could use both for supporting Gmail without "non-supported browser error" and together get links working? When I change browser user-agent to "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:93.0) Gecko/20100101 Firefox/93.0", Gmail starts working without "non-supported browser error", but I'm unable to get links clickable. When I change it to "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36", it shows non-supported browser, switch to HTML version, but I could click on the links with CMD and its workin.

Is there any setup when both things works? :-)

Thanks

**Comment by BenjaminBrossi** [comment] 2021-08-16 08:48
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0` works for me.

**Comment by Tsakatac** [comment] 2021-08-16 14:28
Hello,

I have the same issue. `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:93.0) Gecko/20100101 Firefox/93.0` allow me to use standard mode but I can't open any external links (Ferdi is saying that a pop-up blocker is blocking the app to open a page).

Thanks.

**Comment by michaelhays** [comment] 2021-08-16 15:50
@Tsakatac See [this issue](https://github.com/getferdi/ferdi/issues/321).

You can [get around it](https://github.com/getferdi/ferdi/issues/321#issuecomment-620943121) by using ctrl+click.

**Comment by Tsakatac** [comment] 2021-08-16 16:32
Hello,

Thanks, CTRL + click is working as a work around.
For the user-agent change, I already try but issue is that it triggers the standard version issue.

**Comment by lettucef1re** [comment] 2021-08-17 08:16
oddly if i use `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:93.0) Gecko/20100101 Firefox/93.0` i can use GMail standard mode but then it does not display slack properly

**Comment by excal04** [comment] 2021-08-17 08:38
@lettucef1re and for anyone else who uses this workaround, you can configure the User-Agent on the specific service instead of global. I configured it on Gmail only so that it won't conflict with my other services.

Settings > Your Services > click on your service and fill in the User Agent.

**Comment by vraravam** [comment] 2021-08-21 01:13
Duplicate of #1779. Please continue the conversation there. Closing.

**Closed by vraravam** 2021-08-21 01:13 UTC
