### ISSUE TITLE
Drag-and-Drop rearranging of workspaces

### ISSUE THREAD

**Issue by xerus2000** [getferdi/ferdi#755] opened 2020-05-19 18:06 UTC
**Is your feature request related to a problem? Please describe.**
I currently don't see any way of rearranging workspaces

**Describe the solution you'd like**
A way of rearranging them using drag and drop in the settings menu:
![image](https://user-images.githubusercontent.com/13354331/82361922-d5c50c80-9a0b-11ea-9fc7-0967222a532a.png)
I would suggest to add two small horizontal bars to the left of each workspace to indicate the possibility to use drag and drop - currently can't find an example to illustrate what I mean, I hope you understand.

**Describe alternatives you've considered**
Deleting existing workspaces and recreating them in the right order - yikes!

Maybe editing config files? Haven't yet looked into that.

**Comment by vantezzen** [comment] 2020-05-20 07:00
Duplicate of #245

**Closed by vantezzen** 2020-05-20 07:00 UTC

**Comment by xerus2000** [comment] 2020-05-20 09:51
oh I'm sorry, I searched existing issues but somehow didn't find that ^^
