### ISSUE TITLE
Ferdi Unread Badge Displays Even With No Unread Notifications (macOS) (ferdi 5.6.0)

### ISSUE THREAD

**Issue by Julian88Tex** [getferdi/ferdi#1676] opened 2021-07-22 07:18 UTC
**Bug description:**
Ferdi Dock notification badge on mac shows notification unread symbol when no services have unread notifications after upgrade to Ferdi 5.6.0

**Steps to reproduce:**

1. Click on every service that is enabled and verify no new notifications are present
2. Look at Ferdi dock icon and notice the unread badge icon

**Expected behavior**
No unread badge icon displays when no services have unread notifications.

**Screenshots**
<img width="114" alt="Screen Shot 2021-07-22 at 12 05 38 AM" src="https://user-images.githubusercontent.com/459099/126602204-6bf06cb1-dc11-4f55-ad78-abf8560c0cf6.png">
<img width="65" alt="Screen Shot 2021-07-22 at 12 15 03 AM" src="https://user-images.githubusercontent.com/459099/126602211-fbac21bd-5305-42f2-8c7b-6d3ea92309cc.png">

**Environment:**
- Operating System: macOS 11.4 (20F71)
- Ferdi Version: 5.6.0

- Debug information:
https://gist.github.com/Julian88Tex/0732c3b02ced0937606ba89a1827b08f

**Comment by vraravam** [comment] 2021-07-22 07:23
Duplicate of #1594

**Closed by vraravam** 2021-07-22 07:23 UTC

**Comment by Julian88Tex** [comment] 2021-07-22 07:45
@vraravam thanks for link!
