### ISSUE TITLE
App crash on macOS since 5.4.1-beta.1

### ISSUE THREAD

**Issue by incace** [getferdi/ferdi#242] opened 2019-11-29 02:03 UTC
**Describe the bug**
Many things are broken on the 5.4.1-beta.1 on MacOS. When upgrading, all services are wiped. Logging out and logging back in does not fix this. Unable to create a new account, nothing happens. Using an existing account yields the message "Could not load services and user information". Adding services to the account is impossible, nothing happens. I've tested this both with an in-app update to 5.4.1-beta.1, and a fresh install of 5.4.1-beta.1. Going back to a 5.4.0 install fixes this and the services load up normally as expected.

**To Reproduce**

1. Install 5.4.1-beta.1
2. Nothing works...

**Expected behavior**
A working application.

**Desktop (please complete the following information):**
- OS: MacOS

**Comment by kytwb** [comment] 2019-11-29 04:19
It seems to be an API issue? Which API (Ferdi/Franz) are you using?  
Anything in your developer console that could be of any help? (View > Toggle Developer Console)

**Comment by kytwb** [comment] 2019-11-29 04:28
@vantezzen Did you experience something similar with 5.4.1-beta.1? This is the only report of that kind, not sure if it is a problem with 5.4.1-beta.1 or with an API?

**Comment by kytwb** [comment] 2019-11-29 06:01
@incace do you have any (network) error log in the developer tools console?

**Comment by vantezzen** [comment] 2019-11-29 07:20
I am currently only using the development version so I haven't used the beta. I suspect that it could have something to do with the update to Electron 7?

**Comment by kytwb** [comment] 2019-11-29 07:34
@incace which version did you update from?

**Comment by vraravam** [comment] 2019-11-29 11:05
I upgraded from `5.4.1-beta.1` to `5.4.1-beta.2` - and I had a master password set on the installation. After the upgrade, the next time I restarted my laptop, ferdi wouldn't start. I tried wiping all data from my laptop - all ferdi preferences, etc - still unable to start ferdi.

**Comment by kytwb** [comment] 2019-11-29 11:07
@vraravam The application doesn't start at all? Any crash reports/error message?

**Comment by vraravam** [comment] 2019-11-29 11:30
@kytwb - as I said, it seemed to be working even after upgrade to beta2 - but, once i rebooted my machine, it stopped working. Just the main window would come up for a split-second - and then the process would completely quit.

I have since then, cleaned up ALL the cache folders, installation folders, etc - and gone back to ferdi 5.4.0 (non-beta) version - and am resetting up my services.

**Comment by bkosse** [comment] 2019-11-30 12:26
I'm experiencing the same issue. The main window comes up for a split-second - and then the process quits completely.

MacOS 10.14.6
Ferdi 5.4.1-beta.2

Error log:
`error	13:24:16.732697 +0100	Ferdi	        AEGetDescData of non-desc type 'reco' not a good idea
error	13:24:17.101195 +0100	Ferdi	nw_path_close_fd Failed to close guarded necp fd 32 [9: Bad file descriptor]
error	13:24:17.104911 +0100	tccd	Prompting policy for hardened runtime; service: kTCCServiceAppleEvents requires entitlement com.apple.security.automation.apple-events but it is missing for ACC:{ID: com.kytwb.ferdi, PID[53253], auid: 501, euid: 501, binary path: '/Applications/Ferdi.app/Contents/MacOS/Ferdi'}, REQ:{ID: com.apple.appleeventsd, PID[60], auid: 55, euid: 55, binary path: '/System/Library/CoreServices/appleeventsd'}
error	13:24:48.372414 +0100	Ferdi	        AEGetDescData of non-desc type 'reco' not a good idea
error	13:24:48.483874 +0100	tccd	Prompting policy for hardened runtime; service: kTCCServiceAppleEvents requires entitlement com.apple.security.automation.apple-events but it is missing for ACC:{ID: com.kytwb.ferdi, PID[53262], auid: 501, euid: 501, binary path: '/Applications/Ferdi.app/Contents/MacOS/Ferdi'}, REQ:{ID: com.apple.appleeventsd, PID[60], auid: 55, euid: 55, binary path: '/System/Library/CoreServices/appleeventsd'}
error	13:24:48.747409 +0100	Ferdi	nw_path_close_fd Failed to close guarded necp fd 32 [9: Bad file descriptor]
`

**Comment by incace** [comment] 2019-12-02 05:16
> @incace which version did you update from?

I updated from 5.4.0 stable initially. I also did a fresh install of the beta (no update) with the same results. I don't quite understand the first message, I am referring to beta.1. I haven't had a chance to dig into this since and had reverted back to 5.4.0. After an auto-update (forgot to disable that) it seems to be working ok now. The current version with all services back is 5.4.1-beta.1.887. I have no clue what went wrong initially and I don't understand why it's working again. Server issue?

**Comment by vraravam** [comment] 2019-12-02 07:09
quick update on this: After installing 5.4.0 (non beta), and resetting up all my services, and a few application-restarts, and at least 1 machine (OS) reboot, I felt brave enough to upgrade to the latest beta (5.4.1-beta.2) from within the application's preferences page - and everything seems working as of now (fingers crossed)

**Comment by ylluminate** [comment] 2019-12-07 01:17
Was running 5.4.0 and then after updating to 5.4.1-beta.2 the app will not start whatsoever.

**Comment by incace** [comment] 2019-12-08 17:35
> Was running 5.4.0 and then after updating to 5.4.1-beta.2 the app will not start whatsoever.
> 
> After backing down to 5.4.0 everything worked again and sanity was restored - briefly. I then experienced a crash and now 5.4.0 will not even start properly (comes up for a split second and then disappears).
> 
> I then thought I'd go back to 5.4.1-beta.2, but I assume I should reset everything entirely...
> 
> What folders should I move out of place? The following didn't work (still crashes on startup):
> 
> ```
> $ mv ~/Library/Preferences/com.kytwb.ferdi.plist ~/tmp/
> $ mv ~/Library/Application\ Support/Ferdi/ ~/tmp/
> $ mv ~/Library/Saved\ Application\ State/com.kytwb.ferdi.savedState ~/tmp/
> $ mv ~/private/var/folders/cb/MORE_PATH/C/com.kytwb.ferdi* ~/tmp
> $ mv ~/private/var/folders/cb/MORE_PATH/T/com.kytwb.ferdi* ~/tmp
> ```

Currently experiencing this I think. App starts to load and quits with the following log error: Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]

**Comment by grmon** [comment] 2019-12-18 13:51
Updated from 5.4.0 to 5.4.1-beta.2 and after the unlock, Ferid keeps showing the error:
"Could not load services and user information [Try again]" 
See:
<img width="800" alt="Screenshot 2019-12-18 at 14 45 59" src="https://user-images.githubusercontent.com/500813/71091627-bba9a880-21a5-11ea-95b9-84059bcbc7d8.png">

I have a custom workspace with around 20 services of which 7 are enabled, but the don't show at all in the prefs window.
See:
<img width="800" alt="Screenshot 2019-12-18 at 14 50 07" src="https://user-images.githubusercontent.com/500813/71091625-bba9a880-21a5-11ea-8084-940be1cc6d69.png">
<img width="800" alt="Screenshot 2019-12-18 at 14 50 10" src="https://user-images.githubusercontent.com/500813/71091624-bba9a880-21a5-11ea-80bc-2a478f399469.png">

**Comment by ylluminate** [comment] 2019-12-18 13:57
Yeah @incace, sounds like it.  I wonder if there's anything we can do at this point.  Since now the old version won't work after the update I'm obviously missing something in the "nuclear reset" realm.  It would be nice if @vantezzen or @kytwb might be able to chime in as to exactly what files we can obliterate that would set Ferdi back to its starting point to try again...

**Comment by kytwb** [comment] 2019-12-18 14:09
Sorry guys, I have been mostly offline for the past weeks and haven't been able to work on Ferdi at all. I will be back at it and address the open issues as soon as possible; in the meantime I hope the community can find workarounds and/or contribute 🙏 Thank you all for your patience and your contributions in investigating the issues.

**Comment by ylluminate** [comment] 2019-12-18 14:11
Thanks @kytwb - we understand. One thing, if you have a few minutes to isolate these since we're obviously missing the details somewhere: could you enumerate all of the files that are generated and used by Ferdi at startup and during usage?  I think it would be useful for troubleshooting if we could just "nuke" the app's configuration entirely and get back to a "vanilla" starting point to see if that resolves the upgrade issue that appears to exist in this ticket...

**Comment by vraravam** [comment] 2019-12-18 15:07
If you are on a Mac, one of the above comments (https://github.com/getferdi/ferdi/issues/242#issuecomment-562798812) tells you exactly which files/folders to nuke.

**Comment by kytwb** [comment] 2019-12-18 15:14
@ylluminate 

> Could you enumerate all of the files that are generated and used by Ferdi at startup and during usage

I can't answer this from the top of my head, sorry. Unfortunately, I think a couple of nasty bugs came in with the latest releases and are becoming mixed up in threads.

From what I have quickly investigated, the segmentation faults experienced (app doesn't open at all and crash) were due to an issue with Electron 7 and Sentry for Electron (see this [thread](https://github.com/electron/electron/issues/21240)) introduced via 5.4.1-beta.1 (when we upgraded to Electron 7). This (and other things) should be fixed via https://github.com/getferdi/ferdi/commit/06b26716fc90297b4227668c2d6a48e771e02ba7 and ship in the next release.

**Comment by ylluminate** [comment] 2019-12-18 15:16
@vraravam this is me who asked that question because what I enumerated there did not, apparently, reset the app entirely... which is why I asked for further insight.

**Comment by kytwb** [comment] 2019-12-18 15:40
@ylluminate apologies for that and thanks for bearing with us 😅 I managed to settle in a cafe with a functional WiFi and I'm proceeding to ship a new build to avoid, at least, the segmentation faults. Trying to investigate the rest.

**Comment by ylluminate** [comment] 2019-12-18 15:52
Hey no problem @kytwb!!!! You're awesome and thank you for this!  I'm really grateful you were able to sort this out and find the time.  I've been growing in frustration with Rambox (Pro) with the way multiple devices are handled (and no Dark Mode, etc.) and of course (as everyone here knows) the issues with Franz. Ferdi's openness is really fantastic and moving in the right direction on multiple levels.  Lock-in, especially in communications, has been a scary thing up to now!

**Comment by ylluminate** [comment] 2019-12-18 16:37
@kytwb how long does it usually take for the release assets to generate for Ferdi?

**Comment by kytwb** [comment] 2019-12-18 16:43
Uploading the assets to the GitHub release is done as the last steps of the builds. The release is created as a draft first, then need to be published by a maintainer (@vantezzen or I). It looks like this currently:

<img width="1007" alt="Screen Shot 2019-12-18 at 5 41 48 PM" src="https://user-images.githubusercontent.com/412895/71105427-d851da80-21bd-11ea-91b8-2139861d6080.png">

I will be releasing it once I'm done for the day. I can confirm it fixes the segmentation fault as I was also subject to it on my machine (macOS).

**Comment by kytwb** [comment] 2019-12-18 16:54
@incace can you confirm you don't experience the segmentation fault anymore with [v5.4.1-beta.3](https://github.com/getferdi/ferdi/releases/tag/v5.4.1-beta.3)?

**Comment by ylluminate** [comment] 2019-12-18 16:59
Confirmed I'm back in business with Ferdi - no more crash and it appears the files [I listed above](https://github.com/getferdi/ferdi/issues/242#issuecomment-562798812) did indeed reset it ("nuclear" reset).

**Comment by kytwb** [comment] 2019-12-18 19:01
@grmon are you on Windows?

**Comment by kytwb** [comment] 2019-12-19 12:31
Closing for now.

**Closed by kytwb** 2019-12-19 12:31 UTC
Labels: bug
