### ISSUE TITLE
Ferdi password protect (Manjaro)(Unable to access)

### ISSUE THREAD

**Issue by neondeex** [getferdi/ferdi#1241] opened 2021-03-15 01:21 UTC
![image](https://user-images.githubusercontent.com/30392593/111091944-2907ce80-84fa-11eb-8525-6f652a4ca87a.png)
I'm using ferdi 5.6 and i activate password-protected, now i can't log in
I try to reinstall ferdi but still getting the same screen
Please provide me where is the file where i can deactivate this mode

I'm using manjaro
![image](https://user-images.githubusercontent.com/30392593/111092009-65d3c580-84fa-11eb-8e7f-be3405171de2.png)

**Comment by MosheGross** [comment] 2021-03-15 03:08
I had the same issue on Win10 after updating Ferdi.
for me this worked.
Go to `~/.config/Ferdi/config/settings.json`
and change
~~~
  "lockingFeatureEnabled": true,
  "locked": true,
~~~
to
~~~
  "lockingFeatureEnabled": false,
  "locked": false,
~~~

**Comment by kris7t** [comment] 2021-06-05 19:37
Duplicate of #750

**Closed by kris7t** 2021-06-05 19:37 UTC
