### ISSUE TITLE
Dark mode option is not working

### ISSUE THREAD

**Issue by alexdevero** [getferdi/ferdi#370] opened 2020-02-13 11:42 UTC
**Describe the bug**
The option (toggle) for Enable dark mode doesn't react on clicking. If I click on it, to enable dark mode, nothing happens. Option stays disabled.

Note: Enable universal dark mode works, i.e. clicking enables/disables it.

**To Reproduce**

1. Go to 'Settings'
2. Click on 'Enable dark mode'
4. See error - Enable dark mode option will not change

**Expected behavior**
Toggling "Enable dark mode" option will change the app theme to dark mode.

**Screenshots**
![ferdi](https://user-images.githubusercontent.com/4237724/74430919-23a30500-4e5e-11ea-8658-fdf5000df57e.PNG)

**Desktop (please complete the following information):**

- OS: Windows 10, x64
- Ferdi 5.4.4-beta.1

- Server Used: https://api.getferdi.com

**Additional context**
I am using **portable** version of Ferdi.

**Comment by vantezzen** [comment] 2020-02-13 12:05
Duplicate of #347

**Closed by vantezzen** 2020-02-13 12:05 UTC

**Comment by kytwb** [comment] 2020-03-01 23:19
Shipped in [v5.4.4-beta.2](https://github.com/getferdi/ferdi/releases/tag/v5.4.4-beta.2).
