### ISSUE TITLE
 The right mouse button on services does not work

### ISSUE THREAD

**Issue by P4N1CO** [getferdi/ferdi#535] opened 2020-04-03 12:16 UTC
Some services I believe they use the web I can't use the right button, either to copy information or paste

Ferdi: 5.4.3(x64)
Electron: 7.1.6
Node.js: v12.8.1
Platform: win32

Windows 10 Pro

**Comment by vantezzen** [comment] 2020-04-03 13:47
Duplicate of #357. This issue should already be fixed in Beta versions of Ferdi.

**Closed by vantezzen** 2020-04-03 13:47 UTC
