### ISSUE TITLE
Make workspaces sortable

### ISSUE THREAD

**Issue by cdjost** [getferdi/ferdi#710] opened 2020-05-04 10:09 UTC
**Is your feature request related to a problem? Please describe.**
Creating a workspace is also setting the order in which workspaces are displayed. It would be a nice improvment to be able to manually set the workspace display order.

**Describe the solution you'd like**
It would be great to sort/order the workspaces in the setting menu. As a little bonus it would be cool if we are able to set little icons to our workspaces in order to identify them quickly.

**Comment by vantezzen** [comment] 2020-05-05 06:08
Duplicate of #245

**Closed by vantezzen** 2020-05-05 06:08 UTC
