### ISSUE TITLE
Ferdi closes starts to close after opening

### ISSUE THREAD

**Issue by crossi16** [getferdi/ferdi#1244] opened 2021-03-15 10:29 UTC
I use ferdi since around 2 Months now. Since 1 Week it just closes after I open it. Sometimes after a few seconds or later, sometimes I was also able to just use it. What can I do about this?

Thank you very much!

**Comment by VOOM108** [comment] 2021-04-05 16:43
I have the same or a similar problem. (Ferdi 5.6 beta 5 - Win 10)
Usually I need to start Ferdi 2-4 times until it loads completely. I just "disappears" without any message.

**Comment by vraravam** [comment] 2021-05-01 14:09
Please see my latest comment in [1263](https://github.com/getferdi/ferdi/issues/1263#issuecomment-830636673) - this might be the same issue with the same workaround - please confirm if it works for you on Windows.

**Comment by VOOM108** [comment] 2021-05-01 14:31
I will try that next time. It may be, that the service open when closing, which will be the first to shop when opening, matters. For me this is WhatsApp most of the time. By switching the services while opening like you suggest this may be prevented... Just an idea. I will try to test my theory more thoroughly as well.

**Comment by VOOM108** [comment] 2021-05-02 15:14
I closed Ferdi yesterday with a simple Webpage as a service in focus - and Ferdi started up quickly and instantly. I think it really depends on the service you leave in focus when closing and at least WhatsApp will almost certainly lead to crashed on startup. 

A sufficient workaround could be, to give Ferdi the option to always start with a specific service of one's own choosing or even some kind of internal startpage, no matter what is in focus when closing.

**Comment by vraravam** [comment] 2021-05-02 16:53
That is an excellent idea @VOOM108 - give an ability to start off Ferdi on a welcome page or on the last-used service. But, this might still only sweep the underlying issue "under the rug" - since there can be users who want Ferdi to remember the previous session and continue where it left off.

**Comment by vraravam** [comment] 2021-07-28 15:15
Since the last time I posted the comments, I have switched from using the Ferdi-server to using Ferdi without a server (ie a local / internal server). This has completely removed the crash-at-startup issue. Please try if you are also ok with using Ferdi without any externally-hosted server.

**Comment by vraravam** [comment] 2021-08-29 13:28
Is this still an issue atm? Could someone please try with the latest nightlies and report back?

**Comment by vraravam** [comment] 2021-08-29 13:29
Is this a duplicate of #1263 ?

**Comment by mhatvan** [comment] 2021-09-10 07:11
Closing due to inactivity. 

We can reopen this, if the issues still exist in the latest nightly.

**Closed by mhatvan** 2021-09-10 07:11 UTC
Labels: outstanding question
