### ISSUE TITLE
Cannot add a service

### ISSUE THREAD

**Issue by DanielValahul** [getferdi/ferdi#187] opened 2019-11-02 20:03 UTC
I installed Ferdi 5.4 beta 4 on my Windows PC. I chose not to use an account. Then I tried to add a service (Whatsapp) but it didn't do anything. I click on save and nothing happens.

I tried multiple services and nothing seems to work. I also tried to create a workspace but nothing happens.

**Comment by vantezzen** [comment] 2019-11-03 15:25
Duplicate of #149.

**Closed** 2019-11-03 15:25 UTC
Labels: duplicate
