### ISSUE TITLE
Service 'Disable Hibernation' not being saved

### ISSUE THREAD

**Issue by diego-treitos** [getferdi/ferdi#762] opened 2020-05-21 13:03 UTC
**Bug description:**

When I enable `Disable Hibernation` on an specific service (tried on several) the setting is reset to *disabled* after Ferdi is restarted.

**Steps to reproduce:**

1. Open Ferdi
2. Enable `Disable Hibernation` for a service
3. Close Ferdi
4. Open Ferdi again
5. The `Disable Hibernation` for the service is disabled again.

**Expected behavior**

The setting should be kept after a restart.

**Screenshots**

**Environment:**

- Operating System: Debian 10, Ubuntu 20.04
- Ferdi Version: `5.5.0 (x64)`
- Server: Ferdi

**Comment by vantezzen** [comment] 2020-05-21 13:08
Duplicate of #715. The bug has now been fixed - this fix will be released with the next version of Ferdi.

**Closed by vantezzen** 2020-05-21 13:08 UTC
