### ISSUE TITLE
Grrr! A popup blocker may be preventing......

### ISSUE THREAD

**Issue by sujay1844** [getferdi/ferdi#1153] opened 2021-01-13 16:37 UTC
**Bug description:**

When I click on a link to open it, a dialog box appears saying, "popup blocker may be preventing....."

**Steps to reproduce:**

Click on any external link in your mail or chat

**Expected behavior**

Open the link in my browser

**Screenshots**

![image](https://user-images.githubusercontent.com/68642484/104480990-37fdfd80-55eb-11eb-96d7-8e37dbcb364f.png)

**Environment:**

- Operating System: Windows 10 20H2
- Ferdi Version: 5.5.0
- Server: Franz

- Debug information:

```
{"host":{"platform":"win32","release":"10.0.19042","screens":[{"id":2528732444,"bounds":{"x":0,"y":0,"width":1536,"height":864},"workArea":{"x":35,"y":0,"width":1501,"height":864},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1536,"height":864},"workAreaSize":{"width":1501,"height":864},"scaleFactor":1.25,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.5.0","electron":"8.2.3","installedRecipes":[{"id":"discord","version":"1.1.3"},{"id":"gmail","version":"1.3.1"},{"id":"office365-owa","version":"1.1.0"},{"id":"outlook","version":"1.0.0"},{"id":"proton-mail","version":"1.2.0"},{"id":"reddit","version":"1.0.0"},{"id":"slack","version":"1.0.15"},{"id":"todoist","version":"1.1.0"},{"id":"twitter","version":"1.1.1"},{"id":"twitter-dm","version":"1.0.0"},{"id":"whatsapp","version":"2.0.3"}],"devRecipes":[],"services":[{"id":"e54c4328-cb6e-495e-b1e3-f9c5a1926348","recipe":"gmail","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"80640959-c1b9-4ac8-bd3a-23b3fd67f4d8","recipe":"whatsapp","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"aec61045-b756-4631-a10f-8b969b5b895b","recipe":"proton-mail","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"eebeeda2-5444-4af3-8591-90d7e2d6de1c","recipe":"twitter","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"32537576-8106-4a71-9023-f826fa573c8c","recipe":"reddit","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true}],"messages":[{"type":"error","info":["error","[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@160]'",{}]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"log","info":["log","[ServerApi::getRecipePackage] Downloading recipe from server"]},{"type":"log","info":["log","C:\\Users\\Sujay\\AppData\\Roaming\\Ferdi\\recipes\\temp\\News\\recipe.tar.gz"]},{"type":"error","info":["error",{"errno":-4058,"syscall":"open","code":"ENOENT","path":"C:\\Users\\Sujay\\AppData\\Roaming\\Ferdi\\recipes\\temp\\News\\package.json"}]}],"workspaces":[],"windowSettings":{"width":796,"height":613,"x":252,"y":68,"isMaximized":false,"isFullScreen":false,"displayBounds":{"x":0,"y":0,"width":1536,"height":864}},"settings":{"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":true,"minimizeToSystemTray":true,"privateNotifications":false,"showDisabledServices":true,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":"","spellcheckerLanguage":"en-us","darkMode":false,"locale":"en-US","fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":"","serviceLimit":5,"server":"https://api.getferdi.com","predefinedTodoServer":"https://todo.microsoft.com/?app#","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernate":false,"hibernateOnStartup":true,"hibernationStrategy":"300","inactivityLock":0,"automaticUpdates":true,"showServiceNavigationBar":false,"universalDarkMode":true,"adaptableDarkMode":true,"accentColor":"#32C05C","serviceRibbonWidth":"45","iconSize":20,"sentry":false,"navigationBarBehaviour":"never","customTodoServer":"","todoServer":"isUsingCustomTodoService"},"features":{"isSpellcheckerIncludedInCurrentPlan":true,"needToWaitToProceed":false,"needToWaitToProceedConfig":{"delayOffset":3600000,"wait":10000},"isServiceProxyEnabled":true,"isServiceProxyIncludedInCurrentPlan":true,"isAnnouncementsEnabled":true,"isWorkspaceIncludedInCurrentPlan":true,"isWorkspaceEnabled":true,"isCommunityRecipesIncludedInCurrentPlan":true,"isSpellcheckerPremiumFeature":false,"isServiceProxyPremiumFeature":true,"isWorkspacePremiumFeature":false,"isSettingsWSEnabled":false,"isServiceLimitEnabled":false,"serviceLimitCount":0,"isCommunityRecipesPremiumFeature":false,"isCustomUrlIncludedInCurrentPlan":true,"isMagicBarEnabled":true,"isTeamManagementIncludedInCurrentPlan":true,"isTodosEnabled":true,"isTodosIncludedInCurrentPlan":true,"defaultTrialPlan":"franz-pro-yearly","subscribeURL":"https://getferdi.com","planSelectionURL":"https://getferdi.com","hasInlineCheckout":true,"isPlanSelectionEnabled":false,"isTrialStatusBarEnabled":false,"canSkipTrial":true,"pricingConfig":{"currency":"$","currencyID":"USD","plans":{"personal":{"monthly":{"id":"ferdi-free","price":0,"billed":0},"yearly":{"id":"ferdi-completely-free","price":0,"billed":0}},"pro":{"monthly":{"id":"ferdi-still-free","price":0,"billed":0},"yearly":{"id":"ferdi-forever-free","price":0,"billed":0}}}}},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}
```

**Comment by lisandrocarmona** [comment] 2021-02-04 16:20
Yeah, this message should be addressed. All links you click, there is that message.
Please allow user to choose in this regard: block, open in Ferdi, open in the default system browser.
Thank you for your hard work!

**Comment by MarcusUA** [comment] 2021-02-24 11:10
Same thing on Mac OS, in order to open a link one must right-click on it and select Open Link, by default it uses Open Link In Ferdi. 
I couldn't any setting to override this behaviour.

**Comment by huang-jy** [comment] 2021-02-25 07:19
CTRL+Click/CMD+Click or Middle Click will bypass this.

**Comment by TanZng** [comment] 2021-04-08 02:36
Duplicate of #321

**Comment by vraravam** [comment] 2021-06-01 08:31
This is now fixed by https://github.com/getferdi/ferdi/pull/1474 - which has just been merged! Please pull and rebuild from source, or wait for tonight's nightly build.

**Closed by vraravam** 2021-06-01 08:31 UTC

**Comment by sujay1844** [comment] 2021-06-01 09:09
Thank you. Even if it's six months, it's fixed. Finally!!
