### ISSUE TITLE
Unable to maximize window closed window

### ISSUE THREAD

**Issue by MartinX3** [getferdi/ferdi#2210] opened 2021-11-10 22:21 UTC
**Bug description:**

Since the update to 5.6.3 i can't maximize a closed window with the tray icon.

**Steps to reproduce:**

1. Close the window.
2. Maximize it via the tray icon "show ferdi"

**Expected behavior**
My ferdi window.

**Screenshots**
N/A

**Environment:**

- Operating System: Arch Linux / EndeavourOS
- Ferdi Version: 5.6.3
- Server: Ferdi

- Debug information:
```
TypeError: Cannot read properties of undefined (reading 'isMinimized')
    at click (/opt/ferdi/resources/app.asar/lib/Tray.js:1:692)
    at MenuItem.click (node:electron/js2c/browser_init:73:1908)
    at Object.a._executeCommand (node:electron/js2c/browser_init:81:2453)
(node:161432) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 did-stop-loading listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(Use `ferdi --trace-warnings ...` to show where the warning was created)
TypeError: Cannot read properties of undefined (reading 'isMinimized')
    at click (/opt/ferdi/resources/app.asar/lib/Tray.js:1:692)
    at MenuItem.click (node:electron/js2c/browser_init:73:1908)
    at Object.a._executeCommand (node:electron/js2c/browser_init:81:2453)
TypeError: Cannot read properties of undefined (reading 'isMinimized')
    at click (/opt/ferdi/resources/app.asar/lib/Tray.js:1:692)
    at MenuItem.click (node:electron/js2c/browser_init:73:1908)
    at Object.a._executeCommand (node:electron/js2c/browser_init:81:2453)
```

**Comment by vraravam** [comment] 2021-11-11 01:04
Duplicate of #2147

**Closed by vraravam** 2021-11-11 01:04 UTC
