### ISSUE TITLE
Could not load services and user information

### ISSUE THREAD

**Issue by MichaelBui** [getferdi/ferdi#200] opened 2019-11-12 08:06 UTC
**Describe the bug**
I've got this issue for about an hour. It was intermittent but now it's totally off.
![image](https://user-images.githubusercontent.com/1146708/68653033-bf725b80-0565-11ea-8010-6b18a807eea7.png)

**To Reproduce**
Open Ferdi, this screen appear immediately

**Expected behavior**
Should ask for password (if any) then load added services

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Mac Catalina 10.15
- Browser [e.g. chrome, safari]: 
- Version [e.g. 22]: v5.4.0-beta.4

**Additional context**
I suspect that the Ferdi server was unstable/down. There isn't any "Available services" to be re-added. 
There should be cached data in local to prevent this issue. The app is totally useless now.

**Comment by Gaboris** [comment] 2019-11-12 08:11
Are you actually using the Ferdi servers?
Franz is bombarded with posts cuz their servers are down and people can't log in.

This is why it's a good thing to have an offline option.

**Comment by MichaelBui** [comment] 2019-11-12 08:14
@Gaboris What's different between Ferdi vs Franz server? I'm using default value but I see it is `https://api.franzinfra.com`. Which Ferdi service (if any) I should use?

**Comment by Gaboris** [comment] 2019-11-12 08:21
It's basically an "alternate" server server you can use, but it's mainly about the team trying to separate Ferdi from Franz. Sadly to use it you'll need to log into Franz first and then change the server before restarting Ferdi for it to initialize.

Here is the Ferdi server for when you get your stuff back: https://api.getferdi.com

Also the latest versions finally included the option to store your account data locally so no servers needed at all, but with that you won't be able to sync your data between devices and it still might be unstable at times so keep that in mind.

**Comment by grmon** [comment] 2019-11-12 08:27
Same issue with api.getferdi.com
- OS: [e.g. iOS] macOS 10.14.6

**Comment by Gaboris** [comment] 2019-11-12 08:35
Now that is odd. The Ferdi API page is running just fine.
Guess I got lucky that I logged in an hour earlier than normal?

**Comment by vantezzen** [comment] 2019-11-12 09:34
Just monitored the Ferdi API and everything seems to be running fine - @grmon could you try logging out and back in?

The original issue reported by @MichaelBui  seems to be with Franz's servers and not Ferdi or Ferdi's servers.

**Comment by grmon** [comment] 2019-11-12 10:48
That seems to have worked.

**Comment by keplerk** [comment] 2019-11-25 14:33
Still having that error, at least for me it keeps happening

![image](https://user-images.githubusercontent.com/4659797/69549066-2f1d1900-0f5e-11ea-9eb6-6b4d5734b595.png)

**Comment by Gaboris** [comment] 2019-11-25 14:47
Hey @keplerk

Have you tried logging out? That was my problem, I guess some kind of a token expired or whatever they need to keep connected.

**Comment by keplerk** [comment] 2019-11-25 14:50
> Hey @keplerk
> 
> Have you tried logging out? That was my problem, I guess some kind of a token expired or whatever they need to keep connected.

The problem is, im not even logged.

**Comment by Gaboris** [comment] 2019-11-25 14:53
But that's the weird part.

If I understood correctly you can't even get to that part without being logged in at least on the client side, but I guess you don't have a log out button at the bottom left of the settings menu then...

Darn, hope one of the devs has a better idea then.

**Comment by keplerk** [comment] 2019-11-25 14:56
You got it, i don't see any log in/log out button, i have to mention that I've never logged in, so i dunno why that strange behavior.

**Comment by Gaboris** [comment] 2019-11-25 15:00
Wait, you haven't even logged in?
So you were using Ferdi without an account already?
In that case I really have no idea what could be the solution...

**Comment by keplerk** [comment] 2019-11-25 15:02
> Wait, you haven't even logged in?
Yep, that's my case

**Comment by vantezzen** [comment] 2019-11-25 15:52
What do you see when you close the settings window (using the X in the top right corner)? Normally you should see a screen instructing you to log in to an account.

**Comment by keplerk** [comment] 2019-11-25 16:01
![image](https://user-images.githubusercontent.com/4659797/69556542-7c06ec80-0f6a-11ea-88db-8dad56eccb4d.png)

![image](https://user-images.githubusercontent.com/4659797/69556555-81fccd80-0f6a-11ea-81f7-047baa6d5c2a.png)

**Comment by vantezzen** [comment] 2019-11-25 16:02
Thank you. In the settings popup can you please log out using the "Logout" button in the button left?

**Comment by Gaboris** [comment] 2019-11-25 16:02
Dude!
I asked if you had a logout button at the bottom left of your settings or not. O_o

**Comment by vantezzen** [comment] 2019-11-25 16:04
@Gaboris I think not many people notice that there actually is a logout button in the settings, even if you can't access the "Account" screen (had a similar thing in another issue)

**Comment by keplerk** [comment] 2019-11-25 16:05
> Dude!
> I asked if you had a logout button at the bottom left of your settings or not. O_o

Didnt realize until i see it in detail, my eyes were focused on the red shinny error, sorry :(

@vantezzen Still the could not load services if i start without any account
![image](https://user-images.githubusercontent.com/4659797/69556867-2848d300-0f6b-11ea-94e2-d1837ecac073.png)

**Comment by vantezzen** [comment] 2019-11-25 16:08
It looks like you are using Windows so this issue might be related to #149 now. Would you be willing to log in using an account to see if at least that works?

**Comment by keplerk** [comment] 2019-11-25 17:06
I got it now abou the windows error, i unticked the read only mode and trying firstly to create an account but i cant, i got html as response for the register request

![image](https://user-images.githubusercontent.com/4659797/69561753-8b3e6800-0f73-11ea-9bfe-9c81e1f3f0e4.png)

**Comment by grmon** [comment] 2019-12-02 15:53
> That seems to have worked.

logged of and in again and ferdi is loading for half an hour.

**Comment by kytwb** [comment] 2019-12-19 12:43
Original issue was the Franz API being down. Then @keplerk issue was a mix of https://github.com/getferdi/ferdi/issues/253 and UX-related issues. Closing in favor of https://github.com/getferdi/ferdi/issues/253 and will keep working on enhancing the UX.

**Closed by kytwb** 2019-12-19 12:43 UTC
Labels: Franz server
