### ISSUE TITLE
'Find' within page content is disabled

### ISSUE THREAD

**Issue by vraravam** [getferdi/ferdi#215] opened 2019-11-19 03:37 UTC
**Is your feature request related to a problem? Please describe.**
In some pages/content of services configured in Ferdi, I sometimes like to use the 'Cmd+F' feature present in all browsers to be able to search within the page content. This doesn't seem to be possible in Ferdi (is it disabled from the base Electron/Chromium?)

**Describe the solution you'd like**
'Cmd+F' (or its equivalent in other OSes) should open a text box and allow me to search within the already-rendered page content.

**Describe alternatives you've considered**
Open the same url in my default browser. but this us cumbersome when the page is behind a login window - which forces me to login once again in the default browser.

**Additional context**

**Comment by vantezzen** [comment] 2019-11-19 07:13
Duplicate of #67

**Closed** 2019-11-19 07:13 UTC

**Comment by kytwb** [comment] 2020-03-12 08:05
Shipped in [v5.4.4-beta.3](https://github.com/getferdi/ferdi/releases/tag/v5.4.4-beta.3).
