### ISSUE TITLE
Restart and install button - not doing what I'm expecting

### ISSUE THREAD

**Issue by benja83** [getferdi/ferdi#2232] opened 2021-11-15 10:05 UTC
When I click on the Restart and install button, the app is closed and then nothing else happen.

![image](https://user-images.githubusercontent.com/7469433/141762458-2ad69cf0-0587-40ea-ba27-88593cd44570.png)

**Version data**
`
Version: 5.6.2
Electron: 13.3.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
Platform: macOS Monterey
Arch: x64
Build date: Mon Sep 13 2021 10:23:12 GMT+0200 (Central European Summer Time)
Git SHA: 40a3d0b
Git branch: release
`

I would expect to see the update starting and having some feedback regarding this process.

**Comment by vraravam** [comment] 2021-11-15 10:11
Duplicate of #329

**Closed by vraravam** 2021-11-15 10:11 UTC
