### ISSUE TITLE
App Update not working

### ISSUE THREAD

**Issue by Thane5** [getferdi/ferdi#2013] opened 2021-10-03 09:15 UTC
**Bug description:**
Ferdi is unable to update itself.
When i press "Search for Updates", the button says "updates available, downloading..." for about ten seconds, then returns to its default state and nothing happens. 
It makes no difference wether i have "include nightly versions" enabled or not.

The only way i can update is through downloading the official installer (which is very limiting because i am currently having this bug where Discord will only open all images in my brownser when i click on them)

**Steps to reproduce:**
"Click the "Search for Updates" button

1. Go to settings
2. Click on"Search for Updates" button
3. Wait a few seconds

**Screenshots**

https://user-images.githubusercontent.com/13683581/135747313-153daa3c-1b90-46a9-9167-e40021710e34.mp4

**Environment:**

- Operating System: Windows 11 21H2 (22000.194)
- Ferdi Version: 5.62
- Server: Ferdi

- Debug information:
[Ferdi_Debug.txt](https://github.com/getferdi/ferdi/files/7273036/Ferdi_Debug.txt)

**Comment by vraravam** [comment] 2021-10-03 10:15
Closing - duplicate of #329

**Closed by vraravam** 2021-10-03 10:15 UTC
