### ISSUE TITLE
Disable hibernation per service not persisting after restarting

### ISSUE THREAD

**Issue by cmdln** [getferdi/ferdi#943] opened 2020-09-03 13:59 UTC
**Bug description:**

I have service hibernation enabled. I edit a few services to disable hibernation. After I quit and start Ferdi again, the disable hibernate setting for those services is reset to hibernation enabled.

**Steps to reproduce:**

1. Go to File -> Settings
2. Click on Enable Service Hibernation
3. Right click a service in the side bar then click edit
4. Click on disable hibernation so the service does not hibernate.
5. Quit Ferdi
6. Restart Ferdi
7. Right click a service in the side bar then click edit
8. The disable service hibernation is back to off.

**Expected behavior**

I expected the disable hibernation setting for a service to persist when quitting and restarting the application.

**Environment:**

- Operating System: Linux, Pop_OS! 20.04
- Ferdi Version: 5.5.0 (x86)
- Server: Using without an account

- Debug information:

[debug-json.zip](https://github.com/getferdi/ferdi/files/5169085/debug-json.zip)

**Comment by djprmf** [comment] 2020-09-03 23:30
This also happends in the Windows version of the app

**Comment by kacboy** [comment] 2020-09-25 17:02
I'm also having this issue on my Windows 10 machine!

**Comment by vantezzen** [comment] 2020-10-04 12:38
Duplicate of #715. This is already fixed and will be rolled out in the next version of Ferdi.

I'll leave this open and pin so other people won't open new issues.

**Comment by vraravam** [comment] 2021-05-25 15:44
Closing since #715 has been fixed and closed.

**Closed by vraravam** 2021-05-25 15:44 UTC
Labels: bug
