### ISSUE TITLE
RocketChat - no icon or icon disappears in ferdi

### ISSUE THREAD

**Issue by donagrejja** [getferdi/ferdi#1052] opened 2020-11-02 11:07 UTC
**Bug description:**

RocketChat - no icon or icon disappears in ferdi

**Steps to reproduce:**

I just added RocketChat (my own server) and logged in.
And when I log in or after a while (different result every time) the Icon on the left side disappeares after a while.
Badges are still shown and popups works and I can still use RocketChat it's just that it's an empty space there instead of the RocketChat icon that should be there.

**Expected behavior**

**Screenshots**

**Environment:**

- Operating System: Windows 10
- Ferdi Version: 5.5.0
- Server: Ferdi

- Debug information:

**Comment by donagrejja** [comment] 2020-11-02 11:10
![Ferdi - RocketChat](https://user-images.githubusercontent.com/14802028/97861624-59499000-1d04-11eb-9705-bc19b745d060.png)

**Comment by Irthen** [comment] 2020-11-03 07:44
Same issue here, running latest version of Ferdi on macOS Catalina.

**Comment by LongJohn-Silver** [comment] 2020-11-08 20:03
Duplicate of #780.

**Comment by vantezzen** [comment] 2020-11-09 15:21
Thank you for reporting duplicated @LongJohn-Silver, it really helps keeping our issues clean!

**Closed by vantezzen** 2020-11-09 15:21 UTC
Labels: bug
