### ISSUE TITLE
Zombie processes

### ISSUE THREAD

**Issue by PhiCecHey** [getferdi/ferdi#1560] opened 2021-06-24 12:33 UTC
I have noticed that Ferdi produces between 10 and 20 zombie processes right after launching it and it only gets more. When closing Ferdi, they are all gone.

**Comment by kris7t** [comment] 2021-06-24 14:13
What version of Ferdi are you running? On which operating system?

**Comment by PhiCecHey** [comment] 2021-06-24 14:46
I am running the newest flatpak version available on Pop OS 20.10 which - if I'm not mistaken - is 5.5.0.

**Comment by vraravam** [comment] 2021-06-24 14:51
@PhiCecHey - could you please try with the latest nightlies that can be found [here](http://github.com/vraravam/nightlies/releases) - v5.5.0 is quite old - and we have made huge changes over the past couple of months. Though it says "nightlies", they are quite stable - and the contributors have been dog-fooding these builds for the past few weeks.

**Comment by PhiCecHey** [comment] 2021-06-24 15:05
Ok sure. Does that mean that one should always use the latest nightlies?

**Comment by vraravam** [comment] 2021-06-24 15:06
For now, yes. Once we are able to fix the broken signing process, and we successfully release 5.6.0, then we should be able to go back to the "norm" of GA releases, betas and nightlies.

**Comment by PhiCecHey** [comment] 2021-06-24 15:13
It seems that there are no more zombie processes. :D Thank you. Since I found Ferdi via the Pop Shop, maybe there is a way to put a notice there to use the latest nightlies?

**Comment by vraravam** [comment] 2021-06-24 15:32
Since I don't use PopOS - I'm not sure how I would go about doing that - could you please do it for us? Also, I'm closing this ticket - since the issue is now resolved.

**Closed by vraravam** 2021-06-24 15:32 UTC
Labels: feedback wanted
