### ISSUE TITLE
Searching for update feature does not seem to work

### ISSUE THREAD

**Issue by joshuak94** [getferdi/ferdi#851] opened 2020-06-27 09:56 UTC
**Bug description:** When I go into the settings into Updates, there is a button which is grayed out and says "Is searching for update". It never changes to an update found, even if there are newer versions. I have tried this on Ferdi 5.4.0 and Ferdi 5.5.0, both tested today 27 June 2020. Enable Updates and Include beta versions are both enabled.

With version 5.4.0 it should have at least found version 5.5.0, and with version 5.5.0 it should find the 5.6 beta.

Both versions were installed using the Ubuntu .deb file available on the getferdi website. I can also recreate this on my debian workstation which has it installed via the source package (tar.gz).

**Steps to reproduce:** Go to Settings -> Update (on version 5.5, on version 5.4 just scroll down). Observe the button never changing.

**Expected behavior:** After a few seconds, the button should change to "Update found, download" or something similar.

**Screenshots**

**Environment:**

- Operating System: Ubuntu 18.04.4 LTS
- Ferdi Version: 5.5.0
- Server: Franz

- Debug information: https://debug.getferdi.com/94753d3c-9018-4247-96df-fad9848f8a38

**Comment by martinszy** [comment] 2020-07-03 02:30
Can reproduce. Same thing happens to me. Ubuntu 20.04, installed via .deb.

**Comment by vantezzen** [comment] 2020-07-05 07:10
Duplicate of #329

**Closed by vantezzen** 2020-07-05 07:10 UTC
Labels: bug
