### ISSUE TITLE
Services don't stay logged in after restart.

### ISSUE THREAD

**Issue by djshadowxm82** [getferdi/ferdi#199] opened 2019-11-11 14:18 UTC
**Describe the bug**
It would appear that services do not persist any sessions or cookies after restart of Ferdi.

**To Reproduce**

1. Restart ferdi.
2. Open ferdi
3. Open service and have to login again

**Expected behavior**
Services should be honoring "Remember me" cookies and the like.

**Screenshots**

**Desktop (please complete the following information):**

- Ferdi Version : 5.4.0-beta.4 (x64)
- Electron: 6.0.10
- Node.js: v12.4.0
- Platform: win32

**Comment by vantezzen** [comment] 2019-11-11 14:37
Possible duplicate of #177?
Ferdi normally doesn't change the way Chromium handles cookies and thus they should behave like in any other browser.

**Comment by djshadowxm82** [comment] 2019-11-11 14:46
@vantezzen I did not have this issue with franz. Signing into facebook messenger and other services, it would persist my session (sometimes it would log me out presumably after a cookie or session timeout) however, this is every single time I reopen Ferdi and its super annoying to have to reauth for every single service every time you open it.

**Comment by vraravam** [comment] 2019-11-15 17:21
I see the same with an outlook email tab. Running the latest beta on mac OS Catalina.

**Comment by jandreaucodes** [comment] 2020-06-25 16:55
I just installed Ferdi today after giving up on Stack, Station, Franz and Rambox for all minor annoyances.

After quitting the app and restarting, I have to re-login to everything, which is kind of an annoyance. It sounds like that _shouldn't_ happen here, but it does seem to.

For what it's worth, I'm **not** using the Ferdi account. Perhaps the account is what stores the logged in session?

**Comment by andrsussa** [comment] 2020-07-14 10:06
I started using Ferdi recently and this is the only issue I have at the moment. Although, in my case, it does not log out of Outlook completely. It shows the outlook login screen after restart, and after entering my email address, it logs me in without even entering my password.

Also, I created a Ferdi account to see if that would fix it but the issue is still there.

**Comment by kelmee** [comment] 2020-08-14 19:11
I am also seeing this happen with protonmail accounts. Although it actually seems to be logging me out of protonmail accounts just whenever they go into hibernation?
Not yet sure if it is happening with other accounts.

**Comment by vraravam** [comment] 2020-10-14 02:17
ping to un-stale it

**Comment by internalkernel** [comment] 2020-10-29 14:48
Version: 5.6.0-beta2 (x64)
Electron: 8.2.3
Node.js: 12.13.0
Platform: linux

Seeing this behavior with Protonmail and a private Nextcloud instance (2FA enabled there). Accounts are logged out after restart, hibernation of services or suspend/resume of computer. Both accounts worked fine in Rambox / Franz.

**Comment by Shankar1598** [comment] 2020-11-21 17:52
Am having the same issue too. I use a lot of services with Ferdi and I have 2 step verification for my google accounts. Logging into everything will take 10 minutes!

**Comment by 85danf** [comment] 2021-01-31 08:45
Same here, using Ferdi 5.5.0 on mac os

**Comment by vraravam** [comment] 2021-08-23 16:23
I'm on the latest nightly - and I don't see this behavior. I have tested with ProtonMail that I had logged into quite a few weeks ago - with multiple restarts over the past timeframe as well.

**Closed** 2021-08-25 07:30 UTC
Labels: outstanding question
