### ISSUE TITLE
width of the services ribbon

### ISSUE THREAD

**Issue by vraravam** [getferdi/ferdi#207] opened 2019-11-14 17:47 UTC
**Describe the bug**
The vertical ribbon for the services seems to be unnecessarily wide. Please reduce the width. The service-icons can also be made a bit smaller for better real-estate use.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vantezzen** [comment] 2019-11-15 13:22
Possible duplicate of #153. 
I think the width and Icon Site is great as-is and don’t like the smaller ribbon in Station so this would need to be an optional setting.

**Closed** 2019-11-15 13:23 UTC
Labels: duplicate, enhancement
