### ISSUE TITLE
Enabling/disabling a service does not properly refresh the service container

### ISSUE THREAD

**Issue by webworker01** [getferdi/ferdi#116] opened 2019-10-12 20:09 UTC
**Describe the bug**
Enabling / Disabling a service does not properly refresh the Service container. 

**To Reproduce**
Right click on a disabled service and choose enable service. Service container continues to display "Service is disabled" message with "Enable Service" button until you click another service and come back, then the service is displayed correctly.

Right click on an enabled service and choose disable service. Service container continues to display the service and it continues to be active and maintains a connection to the service until you click another service and come back, then the service is actually disconnected from and the expected "Service is disabled" message with "Enable Service" button is shown.

**Expected behavior**
Enabling or disabling a service immediately disconnects the service and updates the service container state to what was chosen by the user.

**Desktop (please complete the following information):**

- OS: Win10
- Version 5.3.4-beta.6

**Comment by vantezzen** [comment] 2019-10-13 11:18
It looks like [the webview](https://github.com/getferdi/ferdi/blob/6ae97425b0c0da181a9ec26e52535ceadd1f4e46/src/components/services/content/ServiceView.js#L174) doesn't get rerendered when the service model is updated.

I had the same problem when trying to store the hibernation status in the Service model instead of the local state. I fixed this problem [by copying the changes to the local state](https://github.com/getferdi/ferdi/blob/6ae97425b0c0da181a9ec26e52535ceadd1f4e46/src/components/services/content/ServiceView.js#L93-L101) but this solution is [in no way recommended by MobX](https://mobx.js.org/best/pitfalls.html#dont-copy-observables-properties-and-store-them-locally) and we should look into finding the cause of the Component not updating rather than using the same hack for this problem.

By the way, if the reason you are disabling services is to improve performance, you can try the Service Hibernation feature, which will automatically disable and reenable services. You can enable Service Hibernation in Ferdi's settings.

**Comment by kytwb** [comment] 2019-10-18 04:51
In dev mode I see the following warning quite often:

```
Mobx observer: You are trying to use 'observer' on a component that already has 'inject'. Please apply 'observer' before applying 'inject
```

Fixing the warning seem to fix the issue (something related to the observer I guess).

**Comment by vantezzen** [comment] 2019-10-18 07:08
So can we close this issue?

**Comment by kytwb** [comment] 2019-10-18 10:09
Fix will be available in the next release, yes! 🙏

**Closed by kytwb** 2019-10-18 10:09 UTC
Labels: bug
