### ISSUE TITLE
Teams not load

### ISSUE THREAD

**Issue by thomas-sanceo-needone** [getferdi/ferdi#1260] opened 2021-03-31 07:32 UTC
**Bug description:**
When I try to open ferdi for the second time with my service teams to configure. Teams can't load.

**Steps to reproduce:**

1. Configure your workspace
2. Close Ferdi
3. Open Ferdi
4. Teams not load

**Screenshots**
![image](https://user-images.githubusercontent.com/65956649/113107121-d588c680-9203-11eb-8376-c381cdbd8001.png)

**Environment:**

- Operating System: MacOS Big sur 11.1
- Ferdi Version: 5.5.0

**Comment by emzy07** [comment] 2021-04-09 13:50
Same issue for me but its white did you enable darkmode ?

**Comment by thomas-sanceo-needone** [comment] 2021-04-09 13:51
Yes I am in darkmode

**Comment by doverton12** [comment] 2021-04-10 00:26
I'm seeing the same, or I eventually get an Oops error:
![image](https://user-images.githubusercontent.com/50138871/114252143-b6283100-999b-11eb-8b1d-6d712fa302ea.png)

**Comment by mastercko** [comment] 2021-04-14 22:14
I'm having the same problem (on Windows 10). So now I have a dilemma.

In 5.5.0, Teams doesn't work. In 5.6.0, Android Messages doesn't work.

**Comment by vedagel** [comment] 2021-04-20 06:43
Same here on MacOS Big Sur and Ferdi Version 5.5.0 (5.5.0.2116).

**Comment by Coderdude112** [comment] 2021-05-01 02:38
Same issue.
Ive found that it may have something to do with cookies?
I can wait for ~5-10 min and get the we couldn't log you in message, and log in again. If I choose to stay signed in, it has a problem either right then or late, so I've resorted to just saying no literally every single time.

How does Ferdi handle cookies and things stored by an app?

**Comment by vraravam** [comment] 2021-05-14 10:51
@thomas-sanceo-needone @emzy07 @doverton12 @mastercko @vedagel @Coderdude112 : Thanks for trying out Ferdi!

I would suggest all of you to go to the [latest nightly release](https://github.com/getferdi/nightlies/releases). If you are on macos, I have built from source and uploaded the latest (as of this moment) to [this gDrive folder](https://drive.google.com/drive/folders/1mJmKbhpVHdb066IHlrdYiD8TG9wlmuBv).

Once you do that, please follow the upgrade process for recipes as described [here](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help).

Remember that you have to close/quit Ferdi before attempting the swaps of the recipes.

Please report back as to whether the above steps worked. We can try to solve farther if its still not working.

**Comment by fuzzy76** [comment] 2021-06-15 12:30
Any chance this is a duplicate of #475 ?

**Comment by vraravam** [comment] 2021-06-15 12:55
YEs - looks like a duplicate. Can we close this please?

**Comment by vedagel** [comment] 2021-06-20 21:09
Hi @vraravam thank you, this worked!

**Comment by vraravam** [comment] 2021-06-20 23:16
Closing since the issue seems to be fixed in the latest nightlies.

**Closed by vraravam** 2021-06-20 23:16 UTC
Labels: question, service-specific
