### ISSUE TITLE
Add Signal

### ISSUE THREAD

**Issue by Prajwal-Koirala** [getferdi/ferdi#444] opened 2020-03-06 17:45 UTC
Hello,
Can we please add signal.
https://signal.org/
- prajwal

**Comment by vantezzen** [comment] 2020-03-06 20:10
Duplicate of:
getferdi/ferdi#342
getferdi/recipes#26
getferdi/recipes#22
getferdi/recipes#21
getferdi/recipes#18
meetfranz/franz#1702
meetfranz/franz#767
meetfranz/franz#655

Signal cannot be added as it does not have a web client.

**Closed by vantezzen** 2020-03-06 20:10 UTC
