### ISSUE TITLE
Tray icon disappears

### ISSUE THREAD

**Issue by prvn-pa** [getferdi/ferdi#761] opened 2020-05-21 10:19 UTC
**Bug description:**
If we enable tray icon in Gnome DM (usually it is default), after few minutes the icon disappears. This happened in Ubuntu 20.04, Pop_Os 20.04 and Manjaro Linux 20. All with recent Ferdi update. I observed similar issue (but not as much frequent ) in latest Franz.

**Steps to reproduce:**

1. Open Ferdi app
2. In setting "Enable tray icon"
3. Tray icon will appear on the top bar
4. After few minutes that will diappear
5. Other tray icons will work normally
6. Usually it is possible to receive notifications 

**Environment:**

- Operating System: Ubuntu 20.04, Pop OS 20.04, Manjaro 20
- Ferdi Version: 5.5.0
- Server: On all. Ferdi, Franz and Without an account
![Screenshot from 2020-05-21 15-46-11](https://user-images.githubusercontent.com/55174721/82549522-ada7eb80-9b7a-11ea-9164-665e265252ed.png)

**Comment by kytwb** [comment] 2020-05-21 11:40
Thank you for the detailed report! 🙏 
This seems to be a duplicate of https://github.com/getferdi/ferdi/issues/437; a fix should be available in the latest nightly - please see https://github.com/getferdi/ferdi/issues/437#issuecomment-629823664.

**Closed by kytwb** 2020-05-21 11:40 UTC
