### ISSUE TITLE
Whatsapp (beta version) not connecting (falsely reports "no Internet")

### ISSUE THREAD

**Issue by LikDev-256** [getferdi/ferdi#2163] opened 2021-10-29 14:23 UTC
I was using ferdi for about a week now whenever I restart ferdi I have to Logout and Log back in but if someone doesn't know this Whatsapp released a new feature that allows you to connect to WhatsApp web without your phone.

So the problem is there is no use of the feature when I'm using it in ferdi because I have to re-login every time I restart.
Even though I have a stable Internet connection I always get this,

![Screenshot_2021-10-29_18:44:50](https://user-images.githubusercontent.com/81100289/139450075-81eedd8f-1ec1-4bcb-8c34-96df6d9ad944.png)

If I Logout and log in it works.

OS :- Manjaro
Installtion method :- yay package manager

**Comment by vraravam** [comment] 2021-10-30 01:48
I just signed up for the beta. Will test this out and report back on the behavior that I see.

**Comment by LikDev-256** [comment] 2021-10-30 02:40
And another thing I want to point out but irrelevant to this is that even though the app uses cache like 300+mbs it reloads the services every time I wake it up. I have turned on hibernation so I thought that this feature will unload the site to the disk cache and reload it from the disk . Is this the use of the caching feature or am I wrong.

**Comment by vraravam** [comment] 2021-10-30 07:30
The Whatsapp beta is definitely a bug, but at the same time, I am not suer we can support beta applications.

**Comment by Velocet** [comment] 2021-11-02 13:39
Duplicate of #1745

**Closed** 2021-11-02 23:53 UTC
