### ISSUE TITLE
App unusable without account on Windows since v5.4.0

### ISSUE THREAD

**Issue by webbad** [getferdi/ferdi#253] opened 2019-12-09 16:59 UTC
hi, it seem a good app. 
but i have a big problem, i can't do anything on it. i can't create a new account, i can't add new apps or workplace..... i can only change the settings. (v. 5.4 stable)

ps. the webpage link for the windows version didn't work when i discovered your app.

**Comment by vantezzen** [comment] 2019-12-11 11:04
Do you get any error messages? What server are you using? 
What do you mean with "I can't create a new account"? Can't you get to the register screen? Have you tried using Ferdi without an account?

**Comment by webbad** [comment] 2019-12-11 12:04
i don't get any error messages
I have tried both franz and your server
I have tried both with and without an account
in practice it's like the buttons did not work. for example I go on create new workspace, insert a name and click on create, the button makes the animation but does not create anything. the same thing happens to add an app, create an account etc ...
I have tried to run as administrator or not and both the setup.exe or the "portable" version.

**Comment by Cantello** [comment] 2019-12-11 14:03
Same here, the 'Save Service' button just flickers for a short moment and then nothing happens. Is there a log I could provide to add some insight?

![ferdi_adding_services](https://user-images.githubusercontent.com/594700/70627943-6e6a8b80-1c27-11ea-9755-13dcb8327b59.gif)

**Comment by webbad** [comment] 2019-12-11 16:10
> Same here, the 'Save Service' button just flickers for a short moment and then nothing happens. Is there a log I could provide to add some insight? I am using Ferdi 5.4.0 on Windows10, new installation without connecting to any server, just trying to add services.
> 
> ![ferdi_adding_services](https://user-images.githubusercontent.com/594700/70627943-6e6a8b80-1c27-11ea-9755-13dcb8327b59.gif)

yes, that's the problem. only the settings works for me

**Comment by Bluetexon** [comment] 2019-12-11 20:49
I sadly have the same problem. Downgrading to an old version seems to work for me.

**Comment by FWDekker** [comment] 2019-12-12 08:41
For me v5.4.0 works fine on Linux (Ubuntu 18.04), but I can confirm that this issue occurs with both v5.4.0 and v5.3.2 on Windows 10.

@Bluetexon Which version did you downgrade to? v5.3.2 doesn't seem to work for me either.

**Comment by Bluetexon** [comment] 2019-12-12 08:44
I've downgraded to version  5.3.3. It had some other issues, like not being able to do some requests, but I think that was due to me being kinda logged in (I was logged in, but it didn't display my name and some other weird things). After I logged out, logged in again and restarted Ferdi, I was able to use it.

**Comment by Cantello** [comment] 2019-12-13 11:15
Downgrading does not work for me either. I tried 5.3.0, 5.3.1, 5.3.2 & 5.3.3. All apart from 5.4.0 cannot even load the services. Logging out and creating an account did not work (the "Create" button did not do anything).
Franz is already installed on my computer, might this affect the issue?

**Comment by webbad** [comment] 2019-12-13 17:41
@Cantello i don't have and never had franz on my pc

**Comment by AGCaesar** [comment] 2019-12-14 13:04
Just wanted to install on a Windows machine, had the same problem, I can not add services. Neither franz nor ferdi were installed before.

**Comment by Cantello** [comment] 2019-12-17 13:52
Works now for me. Uninstalled & re-installed Franz & Ferdi (5.3.2) and now even 5.4.0 works flawlessly (apart from the discord tab locking the whole app from time to time).

**Comment by webbad** [comment] 2019-12-17 14:09
@Cantello something changed? is the app or windows updated ?

**Comment by Cantello** [comment] 2019-12-17 14:10
The app (Ferdi) was automatically updated to 5.4.0 once I added the services in 5.3.2, Windows has not been updated (but has since then).

**Comment by webbad** [comment] 2019-12-17 14:52
i had hope, but nothin. still not work for me even trimng to update from and older version.

**Comment by queicherius** [comment] 2019-12-17 21:29
When looking into the developer tools I get a 500 to `http://127.0.0.1:45569/v1/service` with `SQLITE_READONLY: attempt to write a readonly database`

**Comment by kytwb** [comment] 2019-12-18 17:51
This is a Windows-only issue due to file permissions issues. Will investigate.

**Comment by webbad** [comment] 2019-12-24 17:39
the v. 5.4.1 the new beta 3 fix the problem??

**Comment by kytwb** [comment] 2019-12-24 17:40
Not yet, I will try to address getferdi/internal-server#2 for the next release.

**Comment by webbad** [comment] 2019-12-24 18:46
ok thank you

**Comment by juanjotoronja** [comment] 2019-12-31 20:49
This method worked for me:

Uninstalled version 5.4.0 and installed 5.3.3 and it let me create an account and login, then after update was autmomatically downloaded by the app everything is working as it should.

**Comment by webbad** [comment] 2020-01-15 13:41
> This method worked for me:
> 
> Uninstalled version 5.4.0 and installed 5.3.3 and it let me create an account and login, then after update was autmomatically downloaded by the app everything is working as it should.

for me don't work that method, maybe there are some files from the 5.4.0

**Comment by VictorHaine** [comment] 2020-01-23 20:42
With logged in accounts its working. It's only without accounts that the error occurs...

**Comment by graphixillusion** [comment] 2020-02-13 22:22
I confirm this issue: 5.4.3 version here, without accounts, and i have the same exact issue: can't do anything, can't save anything.

**Comment by luckydonald** [comment] 2020-02-20 20:49
See the workaround to use it without an account in https://github.com/getferdi/ferdi/issues/381#issuecomment-586686684 with `5.4.4-beta1`.

**Comment by mudnug** [comment] 2020-02-21 19:04
You may want to update your website (remove the download for windows button or link to an older release) until this issue is fixed. As it stands, I downloaded the app and had to sort through three issues to figure out what is going on ... and that isn't likely something most new users will want to do.

I've not yet gotten a working Ferdi as now I have to go track down the beta release and try it.

Just saying you could improve the user experience with some messaging on your website since the issue has been present for months...

**Comment by vantezzen** [comment] 2020-02-21 19:12
@kytwb What do you think about switching the windows download link to 5.3.3 on the website as suggested by @mudnug (leaving the other OSes at the 5.4.0)? I think this would be a good solution until we fixed this problem.

**Comment by kytwb** [comment] 2020-02-21 21:16
@vantezzen I agree! 👍 Thanks for the suggestion @mudnug!

**Comment by luckydonald** [comment] 2020-02-21 22:45
@mudnug In case you still need it, the beta release can be fund in the [release section](https://github.com/getferdi/ferdi/releases), and the direct link to [v5.4.4-beta.1](https://github.com/getferdi/ferdi/releases/tag/v5.4.4-beta.1).

**Comment by luckydonald** [comment] 2020-02-21 22:46
Why exactly did it stop working tough? What changed?

**Comment by kytwb** [comment] 2020-02-22 02:26
@luckydonald A couple of file permissions issues on Windows afaik.

**Comment by vantezzen** [comment] 2020-02-23 11:26
I now added an additional `chmod` to the copy script - maybe that will help.

https://github.com/getferdi/internal-server/blob/3ad266e1371075612ce866332472595bfd89a5d6/start.js#L37-L38

**Comment by thekiefs** [comment] 2020-03-19 21:51
Any way to test this while we wait for the official release? chmod 666 in Windows, which file?

**Comment by kytwb** [comment] 2020-03-26 02:04
@vantezzen tested following completion of https://github.com/getferdi/ferdi/issues/415, seems to be working:

<img width="1150" alt="Screen Shot 2020-03-26 at 3 04 13 AM" src="https://user-images.githubusercontent.com/412895/77602740-8207dc80-6f0e-11ea-94e8-f5b677c8e565.png">

**Comment by kytwb** [comment] 2020-03-27 23:40
This should have been fixed in [v5.4.4-beta.2](https://github.com/getferdi/ferdi/releases/tag/v5.4.4-beta.2) if I'm not mistaken, by the fix mentioned earlier by @vantezeen in https://github.com/getferdi/ferdi/issues/253#issuecomment-590058648.

**Closed by kytwb** 2020-03-27 23:40 UTC
Labels: bug, platform-specific
