### ISSUE TITLE
Navigator bar does not update address

### ISSUE THREAD

**Issue by leandrogehlen** [getferdi/ferdi#1740] opened 2021-08-04 14:12 UTC
**Bug description:**

The navigator bar does not update address

**Steps to reproduce:**

https://user-images.githubusercontent.com/1750751/128195974-cf82ba36-2b96-46fb-bc3d-5b043de5312b.mp4

**Expected behavior**
Update address on navigation links

**Environment:**

Version: 5.6.0-nightly.14 (x64)
Electron: 9.4.0
Node.js: v12.14.1
Platform: win32

**Comment by vraravam** [comment] 2021-08-04 14:21
Duplicate of #1147 . Lets have any new discussion in the original please. Closing.

**Closed by vraravam** 2021-08-04 14:21 UTC
