### ISSUE TITLE
App completly locks when I enable with password lock

### ISSUE THREAD

**Issue by Eris7090** [getferdi/ferdi#813] opened 2020-06-11 13:17 UTC
**Bug description:**

App just shows a purple screen when started since I enabled password lock, I can't disable password lock now
**Steps to reproduce:**

use without an account -> settings -> enable password lock -> reload -> profit

**Expected behavior**

I thought it would prompt for a password to use but instead it told me to reload and I'm like "ok it'll prompt when it reloads" but it didn't

**Screenshots**

![Screenshot_20200611_091432](https://user-images.githubusercontent.com/43220038/84389440-068c0200-abc4-11ea-9b56-94bfc53c4141.png)
**Environment:**

- Operating System: Manjaro Linux KDE
- Ferdi Version: 5.5.0-6
- Server: using without an account

- Debug information:

yeah I don't see "Copy/Publish Debug Information" or anything similar in the help menu

**Comment by lithiil** [comment] 2020-06-11 23:42
Exact same issue on Win10. I even uninstalled it and reinstalled but I think that it cached the settings and got the same exact problem right away.

**Comment by vantezzen** [comment] 2020-06-13 08:45
Thank you for reporting this bug. This is a duplicate of #750

**Closed by vantezzen** 2020-06-13 08:45 UTC
Labels: bug
