### ISSUE TITLE
Messenger videocalling/calling not working

### ISSUE THREAD

**Issue by obvionaoe** [getferdi/ferdi#714] opened 2020-05-04 22:44 UTC
**Describe the bug**
Videocalling/calling in FB Messenger is broken. If you get a call it doesn't even display, and if you try to start a videocall or a normal call nothing happens either.

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to a Messenger conversation
2. Click on the camera button in the top right corner
4. See that nothing happens

**Expected behavior**
A call should start

**Desktop:**

- OS: Manjaro Linux
- Ferdi Version 5.5.0
- Server Used: https://api.getferdi.com

**Comment by vantezzen** [comment] 2020-05-09 16:29
Duplicate of #373

**Closed by vantezzen** 2020-05-09 16:29 UTC
