### ISSUE TITLE
Can't get app to run in development mode - SIGSEGV

### ISSUE THREAD

**Issue by abdamin** [getferdi/ferdi#1237] opened 2021-03-13 07:27 UTC
**Bug description:**
I have trying to setup my development environment and the app crashes after `electron ./build`.

**Steps to reproduce:**
```
$ git clone https://github.com/getferdi/ferdi.git
$ cd ferdi
$ git submodule update --init --recursive
$ npx lerna bootstrap
$ npm run rebuild
$ cd recipes
$ npm install && npm run package
$ cd ..
$ DEBUG=Ferdi:* npx misty
```

**Expected behavior**
App should run in development mode.

**Example Output**

```
[app] <--- Last few GCs --->
[app] 
[app] [60320:0x3d1c00000000]     2774 ms: Scavenge 205.9 (225.4) -> 205.9 (225.4) MB, 35.2 / 0.0 ms  (average mu = 0.999, current mu = 0.999) allocation failure 
[app] [60320:0x3d1c00000000]     3440 ms: Scavenge 333.9 (353.4) -> 333.9 (353.4) MB, 60.5 / 0.0 ms  (average mu = 0.999, current mu = 0.999) allocation failure 
[app] 
[app] 
[app] <--- JS stacktrace --->
[app] 
[app] /Users/ab/ferdi/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron exited with signal SIGSEGV
[app] npm ERR! code ELIFECYCLE
[app] npm ERR! errno 1
[app] npm ERR! ferdi@5.6.0-nightly.14 start: `electron ./build`
[app] npm ERR! Exit status 1
[app] npm ERR! 
[app] npm ERR! Failed at the ferdi@5.6.0-nightly.14 start script.
[app] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Environment:**

- Operating System: macOS Big Sur 11.2.3
- Ferdi Version: v5.6.0
- Node 12.21.0
- npm v6.14.11

**Comment by abdamin** [comment] 2021-03-13 19:34
After clearing all caches in my machine the error output has changed:

```
[code] 
[code] > ferdi@5.6.0-nightly.14 dev /Users/ab/ferdi
[code] > cross-env NODE_ENV=development gulp dev
[code] 
[code] [11:31:17] Requiring external module @babel/register
[code] [11:31:23] Using gulpfile ~/ferdi/gulpfile.babel.js
[code] [11:31:23] Starting 'dev'...
[code] [11:31:23] Starting 'clean'...
[code] [11:31:23] Finished 'clean' after 175 ms
[code] [11:31:23] Starting 'mvSrc'...
[code] [11:31:23] Starting 'mvPackageJson'...
[code] [11:31:23] Starting 'mvLernaPackages'...
[code] [11:31:23] Finished 'mvPackageJson' after 132 ms
[code] [11:31:24] Finished 'mvLernaPackages' after 390 ms
[code] [11:31:24] Finished 'mvSrc' after 488 ms
[code] [11:31:24] Starting 'html'...
[11:31:24] Starting 'scripts'...
[code] [11:31:24] Starting 'styles'...
[code] [11:31:24] Starting 'verticalStyle'...
[code] [11:31:24] Starting 'recipes'...
[code] [11:31:24] Starting 'recipeInfo'...
[code] [11:31:24] Finished 'verticalStyle' after 146 ms
[code] [11:31:24] Finished 'html' after 197 ms
[code] [11:31:24] Finished 'recipeInfo' after 291 ms
[code] [11:31:25] Finished 'styles' after 989 ms
[code] [11:31:27] Finished 'recipes' after 3.15 s
[code] [11:31:29] Finished 'scripts' after 4.82 s
[code] [11:31:29] Starting 'webserver'...
[code] [11:31:29] Starting 'watch'...
[code] [11:31:29] Webserver started at http://localhost:8000
[app] 
[app] > ferdi@5.6.0-nightly.14 prestart /Users/abdullahsumsum/ferdi
[app] > npm run rebuild
[app] 
[app] 
[app] > ferdi@5.6.0-nightly.14 rebuild /Users/ab/ferdi
[app] > npx electron-rebuild
[app] 
[app] - Searching dependency tree
[app] ✔ Rebuild Complete
[app] 
[app] > ferdi@5.6.0-nightly.14 start /Users/ab/ferdi
[app] > electron ./build
[app] 
[app] 2021-03-13T19:31:37.690Z Ferdi:App Set userAgent to  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_16_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
[app] 2021-03-13T19:31:37.691Z Ferdi:App Set userAgent to  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_16_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
[app] 2021-03-13T19:31:37.696Z Ferdi:Settings Hydrate store app {
[app]   autoLaunchInBackground: false,
[app]   runInBackground: true,
[app]   reloadAfterResume: true,
[app]   enableSystemTray: true,
[app]   startMinimized: false,
[app]   minimizeToSystemTray: '',
[app]   closeToSystemTray: false,
[app]   privateNotifications: false,
[app]   notifyTaskBarOnMessage: false,
[app]   showDisabledServices: true,
[app]   showMessageBadgeWhenMuted: true,
[app]   showDragArea: false,
[app]   enableSpellchecking: '',
[app]   spellcheckerLanguage: 'en-us',
[app]   darkMode: false,
[app]   locale: 'en-US',
[app]   fallbackLocale: 'en-US',
[app]   beta: false,
[app]   isAppMuted: false,
[app]   enableGPUAcceleration: '',
[app]   serviceLimit: 5,
[app]   server: 'You are using Ferdi without a server',
[app]   predefinedTodoServer: 'https://app.franztodos.com',
[app]   autohideMenuBar: false,
[app]   lockingFeatureEnabled: false,
[app]   locked: false,
[app]   lockedPassword: '',
[app]   useTouchIdToUnlock: true,
[app]   scheduledDNDEnabled: false,
[app]   scheduledDNDStart: '17:00',
[app]   scheduledDNDEnd: '09:00',
[app]   hibernate: false,
[app]   hibernateOnStartup: true,
[app]   hibernationStrategy: 300,
[app]   inactivityLock: 0,
[app]   automaticUpdates: true,
[app]   showServiceNavigationBar: false,
[app]   universalDarkMode: true,
[app]   adaptableDarkMode: false,
[app]   accentColor: '#7367f0',
[app]   serviceRibbonWidth: 68,
[app]   iconSize: 20,
[app]   sentry: false,
[app]   nightly: false,
[app]   navigationBarBehaviour: 'never',
[app]   useVerticalStyle: false,
[app]   alwaysShowWorkspaces: false,
[app]   todoServer: 'isUsingCustomTodoService',
[app]   customTodoServer: ''
[app] }
[app] 2021-03-13T19:31:37.699Z Ferdi:Settings Hydrate store proxy {
[app]   '9e112e64-ad14-471d-89e3-b24a4042e623': { isEnabled: false, host: '', port: '', user: '', password: '' },
[app]   'a71fceec-2f14-4f92-8d89-1072e37101e4': { isEnabled: false, host: '', port: '', user: '', password: '' },
[app]   '98904a10-d19e-484d-bf1c-2cb3e4e70f3b': { isEnabled: false, host: '', port: '', user: '', password: '' }
[app] }
[app] 2021-03-13T19:31:37.703Z Ferdi:App Disable GPU Acceleration
[app] 2021-03-13T19:31:37.778Z Ferdi:App Window is out of screen bounds, resetting window
[app] /Users/ab/ferdi/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron exited with signal SIGABRT
[app] npm ERR! code ELIFECYCLE
[app] npm ERR! errno 1
[app] npm ERR! ferdi@5.6.0-nightly.14 start: `electron ./build`
[app] npm ERR! Exit status 1
[app] npm ERR! 
[app] npm ERR! Failed at the ferdi@5.6.0-nightly.14 start script.
[app] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by vraravam** [comment] 2021-05-22 09:15
Please try with the latest code - I am also on Big Sur 11.4 and 11.5 beta - and with the latest code which locks the versions of `node`, `npm` and `node-gyp`, the app is running in dev mode. I still don't have `misty` working properly (seems to hang), but the 2-terminal commands seem to work just fine.

**Comment by vraravam** [comment] 2021-07-28 15:16
Closing this ticket since I am unable to reproduce the issue - I have been developing on the same Ferdi codebase for the past few months on a mac without any issues. (misty issue has also been fixed).

**Closed by vraravam** 2021-07-28 15:16 UTC
Labels: feedback wanted
