### ISSUE TITLE
Ferdi does not load

### ISSUE THREAD

**Issue by dimitar-ebot7** [getferdi/ferdi#708] opened 2020-05-04 07:43 UTC
**Describe the bug**
When I try to start the app, the window opens up and I can see the menu bar but that is as far as it goes. It doesn't load any services and is practically unusable.
**Deleting `~/.config/Ferdi` seems to have fixed the issue. All setting fell back to the default ones.**
**UPDATE: It seems to be related to having password lock turned on. As soon as I set it on I got an error saying something like: `Unexpected Error` and the app screen went blank and then I was back at square one**

**To Reproduce**

1. Start Ferdi
1. Open settings
1. Set passcode lock to on
1. Observe an `Unexpected error` show up
1. Observe app window going blank
1. After restart of the app, open up developer tools and observe the errors from the screen shot bellow

**Expected behavior**
Ferdi loads all services and is usable

**Screenshots**
**Blank window after start**
![image](https://user-images.githubusercontent.com/52074229/80945155-794ad600-8deb-11ea-811d-0ee9dcc9a1fa.png)

**Errors in the console**
![image](https://user-images.githubusercontent.com/52074229/80944170-2f60f080-8de9-11ea-99cc-d07e2bbf34fd.png)
![image](https://user-images.githubusercontent.com/52074229/80944219-4dc6ec00-8de9-11ea-9c4e-f597c6c8810d.png)
![image](https://user-images.githubusercontent.com/52074229/80944264-659e7000-8de9-11ea-85ed-10923abb6a3b.png)

**Desktop:**

- OS: Linux Manjaro (Kernel: 5.6.7-1-MANJARO)
- Ferdi Version:  5.5.0-2 (got it from my package manager)
- Server Used: Using the default server. I cannot see it because app doesn't load.

Debug information: There is no such option in the help menu. I am guessing this is because of the app not being able to load

**Additional context**
- I tried removing and re-installing the app but that didn't help
- I have an account with Ferdi to sync services
- I have password lock and auto lock in Ferdi turned on.
 - When I try to run Ferdi from the terminal, I get the following error:
`(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397`. I am guessing it's just a warning though.

**Comment by halcyon101** [comment] 2020-05-04 13:31
I have same issue

**Comment by keunes** [comment] 2020-05-07 15:55
Might be the same as #543. I had no Ferdi account (local server) and password lock enabled. Changing the setting to false as per https://github.com/getferdi/ferdi/issues/543#issuecomment-620490377 did the trick for me - I could enter again.

**Comment by kytwb** [comment] 2020-05-13 01:07
As @keunes mentioned, this seems to be a duplicate of #543. I recommend following the discussion and associated pull requests there 🙏 Thank you everyone!

**Closed** 2020-05-13 01:08 UTC
Labels: duplicate
