### ISSUE TITLE
Ferdi creates an abandoned empty tray icon

### ISSUE THREAD

**Issue by ShrirajHegde** [getferdi/ferdi#1993] opened 2021-09-26 15:24 UTC
**Bug description:**

Ferdi creates an abandoned empty tray icon. It is displayed with 3 dots and and empty inside.

Screenshot: 
![image](https://user-images.githubusercontent.com/66936172/134813695-b49adf21-b363-4ac5-a1a3-d74254c66fe6.png)
The left one is the functional, and the right one is the abandoned (sometimes not responsive, sometimes empty)

This doesn't happen immediately, Happens eventually 

DE: Gnome 40
Extension for tray icons: https://extensions.gnome.org/extension/615/appindicator-support/

**Steps to reproduce:**

1. Open ferdi
2.  Wait for sometime (normal usage)
3. An empty systray icon is created (it gets cleared on quitting Ferdi or restarting gnome)

**Expected behavior**

Single icon on the tray.

**Screenshots**

![image](https://user-images.githubusercontent.com/66936172/134813695-b49adf21-b363-4ac5-a1a3-d74254c66fe6.png)

**Environment:**
Fedora 34
- Operating System: Fedora 34 (GNU/Linux)Fedora 34
- Ferdi Version:5.6.2 
- Server: Using without an account 

- Debug information:

```json
{"host":{"platform":"linux","release":"5.13.19-200.fc34.x86_64","screens":[{"id":3850489720471618,"bounds":{"x":0,"y":0,"width":1536,"height":864},"workArea":{"x":0,"y":22,"width":1536,"height":804},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries_d50_referred: [[0.6850, 0.3095],  [0.2865, 0.6619],  [0.1564, 0.0717]], transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1536,"height":864},"displayFrequency":120,"workAreaSize":{"width":1536,"height":804},"scaleFactor":1.25,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.6.2","electron":"13.3.0","installedRecipes":[{"id":"TickTick","version":"1.2.0"},{"id":"android-messages","version":"2.2.1"},{"id":"franz-custom-website","version":"1.1.0"},{"id":"github","version":"2.0.0"},{"id":"hangouts","version":"1.2.0"},{"id":"hangoutschat","version":"1.5.0"},{"id":"tweetdeck","version":"1.0.2"},{"id":"whatsapp","version":"3.3.2"},{"id":"spotify","version":"1.0.0"}],"devRecipes":[{"id":"spotify","version":"1.0.0"}],"services":[{"id":"2a16b319-e7c6-4eba-9cb8-fa2b8aad45e2","recipe":"whatsapp","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"fa9ab011-88a7-4f02-ab67-70050bb295df","recipe":"hangouts","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"a3b2cfb0-129b-495b-a68f-51df0fa52082","recipe":"hangoutschat","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"28c1a76f-36e1-4f06-a1d9-56c27f404938","recipe":"TickTick","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"fbf913ba-8281-4ba6-a920-418184850039","recipe":"spotify","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"2b5f9546-df01-4ec9-9195-c9caeb1175bb","recipe":"android-messages","isAttached":false,"isActive":false,"isEnabled":true,"isHibernating":true,"hasCrashed":false,"isDarkModeEnabled":true}],"messages":[{"type":"error","info":["error","Warning: Failed prop type: Invalid prop `actions.service` of type `Object` supplied to `_class2`, expected instance of `_class`.\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","info":["error","Warning: Failed prop type: Invalid prop `actions.settings` of type `Object` supplied to `_class2`, expected instance of `_class`.\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in ThemeProvider (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router (created by _class)\n    in _class (created by inject-_class-with-stores-actions)\n    in inject-_class-with-stores-actions\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"You are using Ferdi without a server"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"You are using Ferdi without a server"}],"workspaces":[],"windowSettings":{"width":1200,"height":692,"x":136,"y":92,"displayBounds":{"x":0,"y":0,"width":1536,"height":864},"isMaximized":false,"isFullScreen":false},"settings":{"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":true,"confirmOnQuit":false,"minimizeToSystemTray":false,"closeToSystemTray":false,"privateNotifications":false,"clipboardNotifications":true,"notifyTaskBarOnMessage":false,"showDisabledServices":true,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"en-us","darkMode":true,"locale":"en-US","fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":true,"server":"You are using Ferdi without a server","predefinedTodoServer":"https://app.franztodos.com","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernateOnStartup":true,"hibernationStrategy":300,"wakeUpStrategy":300,"inactivityLock":0,"automaticUpdates":true,"showServiceNavigationBar":false,"universalDarkMode":true,"userAgentPref":"","adaptableDarkMode":true,"accentColor":"#7367f0","serviceRibbonWidth":68,"iconSize":20,"sentry":false,"nightly":false,"navigationBarBehaviour":"never","searchEngine":"duckDuckGo","useVerticalStyle":false,"alwaysShowWorkspaces":false,"liftSingleInstanceLock":false,"serviceLimit":5,"hibernate":false,"todoServer":"isUsingCustomTodoService","customTodoServer":""},"features":{"isServiceProxyEnabled":true,"isWorkspaceEnabled":true,"isTodosEnabled":true,"isSettingsWSEnabled":false},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}
```

**Comment by mitsos1os** [comment] 2021-09-28 07:13
I believe this is a duplicate of an issue I previously reported: #1981

**Comment by vraravam** [comment] 2021-09-28 07:16
thanks for flagging the duplication @mitsos1os - closing this one.

**Closed by vraravam** 2021-09-28 07:16 UTC
