### ISSUE TITLE
[Bug]: 'Show Ferdi' on the taskbar icon does not work.

### ISSUE THREAD

**Issue by RafaelMoreira1180778** [getferdi/ferdi#2316] opened 2021-12-10 12:32 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

### Ferdi Version

5.6.3

### What operating system are you using?

Other Linux

### Server

Using without an account

### Operating System Version

Linux pop-os 5.15.5-76051505-generic #202111250933~1638201579~20.04~09f1aa7-Ubuntu SMP Tue Nov 30 02: x86_64 x86_64 x86_64 GNU/Linux

### What arch are you using?

x64

### Last Known working version of Ferdi

n/a

### Git SHA and/or build date

n/a

### Steps to reproduce

1. Install Ferdi using the `.deb` package;
2. Start Ferdi;
3. Close Ferdi;
4. Click 'Show Ferdi' on the icon that appears on the taskbar;
Nothing happens.

1. Run `ferdi` on a terminal;
2. Close Ferdi;
4. Click 'Show Ferdi' on the icon that appears on the taskbar;
5. Watch the output on the terminal.

### Expected Behavior

The 'Show Ferdi' button makes Ferdi reappear.

### Actual Behavior

Nothing happens, this is the error thrown in the terminal:

```
$ ferdi
Starting local server on port 45569
Ferdi Migration:  🧙‍  Running database migration wizard
info: serving app on http://localhost:45569
Ferdi Migration:  🔧  Nothing to migrate, already on the newest version
TypeError: Cannot read properties of undefined (reading 'isMinimized')
    at click (/opt/Ferdi/resources/app.asar/lib/Tray.js:1:692)
    at MenuItem.click (node:electron/js2c/browser_init:73:1908)
    at Object.a._executeCommand (node:electron/js2c/browser_init:81:2453)
```

**Comment by vraravam** [comment] 2021-12-10 12:51
Duplicate of #2262

**Closed by vraravam** 2021-12-10 12:51 UTC
Labels: bug :beetle:
