### ISSUE TITLE
[Bug]: Show Ferdi from System Tray doesn't work

### ISSUE THREAD

**Issue by noraj** [getferdi/ferdi#2309] opened 2021-12-08 15:08 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

### Ferdi Version

5.6.3

### What operating system are you using?

Other Linux

### Server

Using without an account

### Operating System Version

ArchLinux

### What arch are you using?

x64

### Git SHA and/or build date

7ab8abe

### Steps to reproduce

1. Minimize Ferdi to tray
2. Show Ferdi from system tray

### Expected Behavior

_Show Ferdi_ would show Ferdi.

![image](https://user-images.githubusercontent.com/16578570/145232073-2013dc12-988a-4714-809a-ce680d21f6d4.png)

### Actual Behavior

Show Ferdi from System Tray doesn't work. So once minimized to system tray I can't open it again.

I have to put all system tray option to false to prevent being blocked.

```json
  "startMinimized": false,
  "minimizeToSystemTray": false,
  "closeToSystemTray": false,
```

**Comment by Bananaman** [comment] 2021-12-08 15:43
I can confirm this issue with the Flatpak version too, on Fedora 35.

**Comment by Mowto** [comment] 2021-12-09 12:20
This problem was already discussed and fixed in the nightly.
If you want you can install the last nightly where the system tray icon works regularly.

**Comment by Bananaman** [comment] 2021-12-09 12:21
@Mowto That's great news.

**Comment by vraravam** [comment] 2021-12-09 15:10
Closing the issue due to confirmation that its fixed. Thanks @Mowto

**Closed by vraravam** 2021-12-09 15:10 UTC
Labels: bug :beetle:

**Comment by Bananaman** [comment] 2021-12-28 19:31
@vraravam I decided to try Ferdi again. Latest flatpak version 5.6.5. The "show" from tray icon works now.
