### ISSUE TITLE
Ferdi overwrites mime type of html files

### ISSUE THREAD

**Issue by prisae** [getferdi/ferdi#1466] opened 2021-05-30 08:59 UTC
**Bug description:**

Ferdi overwrites `text/html` entry `~/config/mimeapps.list`

**Steps to reproduce:**

Installing and using Ferdi has the effect that the OS wants to open html-files with Ferdi instead with your default browser.

Changing the line 
```
text/html=ferdi.desktop
```
to
```
text/html=firefox.desktop
```
in `~/.config/mimeapps.list` undoes the issue. However, when you start Ferdi it overwrites that setting again.

**Expected behavior**

Ferdi should *not* add itself to the mimeapps-list for html-pages.

**Environment:**

- Operating System: Ubuntu 20.04
- Ferdi Version: 5.6.0-beta.5
- Server: Ferdi

**Comment by ilopmar** [comment] 2021-05-31 07:48
I was about to open the same issue but found this. I tried with nightly build 48 and it still happens.

**Comment by vraravam** [comment] 2021-05-31 07:50
Can you please try with `beta.6` and report?

**Comment by prisae** [comment] 2021-05-31 07:50
Will do @vraravam

**Comment by prisae** [comment] 2021-05-31 07:55
Yes, it still exists. I removed Ferdi 5.6.0-beta.5, re-set the mime-type setting, checked it works by double-clicking on a html file, installed Ferdi 5.6.0-beta.6, and after starting Ferdi it tries to open html-files with Ferdi when double-clicking them.

**Comment by kswro** [comment] 2021-08-02 01:56
Still exists with v5.6.1-nightly.10

**Comment by mhatvan** [comment] 2021-08-19 07:07
Can confirm that it still happens with the latest nightly.

Unable to figure out where this overwrite is coming from, neither server nor ferdi has any obvious code snippets related to mime types...

**Comment by vraravam** [comment] 2021-08-19 08:15
@mhatvan : This is controlled from [electron-builder](https://www.electron.build/generated/platformspecificbuildoptions)

**Comment by prisae** [comment] 2021-11-10 14:02
I installed 5.6.3, and it seems the issue is solved!?! -- It might be good though if someone else can also confirm.

**Comment by mhatvan** [comment] 2021-11-10 14:23
I just downloaded the latest nightly and I can confirm that this issue is fixed with the newer releases!

Either due to upgrades of `electron-builder` or `electron` I assume.

**Closed by mhatvan** 2021-11-10 14:23 UTC
Labels: Implement upstream, high priority
