### ISSUE TITLE
Instagram "Oops, an error occurred."

### ISSUE THREAD

**Issue by RJVB** [getferdi/ferdi#2185] opened 2021-11-06 13:58 UTC
Since this morning or early afternoon I'm getting "Oops, an error occurred." when I try to load my Instagram service in Ferdi 5.6.2 (the Linux 64bit AppImage build).

I removed my user. css which tries to define the emoji font and text antialiasing, to no avail. Setting the user agent to one from a Chromium-based browser (`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36`) also made no difference.

Instagram itself runs just fine in my browsers, which should be exactly the same site.

**Comment by vraravam** [comment] 2021-11-06 16:06
Sorry, I dont use instagram at all.

One quick debugging that I could suggest is to open the navigation bar in Ferdi preferences, and then check what url your instagram service is hitting. See if there are any inconsistencies there with what you see in a normal browser when you say its working in the normal browser.

Also, within Ferdi, if you open the `View > Toggle Service dev Tools" - does that give any error in the `Console` tab?

**Comment by RJVB** [comment] 2021-11-06 17:26
Well, this is weird. The URL used was correct: https://www.instagram.com/direct/inbox/ . On a hunch, I removed the direct/inbox part in the URL field and hit enter. That reloaded the IG landing page (the feed or however they call it), from where I could navigate back to the DM page. Service reloads also seem to work again.

Maybe a cookie crumb went "down the wrong hole"? ^^

**Comment by vraravam** [comment] 2021-11-07 00:03
@RJVB - I have just put in the same change into the service recipe. Please try the next nightly that'll get released in an hour or so

**Comment by RJVB** [comment] 2021-11-07 09:32
OK, but what change exactly? In the end I didn't change a thing as far as I can tell...

**Comment by huang-jy** [comment] 2021-11-08 08:03
I can confirm this issue, I have the same problem on Linux (Ubuntu 19)
![image](https://user-images.githubusercontent.com/2756283/140705145-ea9bddef-454f-40d0-983a-a5727ac0ae4e.png)

**Comment by huang-jy** [comment] 2021-11-08 08:12
Enabling developer window showws 21 breaking changes:

![image](https://user-images.githubusercontent.com/2756283/140705568-d12361a0-1d2d-44a3-8947-b0cc576aeff8.png)

But there are no console messages, so it looks like something is breaking the service at a very early part of the flow.

There are also only four requests (all 200 responses) to https://api.getferdi.com/v1/service/b9745d23-7b3e-4140-8864-f3b2ef2ebc6f

**Comment by RJVB** [comment] 2021-11-08 10:28
>But there are no console messages, so it looks like something is breaking the service at a very early part of the flow.

That's certainly the case, you don't even get to see the IG logo that normally appears while the page is loading.

>There are also only four requests (all 200 responses) to https://api.getferdi.com/v1/service/b9745d23-7b3e-4140-8864-f3b2ef2ebc6f

What does this mean? FWIW, I haven't transferred my Franz account (yet), so if those 4 requests are traces of users using the IG service, I'm not included. In principle (and I hope it'd be anonymised ;) )

**Comment by RJVB** [comment] 2021-11-08 13:10
Hah! Just got the same error in Google Chrome (on a Chromebook)!

Now to see if I can reproduce it in Firefox too...!

**Comment by harryfear** [comment] 2021-11-16 14:44
This is happening to me, too, all the time.

Any ideas?

**Comment by vraravam** [comment] 2021-11-16 14:53
There might be a bug related to localStorage - either in Ferdi or outside. At this point, i'm not sure of anything beyond that. Also, I dont use instagram, so will have to defer to other contributors to take this further.

**Comment by huang-jy** [comment] 2021-11-16 14:55
> This is happening to me, too, all the time.
> 
> Any ideas?
> 
> Restart Service doesn't work; neither does Restart Ferdi. Deleting the service and adding it again solves the issue, though.
> 
> Oauth glitch? Any hotfix available on the Ferdi side?

Can confirm deleting and re-adding seems to have worked.

**Comment by vraravam** [comment] 2021-11-16 15:43
Thanks @RJVB - Closing this ticket - since it seems this is outside the purview of Ferdi.

**Closed by vraravam** 2021-11-16 15:43 UTC
Labels: outstanding question

**Comment by RJVB** [comment] 2021-11-16 17:11
On Tuesday November 16 2021 08:55:14 harryfear wrote:

>(3) Delete ‘cu_version’ cookie

That reeks of a proper fix: delete this cookie each time the service is (re)started, at the beginning of the process.

Does this cookie correspond to an identifiable file on disk? Or what if this cookie is blocked (as I think might be the case for me in Firefox)?

The weird thing is that the cookie is regenerated with the same value, so it's apparently not its content that counts but the fact it's set (and the time it was set)

R.

**Comment by RJVB** [comment] 2021-11-17 11:45
It looks like the `signal_flush_timestamp` cookie might be involved in the once-per-day aspect of this issue. 

- When I deleted `cu_version` this morning, the value of `signal_flush_timestamp` was updated
- deleting `cu_version` and reloading the service does not cause further changes to that cookie
- deleting `cu_version` AND `signal_flush_timestamp` restores both after a reload, but the value of `signal_flush_timestamp` does NOT change.

**Comment by huang-jy** [comment] 2021-11-28 12:39
Just an additional to add. I just got this on normal browsing on Chrome on Windows 10, and not in Ferdi, so I'm not sure if it's a Ferdi specific issue.

**Comment by RJVB** [comment] 2021-11-28 12:52
What's worse, I'm getting the impression that removing the cu_version whatever no longer is sufficient. Curiously, I'm still not getting it on Firefox.

Surely there must be a NodeJS implementation that uses the Gecko/Quantum engine instead of Chrome's Blink/WebEngine? What, no?! :))

**Comment by huang-jy** [comment] 2021-11-28 13:09
I found that removing all the cookies in the service tools window, then reloading the service put me right back into a working state. At least until the next time it happened.
