### ISSUE TITLE
Notifications / badges not working

### ISSUE THREAD

**Issue by Irthen** [getferdi/ferdi#1050] opened 2020-11-02 07:36 UTC
Hi Ferdi folks!

Yesterday I stumbled upon Ferdi and I was very curious to try it out - great job guys, I really love it!

Unfortunately the current Ferdi version (installed via brew on my Mac running Catalina) does not show that I received a new message in the dock (e.g. new WhatsApp message) and for some services (WhatsApp...), the badge on the service itself is not shown, too.

Is there anything I could do to get this working? Any help is appreciated. If you need more information, I am happy to provide them to you.

Thanks!

Flo

**Comment by jmartsch** [comment] 2020-11-07 18:50
I have the same issue on Windows 10 (latest version). No badge on WhatsApp. It works for Slack and other services.

**Comment by fabricio-garcia** [comment] 2020-11-13 16:37
Same issue here. Tried in Kubuntu 20.04 no notifications to any service at all.

**Comment by zemigpt** [comment] 2020-11-17 15:38
I am experiencing the same issue on:

Windows 10 20H2 (19042.630) 64bit
Ferdi 5.5.0 (x64)
Eletron 8.2.3
Node.js v12.13.0

**Comment by JVDL-1** [comment] 2020-11-18 21:05
For Mac this solved the issue for me: https://github.com/getferdi/ferdi/issues/818#issuecomment-645138272

**Comment by Lucria** [comment] 2020-11-19 16:00
Hey all, so it wasn't working for me initially (am using Windows 10 Version 2004), but I decided to use Franz's implementation for their Whatsapp recipe in webview.js. So similarly, replace
const elements = document.querySelectorAll("[class=OUeyt]");
with
const elements = document.querySelectorAll('.CxUIE, .unread, ._0LqQ, .m61XR .ZKn2B ');

**Comment by JoelPintoRibeiro** [comment] 2020-12-10 10:51
same issue here

**Comment by bpwned** [comment] 2020-12-10 15:27
I've made a pull request to fix it: https://github.com/getferdi/recipes/pull/377

**Comment by JoelPintoRibeiro** [comment] 2020-12-15 09:29
> I've made a pull request to fix it: [getferdi/recipes#377](https://github.com/getferdi/recipes/pull/377)

I can confirm that this fix resolve the issue, i made it locally and now i have my notifications whatapps working again , would be cool to have this merged in the main repo

**Comment by jmartsch** [comment] 2021-02-25 09:15
Problem still exists

**Comment by dabesa** [comment] 2021-03-09 16:10
I confirm it still exists, tested with Messenger and WhatsApp.
Will it be fixed?

**Comment by asymetricbalance** [comment] 2021-04-08 03:24
This issue is not affecting only WhatsApp but it seems like all services.

**Comment by vraravam** [comment] 2021-05-22 14:51
With the latest version of Ferdi and the latest recipes, this should no longer be the case.
<img width="57" alt="Screen Shot 2021-05-22 at 8 21 08 PM" src="https://user-images.githubusercontent.com/69629/119230771-45983680-bb3b-11eb-8aeb-5e4ae0a21c6e.png">

Can you please try to upgrade to the nightlies available [here](https://github.com/getferdi/nightlies/releases) AND then upgrading the recipes by following the steps outlined [here](https://github.com/getferdi/ferdi#troubleshooting-recipes-self-help)?

If you are on macos or linux, I have shared some newer builds of the latest source code [here](https://drive.google.com/drive/folders/1mJmKbhpVHdb066IHlrdYiD8TG9wlmuBv)

**Comment by kaiju23** [comment] 2021-06-02 09:28
For whatsapp bug still persist for unread counter.

got a workaround from https://github.com/getferdi/recipes/pull/377

**Comment by vraravam** [comment] 2021-06-02 10:59
Closing this issue - since the fixes are working in the latest nightly and beta versions.

**Closed by vraravam** 2021-06-02 10:59 UTC
Labels: bug, question, service-specific
