### ISSUE TITLE
Annoying service update notification that doesnt go away on older versions of Ferdi.

### ISSUE THREAD

**Issue by ZeroCool940711** [getferdi/ferdi#504] opened 2020-03-27 16:30 UTC
Today Ferdi showed me a notification saying "Your services have been updated." with a button to reload the services, after clicking the reload button it never goes away, it returns after a few seconds saying the same thing and for someone like me with OCD having that annoying thing at the bottom of the window is killing me. This notification shows from time to time even tho I have disabled all Ferdi updates as I don't want it to update at all as the newer version spell checker is really annoying because you can't disable it for non-English languages. 

I hope this can be fixed soon. Here is a screenshot showing the message, its the same across all ferdi services I have which is weird as I doubt all services decided to have an update at the same time but who knows.

![output-onlinepngtools](https://user-images.githubusercontent.com/5977640/77777010-1dcb4280-700c-11ea-95a8-b0a7814a71c0.png)

**Comment by kiranvaidhya** [comment] 2020-03-27 20:34
I've been facing the same issue as well

**Comment by vantezzen** [comment] 2020-03-28 07:30
Are you using Franz's server? If so, then this is a duplicate of #98

**Comment by ZeroCool940711** [comment] 2020-03-28 07:35
Im using franz's server because I cant find the url thta works for the ferdi server, I tried the one on the ferdi server repository (https://api.getferdi.com/) and it doesnt work for me, when I change the server url to that one nothing works, no a single services load and the account doesn't work either, so, have to use the franz server otherwise I cant use ferdi at all.

**Comment by ZeroCool940711** [comment] 2020-03-28 07:37
Here, this is what happens when I try to use the ferdi server url.

![image](https://user-images.githubusercontent.com/5977640/77818002-4a26a380-708c-11ea-93d3-9689398953d5.png)
![image](https://user-images.githubusercontent.com/5977640/77818008-5448a200-708c-11ea-8f0f-eec3e7ec5171.png)

**Comment by vantezzen** [comment] 2020-03-28 08:29
Please note that you will have to register a new account when switching servers - your Franz account won't work on Ferdi's server!
You can however use our account importer tool (https://api.getferdi.com/import) to import your account and settings to Ferdi's servers - but please note that we are currently experiencing some problems with the importer not correctly importing passwords.

Closing this issue as it is a duplicate.

**Closed by vantezzen** 2020-03-28 08:29 UTC

**Comment by ZeroCool940711** [comment] 2020-03-28 16:50
@vantezzen the problem is the ferdi's server doesnt even connect, it has never worked for me, thats the reason I had to use franz's server, keep in mind im using an older version (5.4.0), that error I showed before when trying to connect to Ferdi's server apparently is because the url for ferdi's server just redirects me somewhere and never even try to login or anything, it just doesnt work at all, the login window doesnt do anything, I do have an account on ferdi's server, the import did work for me  but ferdi just cant login to https://api.getferdi.com, even if I try to use ferdi without an account by just changing the server I cant even save or create services or do anything on ferdi's UI as it doesnt work, I think thats an old bug someone reported sometime ago.
