### ISSUE TITLE
Disable hibernation not working.

### ISSUE THREAD

**Issue by sujay1844** [getferdi/ferdi#993] opened 2020-10-04 01:29 UTC
**Bug description:**

The services for which I disable hibernation, get hiberated like other services once I restart Ferdi.

**Steps to reproduce:**

Toggle on Service hibernation and hibernate on startup. 
Disable hibernation for a service
Restart Ferdi

**Expected behavior**

The service is not supposed to hibernate

**Screenshots**

When I check the setting of the service,
Before restart,
![image](https://user-images.githubusercontent.com/68642484/95004817-e61e0280-060d-11eb-886f-fc5573d27d49.png)

After restart,
![image](https://user-images.githubusercontent.com/68642484/95004810-d30b3280-060d-11eb-8f1d-8458b43bb55e.png)

**Environment:**

- Operating System: Manjaro Linux
- Ferdi Version:5.5.0 (flatpak version)
- Server: Franz

- Debug information:

{"host":{"platform":"linux","release":"5.8.11-1-MANJARO","screens":[{"id":1881264395124819,"bounds":{"x":0,"y":0,"width":1920,"height":1080},"workArea":{"x":0,"y":0,"width":1920,"height":1034},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:INVALID, transfer:INVALID, matrix:INVALID, range:INVALID}","depthPerComponent":8,"size":{"width":1920,"height":1080},"workAreaSize":{"width":1920,"height":1034},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.5.0","electron":"8.2.3","installedRecipes":[{"id":"android-messages","version":"1.3.0"},{"id":"github","version":"2.0.0"},{"id":"gmail","version":"1.3.1"},{"id":"msteams","version":"1.3.2"},{"id":"office365-owa","version":"1.1.0"},{"id":"reddit","version":"1.0.0"},{"id":"telegram","version":"3.0.0"},{"id":"todoist","version":"1.1.0"},{"id":"whatsapp","version":"2.0.3"},{"id":"News","version":"1.0.0"}],"devRecipes":[{"id":"News","version":"1.0.0"}],"services":[{"id":"e54c4328-cb6e-495e-b1e3-f9c5a1926348","recipe":"gmail","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"59f7d957-f381-4c4c-bfc6-fab1097c69a3","recipe":"todoist","isAttached":false,"isActive":false,"isEnabled":true,"isHibernating":true,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"80640959-c1b9-4ac8-bd3a-23b3fd67f4d8","recipe":"whatsapp","isAttached":false,"isActive":false,"isEnabled":true,"isHibernating":true,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"a9a95b96-d755-4424-b9d3-a17086ed14ee","recipe":"office365-owa","isAttached":false,"isActive":false,"isEnabled":true,"isHibernating":true,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"41bed51e-9d01-4d37-b797-85511f9fa06a","recipe":"github","isAttached":false,"isActive":false,"isEnabled":true,"isHibernating":true,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"e84e5ba2-ffc5-4095-94b7-09eeb745354f","recipe":"reddit","isAttached":false,"isActive":false,"isEnabled":true,"isHibernating":true,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"05c81c31-8e97-4856-9a6a-624382250f2e","recipe":"News","isAttached":false,"isActive":false,"isEnabled":true,"isHibernating":true,"hasCrashed":false,"isDarkModeEnabled":true}],"messages":[{"type":"error","info":["error","[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@160]'",{}]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"https://api.getferdi.com"}],"workspaces":[{"id":"46a9e5bf-0de3-44d8-a7cd-d7206d9d9a5e","services":["e54c4328-cb6e-495e-b1e3-f9c5a1926348","80640959-c1b9-4ac8-bd3a-23b3fd67f4d8","0a0aa000-0a0a-49a0-a000-a0a0a0a0a0a0","0a0aa000-0a0a-49a0-a000-a0a0a0a0a0a0","0a0aa000-0a0a-49a0-a000-a0a0a0a0a0a0","0a0aa000-0a0a-49a0-a000-a0a0a0a0a0a0","0a0aa000-0a0a-49a0-a000-a0a0a0a0a0a0","a9a95b96-d755-4424-b9d3-a17086ed14ee","0a0aa000-0a0a-49a0-a000-a0a0a0a0a0a0","0a0aa000-0a0a-49a0-a000-a0a0a0a0a0a0"]}],"windowSettings":{"width":1279,"height":658,"x":0,"y":236,"isMaximized":false,"isFullScreen":false,"displayBounds":{"x":0,"y":0,"width":1920,"height":1080}},"settings":{"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":true,"minimizeToSystemTray":"","privateNotifications":false,"showDisabledServices":true,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"en-us","darkMode":true,"locale":"en-US","fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":true,"serviceLimit":5,"server":"https://api.getferdi.com","predefinedTodoServer":"https://app.franztodos.com","autohideMenuBar":true,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernate":true,"hibernateOnStartup":true,"hibernationStrategy":300,"inactivityLock":0,"automaticUpdates":true,"showServiceNavigationBar":false,"universalDarkMode":true,"adaptableDarkMode":true,"accentColor":"#3fa08e","serviceRibbonWidth":"55","iconSize":"20","sentry":false,"navigationBarBehaviour":"never","customTodoServer":"","todoServer":"isUsingCustomTodoService"},"features":{"isSpellcheckerIncludedInCurrentPlan":true,"needToWaitToProceed":false,"needToWaitToProceedConfig":{"delayOffset":3600000,"wait":10000},"isServiceProxyEnabled":true,"isServiceProxyIncludedInCurrentPlan":true,"isAnnouncementsEnabled":true,"isWorkspaceIncludedInCurrentPlan":true,"isWorkspaceEnabled":true,"isCommunityRecipesIncludedInCurrentPlan":true,"isSpellcheckerPremiumFeature":false,"isServiceProxyPremiumFeature":true,"isWorkspacePremiumFeature":false,"isSettingsWSEnabled":false,"isServiceLimitEnabled":false,"serviceLimitCount":0,"isCommunityRecipesPremiumFeature":false,"isCustomUrlIncludedInCurrentPlan":true,"isMagicBarEnabled":true,"isTeamManagementIncludedInCurrentPlan":true,"isTodosEnabled":true,"isTodosIncludedInCurrentPlan":true,"defaultTrialPlan":"franz-pro-yearly","subscribeURL":"https://getferdi.com","planSelectionURL":"https://getferdi.com","hasInlineCheckout":true,"isPlanSelectionEnabled":false,"isTrialStatusBarEnabled":false,"canSkipTrial":true,"pricingConfig":{"currency":"$","currencyID":"USD","plans":{"personal":{"monthly":{"id":"ferdi-free","price":0,"billed":0},"yearly":{"id":"ferdi-completely-free","price":0,"billed":0}},"pro":{"monthly":{"id":"ferdi-still-free","price":0,"billed":0},"yearly":{"id":"ferdi-forever-free","price":0,"billed":0}}}}},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}

And my system information,

System:
  Kernel: 5.8.11-1-MANJARO x86_64 bits: 64 compiler: N/A 
  Desktop: KDE Plasma 5.19.5 Distro: Manjaro Linux 
Machine:
  Type: Laptop System: Acer product: Swift SF314-42 v: V1.03 
  serial: <filter> 
  Mobo: RO model: Kona_RN v: V1.03 serial: <filter> UEFI: Insyde v: 1.03 
  date: 04/07/2020 
Battery:
  ID-1: BAT1 charge: 39.7 Wh condition: 45.5/47.9 Wh (95%) 
  model: Murata AP18C4K status: Discharging 
CPU:
  Topology: 6-Core model: AMD Ryzen 5 4500U with Radeon Graphics bits: 64 
  type: MCP arch: Zen rev: 1 L2 cache: 3072 KiB 
  flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm 
  bogomips: 28458 
  Speed: 1652 MHz min/max: 1400/2375 MHz Core speeds (MHz): 1: 1389 2: 1390 
  3: 2097 4: 1347 5: 1514 6: 1380 
Graphics:
  Device-1: AMD Renoir vendor: Acer Incorporated ALI driver: amdgpu 
  v: kernel bus ID: 03:00.0 
  Device-2: Quanta HD User Facing type: USB driver: uvcvideo bus ID: 1-3:2 
  Display: x11 server: X.Org 1.20.9 driver: amdgpu FAILED: ati 
  unloaded: modesetting resolution: 1920x1080~60Hz 
  OpenGL: renderer: AMD RENOIR (DRM 3.38.0 5.8.11-1-MANJARO LLVM 10.0.1) 
  v: 4.6 Mesa 20.1.8 direct render: Yes 
Audio:
  Device-1: AMD vendor: Acer Incorporated ALI driver: snd_hda_intel 
  v: kernel bus ID: 03:00.1 
  Device-2: AMD Raven/Raven2/FireFlight/Renoir Audio Processor 
  vendor: Acer Incorporated ALI driver: snd_rn_pci_acp3x v: kernel 
  bus ID: 03:00.5 
  Device-3: AMD Family 17h HD Audio vendor: Acer Incorporated ALI 
  driver: snd_hda_intel v: kernel bus ID: 03:00.6 
  Sound Server: ALSA v: k5.8.11-1-MANJARO 
Network:
  Device-1: Intel Wi-Fi 6 AX200 driver: iwlwifi v: kernel bus ID: 01:00.0 
  IF: wlp1s0 state: up mac: <filter> 
Drives:
  Local Storage: total: 476.94 GiB used: 256.60 GiB (53.8%) 
  ID-1: /dev/nvme0n1 vendor: SK Hynix model: HFM512GDJTNI-82A0A 
  size: 476.94 GiB 
Partition:
  ID-1: / size: 180.69 GiB used: 125.38 GiB (69.4%) fs: ext4 
  dev: /dev/nvme0n1p7 
Swap:
  ID-1: swap-1 type: partition size: 4.00 GiB used: 0 KiB (0.0%) 
  dev: /dev/nvme0n1p6 
Sensors:
  System Temperatures: cpu: 39.8 C mobo: N/A gpu: amdgpu temp: 39 C 
  Fan Speeds (RPM): N/A 
Info:
  Processes: 287 Uptime: 40m Memory: 7.21 GiB used: 3.06 GiB (42.4%) 
  Init: systemd Compilers: gcc: 10.2.0 clang: 10.0.1 Packages: 1779 
  Shell: Bash v: 5.0.18 inxi: 3.1.05

**Comment by vantezzen** [comment] 2020-10-04 12:38
Duplicate of #715. This is already fixed and will be rolled out in the next version of Ferdi.

**Closed by vantezzen** 2020-10-04 12:38 UTC
Labels: bug

**Comment by sujay1844** [comment] 2020-10-04 12:46
Thank you for your quick response. I really really appreciate it.
