### ISSUE TITLE
Ferdi does not open links

### ISSUE THREAD

**Issue by leoheck** [getferdi/ferdi#1339] opened 2021-05-03 15:01 UTC
Hi guys, do you know why Ferdi does not open links?

I am using 5.6.0-Nightly15, but it was like this in 5.5.0 too.
I am running Ubuntu 21.04

It happens on Slack, Whatsapp, Mattermost,  Google Calendar, Reddit.
Actually, some URLs work when holding down the `Ctrl` key. But some don't when on Google Calendar, for instance.

For Google Chat, it is not necessary the `Ctrl` key

**Comment by CarlinhaCamargo** [comment] 2021-05-04 14:01
Also having this problem on Mac Big Sur using the same nightly. 
I had this problem once, long time ago, found a fix at the time, but until now could find the old solution.

**Comment by vraravam** [comment] 2021-05-04 14:11
Can you please try to right click on the link, and use "Open Link"? This might be a workaround for temporary usage while the devs try to search for the root cause.

**Comment by leoheck** [comment] 2021-05-04 14:13
Yeah, sure. The workaround works. Copying+Pasting the link also works. Thanks for the info @vraravam

**Comment by kdlancer** [comment] 2021-05-06 08:27
On Mac, I just hold down the Command key when I click links for a quick open in browser. In Windows, Ctrl might work?

**Comment by leoheck** [comment] 2021-05-06 13:14
@kdlancer this was said in the description. It works for some URLs.

**Comment by alopix** [comment] 2021-05-23 07:24
I’ve seen that issue in the currently nightly as well. Both on Windows and macOS. Command click (and right click "open") seems to work on macOS (have not tried any workaround on Windows yet).

**Comment by lupus2k** [comment] 2021-05-27 02:47
Same here in the last BETA...i rollback to 5.5.0 and works perfect, it's weird to do right click and then OPEN LINK to see it in the browser...

**Comment by vraravam** [comment] 2021-05-27 03:02
Since we are back on track with the latest nightlies, we will try to find the root cause for this change in behavior - I have marked this as a hight priority bug to take a look at.

**Comment by prasann** [comment] 2021-05-31 17:12
The root cause seems to be the electron upgrade here.

to open the links we are using,

`ipcRenderer.send('open-browser-window', event, this.id);` 

here the `event` is a browser event.

Ref: https://github.com/getferdi/ferdi/blob/develop/src/models/Service.js#L291 

Starting electron 9, support for non JS object in `ipcRenderer` is been removed. 

Ref: https://www.electronjs.org/docs/breaking-changes#behavior-changed-sending-non-js-objects-over-ipc-now-throws-an-exception

We might not want to send the entire `event` but then only the necessary attrs. 

will raise a PR soon for this one.

**Comment by vraravam** [comment] 2021-05-31 17:27
@prasann - great find! Reading through other instances of `ipcMain.on()` invocations, there are many such event-objects that are sent, and all of them will have the same issue about serialization. Would really love to take this fix for a spin! Eagerly awaiting your PR!

Thanks for contributing! 🎉

**Closed** 2021-06-01 08:25 UTC
Labels: high priority
