### ISSUE TITLE
File menu item gone on macOS

### ISSUE THREAD

**Issue by probablykasper** [getferdi/ferdi#469] opened 2020-03-15 16:08 UTC
The close window shortcut seems to be entirely gone in Ferdi 5.4.4-beta.3. On startup, the "File" menu item shows up briefly, but after loading it's gone.

- macOS 10.14.6
- Ferdi 5.4.4-beta.3
- Server Used: https://api.getferdi.com

Debug information: https://debug.getferdi.com/d485b478-91f1-4c55-a771-96baadf15a20

**Comment by tezvi** [comment] 2020-03-18 17:20
Same thing happening to me with addition that whole menu bar is gone when services starts to load. Initially it is rendered fine. Afterwards just an empty placeholder stays.

**Comment by tezvi** [comment] 2020-03-25 21:34
Fixed it by completely removing my profile from ~/.config/Ferdi

**Comment by probablykasper** [comment] 2020-03-26 12:24
@tezvi Hmm, there is no `Ferdi` in my `~/.config` folder. Tried deleting `~/Library/Application Support/Ferdi/config` but that didn't fix this issue.

**Comment by tezvi** [comment] 2020-03-27 09:20
I'm on linux so I suppose ~/.config is default place for Ferdi configuration. Be aware that by deleting this directory you will loose your services and will have to define them all over again.

**Comment by probablykasper** [comment] 2020-03-27 13:21
@tezvi Ah thanks for mentioning. Tried deleting the whole `Application Support/Ferdi` folder, that didn't do anything either though. Maybe your issue is entirely unrelated

**Comment by tezvi** [comment] 2020-03-27 14:22
Could be, all though it looked like it was the same thing. Window menu was completely gone.

**Comment by probablykasper** [comment] 2020-04-23 14:04
Still happening for me in 5.5.0-gm.2. @kytwb On macOS, are you not having this issue?

**Comment by probablykasper** [comment] 2020-04-29 18:44
Oh rip, 5.5.0 was shipped with this bug. Hopefully it doesn't affect too many people.

@kytwb @vantezzen Any word on this issue? Are you able to reproduce it?

**Comment by kytwb** [comment] 2020-04-30 05:56
@probablykasper The issue is labeled as bug and is still open, it means we are aware of it and it hasn't been addressed yet. We can see the File menu is gone. It will be addressed when someone take the time to address it. Thank you.

**Comment by kytwb** [comment] 2020-04-30 14:54
@probablykasper There is other issues we deem higher priorities 🙏 You can still minimize/close the window, just not with the shortcut / via the menu. We will address when we can. You are welcome to take a dive in and ask for help if needed in the process, I'll be happy to collaborate! Thanks for your understanding.

**Comment by Just-Insane** [comment] 2020-05-12 17:32
Also having this issue in macOS Catalina where the menu bar at the top is missing a lot of options.

**Comment by kytwb** [comment] 2020-05-12 22:33
@Just-Insane Thank you for reporting your case 🙏 Are you also on 5.5.0? The case you describe seems a bit different; could you please share a screenshot of your menu bar when it is missing options?

**Comment by emanuelst** [comment] 2020-06-15 20:43
This might be related to #550, as the minimize option in the "Window" menu disappeared as well

**Comment by jbredenfeldt** [comment] 2020-06-18 19:28
macOS 10.15.5
Ferdi 5.5.0 (5.5.0.2116)
Server Used: https://api.getferdi.com
Debug information: https://debug.getferdi.com/35390d3c-03d7-4310-bbbe-47c025cc2d93

I too have this issue with the File menu not present, and above all; the "Close Window" keyboard command.

I quite understand that there are other bugs to squash, and I sincerely appreciate what you've done! Ferdi is great and I use it every day, even every hour of my working day. But not being able to close it from the keyboard is, well... annoying. It works by clicking the close button with the mouse of course.

It seems to exist on Windows too:
https://github.com/getferdi/ferdi/issues/550#issuecomment-645984009

**Comment by emanuelst** [comment] 2020-08-18 02:06
> This issue has been automatically marked as stale because it has not had recent activity. Please check if this issue is still relevant and please close it if it's not. This will make sure that our open issues are actually of use and reduce the list of obsolete issues. Thank you for your contributions.

I would vote against marking this issue as stale, as per #852 it still exists in Ferdi Version 5.6.0-beta.2 (5.6.0-beta.2.2329)

**Comment by jbredenfeldt** [comment] 2020-10-17 03:03
It's still an issue, I've just given up on this as I'm not enough of an experienced coder to know what it is that makes the menu / keyboard command disappear, otherwise I'd love to help out! I've made a macro for just Ferdi in Keyboard Maestro that clicks the close widget when I press Command-W, so I can keep using Ferdi. I really like Ferdi over Franz, but it's odd that Franz doesn't have this issue when it's a lot of code overlap.

**Comment by jbredenfeldt** [comment] 2020-12-17 12:34
Sigh, I'll once again bump this issue. Not to pester the developers, I really love that you DO work on Ferdi, and I realize it's low on the priority list, I just want to keep the issue away from the stale-bots grubby hands... But it's a real issue in the day-to-day usability of Ferdi to not be able to use keyboard shortcuts that's fairly ingrained in muscle memory, like ”close window”.

**Comment by jbredenfeldt** [comment] 2021-02-16 10:31
Still the same, macOS 11.2.1 (20D74)

**Comment by vraravam** [comment] 2021-05-27 15:43
Can you please try the latest nightlies from yesterday/today and report back? I am not seeing this behavior on macos Big Sur and Mojave

**Comment by mhatvan** [comment] 2021-08-23 19:56
I can minimize Ferdi with `Cmd+M`, and close the application window with `Cmd+W`.
Additionally, the menu bar works fine and does not disappear on macOS.

Cannot reproduce this, please report back, otherwise will close this ticket.

**Comment by jbredenfeldt** [comment] 2021-08-23 22:31
This is correct! I've sadly not used Ferdi for quite some time (partly due to this problem) but the latest stable release do work with the keyboard shortcuts. **Many thanks** to you all kind and generous people that work on Ferdi!

**Comment by vraravam** [comment] 2021-08-23 23:50
Closing - and thanks for getting back! We hope you can restart your use of Ferdi!

**Closed by vraravam** 2021-08-23 23:50 UTC
Labels: bug, outstanding question, platform-specific
