### ISSUE TITLE
Ferdi can't seem to Update.

### ISSUE THREAD

**Issue by theofficialgrand1** [getferdi/ferdi#1931] opened 2021-09-14 01:38 UTC
So After a long awaited wait there is a new update for ferdi. When clicking the Restart & install update the App closes, however, it doesn't relaunch, and instead stays quit. 

When launching manually it doesn't seem to have updated.

**Comment by vraravam** [comment] 2021-09-14 01:40
Duplicate of #1581

**Comment by vraravam** [comment] 2021-09-14 01:40
Please use the http://github.com/getferdi/ferdi/releases page to download manually (the website is also outdated at this point - we are waiting for @kytwb to update it).

**Closed by vraravam** 2021-09-14 01:40 UTC
