### ISSUE TITLE
[Bug]: Mac version updater closes the app, but does not update it

### ISSUE THREAD

**Issue by APz** [getferdi/ferdi#2354] opened 2021-12-22 19:21 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/getferdi/ferdi/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/getferdi/ferdi/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/getferdi/ferdi/issues) for a feature request that matches the one I want to file, without success.

### Ferdi Version

5.6.4

### What operating system are you using?

macOS

### Server

Ferdi

### Operating System Version

Monterey 12.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known working version of Ferdi

-

### Steps to reproduce

1. Wait until new version is available
2. Click Ferdi's prompt to install the upgrade
3. The App closes, but does not upgrade nor start again. Manual start starts the existing version.

### Expected Behavior

Clicking upgrade would download and install upgrade

### Actual Behavior

Upgrade closes the app but does nothing.

### Debug information

{"host":{"platform":"darwin","release":"21.2.0","screens":[{"id":69734464,"bounds":{"x":0,"y":0,"width":1440,"height":900},"workArea":{"x":0,"y":0,"width":1440,"height":900},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":30,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1_HDR, matrix:RGB, range:FULL}","depthPerComponent":10,"size":{"width":1440,"height":900},"displayFrequency":60,"workAreaSize":{"width":1440,"height":900},"scaleFactor":2,"rotation":0,"internal":true,"touchSupport":"unknown"}]},"ferdi":{"version":"5.6.4","electron":"15.3.3","installedRecipes":[{"id":"instagram","version":"2.2.5"},{"id":"telegram","version":"3.2.4"},{"id":"whatsapp","version":"3.3.7"},{}],"devRecipes":[],"services":[{"id":"7ab79f9c-209c-4be6-b34c-20032f2411f6","recipe":"whatsapp","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"a0440ac8-0f30-43ac-a61e-0d922aefa16b","recipe":"telegram","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"d6f4c18c-0195-479c-a6b1-6b63296903d9","recipe":"whatsapp","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"20e0209d-a389-40d6-a76d-8828abdebe64","recipe":"telegram","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"7eae8c21-0b14-40f9-88ed-722e8a5a042a","recipe":"instagram","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false}],"messages":[{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.service` of type `Object` supplied to `AppLayoutContainer`, expected instance of `_class`.","\n    at AppLayoutContainer (/Applications/Ferdi.app/Contents/Resources/app.asar/containers/layout/AppLayoutContainer.js:1:1816)\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at <anonymous> (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at <anonymous> (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at Routes (/Applications/Ferdi.app/Contents/Resources/app.asar/routes.js:1:2618)\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at IntlProvider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-intl/src/components/provider.js:81:47)\n    at I18N (/Applications/Ferdi.app/Contents/Resources/app.asar/I18n.js:1:470)\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at Provider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:482:24)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.settings` of type `Object` supplied to `Sidebar`, expected instance of `_class`.","\n    at Sidebar (/Applications/Ferdi.app/Contents/Resources/app.asar/components/layout/Sidebar.js:1:1969)\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at injectIntl(inject-with-stores-actions(Sidebar))\n    at div\n    at div\n    at ErrorBoundary (/Applications/Ferdi.app/Contents/Resources/app.asar/components/util/ErrorBoundary/index.js:1:932)\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(ErrorBoundary))\n    at AppLayout (/Applications/Ferdi.app/Contents/Resources/app.asar/components/layout/AppLayout.js:1:2602)\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(AppLayout))\n    at ThemeProvider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/theming/dist/theming.cjs.js:78:37)\n    at AppLayoutContainer (/Applications/Ferdi.app/Contents/Resources/app.asar/containers/layout/AppLayoutContainer.js:1:1816)\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at <anonymous> (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at <anonymous> (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at Routes (/Applications/Ferdi.app/Contents/Resources/app.asar/routes.js:1:2618)\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at IntlProvider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-intl/src/components/provider.js:81:47)\n    at I18N (/Applications/Ferdi.app/Contents/Resources/app.asar/I18n.js:1:470)\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at Provider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:482:24)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.service` of type `Object` supplied to `QuickSwitchModal`, expected instance of `_class`.","\n    at QuickSwitchModal (/Applications/Ferdi.app/Contents/Resources/app.asar/features/quickSwitch/Component.js:1:1976)\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(inject-with-stores-actions(QuickSwitchModal)))\n    at div\n    at div\n    at div\n    at ErrorBoundary (/Applications/Ferdi.app/Contents/Resources/app.asar/components/util/ErrorBoundary/index.js:1:932)\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(ErrorBoundary))\n    at AppLayout (/Applications/Ferdi.app/Contents/Resources/app.asar/components/layout/AppLayout.js:1:2602)\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(AppLayout))\n    at ThemeProvider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/theming/dist/theming.cjs.js:78:37)\n    at AppLayoutContainer (/Applications/Ferdi.app/Contents/Resources/app.asar/containers/layout/AppLayoutContainer.js:1:1816)\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at <anonymous> (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at <anonymous> (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at Routes (/Applications/Ferdi.app/Contents/Resources/app.asar/routes.js:1:2618)\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at IntlProvider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-intl/src/components/provider.js:81:47)\n    at I18N (/Applications/Ferdi.app/Contents/Resources/app.asar/I18n.js:1:470)\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at Provider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:482:24)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.settings` of type `Object` supplied to `NightlyBuildsModal`, expected instance of `_class`.","\n    at NightlyBuildsModal (/Applications/Ferdi.app/Contents/Resources/app.asar/features/nightlyBuilds/Component.js:1:2049)\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(inject-with-stores-actions(NightlyBuildsModal)))\n    at div\n    at div\n    at div\n    at ErrorBoundary (/Applications/Ferdi.app/Contents/Resources/app.asar/components/util/ErrorBoundary/index.js:1:932)\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(ErrorBoundary))\n    at AppLayout (/Applications/Ferdi.app/Contents/Resources/app.asar/components/layout/AppLayout.js:1:2602)\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(AppLayout))\n    at ThemeProvider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/theming/dist/theming.cjs.js:78:37)\n    at AppLayoutContainer (/Applications/Ferdi.app/Contents/Resources/app.asar/containers/layout/AppLayoutContainer.js:1:1816)\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at <anonymous> (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at <anonymous> (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at Routes (/Applications/Ferdi.app/Contents/Resources/app.asar/routes.js:1:2618)\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at IntlProvider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-intl/src/components/provider.js:81:47)\n    at I18N (/Applications/Ferdi.app/Contents/Resources/app.asar/I18n.js:1:470)\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at Provider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:482:24)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","Invalid prop `actions.service` of type `Object` supplied to `PublishDebugLogModal`, expected instance of `_class`.","\n    at PublishDebugLogModal (/Applications/Ferdi.app/Contents/Resources/app.asar/features/publishDebugInfo/Component.js:1:2533)\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(inject-with-stores-actions(PublishDebugLogModal)))\n    at div\n    at div\n    at div\n    at ErrorBoundary (/Applications/Ferdi.app/Contents/Resources/app.asar/components/util/ErrorBoundary/index.js:1:932)\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(ErrorBoundary))\n    at AppLayout (/Applications/Ferdi.app/Contents/Resources/app.asar/components/layout/AppLayout.js:1:2602)\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at injectIntl(WithStyles(AppLayout))\n    at ThemeProvider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/theming/dist/theming.cjs.js:78:37)\n    at AppLayoutContainer (/Applications/Ferdi.app/Contents/Resources/app.asar/containers/layout/AppLayoutContainer.js:1:1816)\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at <anonymous> (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at <anonymous> (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at Routes (/Applications/Ferdi.app/Contents/Resources/app.asar/routes.js:1:2618)\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at IntlProvider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-intl/src/components/provider.js:81:47)\n    at I18N (/Applications/Ferdi.app/Contents/Resources/app.asar/I18n.js:1:470)\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at Provider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:482:24)"]},{"type":"error","info":["error","Warning: Failed %s type: %s%s","prop","The prop `title` is marked as required in `FullscreenLoader`, but its value is `undefined`.","\n    at FullscreenLoader (/Applications/Ferdi.app/Contents/Resources/app.asar/components/ui/FullscreenLoader/index.js:1:696)\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at AppLoader (/Applications/Ferdi.app/Contents/Resources/app.asar/components/ui/AppLoader/index.js:1:935)\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-jss/dist/react-jss.cjs.js:407:25\n    at ThemeProvider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/theming/dist/theming.cjs.js:78:37)\n    at AppLayoutContainer (/Applications/Ferdi.app/Contents/Resources/app.asar/containers/layout/AppLayoutContainer.js:1:1816)\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at <anonymous> (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at <anonymous> (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/create-react-class/factory.js:899:37)\n    at Routes (/Applications/Ferdi.app/Contents/Resources/app.asar/routes.js:1:2618)\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at IntlProvider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/react-intl/src/components/provider.js:81:47)\n    at I18N (/Applications/Ferdi.app/Contents/Resources/app.asar/I18n.js:1:470)\n    at /Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:513:34\n    at Provider (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/mobx-react/dist/mobxreact.cjs.development.js:482:24)"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"https://api.getferdi.com"}],"workspaces":[],"windowSettings":{"width":800,"height":600,"x":438,"y":25,"isMaximized":true,"isFullScreen":true,"displayBounds":{"x":0,"y":0,"width":1440,"height":900}},"settings":{"autoLaunchOnStart":false,"autoLaunchInBackground":false,"runInBackground":true,"reloadAfterResume":true,"enableSystemTray":false,"startMinimized":false,"confirmOnQuit":false,"minimizeToSystemTray":false,"closeToSystemTray":false,"privateNotifications":false,"clipboardNotifications":true,"notifyTaskBarOnMessage":false,"showDisabledServices":true,"showServiceName":false,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":true,"spellcheckerLanguage":"en-us","darkMode":false,"splitMode":false,"splitColumns":3,"fallbackLocale":"en-US","beta":false,"isAppMuted":false,"enableGPUAcceleration":true,"enableGlobalHideShortcut":false,"server":"https://api.getferdi.com","predefinedTodoServer":"https://app.franztodos.com","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernateOnStartup":true,"hibernationStrategy":300,"wakeUpStrategy":300,"inactivityLock":0,"automaticUpdates":true,"universalDarkMode":true,"userAgentPref":"","adaptableDarkMode":true,"accentColor":"#7266F0","serviceRibbonWidth":68,"iconSize":20,"sentry":false,"nightly":false,"navigationBarBehaviour":"custom","searchEngine":"duckDuckGo","useVerticalStyle":false,"alwaysShowWorkspaces":false,"liftSingleInstanceLock":false,"enableLongPressServiceHint":false,"proxyFeatureEnabled":false,"onlyShowFavoritesInUnreadCount":false,"locale":"en-US","customTodoServer":""},"features":{},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}

### Additional Information

Has happened with the past 2-3 point versions. Happens on both, x86 and ARM versions.

**Comment by ebuswf** [comment] 2021-12-23 08:55
Same issue here on Big Sur 11.6.2, M1 mac.

**Comment by kytwb** [comment] 2021-12-23 12:16
Duplicate of https://github.com/getferdi/ferdi/issues/329.

**Closed by kytwb** 2021-12-23 12:16 UTC
Labels: bug :beetle:
