### ISSUE TITLE
Cannot restore window from tray (Linux)

### ISSUE THREAD

**Issue by the-nic** [getferdi/ferdi#2209] opened 2021-11-10 18:16 UTC
Since the new version `5.6.3` I cannot restore the window from the tray. However, I get the following error when starting ferdi from cli:
```
TypeError: Cannot read properties of undefined (reading 'isMinimized')
    at click (/opt/Ferdi/resources/app.asar/lib/Tray.js:1:692)
    at MenuItem.click (node:electron/js2c/browser_init:73:1908)
    at Object.a._executeCommand (node:electron/js2c/browser_init:81:2453)
``` 

OS information:
``` 
Operating System: KDE neon 5.23
KDE Plasma Version: 5.23.3
KDE Frameworks Version: 5.87.0
Qt Version: 5.15.3
Kernel Version: 5.11.0-38-generic (64-bit)
Graphics Platform: X11
Processors: 12 × Intel® Core™ i7-9750H CPU @ 2.60GHz
Memory: 31.0 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1650/PCIe/SSE2
```

**Comment by vraravam** [comment] 2021-11-10 19:41
@the-nic - please do not create duplicate tickets. This is a duplicate of #2147

**Closed by vraravam** 2021-11-10 19:41 UTC
