### ISSUE TITLE
Click on link throws error

### ISSUE THREAD

**Issue by BigHoss** [getferdi/ferdi#1222] opened 2021-02-26 09:27 UTC
**Bug description:**
Every click on a link triggers an error message about a popup blocker.,
when i rightclick on the link and use open link the browser opens.

**Steps to reproduce:**
1. open the gmail service
2. click on any link you find
3. see the error

**Expected behavior**
my default browser should open

**Screenshots**
![image](https://user-images.githubusercontent.com/932436/109281739-f59c2300-781c-11eb-964b-3d8c784164d5.png)

**Environment:**

- Operating System: win 10 20H2
- Ferdi Version: 5.5.0
- Server: 

- Debug information:
{"host":{"platform":"win32","release":"10.0.19042","screens":[{"id":2528732444,"bounds":{"x":0,"y":0,"width":1600,"height":900},"workArea":{"x":0,"y":0,"width":1600,"height":819},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1600,"height":900},"workAreaSize":{"width":1600,"height":819},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"},{"id":2779098405,"bounds":{"x":-1920,"y":-272,"width":1920,"height":1200},"workArea":{"x":-1920,"y":-272,"width":1920,"height":1160},"accelerometerSupport":"unknown","monochrome":false,"colorDepth":24,"colorSpace":"{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}","depthPerComponent":8,"size":{"width":1920,"height":1200},"workAreaSize":{"width":1920,"height":1160},"scaleFactor":1,"rotation":0,"internal":false,"touchSupport":"unknown"}]},"ferdi":{"version":"5.5.0","electron":"8.2.3","installedRecipes":[{"id":"gmail","version":"1.3.1"},{"id":"googlecalendar","version":"1.0.3"},{"id":"slack","version":"1.0.15"},{"id":"telegram","version":"3.0.0"},{"id":"telegram-react","version":"1.0.0"},{"id":"whatsapp","version":"2.0.3"},{}],"devRecipes":[],"services":[{"id":"53644517-51fe-4fe1-9c1a-2e861d3dc88e","recipe":"whatsapp","isAttached":false,"isActive":false,"isEnabled":true,"isHibernating":true,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"a890b3f9-591d-421b-819e-c578b4368453","recipe":"telegram-react","isAttached":false,"isActive":false,"isEnabled":true,"isHibernating":true,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"fdd03c9a-3ba8-4050-82ec-70c41b500f9f","recipe":"gmail","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"7b863297-742d-436a-9f82-dae1c964459c","recipe":"googlecalendar","isAttached":false,"isActive":false,"isEnabled":true,"isHibernating":true,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"b88303d7-4be2-44b5-8a61-a62d42af5be6","recipe":"slack","isAttached":false,"isActive":false,"isEnabled":true,"isHibernating":true,"hasCrashed":false,"isDarkModeEnabled":false}],"messages":[{"type":"error","info":["error","[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@160]'",{}]},{"type":"error","info":["error","Warning: Failed prop type: Invalid prop `showMessageBadgeWhenMutedSetting` of type `string` supplied to `_class2`, expected `boolean`.\n    in _class2 (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by _class2)\n    in div (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in ThemeProvider (created by _class2)\n    in _class2 (created by inject-_class2-with-stores-actions)\n    in inject-_class2-with-stores-actions (created by RouterContext)\n    in RouterContext (created by Router)\n    in Router\n    in IntlProvider (created by _class)\n    in _class (created by inject-_class-with-stores)\n    in inject-_class-with-stores\n    in Provider"]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","info":["error","Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s","the componentWillUnmount method","\n    in WindowControls\n    in div\n    in Unknown (created by _class2)\n    in div (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)\n    in _class2 (created by Jss(_class2))\n    in Jss(_class2) (created by _class2)"]},{"type":"error","info":["error","Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state."]},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"featured"},"error":{},"response":{},"server":"https://api.getferdi.com"}],"workspaces":[],"windowSettings":{"width":800,"height":600,"x":373,"y":114,"isMaximized":false,"isFullScreen":false,"displayBounds":{"x":0,"y":0,"width":1600,"height":900}},"settings":{"autoLaunchInBackground":false,"runInBackground":false,"reloadAfterResume":true,"enableSystemTray":true,"startMinimized":false,"minimizeToSystemTray":false,"privateNotifications":false,"showDisabledServices":true,"showMessageBadgeWhenMuted":true,"showDragArea":false,"enableSpellchecking":"","spellcheckerLanguage":"en-us","darkMode":false,"locale":"en-US","fallbackLocale":"en-US","beta":false,"isAppMuted":true,"enableGPUAcceleration":"","serviceLimit":5,"server":"https://api.getferdi.com","predefinedTodoServer":"https://todo.microsoft.com/?app#","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","useTouchIdToUnlock":true,"scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernate":true,"hibernateOnStartup":true,"hibernationStrategy":300,"inactivityLock":0,"automaticUpdates":true,"showServiceNavigationBar":false,"universalDarkMode":true,"adaptableDarkMode":true,"accentColor":"#7367f0","serviceRibbonWidth":"45","iconSize":"20","sentry":false,"navigationBarBehaviour":"never","customTodoServer":"","todoServer":"isUsingCustomTodoService"},"features":{"isSpellcheckerIncludedInCurrentPlan":true,"needToWaitToProceed":false,"needToWaitToProceedConfig":{"delayOffset":3600000,"wait":10000},"isServiceProxyEnabled":true,"isServiceProxyIncludedInCurrentPlan":true,"isAnnouncementsEnabled":true,"isWorkspaceIncludedInCurrentPlan":true,"isWorkspaceEnabled":true,"isCommunityRecipesIncludedInCurrentPlan":true,"isSpellcheckerPremiumFeature":false,"isServiceProxyPremiumFeature":true,"isWorkspacePremiumFeature":false,"isSettingsWSEnabled":false,"isServiceLimitEnabled":false,"serviceLimitCount":0,"isCommunityRecipesPremiumFeature":false,"isCustomUrlIncludedInCurrentPlan":true,"isMagicBarEnabled":true,"isTeamManagementIncludedInCurrentPlan":true,"isTodosEnabled":true,"isTodosIncludedInCurrentPlan":true,"defaultTrialPlan":"franz-pro-yearly","subscribeURL":"https://getferdi.com","planSelectionURL":"https://getferdi.com","hasInlineCheckout":true,"isPlanSelectionEnabled":false,"isTrialStatusBarEnabled":false,"canSkipTrial":true,"pricingConfig":{"currency":"$","currencyID":"USD","plans":{"personal":{"monthly":{"id":"ferdi-free","price":0,"billed":0},"yearly":{"id":"ferdi-completely-free","price":0,"billed":0}},"pro":{"monthly":{"id":"ferdi-still-free","price":0,"billed":0},"yearly":{"id":"ferdi-forever-free","price":0,"billed":0}}}}},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}

**Comment by steveharman** [comment] 2021-03-03 09:00
Same here.  5.6.0 Beta-5 (5.2.274) macOS Big Sur.

At best I have to right-click on a link and choose Open Link, assuming the service I'm using offers that - and sometimes links will open in my browser.  Most times I get the same as @BigHoss

**Comment by ryanpcmcquen** [comment] 2021-03-03 17:34
Looks like a dupe of https://github.com/getferdi/ferdi/issues/941.

**Comment by steveharman** [comment] 2021-03-03 17:36
#941 seems to be "links are opening in Ferdi" ?  

Certainly my experience is more like "Links aren't opening at all" and throw an error.  Per @BigHoss

**Comment by kemenaran** [comment] 2021-03-08 14:19
When I click "open link', I get this error in the Console:

```
/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/@sentry/browser/dist/helpers.js:91 Uncaught Error: An object could not be cloned.
    at EventEmitter.i.send.i.send (electron/js2c/renderer_init.js:75)
    at HTMLElement.<anonymous> (/Applications/Ferdi.app/Contents/Resources/app.asar/models/Service.js:1)
    at HTMLElement.sentryWrapped (/Applications/Ferdi.app/Contents/Resources/app.asar/node_modules/@sentry/browser/dist/helpers.js:74)
    at WebViewImpl.dispatchEvent (electron/js2c/renderer_init.js:155)
    at dispatchEvent (electron/js2c/renderer_init.js:143)
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:143)
    at EventEmitter.emit (events.js:223)
    at EventEmitter.emit (domain.js:475)
    at Object.onMessage (electron/js2c/renderer_init.js:115)
```

**Comment by kemenaran** [comment] 2021-03-29 17:35
Workaround on macOS : `Cmd+Click` opens the link properly (but a simple `Click` triggers the error above).

**Comment by vraravam** [comment] 2021-06-01 08:27
This is now fixed by https://github.com/getferdi/ferdi/pull/1474 - which has just been merged! Please pull and rebuild from source, or wait for tonight's nightly build.

**Closed by vraravam** 2021-06-01 08:27 UTC

**Comment by steveharman** [comment] 2021-06-01 10:06
thanks!  Where can I find the nightlies please?

**Comment by vraravam** [comment] 2021-06-01 10:44
@steveharman - you can find the nightlies [here](https://github.com/getferdi/nightlies/releases)
