### ISSUE TITLE
Ferdi not opening from tray after last update

### ISSUE THREAD

**Issue by pjom** [getferdi/ferdi#2197] opened 2021-11-09 09:56 UTC
Hi, guys.

I've just updated Ferdi to the latest version and since then I don't seem to make the window show when double clicking the tray icon, nor selecting the "Show Ferdi" option from the tray menu.
In order to open the window, I have to use the application's shortcut.

Windows 10 - 64 bits

Paulo

**Comment by geofausto** [comment] 2021-11-09 11:56
Same here. Linux Mint 20.2 Cinnamon.

**Comment by vraravam** [comment] 2021-11-09 12:13
Duplicate of #2147

**Closed by vraravam** 2021-11-09 12:13 UTC
