### ISSUE TITLE
Quick Switch does not always have focus after opening it

### ISSUE THREAD

**Issue by CombeeMike** [getferdi/ferdi#877] opened 2020-07-10 08:51 UTC
**Bug description:**
After pressing `Ctrl+S`, the dialog oftentimes does not have focus and can not be navigated using keyboard.
E.g. when pressing `up` or `down` arrow keys, the selection does not change. When pressing `tab`, the selection does not change, but I can see in the "blurred" background, that the focused element in the currently open service changes. I.e. the focus is still on the service instead of the quick switch dialog.

Also oftentimes pressing `Esc` does not close the quick switch dialog.

**Steps to reproduce:**

1. Go to slack service tab
2. Place cursor in "Message input" area
3. Press `Ctrl+S`

The error is not 100% reproducible this way but it happens quite frequently.

**Expected behavior**
Keyboard navigation with `up`, `down`, `tab` & `esc` keys shall always work, when quick switch dialog is open.
Also, when opening the quick switcher, the "search" textbox should always be focused so that I can start typing immediately to filter the list.

**Environment:**

- Operating System: `Windows 10 v1909`
- Ferdi Version: See image below
- Server: Using without an account

![image](https://user-images.githubusercontent.com/30658772/87135623-947a0c00-c29a-11ea-94e8-f7f0b50e9a1f.png)

- Debug information:
I'm hesitant publishing the debug info here and don't think that it is needed/helpful in this case. Please let me know if you think that it'll help you fix the bug, then I'll post it later.

**Comment by vantezzen** [comment] 2020-07-10 19:30
Duplicate of #322.

This is a known bug which we unfortunately cannot fix: Electron does not allow Ferdi to focus the box if the focus is currently inside a webview.

Related:
https://github.com/electron/electron/issues/17882
https://github.com/getferdi/ferdi/issues/68#issuecomment-534146281
https://github.com/getferdi/ferdi/blob/1fea645b0b94e52a31158d47d0ad921110dfa95e/src/features/quickSwitch/Component.js#L232-L235

**Closed by vantezzen** 2020-07-10 19:30 UTC
Labels: bug

**Comment by CombeeMike** [comment] 2020-07-11 10:13
Wow, that is unfortunate. I'd even go so far and say that this bug renders the quick switcher completely useless. I mean the quick switcher is there to allow easier keyboard only navigation which is simply not possible with this bug 🙁
