### ISSUE TITLE
Discord URLs with /channels/ in URL should open in same Discord instance by default

### ISSUE THREAD

**Issue by ylluminate** [getferdi/ferdi#2047] opened 2021-10-09 17:52 UTC
I've noticed a new behavior where when I open a message URL in Discord from within Ferdi it no longer jumps to the linked message. This is very inconvenient as a server moderator or when working with message links frequently. In the past these simply jumped to the message and/or channel+message in question. Now it opens another browser.

Could we please have a way to instruct Ferdi to handle certain URLs, especially from the web app in use, to use it's own instance to handle certain URLs? For example, if ti is from the same current app URL parent, then it would make sense to open it with itself... Does this make sense?

**Comment by vraravam** [comment] 2021-10-21 22:34
You can right click on any link in a service, and it should show you the option to "Open link in Ferdi" - please try that and report whether that works for you. (though its an inconvenient workaround, at least it'll enable you to use Ferdi for the timebeing)

**Comment by ylluminate** [comment] 2021-10-21 22:36
Wow, that's an odd one. Thanks for letting me know about that - at least I won't go insane any longer. It's rough when working on projects with folks in Discord especially.

Definitely feels funky/clnky and was most certainly unexpected, but at least you're aware of it. Thanks.

**Comment by vraravam** [comment] 2021-11-16 11:57
Duplicate of #1501

**Closed by vraravam** 2021-11-16 11:57 UTC
Labels: enhancement
