### ISSUE TITLE
"WhatsApp works only with Google Chrome 49+" at startup only in Ferdi 5.5.0-gm.2

### ISSUE THREAD

**Issue by rctneil** [getferdi/ferdi#603] opened 2020-04-19 13:52 UTC
WhatsApp just continually says "WhatsApp works with Google Chrome 49+"

**To Reproduce**

Add WhatsApp service
Enable it.

It should allow you to use WA

**Screenshots**

**Desktop:**

- OS: [e.g. macOS, Windows 10 etc.]
- Ferdi Version [e.g. 5.4.3]

- Server Used: [e.g. https://api.getferdi.com]

Debug information: https://debug.getferdi.com/...

**Additional context**

**Comment by RobCruzo** [comment] 2020-04-19 14:10
Same here!

**Comment by vantezzen** [comment] 2020-04-19 14:22
We have already received reports (#601, #598), identified the issue and are working on it (see #536)).

I will pin this issue though so new users hopefully look into this issue instead of creating a new one every time.

**Comment by kytwb** [comment] 2020-04-23 10:05
Fixed in [v5.5.0-gm.2](https://github.com/getferdi/ferdi/releases/tag/v5.5.0-gm.2) 🙏

**Comment by sampathBlam** [comment] 2020-04-25 09:57
@kytwb : 
I got the same error in [v5.5.0-gm.2](https://github.com/getferdi/ferdi/releases/tag/v5.5.0-gm.2)

![whatsapp_chrome_bug](https://user-images.githubusercontent.com/17728976/80276863-fa79dd00-8708-11ea-98ed-24706a9c7818.gif)


But after reloading the service, it started working. 

Debug information:
[debug.txt](https://github.com/getferdi/ferdi/files/4532683/debug.txt)

Tested in Windows 10.

**Comment by kytwb** [comment] 2020-04-25 10:41
@sampathBlam Thanks! I had this happen too, and a service reload works as well. Should we re-open only if it's becoming a blocking issue like it was before (when no reload would fix it)?

**Comment by sampathBlam** [comment] 2020-04-25 12:53
@kytwb : I see this happening everytime I start Ferdi. Is it the same for you as well ? If it is the case for everyone, I would recommend to reopen the issue.

**Comment by kytwb** [comment] 2020-04-25 15:08
@sampathBlam you are right, it's happening everytime I start Ferdi as well.  
Re-opened 🙏

**Comment by mahadevans87** [comment] 2020-04-25 16:36
> @sampathBlam you are right, it's happening everytime I start Ferdi as well.  
> Re-opened! 🙏 

Can be reproduced if you disable and the enable the service as well. A temporary dirty fix would be go to back to the set interval loop that was present in the recipe which we removed. But finding the root cause would be helpful

**Comment by doprado** [comment] 2020-04-25 21:28
Even placing the User Agent is not working. I use 2 WhatsApps and when one works the other goes back to the 49+ version message.

![2020-04-25_18h26_28](https://user-images.githubusercontent.com/15928422/80291244-76ccea00-8722-11ea-9c32-75fecd811bdd.gif)

**Comment by mahadevans87** [comment] 2020-04-26 05:17
I will take this up and provide more inputs.

**Comment by mahadevans87** [comment] 2020-04-26 09:01
@kytwb - This issue is addressed in the recipes repo - https://github.com/getferdi/recipes/pull/140

![ferdi_603_fix](https://user-images.githubusercontent.com/1255523/80302837-1f825480-87ca-11ea-8175-3e0259ea59e1.gif)

The overrideUserAgent() hook in recipes set the user-agent header only after the webview has been loaded initially. This is the reason whatsapp works when we reload the service and possibly the recipe developer put in a setInterval(reload(), 1000) hoping that the user-agent would be set correctly during subsequent reloads.

But now, I used the new modifyRequestHeaders() hook that we introduced a couple of days back so that recipes can use it to pass in request headers which will be sent before the actual request is being sent.

For users to test this, this new functionality needs to go into 5.5-gm-3 I guess.

**Comment by kytwb** [comment] 2020-04-26 09:11
@mahadevans87 Thank you! The `modifyRequestHeaders` change really is going to unblock a lot of the service-specific issues users were reporting before. I think we can wait for 5.5.0 to ship that fix. One of the feature we want to include in 5.5.0 is https://github.com/getferdi/server/issues/14 so we don't have to release new versions to provide updates to recipes.

**Comment by kytwb** [comment] 2020-04-26 09:39
Closing for now 🙏 It will be fixed in the next release, until then, the fixes above should work for those experiencing the same issue on different versions.

**Closed by kytwb** 2020-04-26 09:39 UTC
Labels: bug, low priority, service-specific

**Comment by kytwb** [comment] 2020-04-26 16:06
@mahadevans87 @sampathBlam erratum, my last comment isn't valid anymore, latest update regarding the next release at https://github.com/getferdi/ferdi/issues/536#issuecomment-619562782 🙏

**Comment by mahadevans87** [comment] 2020-04-27 06:29
If you still experience problems with whatsapp after 5.5.0 stable, please clear your cache by going to Ferdi settings and restart Ferdi. You might need to re-login to all the services after you clear cache.

@kytwb which makes me think, we should enable service specific "clear cache" functionality.

**Comment by kytwb** [comment] 2020-04-27 10:03
@mahadevans87 Agreed. In addition to "clear cache", I think it could be interesting to bring all the applicable global settings to the service level.

**Comment by idonthaveanametoday** [comment] 2020-06-27 15:21
This worked for me thanks!

**Comment by bchooxg** [comment] 2020-11-24 05:12
Currently experiencing this issue
WhatsApp asking for chrome to be updated to 60+
