### ISSUE TITLE
Right-click context window doesn't open

### ISSUE THREAD

**Issue by cCaptainn** [getferdi/ferdi#572] opened 2020-04-15 07:29 UTC
**Bug** 
Right-click context window doesn't open when pressing right-click in while highlighting text on any service. Instead, the context menu flashes. If you spam right-click enough it will open the menu as it should normally.

**Steps to reproduce the behavior:**

1. Open Ferdi
2. Navigate to any service with text inside
3.Highlight text;right click to bring up context menu (or use key on keyboard)
4. Attempt to right-click and bring up the context menu
5. See error

**Expected behavior**
I expected the context menu to remain open

**Screenshots**
Check the attached file for a gif of the bug
![bugferdi](https://user-images.githubusercontent.com/63703939/79309944-1be8f680-7ec9-11ea-9447-9ae83014b9ef.gif)

**Desktop:**

- OS: Windows 10
- Ferdi Version 5.4.3- Server Used: none

**Comment by vantezzen** [comment] 2020-04-15 07:51
Thank you for reporting this bug.
This is a duplicate of #357: Context menus are already fixed on newer beta versions of Ferdi and the fix will be released in v5.4.4

**Closed by vantezzen** 2020-04-15 07:51 UTC

**Comment by cCaptainn** [comment] 2020-04-15 07:53
Thanks! Sorry for the duplicate issue!
