### ISSUE TITLE
Missing System Tray Icon

### ISSUE THREAD

**Issue by cihanisma** [getferdi/ferdi#765] opened 2020-05-22 10:00 UTC
**Bug description:**
Ferdi is not being displayed in system tray

**Steps to reproduce:**

1. Settings -> Show Ferdi in system tray
2. Close Ferdi window from close button
3. Ferdi icon is missing in system tray
4. Open Ferdi from start menu
5. Window becomes visible again

**Expected behavior**
Ferdi is visible at system tray and displayable from there

**Environment:**

- Operating System: Linux Mint Cinnamon
- Ferdi Version: 5.5.0
- Server: Franz

**Comment by vantezzen** [comment] 2020-05-22 11:57
Duplicate of #437

**Closed by vantezzen** 2020-05-22 11:57 UTC
