### ISSUE TITLE
Disable hibernation per service gets deactivated after restart

### ISSUE THREAD

**Issue by spi43984** [getferdi/ferdi#715] opened 2020-05-05 09:58 UTC
**Describe the bug**
In Ferdi settings hibernation in general can be activated. Per service hibernation can be disabled (setting "Disable hibernation" in service menu). When this setting gets switched on (i. e. the hibernation is disabled for this service), the next time Ferdi gets restarted, the settign is turned off again (i. e. the hibernation for this service is enabled again).

**To Reproduce**
1) Switch on "Service Hibernation" in Ferdi settings.
2. Disable hibernation for a particular service.
3. Restart Ferdi.
4. Check hibernation settings for particular service.

**Expected behavior**
Service setting isn't changed upon restart.

**Desktop:**
- OS: Ubuntu 18.04.4 LTS
- Ferdi Version: 5.5.0-gm.2, 5.5.0

**Comment by kytwb** [comment] 2020-05-05 11:36
Are you using Ferdi with or without an account?

**Comment by vantezzen** [comment] 2020-05-05 11:57
Are you using Franz's server? If so, this is a duplicate of #702

**Comment by spi43984** [comment] 2020-05-05 12:07
> Are you using Ferdi with or without an account?

Just offline. No account.

**Comment by RalphBurger** [comment] 2020-05-07 09:15
I'm using Ferdi with an account and experience the same problem.

**Desktop:**
OS: Windows 10 Home 1903
Ferdi Version: 5.5.0

**Comment by anotherjames** [comment] 2020-05-07 14:43
I have this issue too, with a Ferdi account on Ferdi's servers.

Mac OS X Catalina (10.15.4)
Ferdi 5.5.0

**Comment by anotherjames** [comment] 2020-05-07 14:46
Interestingly, when I view my data at https://api.getferdi.com/user/data , the `disableHibernation` setting is correctly set to `true`/`false` for each service as I intend -- but when I actually view the settings within Ferdi, all services appear to have it disabled (i.e. hibernation is enabled), as if perhaps the setting just isn't getting loaded correctly?

**Comment by kris7t** [comment] 2020-05-09 14:41
This also happens to me with both the `ferdi` and `ferd-git` archlinux packages (I am not using a Ferdi server).

**Comment by Jashnok** [comment] 2020-05-11 18:55
I'm using Ferdi on macOS Catalina 10.15.4 and on Windows 10 1909.
I also have the problem that the setting is not saved after a restart or is not accessed properly. I use my own instance of the Ferdi server (without changes). In the API-Data everything is stored correctly

**Comment by kris7t** [comment] 2020-05-11 22:58
Maybe I am completely off the base here, but https://github.com/getferdi/ferdi/blob/2f28ec495d5ba2f9368020391dd52da16ed008cd/src/components/services/content/ServiceView.js#L196 looks at the `disableHibernation` property `this.props.service`, which should be a `ServiceModel`, but https://github.com/getferdi/ferdi/blob/3239172af9fb68226e1e11392b16f833b726ad72/src/models/Service.js has no property named `disableHibernation`. On the other hand, it does have a property named `isHibernationEnabled`, but that is not referenced anywhere in the codebase (according to GitHub search) outside of `models/Service.js`. So how are hibernation settings supposed to be piped into `ServiceView`?

**Comment by StormPooper** [comment] 2020-05-12 08:15
This is also occuring for me on Windows 10 with a Ferdi account.

Version: 5.5.0 (x64)
Electron: 8.2.3
Node.js: v12.13.0
Platform: win32

The setting will stay enabled until Ferdi is closed, then once reopened I have to set it again.

**Closed** 2020-05-20 15:47 UTC
Labels: bug
