### ISSUE TITLE
In-app update check (Restart and install) does not work

### ISSUE THREAD

**Issue by Stanzilla** [getferdi/ferdi#329] opened 2020-01-29 17:28 UTC
**Describe the bug**
update check does not work

**To Reproduce**

1. Go to settings
2. Click on check for updates

**Expected behavior**
update gets downloaded

**Screenshots**

**Desktop (please complete the following information):**

Ferdi: Version 5.4.1-beta.4 (5.4.1-beta.4.952)
OS: macOS Catalina

`{"host":{"platform":"darwin","release":"19.3.0","screens":[{"accelerometerSupport":"unknown","bounds":{"height":1120,"width":1792,"x":0,"y":0},"colorDepth":24,"colorSpace":"{primaries_d50_referred: [[0.6818, 0.3196],  [0.2846, 0.6747],  [0.1562, 0.0554]], transfer:0.0777*x + 0.0000 if x < 0.0450 else (0.9495*x + 0.0495)**2.3955 + 0.0003, matrix:RGB, range:FULL}","depthPerComponent":8,"id":69734662,"internal":false,"monochrome":false,"rotation":0,"scaleFactor":2,"size":{"height":1120,"width":1792},"touchSupport":"unknown","workArea":{"height":1097,"width":1792,"x":0,"y":23},"workAreaSize":{"height":1097,"width":1792}}]},"ferdi":{"version":"5.4.1-beta.4","electron":"7.1.6","installedRecipes":[{"id":"android-messages","version":"1.2.0"},{"id":"googlekeep","version":"1.0.0"},{"id":"messenger","version":"1.0.8"},{"id":"skype","version":"1.1.1"},{"id":"slack","version":"1.0.9"},{"id":"telegram","version":"1.0.5"},{"id":"whatsapp","version":"1.0.17"},{}],"devRecipes":[],"services":[{"id":"382d78ee-b143-4043-a461-acc0e2351d88","recipe":"whatsapp","isAttached":true,"isActive":true,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"2537052a-2047-424e-9ee5-1e014f29622c","recipe":"slack","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"c4db7b48-691f-4192-b08b-5a07dea10d30","recipe":"slack","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":""},{"id":"487b879d-5471-4760-9af1-59358d6e7a7b","recipe":"messenger","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"55b43572-1733-4bb7-99a3-7edfe9ae16c5","recipe":"telegram","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true},{"id":"47a7366d-2bc0-467a-b610-eeee1594b027","recipe":"skype","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"39fc1e9d-cd05-42cf-90f3-ebe7d13da49e","recipe":"android-messages","isAttached":false,"isActive":false,"isEnabled":false,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":""},{"id":"4816b9e8-d38e-4e1b-b902-96593813efed","recipe":"googlekeep","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":""},{"id":"bfb78fe2-9a55-4145-b3b7-0845b87892e3","recipe":"slack","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":false},{"id":"612e9f70-9ad6-45d0-b51d-d9536feec9e8","recipe":"slack","isAttached":true,"isActive":false,"isEnabled":true,"isHibernating":false,"hasCrashed":false,"isDarkModeEnabled":true}],"messages":[{"type":"error","request":{"result":null,"wasExecuted":true,"method":"getInfo"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"features"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"error","request":{"result":null,"wasExecuted":true,"method":"all"},"error":{},"response":{},"server":"https://api.getferdi.com"},{"type":"log","info":["log","[ServerApi::getRecipePackage] Downloading recipe from server"]},{"type":"log","info":["log","/Users/stan/Library/Application Support/Ferdi/recipes/temp/telegram-react/recipe.tar.gz"]},{"type":"error","info":["error",{"errno":-2,"syscall":"open","code":"ENOENT","path":"/Users/stan/Library/Application Support/Ferdi/recipes/temp/telegram-react/package.json"}]},{"type":"error","info":["error","Warning: You cannot PUSH the same path using hash history"]}],"workspaces":[],"windowSettings":{"width":1421,"height":866,"x":192,"y":147,"isMaximized":false,"isFullScreen":false,"displayBounds":{"x":0,"y":0,"width":1792,"height":1120}},"settings":{"autoLaunchInBackground":false,"runInBackground":false,"enableSystemTray":false,"minimizeToSystemTray":false,"privateNotifications":false,"showDisabledServices":false,"showMessageBadgeWhenMuted":true,"enableSpellchecking":false,"spellcheckerLanguage":"en-us","darkMode":true,"locale":"en-US","fallbackLocale":"en-US","beta":true,"isAppMuted":false,"enableGPUAcceleration":true,"serviceLimit":5,"server":"https://api.getferdi.com","todoServer":"https://app.franztodos.com","autohideMenuBar":false,"lockingFeatureEnabled":false,"locked":false,"lockedPassword":"******","scheduledDNDEnabled":false,"scheduledDNDStart":"17:00","scheduledDNDEnd":"09:00","hibernate":false,"hibernationStrategy":300,"noUpdates":false,"showServiceNavigationBar":false,"universalDarkMode":false,"adaptableDarkMode":true,"accentColor":"#7367f0","serviceRibbonWidth":68},"features":{"isSpellcheckerIncludedInCurrentPlan":true,"needToWaitToProceed":false,"needToWaitToProceedConfig":{"delayOffset":3600000,"wait":10000},"isServiceProxyEnabled":true,"isServiceProxyIncludedInCurrentPlan":true,"isAnnouncementsEnabled":true,"isWorkspaceIncludedInCurrentPlan":true,"isWorkspaceEnabled":true,"isCommunityRecipesIncludedInCurrentPlan":true,"isSpellcheckerPremiumFeature":false,"isServiceProxyPremiumFeature":true,"isWorkspacePremiumFeature":false,"isSettingsWSEnabled":false,"isServiceLimitEnabled":false,"serviceLimitCount":0,"isCommunityRecipesPremiumFeature":false,"isCustomUrlIncludedInCurrentPlan":true,"isMagicBarEnabled":true,"isTeamManagementIncludedInCurrentPlan":true,"isTodosEnabled":true,"isTodosIncludedInCurrentPlan":true,"defaultTrialPlan":"franz-pro-yearly","subscribeURL":"https://getferdi.com","planSelectionURL":"https://getferdi.com","hasInlineCheckout":true,"isPlanSelectionEnabled":false,"isTrialStatusBarEnabled":false,"canSkipTrial":true,"pricingConfig":{"currency":"$","currencyID":"USD","plans":{"personal":{"monthly":{"id":"ferdi-free","price":0,"billed":0},"yearly":{"id":"ferdi-completely-free","price":0,"billed":0}},"pro":{"monthly":{"id":"ferdi-still-free","price":0,"billed":0},"yearly":{"id":"ferdi-forever-free","price":0,"billed":0}}}}},"user":"82c1cf9d-ab58-4da2-b55e-aaa41d2142d8"}}`

**Additional context**

**Comment by Gaboris** [comment] 2020-01-29 19:48
I can confirm that this is the case on Win7 as well.

Even Franz had problems where it sometimes took several days to register an update especially when leaving a Beta, but as of the latest few Betas Ferdi outright doesn't notice that there's been an update, but still downloads something, probably the installer, but does nothing with it.

I didn't want to report this in case it was just a broken installation or it would get fixed by a new major version, but it's still happening.

**Comment by kytwb** [comment] 2020-02-29 00:32
Seems related to https://github.com/electron-userland/electron-builder/issues/4583.

**Comment by kytwb** [comment] 2020-03-01 23:24
Or could it be because of the mishaps that took place between these tags?

<img width="513" alt="Screen Shot 2020-03-02 at 12 21 53 AM" src="https://user-images.githubusercontent.com/412895/75636066-e2f80980-5c1b-11ea-90df-45749f4007b4.png">

Maybe some clients first picked up the deleted releases/versions and got stuck once they were removed? Adding this as a note to double check in the source code later if that could have happen.

**Comment by probablykasper** [comment] 2020-03-15 15:23
Can confirm it happens on macOS 10.14.6.

In 5.4.3, the update button showed `Update available, downloading...` for only a couple frames (had to screen record to read it). Then, it goes back to normal.

In 5.4.4-beta.2, the behavior was different for me. The update button changed to `Update available, downloading...` and after a minute-ish, it went back to normal without performing any update.

**Comment by kytwb** [comment] 2020-04-26 14:46
Reviewing priorities 🙏 See https://github.com/getferdi/ferdi/issues/536#issuecomment-619562782

**Comment by kytwb** [comment] 2020-05-11 07:55
<img width="570" alt="Screen Shot 2020-05-10 at 2 02 36 PM" src="https://user-images.githubusercontent.com/412895/81537394-a273e500-935c-11ea-8d36-92e1eea7389c.png">

I had a successful update download from the `nightly.11` to `nightly.12`. No ideas how that happened, will have to double check but took a screenshot for reference.

**Comment by lukefisklennon** [comment] 2020-05-13 15:52
Until this bug fixed, do we just download the latest version manually? Will installing it automatically overwrite the old version?

**Comment by lukefisklennon** [comment] 2020-05-13 15:58
Update: here's the console output when clicking "Check for updates":

![image](https://user-images.githubusercontent.com/43358885/81836034-47bdd180-9586-11ea-8648-8f109a0a4fe7.png)

What's the `chmod 'C:\'` about?

**Comment by kytwb** [comment] 2020-05-16 14:10
@lukefisklennon You will have to update manually for now, yes 🙏 I think it will override the old version, but I am not 100% sure.

**Comment by kytwb** [comment] 2020-05-16 14:12
Regarding your second question, are you using Ferdi without an account?  
Can you please update to 5.5.0 manually and see if you still see this `chmod`?
Thank you!

**Comment by dsmith-digitalmint** [comment] 2020-11-02 17:50
This issue is still occurring.

Currently on v5.5.0. 

In the setting with "Check for betas" checkbox selected, the 5.6.0-beta.3 does not show as visible.

**Comment by Stanzilla** [comment] 2021-05-31 16:23
Still does not work. It now says "downloading" but then nothing happens

**Comment by vraravam** [comment] 2021-05-31 16:43
@Stanzilla - what version of Ferdi are you trying to upgrade **from**? At some point in between `5.6.beta`s, the upgrade checker was broken, and to "jump past that build", you need to manually upgrade. Also, if you are on mac, the signed vs unsigned issue for Apple's security will not allow an app (that is not downloaded from the Apple App Store) to autorun through the installation process.

**Comment by Stanzilla** [comment] 2021-05-31 16:44
Windows and upgrade was from 5.6.0-beta.5 to beta.6

**Comment by Stanzilla** [comment] 2021-07-20 08:58
mac does not work either, I just tried updating from .7 to .8 and when you hit update & restart it just closes and does not update nor restart

**Comment by vraravam** [comment] 2021-07-20 10:33
Yes - this is a known issue #1476 and I am unable to find the fix since we are using the in-app updater from `electron-updater` module.

**Comment by vraravam** [comment] 2021-11-09 08:29
Might be related (need to test): https://github.com/electron-userland/electron-builder/releases/tag/v22.14.6

**Comment by vraravam** [comment] 2021-11-15 10:13
@kytwb - as you can see there are numerous tickets being raised for this. Could you please prioritize fixing of this ticket soon?

**Comment by mhatvan** [comment] 2021-12-03 07:51
I switched from Ubuntu (.deb) to Linux Manjaro (AppImage) recently and this does work for me now (or always worked?)

I get the "Update & Restart" prompt, then once it quits, I get a prompt asking me to overwrite the current Ferdi install with the latest nightly. After confirming, the latest version starts.

So AppImage seems to work as expected, but macOS `.dmg` does not.

**Comment by jasmines** [comment] 2021-12-17 09:10
5.6.4 deb just installed.
If I click on the button to search for upgrades, nothing happens.
Good job! ;D

**Comment by vraravam** [comment] 2021-12-17 12:17
Still not working for macos

**Comment by sbcgm** [comment] 2021-12-17 12:34
Not working for Linux either.

By the way, the download link for Ubuntu on https://getferdi.com/download/ yields a HTTP 404 error.

**Comment by kytwb** [comment] 2021-12-23 12:20
The following commits are related to the in-app updater and landed in 5.6.5: https://github.com/getferdi/ferdi/commit/547d462243b26b3c1ee1dcf040f7d63081a1a4af, https://github.com/getferdi/ferdi/commit/8ba714e856420da09620a7d55d6412f5e8c5c027, https://github.com/getferdi/ferdi/commit/18494f66a7e0f4020cbc77374d4679421fcf469a, https://github.com/getferdi/ferdi/commit/01062664af1a9564d50759d1c23ab849376a6615.

**Comment by sbcgm** [comment] 2021-12-23 12:25
Dear sender, 

due to a ransomware attack and necessary security measures, CGM is temporarily not reachable in some regions via the usual eMail addresses and landline numbers. 
In these cases, please feel free to use SMS and mobile telephony of your individual contact persons, as far as they are known to you or inform yourself about further contact possibilities via the respective company or product page. 

Thank you for your understanding and best regards,
Your CGM Team

----------------------

Sehr geehrte Absenderin, 
sehr geehrter Absender,  

aufgrund einer Ransomware-Attacke und notwendiger Sicherheitsmaßnahmen, ist CGM in einigen Regionen vorübergehend nicht über die gewohnten eMail-Adressen und Festnetznummern erreichbar. 
Bitte nutzen Sie gerne in diesem Fall SMS und Mobilfunk-Telefonie Ihrer individuellen Ansprechpartner, soweit diese ihnen bekannt sind oder informieren Sie sich über die jeweilige Firmen- bzw. Produktseite über weitere Kontaktmöglichkeiten. 

Vielen Dank für Ihr Verständnis und freundliche Grüße, 
Ihr CGM-Team

**Comment by klonos** [comment] 2021-12-31 18:23
Running 5.6.5 on latest Mac OS 12.1, and just received the update notification for 5.6.6. The "restart and update" button would not work, but then I noticed that the app would not actually terminate. So I disabled the "Keep Ferdi in background when closing the window" option, and then tried again. That time the update worked w/o any issues.

I hope that this helps.

**Comment by sbcgm** [comment] 2021-12-31 18:28
Dear sender,

CGM is temporarily not reachable in some regions via the usual eMail addresses and landline numbers.  In these cases, please feel free to use SMS and mobile telephony of your individual contact persons, as far as they are known to you or inform yourself about further contact possibilities via the respective company or product page.  

Thank you for your understanding and best regards, 
Your CGM Team  

-------------------------

Sehr geehrte Absenderin, 
sehr geehrter Absender,

CGM ist in einigen Regionen vorübergehend nicht über die gewohnten eMail-Adressen und Festnetznummern erreichbar.  Bitte nutzen Sie gerne in diesem Fall SMS und Mobilfunk-Telefonie Ihrer individuellen Ansprechpartner, soweit diese ihnen bekannt sind oder informieren Sie sich über die jeweilige Firmen- bzw. Produktseite über weitere Kontaktmöglichkeiten. 

Vielen Dank für Ihr Verständnis und freundliche Grüße,  
Ihr CGM-Team

**Comment by kytwb** [comment] 2021-12-31 18:36
@all-contributors please add @klonos for userTesting

**Comment by kytwb** [comment] 2022-01-02 12:47
Updating from 5.6.6 to 5.6.7, the update was downloaded but clicking on **Restart & install update** failed with the following error in the console: `Updater error: Error: The network connection was lost.`

Using a VPN fixed it for me.

**Comment by jasmines** [comment] 2022-01-02 13:00
5.6.7 Ubuntu 64.
Still hangs on "searching for updates".
I really don't come to terms with developers.

**Comment by kytwb** [comment] 2022-01-02 13:09
Still relevant: https://github.com/getferdi/ferdi/issues/512

**Closed** 2022-01-02 13:48 UTC
Labels: bug :beetle:, high priority

**Comment by klonos** [comment] 2022-01-02 16:24
Updating from 5.6.6 to 5.6.7 on MacOS has the same problem. Disabling the "Keep Ferdi in background when closing the window" option is the workaround.

@kytwb I see that you have closed this issue. Does that mean that it has been fixed in 5.6.7? I don't see anything relevant in the changelog.

**Comment by kytwb** [comment] 2022-01-02 19:08
@klonos yes, fixed via https://github.com/getferdi/ferdi/commit/610923e48784352fcb45c6a56a185682690c16a3

**Comment by klonos** [comment] 2022-01-02 19:13
Cool 👍thanks.

**Comment by Privatecoder** [comment] 2022-01-10 12:03
I can't confirm this is fixed with "Keep Ferdi in background when closing the window" turned on. I removed Ferdi, installed 5.6.9 and tried to run the update which failed until I unchecked the option as @klonos described.

**Comment by IjonFryderyk** [comment] 2022-01-10 12:08
> @kytwb I can't confirm this is fixed with "Keep Ferdi in background when closing the window" turned on on macOS 12.1 (arm). I removed Ferdi, installed 5.6.9 and tried to run the update which failed until I unchecked the option as @klonos described.

I have the same problem.

**Comment by Privatecoder** [comment] 2022-01-10 12:18
@kytwb check this: https://github.com/electron-userland/electron-builder/issues/1604

It probably  makes sense to run

```
if (focusedWindow != null) {
    focusedWindow.close()
}
```

as suggested there (and as per unchecking the "background when closing the window" _fixes_ the issue)

**Comment by kytwb** [comment] 2022-01-11 12:16
@Privatecoder the docs says:

> Under the hood calling autoUpdater.quitAndInstall() will close all application windows first, and automatically call app.quit() after all windows have been closed.

It's not necessary to manually call `params.mainWindow.close()` here, but removing the `close` listener from `mainWindow` should help.

**Comment by Privatecoder** [comment] 2022-01-11 16:18
@kytwb you're right about the docs however I cannot confirm that updating Ferdi works after commit 610923e, i.e. build 5.6.9+ to any newer version. I will build it locally, check if I can find something and report back

**Comment by kytwb** [comment] 2022-01-11 16:25
@Privatecoder I have pushed a fix via https://github.com/getferdi/ferdi/commit/820a92de96652967e809e7f3ba163a4654e40ffc.

**Comment by Privatecoder** [comment] 2022-01-11 18:57
I just checked the commit and must admit that I did not read properly what you wrote in your previous answer.

Yes, removing the handler before calling quitAndInstall() should indeed fix it (also with that handler in place my proposed solution would not have worked either as it would have been intercepted by named handler..)

Thanks @kytwb
