### ISSUE TITLE
Multiple tray icons in Ubuntu Gnome

### ISSUE THREAD

**Issue by ddellarocca** [getferdi/ferdi#1980] opened 2021-09-23 10:24 UTC
**Bug description:**
The Ferdi icon in system tray is duplicated on lock.

**Steps to reproduce:**

1. In the settings enable "Show Ferdi in system tray"
2. Lock the session with super+L (super key is usually the windows key)
3. Unlock the session
4. The Ferdi icon is now double in the tray but only one works
![image](https://user-images.githubusercontent.com/29358615/134491484-9cf11ed9-6aad-4196-a2b7-58a374c48d64.png)

Another problem can be found by enabling and disabling system tray icon in Ferdi settings multiple times, and instead of being removed the icon it is replaced with 3 dots, then, when it is enabled again, it is being created again.
![image](https://user-images.githubusercontent.com/29358615/134491449-cfc69e95-70d3-4f6b-ab06-f429e4447679.png)

**Expected behavior**
The tray icon should be always one, and it should be removed when disabled.

**Environment:**

- Operating System: Ubuntu 21.04 - Gnome 3.38.5 - Wayland
- Ferdi Version: 5.6.2
- Server: Using without an account

**Comment by douglasilvadev** [comment] 2021-12-10 22:47
> GNOME on Arch Linux have the same issue. Multiple tray icons after lock screen. Extension I used to display tray icons: https://extensions.gnome.org/extension/615/appindicator-support/

Manjaro with Gnome 41 has the same behavior. Tks

**Comment by mhatvan** [comment] 2021-12-17 19:35
Closing as duplicate of https://github.com/getferdi/ferdi/issues/1189

**Closed by mhatvan** 2021-12-17 19:35 UTC
Labels: bug :beetle:, platform-specific
