### ISSUE TITLE
Ferdi system tray single left mouse click problem

### ISSUE THREAD

**Issue by tonypachino** [getferdi/ferdi#2054] opened 2021-10-11 03:37 UTC
**Bug description:**

I'm using KDE Plasma and when Ferdi is minimized and i single click on it, it won't maximize Ferdi but i'm getting the same options like when i'm making a right mouse click: Show Ferdi, Disable notifications & audio, Quit Ferdi.

I wan't when i left click with mouse to restore Ferdi window to my previous state.

**Environment:**

- Operating System: Arch Linux
- Ferdi Version: 5.6.2-nightly.2

**Comment by Argus-Kan** [comment] 2021-10-11 07:59
I am facing the same issue, whether I do a right click or left click on the system tray icon, it always shows the menu. And not just that, for some reason a lot of things behave oddly in the Linux version compared to the Windows version of Ferdi.

**Comment by fermmm** [comment] 2021-11-11 21:22
Any news on this? I always have to click the tray icon, then click on "Show Ferdi" why 2 clicks when a single left mouse click should show Ferdi? If I want the context menu I can right click the tray icon.

**Comment by vraravam** [comment] 2021-11-12 02:37
There's a lot of conversation going on in #2147 - and we would appreciate some code contributors to step in and help solve the problem.

**Comment by fermmm** [comment] 2021-11-12 02:45
> There's a lot of conversation going on in #2147 - and we would appreciate some code contributors to step in and help solve the problem.

The issue reported here is not related with #2147 . The issue is that at least in Linux when clicking on the Ferdi tray icon using the left mouse button a context menu is opened. 2 clicks are required to show Ferdi window. If I want context menu I can click with the right mouse button.

**Comment by vraravam** [comment] 2021-11-15 23:41
This should now be fixed via #2234 - please try out the latest nightly (should appear in a couple of hours from now) and close this ticket.

**Comment by norbusan** [comment] 2021-11-16 01:58
Thanks a lot, now hiding/showing works again.

**Comment by martinbernat** [comment] 2021-11-18 12:39
@vraravam this bug can be closed I guess.

**Closed** 2021-11-18 12:56 UTC
Labels: enhancement :sparkles:, help wanted, outstanding question

**Comment by tonypachino** [comment] 2021-12-31 19:56
> 

what did you do to make it work?

**Comment by tonypachino** [comment] 2021-12-31 19:57
> 

Hey norbusan, what did you do to make it work?

**Comment by norbusan** [comment] 2021-12-31 23:52
@tonypachino Install the latest version, it is fixed.

**Comment by tonypachino** [comment] 2022-01-01 00:17
> @tonypachino Install the latest version, it is fixed.

i'm on Arch and i installed it from AUR, ferdi 5.6.5-1, not bin, not git, and doesn't work, but something is interesting, it was working on the beginning and then i think i updated my system with some package python.something, and then again i'm getting the options, show ferdi, disable notifications & audio, quit ferdi.

I don't know where is the problem?
